[package]
name = "kamino-vault-test"
version = "0.1.0"
edition.workspace = true
publish = false
autotests = false

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
sha2 = { workspace = true }
solana-account = { workspace = true }
solana-address = { workspace = true }
solana-instruction = { workspace = true }
solana-keypair = { workspace = true }
solana-signature = { workspace = true }
solana-signer = { workspace = true }
thiserror = { workspace = true }
zolana-client = { workspace = true, features = ["indexer-api", "solana-rpc"] }
zolana-event = { workspace = true }
zolana-interface = { workspace = true }
zolana-keypair = { workspace = true }
zolana-program = { workspace = true }
zolana-program-test = { workspace = true, features = ["localnet"] }
zolana-test-utils = { workspace = true }
zolana-transaction = { workspace = true }

[[test]]
name = "kamino_vault"
path = "tests/kamino_vault.rs"
