[package]
name = "zolana-ring-client"
version = "0.1.0"
description = "Custom ring audit encryption and transaction recovery client."
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
hex = { workspace = true }
curve25519-dalek = { version = "4.1", default-features = false }
p256 = { workspace = true }
sha2 = { workspace = true }
solana-address = { workspace = true, features = ["curve25519"] }
solana-signature = { workspace = true }
thiserror = { workspace = true }
zeroize = { workspace = true }
zolana-client = { workspace = true }
zolana-interface = { workspace = true }
zolana-keypair = { workspace = true }
zolana-transaction = { workspace = true }

[dev-dependencies]
borsh = { workspace = true }
