// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        6u8, 211u8, 12u8, 81u8, 230u8, 199u8, 18u8, 151u8, 85u8, 206u8, 148u8, 47u8, 112u8, 204u8,
        65u8, 177u8, 182u8, 147u8, 248u8, 155u8, 40u8, 103u8, 54u8, 0u8, 20u8, 234u8, 48u8, 71u8,
        127u8, 96u8, 165u8, 238u8, 37u8, 254u8, 205u8, 3u8, 163u8, 0u8, 110u8, 151u8, 98u8, 211u8,
        14u8, 184u8, 234u8, 28u8, 39u8, 156u8, 15u8, 22u8, 18u8, 127u8, 31u8, 124u8, 67u8, 93u8,
        184u8, 127u8, 95u8, 53u8, 151u8, 144u8, 2u8, 221u8,
    ],
    [
        0u8, 58u8, 198u8, 109u8, 225u8, 21u8, 109u8, 228u8, 99u8, 128u8, 138u8, 237u8, 193u8, 4u8,
        207u8, 22u8, 232u8, 124u8, 20u8, 83u8, 162u8, 104u8, 184u8, 60u8, 150u8, 175u8, 224u8,
        174u8, 253u8, 207u8, 226u8, 249u8, 19u8, 152u8, 155u8, 16u8, 192u8, 69u8, 66u8, 9u8, 79u8,
        224u8, 153u8, 103u8, 252u8, 102u8, 84u8, 77u8, 125u8, 81u8, 254u8, 242u8, 0u8, 7u8, 221u8,
        71u8, 31u8, 201u8, 172u8, 94u8, 124u8, 248u8, 174u8, 13u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        21u8, 192u8, 242u8, 98u8, 94u8, 162u8, 73u8, 83u8, 131u8, 106u8, 33u8, 142u8, 209u8, 49u8,
        16u8, 250u8, 98u8, 241u8, 115u8, 207u8, 42u8, 141u8, 214u8, 202u8, 47u8, 109u8, 48u8,
        191u8, 252u8, 218u8, 172u8, 249u8, 26u8, 148u8, 49u8, 6u8, 240u8, 245u8, 210u8, 182u8,
        228u8, 219u8, 201u8, 245u8, 96u8, 108u8, 78u8, 119u8, 57u8, 245u8, 160u8, 246u8, 166u8,
        196u8, 206u8, 41u8, 248u8, 210u8, 252u8, 116u8, 7u8, 249u8, 85u8, 139u8,
    ],
    vk_beta_g2: [
        9u8, 151u8, 201u8, 101u8, 233u8, 215u8, 80u8, 148u8, 187u8, 190u8, 162u8, 224u8, 32u8,
        109u8, 185u8, 120u8, 205u8, 183u8, 0u8, 6u8, 124u8, 15u8, 137u8, 160u8, 156u8, 20u8, 240u8,
        237u8, 177u8, 193u8, 218u8, 40u8, 29u8, 58u8, 178u8, 19u8, 190u8, 177u8, 52u8, 1u8, 23u8,
        39u8, 204u8, 204u8, 50u8, 84u8, 85u8, 14u8, 167u8, 106u8, 155u8, 0u8, 75u8, 235u8, 207u8,
        123u8, 243u8, 43u8, 94u8, 184u8, 197u8, 232u8, 75u8, 80u8, 45u8, 25u8, 220u8, 101u8, 67u8,
        243u8, 251u8, 89u8, 27u8, 254u8, 139u8, 175u8, 107u8, 114u8, 98u8, 22u8, 116u8, 252u8,
        250u8, 100u8, 191u8, 61u8, 200u8, 48u8, 247u8, 19u8, 58u8, 133u8, 12u8, 163u8, 148u8,
        205u8, 31u8, 229u8, 128u8, 14u8, 205u8, 83u8, 119u8, 242u8, 193u8, 34u8, 84u8, 18u8, 112u8,
        109u8, 155u8, 68u8, 219u8, 120u8, 101u8, 159u8, 254u8, 212u8, 213u8, 52u8, 102u8, 214u8,
        225u8, 12u8, 187u8, 248u8, 162u8, 19u8,
    ],
    vk_gamma_g2: [
        12u8, 98u8, 65u8, 160u8, 210u8, 133u8, 134u8, 234u8, 250u8, 37u8, 84u8, 54u8, 103u8, 64u8,
        171u8, 122u8, 113u8, 137u8, 83u8, 68u8, 69u8, 234u8, 177u8, 96u8, 97u8, 35u8, 249u8, 53u8,
        22u8, 42u8, 35u8, 241u8, 7u8, 249u8, 163u8, 73u8, 232u8, 155u8, 149u8, 209u8, 234u8, 140u8,
        144u8, 166u8, 68u8, 144u8, 241u8, 102u8, 58u8, 155u8, 236u8, 237u8, 155u8, 105u8, 136u8,
        108u8, 225u8, 126u8, 153u8, 226u8, 193u8, 206u8, 17u8, 214u8, 0u8, 176u8, 83u8, 81u8, 10u8,
        209u8, 22u8, 53u8, 106u8, 53u8, 16u8, 174u8, 10u8, 225u8, 245u8, 196u8, 137u8, 101u8,
        185u8, 20u8, 204u8, 188u8, 164u8, 102u8, 220u8, 178u8, 150u8, 41u8, 128u8, 41u8, 167u8,
        253u8, 27u8, 217u8, 86u8, 210u8, 113u8, 192u8, 226u8, 137u8, 136u8, 144u8, 202u8, 174u8,
        74u8, 90u8, 198u8, 232u8, 125u8, 157u8, 159u8, 209u8, 21u8, 25u8, 194u8, 37u8, 21u8, 42u8,
        30u8, 252u8, 157u8, 154u8, 150u8, 15u8,
    ],
    vk_delta_g2: [
        19u8, 124u8, 85u8, 71u8, 218u8, 54u8, 203u8, 114u8, 23u8, 212u8, 197u8, 239u8, 22u8, 9u8,
        20u8, 99u8, 226u8, 236u8, 5u8, 216u8, 246u8, 252u8, 9u8, 129u8, 113u8, 26u8, 52u8, 221u8,
        229u8, 6u8, 177u8, 146u8, 9u8, 127u8, 66u8, 150u8, 173u8, 157u8, 198u8, 252u8, 167u8, 88u8,
        93u8, 115u8, 77u8, 109u8, 111u8, 124u8, 58u8, 32u8, 134u8, 123u8, 231u8, 180u8, 78u8,
        252u8, 44u8, 69u8, 115u8, 216u8, 126u8, 10u8, 102u8, 230u8, 15u8, 44u8, 198u8, 58u8, 25u8,
        247u8, 251u8, 57u8, 95u8, 37u8, 167u8, 54u8, 198u8, 241u8, 29u8, 146u8, 104u8, 219u8,
        106u8, 42u8, 34u8, 44u8, 234u8, 51u8, 91u8, 99u8, 187u8, 89u8, 65u8, 149u8, 41u8, 140u8,
        41u8, 179u8, 152u8, 149u8, 105u8, 20u8, 182u8, 233u8, 167u8, 168u8, 3u8, 33u8, 24u8, 179u8,
        234u8, 140u8, 213u8, 96u8, 212u8, 191u8, 101u8, 96u8, 249u8, 78u8, 239u8, 181u8, 252u8,
        179u8, 215u8, 47u8, 168u8, 46u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [77u8, 4u8, 228u8, 63u8, 16u8, 181u8, 26u8, 243u8, 248u8, 23u8, 190u8, 19u8, 140u8, 21u8, 28u8, 82u8, 30u8, 165u8, 57u8, 88u8, 188u8, 147u8, 202u8, 122u8, 76u8, 246u8, 50u8, 223u8, 193u8, 24u8, 159u8, 190u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_674453ed9864991e")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x004d04e43f10b51af3f817be138c151c521ea53958bc93ca7a4cf632dfc1189fbe\x00=======END GROTH16 VK SETUP V1=======\x00";
