// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        34u8, 33u8, 237u8, 6u8, 7u8, 10u8, 227u8, 184u8, 112u8, 198u8, 128u8, 120u8, 11u8, 121u8,
        188u8, 155u8, 43u8, 229u8, 117u8, 87u8, 122u8, 158u8, 98u8, 27u8, 208u8, 239u8, 255u8,
        216u8, 41u8, 62u8, 119u8, 48u8, 9u8, 89u8, 214u8, 138u8, 77u8, 88u8, 90u8, 21u8, 107u8,
        168u8, 224u8, 102u8, 170u8, 101u8, 66u8, 28u8, 91u8, 60u8, 105u8, 215u8, 59u8, 206u8,
        179u8, 223u8, 190u8, 144u8, 251u8, 244u8, 10u8, 193u8, 148u8, 161u8,
    ],
    [
        22u8, 24u8, 250u8, 139u8, 125u8, 92u8, 240u8, 178u8, 58u8, 187u8, 201u8, 167u8, 64u8, 51u8,
        170u8, 58u8, 91u8, 205u8, 179u8, 26u8, 226u8, 30u8, 28u8, 81u8, 54u8, 178u8, 206u8, 191u8,
        178u8, 46u8, 97u8, 153u8, 13u8, 83u8, 143u8, 25u8, 69u8, 120u8, 150u8, 242u8, 60u8, 24u8,
        198u8, 143u8, 206u8, 186u8, 169u8, 109u8, 34u8, 252u8, 131u8, 207u8, 191u8, 77u8, 75u8,
        155u8, 70u8, 47u8, 2u8, 156u8, 78u8, 72u8, 154u8, 168u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        19u8, 163u8, 50u8, 193u8, 98u8, 225u8, 219u8, 129u8, 199u8, 213u8, 75u8, 125u8, 201u8,
        58u8, 76u8, 87u8, 27u8, 243u8, 190u8, 242u8, 204u8, 232u8, 48u8, 180u8, 185u8, 12u8, 19u8,
        165u8, 217u8, 157u8, 101u8, 196u8, 22u8, 248u8, 79u8, 210u8, 120u8, 143u8, 118u8, 105u8,
        247u8, 128u8, 129u8, 52u8, 209u8, 145u8, 62u8, 224u8, 204u8, 236u8, 57u8, 227u8, 194u8,
        250u8, 128u8, 115u8, 195u8, 253u8, 166u8, 186u8, 127u8, 162u8, 96u8, 6u8,
    ],
    vk_beta_g2: [
        12u8, 198u8, 109u8, 64u8, 78u8, 246u8, 38u8, 192u8, 227u8, 86u8, 85u8, 254u8, 72u8, 58u8,
        45u8, 113u8, 205u8, 45u8, 125u8, 41u8, 89u8, 83u8, 53u8, 159u8, 151u8, 156u8, 102u8, 201u8,
        60u8, 68u8, 141u8, 51u8, 29u8, 158u8, 101u8, 194u8, 175u8, 207u8, 67u8, 189u8, 87u8, 237u8,
        123u8, 45u8, 196u8, 207u8, 102u8, 234u8, 208u8, 72u8, 215u8, 0u8, 115u8, 13u8, 119u8,
        233u8, 178u8, 74u8, 187u8, 110u8, 101u8, 141u8, 188u8, 0u8, 5u8, 136u8, 75u8, 24u8, 242u8,
        207u8, 253u8, 154u8, 164u8, 255u8, 120u8, 232u8, 159u8, 37u8, 85u8, 235u8, 214u8, 150u8,
        198u8, 162u8, 10u8, 178u8, 103u8, 170u8, 234u8, 152u8, 18u8, 221u8, 221u8, 32u8, 156u8,
        104u8, 32u8, 3u8, 195u8, 24u8, 52u8, 189u8, 205u8, 218u8, 53u8, 248u8, 215u8, 232u8, 213u8,
        230u8, 110u8, 160u8, 152u8, 128u8, 208u8, 103u8, 78u8, 176u8, 21u8, 242u8, 252u8, 52u8,
        16u8, 221u8, 41u8, 168u8, 24u8, 33u8,
    ],
    vk_gamma_g2: [
        44u8, 149u8, 117u8, 15u8, 12u8, 200u8, 152u8, 22u8, 11u8, 127u8, 252u8, 37u8, 236u8, 47u8,
        24u8, 181u8, 132u8, 12u8, 73u8, 239u8, 193u8, 102u8, 155u8, 236u8, 133u8, 144u8, 82u8,
        10u8, 200u8, 75u8, 6u8, 118u8, 20u8, 248u8, 216u8, 99u8, 91u8, 224u8, 99u8, 205u8, 63u8,
        141u8, 147u8, 19u8, 225u8, 63u8, 68u8, 73u8, 121u8, 208u8, 249u8, 62u8, 174u8, 58u8, 50u8,
        47u8, 55u8, 129u8, 70u8, 72u8, 116u8, 60u8, 235u8, 16u8, 8u8, 46u8, 105u8, 162u8, 220u8,
        26u8, 34u8, 231u8, 124u8, 74u8, 73u8, 165u8, 20u8, 119u8, 119u8, 0u8, 110u8, 246u8, 41u8,
        125u8, 225u8, 165u8, 220u8, 195u8, 202u8, 92u8, 23u8, 51u8, 183u8, 140u8, 114u8, 245u8,
        33u8, 238u8, 227u8, 152u8, 1u8, 6u8, 15u8, 62u8, 166u8, 25u8, 194u8, 19u8, 137u8, 185u8,
        131u8, 47u8, 94u8, 86u8, 223u8, 93u8, 10u8, 179u8, 214u8, 199u8, 21u8, 175u8, 138u8, 212u8,
        32u8, 8u8, 53u8, 10u8,
    ],
    vk_delta_g2: [
        7u8, 65u8, 101u8, 104u8, 63u8, 205u8, 178u8, 179u8, 126u8, 198u8, 102u8, 27u8, 59u8, 27u8,
        28u8, 193u8, 174u8, 162u8, 119u8, 59u8, 166u8, 53u8, 15u8, 7u8, 216u8, 200u8, 98u8, 188u8,
        120u8, 210u8, 117u8, 121u8, 11u8, 61u8, 38u8, 235u8, 70u8, 243u8, 149u8, 134u8, 140u8,
        14u8, 163u8, 192u8, 80u8, 11u8, 32u8, 167u8, 146u8, 129u8, 170u8, 101u8, 227u8, 46u8, 74u8,
        239u8, 50u8, 81u8, 204u8, 151u8, 232u8, 128u8, 114u8, 34u8, 29u8, 207u8, 192u8, 169u8,
        109u8, 36u8, 172u8, 198u8, 96u8, 191u8, 229u8, 203u8, 173u8, 209u8, 60u8, 122u8, 34u8,
        177u8, 220u8, 99u8, 98u8, 92u8, 25u8, 18u8, 26u8, 216u8, 133u8, 241u8, 76u8, 69u8, 147u8,
        102u8, 39u8, 115u8, 209u8, 74u8, 83u8, 87u8, 39u8, 75u8, 90u8, 171u8, 158u8, 166u8, 32u8,
        84u8, 197u8, 12u8, 140u8, 156u8, 172u8, 38u8, 56u8, 64u8, 46u8, 112u8, 0u8, 25u8, 77u8,
        172u8, 159u8, 130u8, 146u8, 8u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [85u8, 78u8, 95u8, 253u8, 251u8, 122u8, 187u8, 144u8, 59u8, 252u8, 6u8, 97u8, 12u8, 126u8, 244u8, 112u8, 200u8, 147u8, 64u8, 204u8, 162u8, 189u8, 74u8, 184u8, 235u8, 16u8, 70u8, 128u8, 221u8, 136u8, 85u8, 234u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_d4a37d88050d304c")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00554e5ffdfb7abb903bfc06610c7ef470c89340cca2bd4ab8eb104680dd8855ea\x00=======END GROTH16 VK SETUP V1=======\x00";
