// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        7u8, 7u8, 193u8, 101u8, 113u8, 192u8, 180u8, 112u8, 222u8, 254u8, 250u8, 236u8, 195u8,
        26u8, 166u8, 255u8, 237u8, 232u8, 188u8, 144u8, 167u8, 14u8, 131u8, 207u8, 193u8, 226u8,
        146u8, 245u8, 224u8, 177u8, 79u8, 195u8, 23u8, 98u8, 165u8, 216u8, 143u8, 220u8, 67u8,
        138u8, 130u8, 175u8, 41u8, 107u8, 149u8, 97u8, 161u8, 57u8, 185u8, 21u8, 170u8, 171u8,
        243u8, 93u8, 13u8, 222u8, 185u8, 84u8, 47u8, 214u8, 49u8, 205u8, 250u8, 47u8,
    ],
    [
        32u8, 21u8, 212u8, 31u8, 95u8, 138u8, 253u8, 74u8, 230u8, 222u8, 33u8, 177u8, 78u8, 201u8,
        68u8, 247u8, 66u8, 129u8, 86u8, 22u8, 204u8, 47u8, 228u8, 83u8, 40u8, 237u8, 89u8, 98u8,
        174u8, 147u8, 60u8, 101u8, 18u8, 216u8, 138u8, 130u8, 67u8, 98u8, 142u8, 82u8, 6u8, 111u8,
        118u8, 146u8, 153u8, 2u8, 87u8, 188u8, 250u8, 161u8, 204u8, 61u8, 151u8, 74u8, 249u8, 85u8,
        171u8, 166u8, 10u8, 140u8, 107u8, 91u8, 191u8, 121u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        8u8, 189u8, 120u8, 162u8, 48u8, 144u8, 165u8, 182u8, 73u8, 168u8, 33u8, 22u8, 46u8, 186u8,
        159u8, 165u8, 3u8, 103u8, 75u8, 246u8, 119u8, 58u8, 27u8, 122u8, 151u8, 57u8, 56u8, 36u8,
        38u8, 221u8, 155u8, 216u8, 19u8, 104u8, 197u8, 224u8, 56u8, 110u8, 109u8, 46u8, 120u8,
        186u8, 190u8, 113u8, 173u8, 175u8, 88u8, 174u8, 109u8, 117u8, 111u8, 3u8, 221u8, 193u8,
        21u8, 128u8, 128u8, 158u8, 185u8, 214u8, 151u8, 155u8, 106u8, 210u8,
    ],
    vk_beta_g2: [
        21u8, 248u8, 123u8, 20u8, 44u8, 234u8, 25u8, 220u8, 214u8, 251u8, 23u8, 179u8, 246u8,
        213u8, 203u8, 183u8, 79u8, 208u8, 145u8, 107u8, 227u8, 246u8, 116u8, 31u8, 187u8, 19u8,
        150u8, 14u8, 128u8, 241u8, 34u8, 91u8, 2u8, 133u8, 253u8, 244u8, 35u8, 165u8, 68u8, 214u8,
        218u8, 51u8, 80u8, 184u8, 227u8, 67u8, 145u8, 127u8, 152u8, 76u8, 108u8, 212u8, 11u8,
        239u8, 135u8, 33u8, 159u8, 75u8, 197u8, 154u8, 81u8, 106u8, 151u8, 228u8, 13u8, 28u8, 23u8,
        200u8, 56u8, 143u8, 103u8, 115u8, 170u8, 153u8, 243u8, 203u8, 23u8, 81u8, 66u8, 9u8, 193u8,
        17u8, 105u8, 135u8, 127u8, 24u8, 149u8, 61u8, 241u8, 111u8, 249u8, 50u8, 30u8, 183u8,
        170u8, 155u8, 2u8, 56u8, 107u8, 156u8, 150u8, 2u8, 96u8, 136u8, 207u8, 51u8, 173u8, 219u8,
        93u8, 90u8, 191u8, 94u8, 217u8, 221u8, 138u8, 77u8, 137u8, 89u8, 254u8, 62u8, 175u8, 123u8,
        90u8, 172u8, 5u8, 94u8, 168u8, 16u8,
    ],
    vk_gamma_g2: [
        28u8, 127u8, 60u8, 79u8, 233u8, 208u8, 13u8, 26u8, 223u8, 223u8, 118u8, 218u8, 83u8, 188u8,
        212u8, 27u8, 89u8, 232u8, 65u8, 187u8, 111u8, 1u8, 11u8, 42u8, 205u8, 20u8, 103u8, 85u8,
        149u8, 25u8, 9u8, 5u8, 37u8, 19u8, 103u8, 61u8, 68u8, 94u8, 183u8, 74u8, 27u8, 165u8,
        142u8, 213u8, 29u8, 174u8, 15u8, 76u8, 242u8, 20u8, 229u8, 32u8, 131u8, 253u8, 246u8,
        203u8, 112u8, 185u8, 33u8, 63u8, 175u8, 198u8, 19u8, 53u8, 39u8, 36u8, 79u8, 176u8, 43u8,
        246u8, 192u8, 74u8, 50u8, 39u8, 6u8, 110u8, 180u8, 250u8, 152u8, 232u8, 18u8, 199u8, 113u8,
        101u8, 218u8, 204u8, 123u8, 99u8, 114u8, 88u8, 157u8, 122u8, 129u8, 24u8, 122u8, 196u8,
        26u8, 42u8, 145u8, 101u8, 26u8, 174u8, 197u8, 144u8, 21u8, 239u8, 47u8, 130u8, 182u8,
        100u8, 177u8, 109u8, 140u8, 201u8, 201u8, 94u8, 26u8, 164u8, 10u8, 247u8, 157u8, 51u8,
        181u8, 107u8, 134u8, 197u8, 190u8, 108u8,
    ],
    vk_delta_g2: [
        29u8, 227u8, 238u8, 113u8, 237u8, 24u8, 249u8, 254u8, 20u8, 53u8, 102u8, 207u8, 246u8,
        112u8, 151u8, 199u8, 185u8, 50u8, 224u8, 5u8, 214u8, 156u8, 16u8, 55u8, 104u8, 239u8, 82u8,
        127u8, 16u8, 249u8, 65u8, 56u8, 19u8, 177u8, 6u8, 122u8, 178u8, 69u8, 6u8, 54u8, 192u8,
        12u8, 175u8, 116u8, 229u8, 104u8, 13u8, 41u8, 2u8, 217u8, 40u8, 96u8, 213u8, 149u8, 223u8,
        104u8, 136u8, 72u8, 36u8, 17u8, 25u8, 216u8, 72u8, 13u8, 26u8, 80u8, 237u8, 28u8, 162u8,
        125u8, 197u8, 85u8, 198u8, 109u8, 142u8, 45u8, 14u8, 250u8, 41u8, 125u8, 66u8, 130u8,
        114u8, 108u8, 157u8, 206u8, 148u8, 173u8, 109u8, 208u8, 89u8, 60u8, 184u8, 193u8, 1u8,
        128u8, 13u8, 70u8, 195u8, 13u8, 27u8, 72u8, 9u8, 174u8, 191u8, 38u8, 245u8, 218u8, 203u8,
        88u8, 149u8, 60u8, 51u8, 229u8, 24u8, 56u8, 23u8, 95u8, 185u8, 248u8, 132u8, 9u8, 7u8,
        143u8, 128u8, 134u8, 135u8, 55u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [69u8, 203u8, 145u8, 73u8, 152u8, 249u8, 186u8, 200u8, 166u8, 30u8, 218u8, 166u8, 7u8, 179u8, 11u8, 166u8, 206u8, 35u8, 190u8, 90u8, 248u8, 29u8, 23u8, 60u8, 164u8, 182u8, 87u8, 62u8, 96u8, 227u8, 185u8, 55u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_49018c597513a81d")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0045cb914998f9bac8a61edaa607b30ba6ce23be5af81d173ca4b6573e60e3b937\x00=======END GROTH16 VK SETUP V1=======\x00";
