// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        24u8, 234u8, 235u8, 87u8, 0u8, 242u8, 55u8, 163u8, 34u8, 80u8, 213u8, 92u8, 229u8, 72u8,
        4u8, 116u8, 234u8, 140u8, 20u8, 164u8, 71u8, 192u8, 162u8, 255u8, 236u8, 249u8, 160u8,
        26u8, 47u8, 202u8, 117u8, 239u8, 18u8, 80u8, 51u8, 20u8, 104u8, 236u8, 40u8, 156u8, 212u8,
        150u8, 148u8, 124u8, 90u8, 32u8, 43u8, 126u8, 145u8, 27u8, 243u8, 181u8, 11u8, 146u8, 27u8,
        141u8, 218u8, 213u8, 198u8, 167u8, 143u8, 164u8, 239u8, 10u8,
    ],
    [
        26u8, 37u8, 127u8, 92u8, 108u8, 104u8, 124u8, 99u8, 21u8, 98u8, 166u8, 245u8, 126u8, 110u8,
        60u8, 73u8, 2u8, 19u8, 128u8, 155u8, 189u8, 14u8, 246u8, 50u8, 198u8, 6u8, 113u8, 228u8,
        81u8, 180u8, 24u8, 102u8, 11u8, 56u8, 253u8, 152u8, 148u8, 173u8, 41u8, 245u8, 253u8,
        148u8, 33u8, 23u8, 149u8, 15u8, 94u8, 137u8, 78u8, 173u8, 45u8, 168u8, 177u8, 139u8, 221u8,
        12u8, 59u8, 217u8, 87u8, 169u8, 250u8, 201u8, 153u8, 167u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        46u8, 26u8, 215u8, 155u8, 8u8, 9u8, 231u8, 87u8, 22u8, 63u8, 183u8, 166u8, 58u8, 90u8,
        42u8, 5u8, 124u8, 220u8, 163u8, 216u8, 100u8, 19u8, 217u8, 182u8, 63u8, 138u8, 181u8,
        157u8, 86u8, 193u8, 55u8, 198u8, 8u8, 82u8, 141u8, 97u8, 170u8, 142u8, 213u8, 152u8, 33u8,
        151u8, 92u8, 106u8, 166u8, 147u8, 115u8, 148u8, 123u8, 182u8, 72u8, 142u8, 208u8, 68u8,
        183u8, 91u8, 178u8, 222u8, 251u8, 141u8, 14u8, 107u8, 8u8, 24u8,
    ],
    vk_beta_g2: [
        7u8, 21u8, 86u8, 67u8, 194u8, 231u8, 163u8, 156u8, 49u8, 189u8, 95u8, 162u8, 250u8, 52u8,
        99u8, 156u8, 199u8, 13u8, 7u8, 22u8, 106u8, 231u8, 24u8, 186u8, 177u8, 113u8, 56u8, 213u8,
        46u8, 217u8, 145u8, 122u8, 37u8, 56u8, 170u8, 213u8, 145u8, 227u8, 132u8, 205u8, 32u8,
        194u8, 248u8, 114u8, 126u8, 136u8, 19u8, 74u8, 241u8, 242u8, 33u8, 1u8, 127u8, 220u8,
        255u8, 120u8, 104u8, 200u8, 127u8, 103u8, 229u8, 119u8, 124u8, 28u8, 15u8, 108u8, 203u8,
        190u8, 157u8, 90u8, 12u8, 219u8, 5u8, 74u8, 133u8, 202u8, 230u8, 248u8, 250u8, 128u8, 85u8,
        179u8, 61u8, 213u8, 91u8, 14u8, 36u8, 232u8, 207u8, 173u8, 189u8, 198u8, 78u8, 222u8,
        217u8, 204u8, 27u8, 28u8, 139u8, 17u8, 178u8, 75u8, 232u8, 206u8, 218u8, 165u8, 70u8,
        146u8, 230u8, 20u8, 203u8, 221u8, 218u8, 174u8, 81u8, 245u8, 28u8, 163u8, 227u8, 13u8,
        128u8, 173u8, 28u8, 109u8, 167u8, 165u8, 22u8, 58u8,
    ],
    vk_gamma_g2: [
        23u8, 151u8, 6u8, 156u8, 236u8, 151u8, 91u8, 216u8, 67u8, 238u8, 144u8, 225u8, 117u8,
        147u8, 73u8, 78u8, 108u8, 232u8, 245u8, 89u8, 208u8, 52u8, 178u8, 58u8, 134u8, 18u8, 47u8,
        87u8, 52u8, 193u8, 177u8, 14u8, 1u8, 87u8, 207u8, 188u8, 30u8, 38u8, 200u8, 233u8, 230u8,
        225u8, 222u8, 198u8, 88u8, 10u8, 55u8, 101u8, 88u8, 232u8, 231u8, 213u8, 236u8, 5u8, 243u8,
        55u8, 140u8, 41u8, 28u8, 251u8, 108u8, 135u8, 127u8, 4u8, 48u8, 53u8, 114u8, 46u8, 51u8,
        175u8, 119u8, 186u8, 150u8, 164u8, 241u8, 10u8, 210u8, 132u8, 252u8, 82u8, 2u8, 0u8, 240u8,
        60u8, 84u8, 38u8, 113u8, 73u8, 64u8, 234u8, 225u8, 151u8, 161u8, 189u8, 113u8, 108u8, 29u8,
        128u8, 227u8, 187u8, 129u8, 106u8, 32u8, 161u8, 100u8, 79u8, 254u8, 27u8, 140u8, 44u8,
        206u8, 210u8, 120u8, 179u8, 5u8, 123u8, 65u8, 18u8, 64u8, 145u8, 160u8, 8u8, 11u8, 18u8,
        101u8, 127u8, 71u8, 246u8,
    ],
    vk_delta_g2: [
        32u8, 54u8, 74u8, 213u8, 27u8, 57u8, 21u8, 155u8, 147u8, 201u8, 164u8, 9u8, 16u8, 89u8,
        70u8, 9u8, 168u8, 23u8, 79u8, 225u8, 197u8, 73u8, 249u8, 47u8, 43u8, 149u8, 216u8, 163u8,
        143u8, 136u8, 229u8, 150u8, 10u8, 139u8, 196u8, 11u8, 177u8, 210u8, 60u8, 133u8, 157u8,
        206u8, 127u8, 246u8, 93u8, 180u8, 232u8, 154u8, 22u8, 138u8, 252u8, 195u8, 149u8, 126u8,
        125u8, 201u8, 138u8, 83u8, 102u8, 238u8, 192u8, 127u8, 51u8, 82u8, 18u8, 205u8, 5u8, 240u8,
        183u8, 119u8, 202u8, 189u8, 164u8, 202u8, 108u8, 211u8, 177u8, 17u8, 185u8, 48u8, 172u8,
        234u8, 184u8, 15u8, 159u8, 219u8, 83u8, 5u8, 181u8, 86u8, 216u8, 102u8, 14u8, 40u8, 227u8,
        14u8, 41u8, 88u8, 95u8, 57u8, 227u8, 104u8, 210u8, 173u8, 39u8, 100u8, 86u8, 103u8, 159u8,
        140u8, 207u8, 51u8, 186u8, 196u8, 128u8, 254u8, 38u8, 80u8, 67u8, 251u8, 166u8, 37u8,
        149u8, 21u8, 129u8, 11u8, 144u8, 124u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [225u8, 73u8, 23u8, 90u8, 80u8, 3u8, 212u8, 156u8, 227u8, 234u8, 223u8, 45u8, 36u8, 54u8, 20u8, 72u8, 225u8, 76u8, 203u8, 121u8, 204u8, 240u8, 28u8, 21u8, 3u8, 63u8, 241u8, 232u8, 203u8, 167u8, 72u8, 130u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_5383a94a5117960b")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00e149175a5003d49ce3eadf2d24361448e14ccb79ccf01c15033ff1e8cba74882\x00=======END GROTH16 VK SETUP V1=======\x00";
