// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        24u8, 28u8, 56u8, 10u8, 192u8, 39u8, 39u8, 71u8, 37u8, 20u8, 197u8, 160u8, 53u8, 244u8,
        207u8, 254u8, 201u8, 252u8, 30u8, 137u8, 207u8, 144u8, 66u8, 226u8, 82u8, 243u8, 213u8,
        86u8, 130u8, 159u8, 232u8, 41u8, 30u8, 103u8, 141u8, 210u8, 135u8, 28u8, 62u8, 223u8,
        116u8, 214u8, 114u8, 124u8, 33u8, 28u8, 234u8, 62u8, 148u8, 135u8, 95u8, 243u8, 122u8,
        226u8, 216u8, 81u8, 79u8, 239u8, 227u8, 78u8, 219u8, 146u8, 170u8, 35u8,
    ],
    [
        11u8, 133u8, 251u8, 63u8, 47u8, 247u8, 107u8, 36u8, 219u8, 105u8, 220u8, 81u8, 52u8, 142u8,
        239u8, 178u8, 198u8, 178u8, 31u8, 178u8, 108u8, 249u8, 141u8, 0u8, 19u8, 126u8, 179u8,
        233u8, 54u8, 244u8, 210u8, 179u8, 26u8, 186u8, 8u8, 240u8, 154u8, 51u8, 85u8, 43u8, 164u8,
        251u8, 58u8, 190u8, 84u8, 125u8, 46u8, 180u8, 32u8, 207u8, 195u8, 153u8, 4u8, 181u8, 120u8,
        230u8, 230u8, 200u8, 169u8, 174u8, 105u8, 252u8, 178u8, 163u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        25u8, 2u8, 10u8, 138u8, 74u8, 215u8, 115u8, 136u8, 105u8, 180u8, 41u8, 115u8, 237u8, 244u8,
        32u8, 138u8, 91u8, 154u8, 236u8, 105u8, 206u8, 90u8, 56u8, 231u8, 129u8, 7u8, 161u8, 65u8,
        121u8, 100u8, 134u8, 134u8, 20u8, 105u8, 94u8, 193u8, 3u8, 21u8, 101u8, 171u8, 158u8,
        246u8, 41u8, 57u8, 74u8, 158u8, 113u8, 103u8, 62u8, 70u8, 183u8, 72u8, 222u8, 114u8, 255u8,
        15u8, 40u8, 153u8, 4u8, 177u8, 225u8, 208u8, 7u8, 33u8,
    ],
    vk_beta_g2: [
        14u8, 128u8, 224u8, 91u8, 145u8, 39u8, 146u8, 42u8, 200u8, 58u8, 217u8, 251u8, 202u8,
        136u8, 143u8, 60u8, 135u8, 34u8, 97u8, 76u8, 47u8, 24u8, 218u8, 123u8, 175u8, 111u8, 148u8,
        112u8, 241u8, 245u8, 228u8, 176u8, 30u8, 114u8, 127u8, 17u8, 40u8, 130u8, 243u8, 132u8,
        30u8, 34u8, 21u8, 138u8, 62u8, 146u8, 206u8, 219u8, 130u8, 195u8, 155u8, 59u8, 207u8,
        207u8, 227u8, 174u8, 202u8, 238u8, 186u8, 185u8, 187u8, 210u8, 207u8, 255u8, 2u8, 98u8,
        43u8, 180u8, 203u8, 133u8, 24u8, 114u8, 101u8, 250u8, 221u8, 152u8, 41u8, 59u8, 164u8,
        86u8, 170u8, 131u8, 177u8, 57u8, 246u8, 109u8, 84u8, 7u8, 170u8, 42u8, 207u8, 224u8, 226u8,
        19u8, 102u8, 1u8, 16u8, 173u8, 6u8, 150u8, 205u8, 110u8, 119u8, 234u8, 167u8, 48u8, 188u8,
        22u8, 228u8, 195u8, 34u8, 211u8, 89u8, 55u8, 116u8, 58u8, 45u8, 138u8, 50u8, 213u8, 253u8,
        7u8, 179u8, 27u8, 170u8, 119u8, 228u8, 163u8,
    ],
    vk_gamma_g2: [
        38u8, 202u8, 106u8, 37u8, 70u8, 160u8, 1u8, 126u8, 155u8, 138u8, 110u8, 105u8, 143u8, 21u8,
        61u8, 108u8, 102u8, 207u8, 197u8, 203u8, 57u8, 213u8, 194u8, 11u8, 170u8, 152u8, 89u8,
        145u8, 239u8, 198u8, 197u8, 158u8, 7u8, 11u8, 163u8, 232u8, 27u8, 212u8, 178u8, 54u8,
        166u8, 212u8, 77u8, 67u8, 234u8, 125u8, 245u8, 12u8, 126u8, 68u8, 45u8, 48u8, 141u8, 255u8,
        114u8, 142u8, 72u8, 241u8, 49u8, 111u8, 219u8, 215u8, 130u8, 62u8, 18u8, 46u8, 61u8, 157u8,
        86u8, 98u8, 188u8, 87u8, 162u8, 178u8, 46u8, 165u8, 242u8, 200u8, 212u8, 31u8, 210u8,
        212u8, 8u8, 249u8, 37u8, 106u8, 196u8, 244u8, 47u8, 109u8, 75u8, 39u8, 69u8, 97u8, 205u8,
        12u8, 43u8, 4u8, 204u8, 30u8, 32u8, 52u8, 22u8, 39u8, 126u8, 254u8, 184u8, 136u8, 160u8,
        221u8, 96u8, 241u8, 196u8, 28u8, 244u8, 173u8, 20u8, 41u8, 89u8, 207u8, 246u8, 44u8, 14u8,
        93u8, 196u8, 1u8, 103u8, 145u8,
    ],
    vk_delta_g2: [
        43u8, 151u8, 207u8, 175u8, 190u8, 166u8, 142u8, 241u8, 215u8, 202u8, 194u8, 91u8, 109u8,
        149u8, 213u8, 13u8, 147u8, 76u8, 93u8, 241u8, 133u8, 57u8, 237u8, 2u8, 193u8, 193u8, 25u8,
        210u8, 99u8, 64u8, 70u8, 136u8, 32u8, 217u8, 62u8, 50u8, 189u8, 35u8, 122u8, 99u8, 154u8,
        141u8, 14u8, 195u8, 71u8, 50u8, 93u8, 202u8, 14u8, 228u8, 82u8, 5u8, 73u8, 79u8, 133u8,
        46u8, 250u8, 54u8, 101u8, 252u8, 144u8, 90u8, 154u8, 202u8, 14u8, 163u8, 202u8, 2u8, 106u8,
        202u8, 60u8, 225u8, 222u8, 0u8, 36u8, 67u8, 188u8, 180u8, 129u8, 108u8, 45u8, 183u8, 99u8,
        152u8, 20u8, 20u8, 173u8, 123u8, 76u8, 200u8, 32u8, 85u8, 179u8, 154u8, 174u8, 70u8, 15u8,
        209u8, 84u8, 156u8, 75u8, 65u8, 158u8, 243u8, 22u8, 18u8, 175u8, 121u8, 46u8, 89u8, 183u8,
        65u8, 54u8, 168u8, 86u8, 177u8, 65u8, 182u8, 83u8, 157u8, 178u8, 244u8, 243u8, 179u8,
        119u8, 35u8, 117u8, 4u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [125u8, 166u8, 135u8, 149u8, 32u8, 106u8, 225u8, 219u8, 157u8, 199u8, 30u8, 4u8, 122u8, 204u8, 132u8, 152u8, 230u8, 208u8, 203u8, 158u8, 212u8, 21u8, 157u8, 238u8, 95u8, 128u8, 102u8, 24u8, 208u8, 7u8, 121u8, 188u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_7e2501f69d23a5ed")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x007da68795206ae1db9dc71e047acc8498e6d0cb9ed4159dee5f806618d00779bc\x00=======END GROTH16 VK SETUP V1=======\x00";
