// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        10u8, 216u8, 50u8, 78u8, 48u8, 165u8, 89u8, 196u8, 233u8, 126u8, 146u8, 229u8, 200u8,
        175u8, 226u8, 70u8, 248u8, 82u8, 43u8, 112u8, 254u8, 68u8, 232u8, 114u8, 106u8, 88u8, 25u8,
        194u8, 76u8, 227u8, 176u8, 84u8, 23u8, 61u8, 232u8, 152u8, 71u8, 91u8, 61u8, 179u8, 130u8,
        176u8, 117u8, 82u8, 40u8, 182u8, 87u8, 204u8, 2u8, 91u8, 104u8, 200u8, 42u8, 89u8, 10u8,
        40u8, 39u8, 176u8, 32u8, 66u8, 92u8, 129u8, 208u8, 149u8,
    ],
    [
        48u8, 79u8, 222u8, 31u8, 69u8, 225u8, 174u8, 253u8, 43u8, 88u8, 151u8, 22u8, 109u8, 7u8,
        87u8, 70u8, 14u8, 28u8, 126u8, 30u8, 53u8, 22u8, 14u8, 128u8, 222u8, 141u8, 254u8, 159u8,
        187u8, 23u8, 87u8, 225u8, 0u8, 129u8, 152u8, 25u8, 187u8, 76u8, 244u8, 126u8, 232u8, 84u8,
        58u8, 82u8, 24u8, 106u8, 112u8, 247u8, 78u8, 250u8, 36u8, 8u8, 138u8, 129u8, 193u8, 227u8,
        197u8, 91u8, 97u8, 195u8, 248u8, 164u8, 8u8, 202u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        41u8, 137u8, 255u8, 33u8, 143u8, 105u8, 121u8, 225u8, 44u8, 205u8, 179u8, 9u8, 237u8,
        229u8, 31u8, 22u8, 79u8, 215u8, 142u8, 42u8, 61u8, 44u8, 89u8, 71u8, 73u8, 207u8, 28u8,
        124u8, 158u8, 183u8, 40u8, 205u8, 1u8, 187u8, 192u8, 15u8, 36u8, 228u8, 233u8, 152u8,
        232u8, 74u8, 142u8, 161u8, 168u8, 184u8, 142u8, 229u8, 6u8, 31u8, 58u8, 243u8, 29u8, 205u8,
        160u8, 101u8, 135u8, 26u8, 20u8, 184u8, 184u8, 166u8, 202u8, 107u8,
    ],
    vk_beta_g2: [
        21u8, 123u8, 102u8, 217u8, 16u8, 45u8, 65u8, 21u8, 177u8, 73u8, 112u8, 230u8, 232u8, 201u8,
        91u8, 183u8, 142u8, 21u8, 28u8, 198u8, 78u8, 123u8, 32u8, 191u8, 131u8, 87u8, 218u8, 62u8,
        233u8, 48u8, 86u8, 12u8, 39u8, 41u8, 221u8, 108u8, 129u8, 253u8, 99u8, 38u8, 15u8, 98u8,
        113u8, 141u8, 107u8, 89u8, 191u8, 171u8, 140u8, 74u8, 180u8, 218u8, 211u8, 177u8, 240u8,
        248u8, 173u8, 226u8, 73u8, 132u8, 196u8, 147u8, 113u8, 43u8, 5u8, 143u8, 30u8, 30u8, 159u8,
        32u8, 220u8, 156u8, 209u8, 243u8, 199u8, 211u8, 252u8, 110u8, 108u8, 194u8, 159u8, 72u8,
        161u8, 184u8, 22u8, 26u8, 92u8, 72u8, 150u8, 252u8, 124u8, 35u8, 172u8, 41u8, 233u8, 254u8,
        5u8, 122u8, 44u8, 211u8, 118u8, 110u8, 78u8, 37u8, 17u8, 208u8, 199u8, 196u8, 143u8, 115u8,
        53u8, 32u8, 29u8, 251u8, 138u8, 101u8, 189u8, 120u8, 51u8, 160u8, 76u8, 175u8, 78u8, 65u8,
        171u8, 90u8, 253u8, 91u8,
    ],
    vk_gamma_g2: [
        1u8, 249u8, 12u8, 81u8, 245u8, 69u8, 1u8, 121u8, 176u8, 197u8, 93u8, 37u8, 6u8, 90u8, 20u8,
        79u8, 69u8, 96u8, 237u8, 19u8, 196u8, 162u8, 102u8, 66u8, 135u8, 217u8, 35u8, 114u8, 96u8,
        205u8, 52u8, 223u8, 21u8, 181u8, 186u8, 234u8, 93u8, 133u8, 186u8, 117u8, 111u8, 212u8,
        97u8, 184u8, 194u8, 220u8, 163u8, 22u8, 60u8, 96u8, 155u8, 205u8, 130u8, 209u8, 211u8,
        123u8, 49u8, 13u8, 88u8, 212u8, 146u8, 76u8, 186u8, 174u8, 20u8, 243u8, 143u8, 90u8, 34u8,
        245u8, 178u8, 84u8, 67u8, 118u8, 138u8, 4u8, 8u8, 98u8, 85u8, 234u8, 34u8, 112u8, 73u8,
        56u8, 39u8, 241u8, 109u8, 116u8, 75u8, 105u8, 239u8, 24u8, 167u8, 17u8, 245u8, 34u8, 32u8,
        239u8, 165u8, 37u8, 12u8, 13u8, 49u8, 95u8, 94u8, 16u8, 9u8, 226u8, 152u8, 187u8, 209u8,
        74u8, 245u8, 178u8, 87u8, 42u8, 127u8, 215u8, 221u8, 170u8, 158u8, 177u8, 203u8, 95u8,
        50u8, 227u8, 127u8, 172u8,
    ],
    vk_delta_g2: [
        2u8, 154u8, 176u8, 86u8, 3u8, 54u8, 35u8, 247u8, 137u8, 96u8, 251u8, 39u8, 29u8, 200u8,
        113u8, 114u8, 115u8, 65u8, 114u8, 85u8, 215u8, 27u8, 101u8, 230u8, 42u8, 162u8, 204u8,
        46u8, 12u8, 163u8, 203u8, 160u8, 4u8, 136u8, 71u8, 182u8, 225u8, 164u8, 163u8, 196u8,
        159u8, 180u8, 171u8, 144u8, 98u8, 90u8, 221u8, 63u8, 133u8, 233u8, 209u8, 26u8, 138u8,
        206u8, 248u8, 246u8, 185u8, 146u8, 173u8, 150u8, 70u8, 71u8, 76u8, 195u8, 47u8, 65u8,
        193u8, 157u8, 53u8, 43u8, 197u8, 125u8, 181u8, 204u8, 12u8, 126u8, 109u8, 81u8, 16u8,
        101u8, 151u8, 239u8, 70u8, 223u8, 140u8, 54u8, 246u8, 79u8, 142u8, 79u8, 178u8, 82u8, 11u8,
        226u8, 198u8, 79u8, 32u8, 247u8, 156u8, 156u8, 16u8, 147u8, 252u8, 14u8, 147u8, 192u8,
        17u8, 140u8, 132u8, 84u8, 213u8, 45u8, 232u8, 25u8, 161u8, 219u8, 221u8, 126u8, 146u8,
        28u8, 86u8, 166u8, 6u8, 124u8, 122u8, 229u8, 58u8, 148u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [163u8, 108u8, 49u8, 78u8, 89u8, 147u8, 67u8, 104u8, 244u8, 100u8, 142u8, 8u8, 38u8, 165u8, 132u8, 98u8, 44u8, 74u8, 157u8, 90u8, 240u8, 108u8, 195u8, 198u8, 26u8, 15u8, 76u8, 243u8, 75u8, 201u8, 211u8, 162u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_074b28e028c7b380")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00a36c314e59934368f4648e0826a584622c4a9d5af06cc3c61a0f4cf34bc9d3a2\x00=======END GROTH16 VK SETUP V1=======\x00";
