// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        10u8, 247u8, 135u8, 53u8, 181u8, 141u8, 120u8, 0u8, 78u8, 169u8, 253u8, 89u8, 155u8, 155u8,
        27u8, 85u8, 92u8, 90u8, 89u8, 145u8, 84u8, 229u8, 22u8, 185u8, 246u8, 112u8, 87u8, 124u8,
        30u8, 80u8, 208u8, 3u8, 42u8, 207u8, 121u8, 184u8, 120u8, 10u8, 30u8, 116u8, 179u8, 184u8,
        120u8, 92u8, 155u8, 62u8, 65u8, 18u8, 110u8, 36u8, 143u8, 28u8, 15u8, 113u8, 201u8, 64u8,
        10u8, 177u8, 202u8, 146u8, 70u8, 32u8, 179u8, 252u8,
    ],
    [
        4u8, 97u8, 28u8, 87u8, 21u8, 243u8, 69u8, 203u8, 172u8, 200u8, 48u8, 64u8, 250u8, 143u8,
        51u8, 204u8, 60u8, 207u8, 103u8, 110u8, 41u8, 25u8, 207u8, 152u8, 164u8, 3u8, 7u8, 108u8,
        170u8, 216u8, 41u8, 29u8, 16u8, 134u8, 96u8, 194u8, 27u8, 116u8, 58u8, 148u8, 90u8, 122u8,
        251u8, 234u8, 224u8, 38u8, 183u8, 88u8, 200u8, 17u8, 142u8, 69u8, 128u8, 184u8, 118u8,
        213u8, 182u8, 232u8, 99u8, 158u8, 72u8, 121u8, 112u8, 31u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        47u8, 141u8, 52u8, 169u8, 217u8, 193u8, 1u8, 70u8, 137u8, 30u8, 176u8, 102u8, 50u8, 14u8,
        211u8, 239u8, 138u8, 87u8, 24u8, 0u8, 109u8, 13u8, 120u8, 205u8, 220u8, 148u8, 152u8, 41u8,
        197u8, 157u8, 110u8, 191u8, 29u8, 191u8, 9u8, 51u8, 172u8, 65u8, 147u8, 253u8, 39u8, 198u8,
        24u8, 219u8, 63u8, 77u8, 254u8, 252u8, 6u8, 120u8, 72u8, 46u8, 116u8, 137u8, 34u8, 242u8,
        43u8, 227u8, 120u8, 236u8, 89u8, 228u8, 217u8, 212u8,
    ],
    vk_beta_g2: [
        46u8, 249u8, 194u8, 44u8, 86u8, 178u8, 72u8, 9u8, 202u8, 97u8, 168u8, 67u8, 184u8, 82u8,
        130u8, 250u8, 215u8, 202u8, 243u8, 105u8, 184u8, 99u8, 145u8, 141u8, 71u8, 179u8, 231u8,
        253u8, 49u8, 80u8, 164u8, 211u8, 13u8, 213u8, 64u8, 102u8, 101u8, 217u8, 75u8, 237u8,
        176u8, 27u8, 255u8, 71u8, 62u8, 190u8, 61u8, 78u8, 236u8, 63u8, 156u8, 79u8, 104u8, 244u8,
        21u8, 234u8, 132u8, 205u8, 164u8, 41u8, 151u8, 11u8, 13u8, 143u8, 23u8, 223u8, 92u8, 28u8,
        94u8, 120u8, 247u8, 58u8, 58u8, 105u8, 186u8, 84u8, 72u8, 227u8, 250u8, 63u8, 56u8, 53u8,
        15u8, 129u8, 25u8, 92u8, 236u8, 245u8, 176u8, 8u8, 3u8, 61u8, 184u8, 217u8, 250u8, 180u8,
        9u8, 96u8, 206u8, 117u8, 142u8, 224u8, 242u8, 71u8, 124u8, 95u8, 84u8, 236u8, 200u8, 113u8,
        178u8, 66u8, 224u8, 143u8, 131u8, 194u8, 22u8, 30u8, 143u8, 241u8, 68u8, 74u8, 43u8, 255u8,
        187u8, 61u8, 72u8, 100u8,
    ],
    vk_gamma_g2: [
        43u8, 196u8, 50u8, 230u8, 193u8, 229u8, 122u8, 111u8, 150u8, 115u8, 237u8, 112u8, 145u8,
        85u8, 166u8, 106u8, 45u8, 225u8, 21u8, 54u8, 211u8, 179u8, 23u8, 214u8, 119u8, 226u8, 30u8,
        42u8, 64u8, 69u8, 156u8, 224u8, 40u8, 11u8, 162u8, 76u8, 8u8, 82u8, 159u8, 240u8, 79u8,
        226u8, 225u8, 38u8, 180u8, 162u8, 115u8, 161u8, 185u8, 9u8, 240u8, 126u8, 132u8, 198u8,
        23u8, 211u8, 138u8, 95u8, 109u8, 178u8, 155u8, 0u8, 228u8, 59u8, 46u8, 77u8, 184u8, 115u8,
        190u8, 147u8, 121u8, 165u8, 129u8, 154u8, 55u8, 124u8, 226u8, 243u8, 3u8, 25u8, 196u8,
        234u8, 210u8, 122u8, 124u8, 174u8, 38u8, 197u8, 33u8, 141u8, 94u8, 88u8, 213u8, 157u8,
        68u8, 192u8, 19u8, 83u8, 132u8, 146u8, 23u8, 71u8, 216u8, 222u8, 43u8, 37u8, 110u8, 190u8,
        187u8, 99u8, 155u8, 181u8, 118u8, 24u8, 29u8, 161u8, 181u8, 23u8, 17u8, 219u8, 41u8, 84u8,
        117u8, 115u8, 73u8, 14u8, 48u8, 233u8,
    ],
    vk_delta_g2: [
        6u8, 134u8, 85u8, 239u8, 224u8, 196u8, 255u8, 162u8, 56u8, 205u8, 102u8, 129u8, 82u8, 7u8,
        59u8, 227u8, 246u8, 230u8, 83u8, 95u8, 198u8, 206u8, 166u8, 247u8, 128u8, 221u8, 248u8,
        194u8, 111u8, 32u8, 63u8, 91u8, 21u8, 182u8, 94u8, 148u8, 106u8, 108u8, 80u8, 143u8, 86u8,
        188u8, 170u8, 72u8, 28u8, 106u8, 106u8, 169u8, 154u8, 38u8, 56u8, 183u8, 2u8, 98u8, 133u8,
        130u8, 236u8, 128u8, 95u8, 170u8, 40u8, 250u8, 124u8, 159u8, 33u8, 163u8, 163u8, 28u8,
        92u8, 183u8, 24u8, 156u8, 82u8, 126u8, 214u8, 19u8, 124u8, 231u8, 189u8, 220u8, 253u8,
        195u8, 111u8, 226u8, 71u8, 225u8, 144u8, 72u8, 113u8, 228u8, 31u8, 68u8, 38u8, 71u8, 90u8,
        201u8, 44u8, 245u8, 235u8, 244u8, 17u8, 128u8, 235u8, 246u8, 189u8, 50u8, 157u8, 1u8,
        157u8, 27u8, 133u8, 59u8, 230u8, 19u8, 95u8, 6u8, 145u8, 177u8, 135u8, 105u8, 37u8, 227u8,
        8u8, 138u8, 6u8, 42u8, 171u8, 117u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [160u8, 136u8, 127u8, 84u8, 49u8, 241u8, 45u8, 250u8, 22u8, 246u8, 242u8, 230u8, 97u8, 244u8, 104u8, 140u8, 13u8, 69u8, 83u8, 140u8, 150u8, 199u8, 161u8, 231u8, 245u8, 15u8, 65u8, 226u8, 50u8, 202u8, 19u8, 200u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_2225a50de777a9c7")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00a0887f5431f12dfa16f6f2e661f4688c0d45538c96c7a1e7f50f41e232ca13c8\x00=======END GROTH16 VK SETUP V1=======\x00";
