// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        5u8, 122u8, 251u8, 196u8, 41u8, 178u8, 245u8, 216u8, 85u8, 225u8, 117u8, 82u8, 195u8, 7u8,
        152u8, 155u8, 201u8, 247u8, 32u8, 229u8, 177u8, 187u8, 29u8, 182u8, 235u8, 210u8, 58u8,
        168u8, 98u8, 215u8, 128u8, 254u8, 15u8, 132u8, 234u8, 243u8, 30u8, 140u8, 219u8, 92u8,
        232u8, 80u8, 133u8, 161u8, 232u8, 62u8, 134u8, 160u8, 62u8, 189u8, 23u8, 135u8, 102u8,
        232u8, 24u8, 28u8, 52u8, 155u8, 254u8, 252u8, 98u8, 227u8, 225u8, 87u8,
    ],
    [
        38u8, 204u8, 22u8, 200u8, 57u8, 119u8, 34u8, 1u8, 8u8, 215u8, 219u8, 10u8, 80u8, 202u8,
        122u8, 42u8, 136u8, 41u8, 100u8, 126u8, 131u8, 19u8, 183u8, 229u8, 34u8, 178u8, 161u8,
        219u8, 208u8, 223u8, 102u8, 225u8, 14u8, 41u8, 30u8, 218u8, 7u8, 136u8, 96u8, 152u8, 74u8,
        18u8, 113u8, 23u8, 241u8, 239u8, 221u8, 213u8, 128u8, 252u8, 92u8, 71u8, 93u8, 42u8, 70u8,
        101u8, 27u8, 224u8, 173u8, 65u8, 167u8, 55u8, 21u8, 80u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        13u8, 12u8, 216u8, 60u8, 75u8, 94u8, 78u8, 57u8, 219u8, 158u8, 124u8, 131u8, 213u8, 71u8,
        174u8, 76u8, 116u8, 184u8, 106u8, 35u8, 182u8, 45u8, 30u8, 205u8, 64u8, 8u8, 107u8, 222u8,
        18u8, 117u8, 19u8, 212u8, 31u8, 49u8, 26u8, 7u8, 236u8, 1u8, 59u8, 145u8, 140u8, 166u8,
        149u8, 6u8, 170u8, 141u8, 72u8, 108u8, 72u8, 158u8, 203u8, 254u8, 163u8, 110u8, 119u8,
        124u8, 59u8, 223u8, 210u8, 54u8, 31u8, 249u8, 161u8, 59u8,
    ],
    vk_beta_g2: [
        9u8, 187u8, 129u8, 49u8, 10u8, 222u8, 185u8, 120u8, 109u8, 8u8, 31u8, 83u8, 175u8, 240u8,
        90u8, 17u8, 159u8, 217u8, 93u8, 215u8, 251u8, 50u8, 36u8, 230u8, 228u8, 25u8, 78u8, 91u8,
        156u8, 181u8, 91u8, 57u8, 17u8, 164u8, 196u8, 194u8, 155u8, 98u8, 100u8, 89u8, 167u8,
        166u8, 26u8, 216u8, 67u8, 139u8, 164u8, 42u8, 191u8, 122u8, 202u8, 230u8, 57u8, 177u8,
        136u8, 92u8, 84u8, 41u8, 250u8, 27u8, 235u8, 178u8, 29u8, 138u8, 19u8, 79u8, 28u8, 114u8,
        169u8, 44u8, 4u8, 215u8, 129u8, 164u8, 71u8, 113u8, 14u8, 201u8, 60u8, 45u8, 21u8, 9u8,
        118u8, 225u8, 83u8, 128u8, 168u8, 167u8, 28u8, 145u8, 92u8, 58u8, 63u8, 66u8, 237u8, 24u8,
        42u8, 225u8, 6u8, 38u8, 112u8, 233u8, 38u8, 82u8, 201u8, 72u8, 226u8, 31u8, 188u8, 66u8,
        162u8, 53u8, 187u8, 169u8, 186u8, 79u8, 221u8, 184u8, 37u8, 46u8, 53u8, 190u8, 170u8,
        116u8, 180u8, 246u8, 165u8, 111u8,
    ],
    vk_gamma_g2: [
        17u8, 195u8, 172u8, 205u8, 36u8, 167u8, 170u8, 9u8, 201u8, 12u8, 189u8, 180u8, 117u8,
        111u8, 7u8, 140u8, 178u8, 212u8, 244u8, 89u8, 25u8, 59u8, 214u8, 247u8, 142u8, 170u8,
        176u8, 90u8, 19u8, 188u8, 2u8, 249u8, 20u8, 155u8, 146u8, 67u8, 24u8, 89u8, 65u8, 15u8,
        218u8, 219u8, 254u8, 3u8, 247u8, 216u8, 181u8, 149u8, 220u8, 1u8, 38u8, 108u8, 133u8,
        230u8, 40u8, 117u8, 20u8, 186u8, 68u8, 92u8, 51u8, 236u8, 147u8, 115u8, 23u8, 244u8, 0u8,
        58u8, 149u8, 59u8, 179u8, 3u8, 176u8, 247u8, 66u8, 250u8, 153u8, 156u8, 145u8, 22u8, 143u8,
        132u8, 146u8, 107u8, 83u8, 4u8, 72u8, 80u8, 165u8, 65u8, 151u8, 134u8, 85u8, 209u8, 178u8,
        246u8, 14u8, 249u8, 174u8, 102u8, 15u8, 156u8, 119u8, 77u8, 255u8, 206u8, 215u8, 251u8,
        51u8, 151u8, 42u8, 220u8, 93u8, 230u8, 94u8, 205u8, 147u8, 125u8, 220u8, 166u8, 162u8,
        245u8, 52u8, 177u8, 220u8, 101u8, 89u8, 138u8,
    ],
    vk_delta_g2: [
        34u8, 44u8, 211u8, 242u8, 37u8, 120u8, 97u8, 40u8, 213u8, 179u8, 203u8, 6u8, 153u8, 249u8,
        153u8, 200u8, 224u8, 0u8, 219u8, 241u8, 19u8, 1u8, 46u8, 38u8, 13u8, 202u8, 55u8, 181u8,
        220u8, 1u8, 165u8, 51u8, 2u8, 178u8, 20u8, 156u8, 255u8, 195u8, 231u8, 190u8, 157u8, 7u8,
        188u8, 41u8, 242u8, 141u8, 252u8, 147u8, 130u8, 84u8, 23u8, 200u8, 121u8, 34u8, 78u8,
        163u8, 148u8, 59u8, 180u8, 167u8, 174u8, 183u8, 188u8, 212u8, 20u8, 180u8, 188u8, 5u8,
        118u8, 149u8, 11u8, 202u8, 184u8, 189u8, 96u8, 217u8, 99u8, 237u8, 89u8, 152u8, 197u8,
        33u8, 77u8, 14u8, 183u8, 82u8, 245u8, 133u8, 214u8, 18u8, 11u8, 145u8, 84u8, 24u8, 23u8,
        154u8, 37u8, 207u8, 213u8, 134u8, 55u8, 185u8, 175u8, 227u8, 187u8, 171u8, 154u8, 180u8,
        224u8, 165u8, 63u8, 204u8, 241u8, 42u8, 137u8, 95u8, 230u8, 202u8, 106u8, 132u8, 193u8,
        251u8, 208u8, 229u8, 102u8, 197u8, 175u8, 39u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [67u8, 55u8, 131u8, 86u8, 10u8, 248u8, 201u8, 215u8, 170u8, 210u8, 191u8, 89u8, 233u8, 158u8, 124u8, 172u8, 5u8, 114u8, 82u8, 222u8, 3u8, 1u8, 53u8, 138u8, 236u8, 94u8, 101u8, 121u8, 4u8, 196u8, 153u8, 112u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_e720d7a89c918632")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00433783560af8c9d7aad2bf59e99e7cac057252de0301358aec5e657904c49970\x00=======END GROTH16 VK SETUP V1=======\x00";
