// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        37u8, 155u8, 76u8, 17u8, 29u8, 237u8, 135u8, 83u8, 193u8, 200u8, 29u8, 156u8, 237u8, 80u8,
        168u8, 167u8, 47u8, 34u8, 49u8, 157u8, 186u8, 127u8, 69u8, 143u8, 86u8, 85u8, 228u8, 189u8,
        186u8, 93u8, 13u8, 17u8, 38u8, 86u8, 216u8, 239u8, 124u8, 136u8, 50u8, 81u8, 212u8, 29u8,
        37u8, 28u8, 38u8, 204u8, 154u8, 211u8, 219u8, 139u8, 228u8, 63u8, 51u8, 69u8, 44u8, 114u8,
        24u8, 166u8, 134u8, 87u8, 209u8, 164u8, 36u8, 181u8,
    ],
    [
        18u8, 56u8, 243u8, 206u8, 59u8, 115u8, 192u8, 187u8, 213u8, 68u8, 197u8, 97u8, 102u8, 58u8,
        29u8, 219u8, 142u8, 222u8, 143u8, 72u8, 205u8, 222u8, 151u8, 230u8, 146u8, 249u8, 155u8,
        191u8, 111u8, 216u8, 181u8, 182u8, 24u8, 197u8, 253u8, 112u8, 78u8, 249u8, 6u8, 13u8, 51u8,
        59u8, 90u8, 88u8, 218u8, 222u8, 35u8, 46u8, 87u8, 159u8, 91u8, 137u8, 106u8, 49u8, 45u8,
        46u8, 103u8, 181u8, 37u8, 205u8, 199u8, 56u8, 127u8, 168u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        38u8, 78u8, 174u8, 239u8, 142u8, 222u8, 217u8, 56u8, 86u8, 227u8, 205u8, 32u8, 172u8, 7u8,
        137u8, 249u8, 91u8, 184u8, 63u8, 159u8, 83u8, 129u8, 242u8, 11u8, 122u8, 75u8, 90u8, 195u8,
        221u8, 26u8, 65u8, 117u8, 20u8, 48u8, 68u8, 77u8, 31u8, 24u8, 120u8, 77u8, 93u8, 124u8,
        248u8, 103u8, 79u8, 237u8, 240u8, 106u8, 41u8, 237u8, 48u8, 31u8, 57u8, 67u8, 124u8, 180u8,
        149u8, 170u8, 139u8, 13u8, 5u8, 9u8, 113u8, 211u8,
    ],
    vk_beta_g2: [
        1u8, 167u8, 94u8, 99u8, 161u8, 132u8, 110u8, 166u8, 133u8, 79u8, 78u8, 129u8, 101u8, 124u8,
        157u8, 209u8, 217u8, 158u8, 196u8, 81u8, 100u8, 216u8, 166u8, 84u8, 248u8, 204u8, 207u8,
        237u8, 10u8, 162u8, 26u8, 128u8, 38u8, 103u8, 118u8, 240u8, 38u8, 26u8, 182u8, 125u8, 41u8,
        48u8, 185u8, 152u8, 39u8, 201u8, 208u8, 210u8, 120u8, 253u8, 20u8, 44u8, 75u8, 172u8, 56u8,
        238u8, 216u8, 33u8, 14u8, 182u8, 159u8, 154u8, 11u8, 48u8, 12u8, 23u8, 248u8, 231u8, 244u8,
        104u8, 167u8, 246u8, 190u8, 174u8, 245u8, 249u8, 241u8, 154u8, 231u8, 229u8, 208u8, 162u8,
        48u8, 239u8, 33u8, 26u8, 142u8, 219u8, 160u8, 180u8, 235u8, 94u8, 187u8, 197u8, 108u8,
        30u8, 22u8, 141u8, 184u8, 112u8, 122u8, 151u8, 207u8, 239u8, 98u8, 216u8, 242u8, 86u8,
        193u8, 222u8, 140u8, 127u8, 133u8, 209u8, 160u8, 86u8, 53u8, 69u8, 178u8, 173u8, 125u8,
        88u8, 191u8, 64u8, 99u8, 156u8, 54u8, 22u8,
    ],
    vk_gamma_g2: [
        38u8, 221u8, 163u8, 106u8, 213u8, 3u8, 228u8, 198u8, 208u8, 167u8, 99u8, 100u8, 25u8,
        144u8, 154u8, 193u8, 237u8, 135u8, 208u8, 5u8, 5u8, 174u8, 112u8, 57u8, 231u8, 88u8, 146u8,
        139u8, 181u8, 175u8, 250u8, 170u8, 20u8, 89u8, 122u8, 1u8, 243u8, 142u8, 195u8, 10u8,
        253u8, 93u8, 204u8, 180u8, 1u8, 74u8, 40u8, 149u8, 136u8, 202u8, 133u8, 2u8, 180u8, 249u8,
        203u8, 106u8, 176u8, 44u8, 108u8, 254u8, 124u8, 4u8, 159u8, 174u8, 46u8, 68u8, 159u8, 79u8,
        110u8, 110u8, 31u8, 5u8, 153u8, 6u8, 62u8, 120u8, 33u8, 161u8, 155u8, 98u8, 9u8, 111u8,
        219u8, 78u8, 93u8, 175u8, 195u8, 199u8, 232u8, 12u8, 61u8, 104u8, 68u8, 214u8, 65u8, 154u8,
        16u8, 242u8, 43u8, 214u8, 229u8, 130u8, 27u8, 214u8, 30u8, 244u8, 188u8, 141u8, 78u8, 79u8,
        174u8, 132u8, 57u8, 206u8, 174u8, 193u8, 59u8, 28u8, 80u8, 162u8, 153u8, 224u8, 133u8,
        168u8, 202u8, 213u8, 54u8, 138u8,
    ],
    vk_delta_g2: [
        44u8, 7u8, 251u8, 186u8, 4u8, 44u8, 94u8, 161u8, 172u8, 216u8, 4u8, 91u8, 232u8, 118u8,
        222u8, 129u8, 227u8, 50u8, 168u8, 189u8, 42u8, 250u8, 176u8, 32u8, 129u8, 217u8, 170u8,
        237u8, 14u8, 67u8, 234u8, 123u8, 20u8, 159u8, 109u8, 224u8, 80u8, 184u8, 247u8, 231u8,
        246u8, 227u8, 25u8, 51u8, 117u8, 251u8, 255u8, 181u8, 13u8, 181u8, 173u8, 22u8, 171u8,
        147u8, 50u8, 126u8, 96u8, 120u8, 215u8, 250u8, 30u8, 158u8, 22u8, 181u8, 8u8, 88u8, 124u8,
        199u8, 57u8, 243u8, 192u8, 87u8, 227u8, 140u8, 130u8, 35u8, 28u8, 108u8, 52u8, 153u8, 89u8,
        35u8, 163u8, 78u8, 212u8, 64u8, 97u8, 123u8, 115u8, 117u8, 140u8, 108u8, 55u8, 147u8,
        124u8, 197u8, 44u8, 115u8, 13u8, 185u8, 124u8, 77u8, 207u8, 205u8, 24u8, 76u8, 93u8, 144u8,
        169u8, 77u8, 219u8, 196u8, 60u8, 206u8, 223u8, 192u8, 96u8, 194u8, 248u8, 28u8, 130u8,
        187u8, 228u8, 54u8, 13u8, 208u8, 75u8, 137u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [1u8, 14u8, 43u8, 161u8, 97u8, 116u8, 115u8, 179u8, 221u8, 252u8, 182u8, 127u8, 194u8, 76u8, 133u8, 50u8, 112u8, 19u8, 183u8, 63u8, 65u8, 206u8, 58u8, 64u8, 119u8, 229u8, 58u8, 30u8, 19u8, 160u8, 16u8, 21u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_b9efe406bc67e3b3")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00010e2ba1617473b3ddfcb67fc24c85327013b73f41ce3a4077e53a1e13a01015\x00=======END GROTH16 VK SETUP V1=======\x00";
