//! Committed Groth16 verifying keys.
//!
//! The key modules are generated by `regenerate_all_vkeys.sh` from Prover keys.

mod circuit;
pub use circuit::{
    valid_cache_writes, Bsb22Commitment, CacheAccess, CacheWrite, CircuitId, OutputOwnerMode,
    RingP256ProofData, MAX_CACHE_WRITES,
};

#[cfg(feature = "verifying-keys")]
pub mod merge_36_1;
#[cfg(feature = "verifying-keys")]
pub mod merge_8_1;
#[cfg(feature = "verifying-keys")]
pub mod merge_ring_36_1;
#[cfg(feature = "verifying-keys")]
pub mod merge_ring_8_1;
#[cfg(feature = "verifying-keys")]
pub mod transfer_confidential_1_1;
#[cfg(feature = "verifying-keys")]
pub mod transfer_confidential_1_2;
#[cfg(feature = "verifying-keys")]
pub mod transfer_confidential_1_8;
#[cfg(feature = "verifying-keys")]
pub mod transfer_confidential_2_2;
#[cfg(feature = "verifying-keys")]
pub mod transfer_confidential_2_3;
#[cfg(feature = "verifying-keys")]
pub mod transfer_confidential_36_2;
#[cfg(feature = "verifying-keys")]
pub mod transfer_confidential_3_3;
#[cfg(feature = "verifying-keys")]
pub mod transfer_confidential_4_3;
#[cfg(feature = "verifying-keys")]
pub mod transfer_confidential_4_4;
#[cfg(feature = "verifying-keys")]
pub mod transfer_confidential_5_3;
#[cfg(feature = "verifying-keys")]
pub mod transfer_confidential_5_4;
#[cfg(feature = "verifying-keys")]
pub mod transfer_p256_ring_1_1;
#[cfg(feature = "verifying-keys")]
pub mod transfer_p256_ring_1_2;
#[cfg(feature = "verifying-keys")]
pub mod transfer_p256_ring_1_8;
#[cfg(feature = "verifying-keys")]
pub mod transfer_p256_ring_2_2;
#[cfg(feature = "verifying-keys")]
pub mod transfer_p256_ring_2_3;
#[cfg(feature = "verifying-keys")]
pub mod transfer_p256_ring_36_2;
#[cfg(feature = "verifying-keys")]
pub mod transfer_p256_ring_3_3;
#[cfg(feature = "verifying-keys")]
pub mod transfer_p256_ring_4_3;
#[cfg(feature = "verifying-keys")]
pub mod transfer_p256_ring_4_4;
#[cfg(feature = "verifying-keys")]
pub mod transfer_p256_ring_5_3;
#[cfg(feature = "verifying-keys")]
pub mod transfer_p256_ring_5_4;
#[cfg(feature = "verifying-keys")]
pub mod transfer_ring_1_1;
#[cfg(feature = "verifying-keys")]
pub mod transfer_ring_1_2;
#[cfg(feature = "verifying-keys")]
pub mod transfer_ring_1_8;
#[cfg(feature = "verifying-keys")]
pub mod transfer_ring_2_2;
#[cfg(feature = "verifying-keys")]
pub mod transfer_ring_2_3;
#[cfg(feature = "verifying-keys")]
pub mod transfer_ring_36_2;
#[cfg(feature = "verifying-keys")]
pub mod transfer_ring_3_3;
#[cfg(feature = "verifying-keys")]
pub mod transfer_ring_4_3;
#[cfg(feature = "verifying-keys")]
pub mod transfer_ring_4_4;
#[cfg(feature = "verifying-keys")]
pub mod transfer_ring_5_3;
#[cfg(feature = "verifying-keys")]
pub mod transfer_ring_5_4;
#[cfg(feature = "verifying-keys")]
pub mod transfer_ring_authority_1_1;
#[cfg(feature = "verifying-keys")]
pub mod transfer_ring_authority_2_2;
#[cfg(feature = "verifying-keys")]
pub mod transfer_ring_authority_3_3;
#[cfg(feature = "verifying-keys")]
pub mod transfer_ring_authority_4_4;

/// Proving key file name, as in proving-keys.lock and the prover's
/// `/proving-keys`, and the sha256 its committed verifying key pins.
#[cfg(feature = "verifying-keys")]
pub const PROVING_KEY_SHA256S: &[(&str, [u8; 32])] = &[
    (
        "merge_36_1.key",
        merge_36_1::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    ("merge_8_1.key", merge_8_1::VERIFYINGKEY_PROVING_KEY_SHA256),
    (
        "merge_ring_36_1.key",
        merge_ring_36_1::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "merge_ring_8_1.key",
        merge_ring_8_1::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_confidential_1_1.key",
        transfer_confidential_1_1::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_confidential_1_2.key",
        transfer_confidential_1_2::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_confidential_1_8.key",
        transfer_confidential_1_8::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_confidential_2_2.key",
        transfer_confidential_2_2::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_confidential_2_3.key",
        transfer_confidential_2_3::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_confidential_36_2.key",
        transfer_confidential_36_2::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_confidential_3_3.key",
        transfer_confidential_3_3::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_confidential_4_3.key",
        transfer_confidential_4_3::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_confidential_4_4.key",
        transfer_confidential_4_4::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_confidential_5_3.key",
        transfer_confidential_5_3::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_confidential_5_4.key",
        transfer_confidential_5_4::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_p256_ring_1_1.key",
        transfer_p256_ring_1_1::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_p256_ring_1_2.key",
        transfer_p256_ring_1_2::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_p256_ring_1_8.key",
        transfer_p256_ring_1_8::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_p256_ring_2_2.key",
        transfer_p256_ring_2_2::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_p256_ring_2_3.key",
        transfer_p256_ring_2_3::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_p256_ring_36_2.key",
        transfer_p256_ring_36_2::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_p256_ring_3_3.key",
        transfer_p256_ring_3_3::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_p256_ring_4_3.key",
        transfer_p256_ring_4_3::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_p256_ring_4_4.key",
        transfer_p256_ring_4_4::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_p256_ring_5_3.key",
        transfer_p256_ring_5_3::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_p256_ring_5_4.key",
        transfer_p256_ring_5_4::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_ring_1_1.key",
        transfer_ring_1_1::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_ring_1_2.key",
        transfer_ring_1_2::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_ring_1_8.key",
        transfer_ring_1_8::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_ring_2_2.key",
        transfer_ring_2_2::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_ring_2_3.key",
        transfer_ring_2_3::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_ring_36_2.key",
        transfer_ring_36_2::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_ring_3_3.key",
        transfer_ring_3_3::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_ring_4_3.key",
        transfer_ring_4_3::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_ring_4_4.key",
        transfer_ring_4_4::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_ring_5_3.key",
        transfer_ring_5_3::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_ring_5_4.key",
        transfer_ring_5_4::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_ring_authority_1_1.key",
        transfer_ring_authority_1_1::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_ring_authority_2_2.key",
        transfer_ring_authority_2_2::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_ring_authority_3_3.key",
        transfer_ring_authority_3_3::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
    (
        "transfer_ring_authority_4_4.key",
        transfer_ring_authority_4_4::VERIFYINGKEY_PROVING_KEY_SHA256,
    ),
];
