// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        26u8, 170u8, 43u8, 27u8, 43u8, 59u8, 10u8, 221u8, 204u8, 162u8, 169u8, 29u8, 99u8, 66u8,
        29u8, 42u8, 39u8, 189u8, 218u8, 136u8, 64u8, 18u8, 75u8, 246u8, 245u8, 20u8, 133u8, 127u8,
        55u8, 159u8, 159u8, 231u8, 3u8, 66u8, 91u8, 172u8, 127u8, 169u8, 15u8, 242u8, 212u8, 138u8,
        50u8, 88u8, 58u8, 166u8, 129u8, 59u8, 236u8, 168u8, 33u8, 158u8, 28u8, 175u8, 177u8, 44u8,
        167u8, 14u8, 236u8, 155u8, 70u8, 20u8, 253u8, 195u8,
    ],
    [
        36u8, 114u8, 187u8, 149u8, 208u8, 87u8, 39u8, 76u8, 225u8, 99u8, 210u8, 73u8, 207u8, 112u8,
        157u8, 223u8, 35u8, 128u8, 5u8, 157u8, 86u8, 108u8, 60u8, 97u8, 243u8, 125u8, 77u8, 225u8,
        131u8, 250u8, 180u8, 113u8, 22u8, 32u8, 33u8, 41u8, 146u8, 233u8, 143u8, 108u8, 180u8,
        48u8, 26u8, 127u8, 1u8, 201u8, 223u8, 217u8, 18u8, 61u8, 118u8, 53u8, 86u8, 77u8, 63u8,
        35u8, 6u8, 227u8, 30u8, 222u8, 96u8, 3u8, 235u8, 241u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        18u8, 194u8, 164u8, 231u8, 57u8, 201u8, 154u8, 130u8, 6u8, 202u8, 224u8, 174u8, 123u8,
        119u8, 119u8, 225u8, 211u8, 35u8, 124u8, 154u8, 154u8, 247u8, 68u8, 252u8, 168u8, 116u8,
        14u8, 109u8, 132u8, 114u8, 50u8, 171u8, 27u8, 92u8, 4u8, 65u8, 84u8, 186u8, 122u8, 42u8,
        115u8, 245u8, 142u8, 13u8, 73u8, 78u8, 81u8, 195u8, 218u8, 19u8, 7u8, 114u8, 164u8, 176u8,
        18u8, 242u8, 105u8, 218u8, 20u8, 85u8, 211u8, 8u8, 15u8, 34u8,
    ],
    vk_beta_g2: [
        42u8, 63u8, 167u8, 204u8, 185u8, 112u8, 195u8, 67u8, 235u8, 111u8, 52u8, 189u8, 108u8,
        172u8, 144u8, 74u8, 184u8, 4u8, 49u8, 40u8, 1u8, 175u8, 122u8, 225u8, 57u8, 179u8, 172u8,
        102u8, 233u8, 138u8, 4u8, 53u8, 31u8, 26u8, 104u8, 228u8, 17u8, 134u8, 78u8, 46u8, 2u8,
        189u8, 81u8, 117u8, 252u8, 248u8, 230u8, 151u8, 136u8, 104u8, 247u8, 102u8, 226u8, 22u8,
        181u8, 210u8, 50u8, 8u8, 201u8, 70u8, 112u8, 110u8, 239u8, 225u8, 26u8, 111u8, 56u8, 13u8,
        174u8, 219u8, 198u8, 54u8, 206u8, 118u8, 43u8, 132u8, 33u8, 24u8, 26u8, 76u8, 213u8, 38u8,
        209u8, 228u8, 203u8, 123u8, 107u8, 127u8, 89u8, 255u8, 225u8, 198u8, 67u8, 27u8, 87u8,
        49u8, 31u8, 203u8, 88u8, 208u8, 69u8, 191u8, 102u8, 118u8, 250u8, 254u8, 95u8, 146u8,
        111u8, 209u8, 192u8, 97u8, 122u8, 12u8, 147u8, 35u8, 157u8, 212u8, 93u8, 40u8, 224u8,
        242u8, 172u8, 105u8, 74u8, 92u8, 73u8, 56u8,
    ],
    vk_gamma_g2: [
        7u8, 231u8, 138u8, 60u8, 113u8, 176u8, 76u8, 204u8, 215u8, 160u8, 13u8, 42u8, 173u8, 164u8,
        230u8, 110u8, 46u8, 158u8, 247u8, 52u8, 101u8, 210u8, 73u8, 134u8, 195u8, 156u8, 93u8,
        200u8, 176u8, 207u8, 28u8, 153u8, 47u8, 180u8, 77u8, 252u8, 172u8, 210u8, 81u8, 49u8,
        170u8, 135u8, 226u8, 143u8, 164u8, 36u8, 83u8, 18u8, 237u8, 72u8, 190u8, 181u8, 54u8, 37u8,
        185u8, 132u8, 159u8, 146u8, 109u8, 150u8, 142u8, 10u8, 239u8, 232u8, 30u8, 90u8, 233u8,
        56u8, 163u8, 20u8, 17u8, 221u8, 145u8, 172u8, 16u8, 4u8, 242u8, 67u8, 16u8, 241u8, 158u8,
        188u8, 244u8, 156u8, 100u8, 147u8, 12u8, 81u8, 117u8, 154u8, 238u8, 99u8, 205u8, 155u8,
        123u8, 84u8, 30u8, 223u8, 226u8, 166u8, 10u8, 82u8, 140u8, 146u8, 6u8, 241u8, 33u8, 253u8,
        110u8, 43u8, 188u8, 202u8, 212u8, 168u8, 30u8, 213u8, 60u8, 64u8, 145u8, 50u8, 169u8, 71u8,
        116u8, 101u8, 33u8, 28u8, 211u8, 94u8,
    ],
    vk_delta_g2: [
        33u8, 117u8, 89u8, 153u8, 218u8, 253u8, 186u8, 187u8, 224u8, 217u8, 193u8, 184u8, 151u8,
        134u8, 166u8, 22u8, 119u8, 91u8, 238u8, 179u8, 157u8, 208u8, 234u8, 189u8, 133u8, 251u8,
        105u8, 20u8, 12u8, 26u8, 235u8, 100u8, 22u8, 79u8, 73u8, 178u8, 54u8, 207u8, 129u8, 110u8,
        29u8, 37u8, 74u8, 205u8, 145u8, 13u8, 29u8, 198u8, 54u8, 126u8, 192u8, 1u8, 243u8, 17u8,
        130u8, 28u8, 99u8, 95u8, 243u8, 216u8, 119u8, 242u8, 123u8, 111u8, 21u8, 12u8, 164u8,
        120u8, 254u8, 9u8, 106u8, 153u8, 230u8, 21u8, 177u8, 31u8, 77u8, 44u8, 77u8, 132u8, 32u8,
        201u8, 33u8, 68u8, 105u8, 92u8, 0u8, 50u8, 208u8, 98u8, 163u8, 171u8, 64u8, 24u8, 206u8,
        38u8, 27u8, 16u8, 155u8, 233u8, 42u8, 164u8, 182u8, 224u8, 203u8, 101u8, 243u8, 112u8,
        176u8, 67u8, 66u8, 113u8, 11u8, 108u8, 145u8, 157u8, 230u8, 59u8, 103u8, 69u8, 241u8,
        129u8, 194u8, 179u8, 44u8, 69u8, 166u8, 66u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [108u8, 110u8, 217u8, 58u8, 244u8, 221u8, 96u8, 74u8, 36u8, 0u8, 88u8, 115u8, 144u8, 113u8, 103u8, 191u8, 113u8, 184u8, 103u8, 22u8, 59u8, 107u8, 55u8, 37u8, 8u8, 148u8, 38u8, 170u8, 34u8, 20u8, 61u8, 125u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_5fcbdd326c497525")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x006c6ed93af4dd604a24005873907167bf71b867163b6b3725089426aa22143d7d\x00=======END GROTH16 VK SETUP V1=======\x00";
