// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        6u8, 240u8, 96u8, 136u8, 144u8, 5u8, 76u8, 233u8, 173u8, 213u8, 41u8, 74u8, 62u8, 145u8,
        243u8, 76u8, 171u8, 27u8, 96u8, 32u8, 12u8, 197u8, 228u8, 93u8, 102u8, 159u8, 83u8, 42u8,
        208u8, 186u8, 255u8, 204u8, 37u8, 101u8, 50u8, 125u8, 171u8, 217u8, 11u8, 83u8, 27u8,
        122u8, 129u8, 128u8, 140u8, 120u8, 33u8, 139u8, 65u8, 201u8, 145u8, 224u8, 16u8, 188u8,
        44u8, 90u8, 209u8, 247u8, 23u8, 92u8, 31u8, 86u8, 131u8, 34u8,
    ],
    [
        6u8, 127u8, 24u8, 91u8, 249u8, 45u8, 253u8, 37u8, 184u8, 63u8, 124u8, 164u8, 80u8, 54u8,
        29u8, 152u8, 142u8, 0u8, 81u8, 35u8, 145u8, 75u8, 163u8, 43u8, 221u8, 253u8, 105u8, 173u8,
        164u8, 68u8, 53u8, 233u8, 44u8, 243u8, 109u8, 50u8, 227u8, 175u8, 247u8, 116u8, 247u8,
        236u8, 83u8, 214u8, 216u8, 28u8, 225u8, 176u8, 157u8, 47u8, 196u8, 149u8, 188u8, 109u8,
        14u8, 208u8, 19u8, 0u8, 52u8, 50u8, 230u8, 165u8, 234u8, 26u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        2u8, 34u8, 88u8, 113u8, 174u8, 246u8, 193u8, 110u8, 27u8, 64u8, 120u8, 6u8, 195u8, 147u8,
        69u8, 129u8, 239u8, 215u8, 67u8, 196u8, 37u8, 84u8, 106u8, 165u8, 126u8, 46u8, 104u8,
        222u8, 187u8, 169u8, 177u8, 207u8, 46u8, 144u8, 98u8, 130u8, 188u8, 86u8, 161u8, 163u8,
        19u8, 50u8, 64u8, 186u8, 132u8, 109u8, 91u8, 215u8, 17u8, 27u8, 76u8, 29u8, 31u8, 9u8,
        236u8, 136u8, 157u8, 120u8, 65u8, 179u8, 22u8, 166u8, 210u8, 110u8,
    ],
    vk_beta_g2: [
        40u8, 15u8, 146u8, 26u8, 95u8, 154u8, 215u8, 207u8, 103u8, 188u8, 85u8, 249u8, 168u8, 68u8,
        226u8, 214u8, 128u8, 56u8, 196u8, 231u8, 121u8, 5u8, 119u8, 107u8, 45u8, 22u8, 132u8, 45u8,
        210u8, 211u8, 191u8, 161u8, 44u8, 115u8, 170u8, 201u8, 127u8, 239u8, 176u8, 228u8, 252u8,
        81u8, 99u8, 139u8, 44u8, 27u8, 253u8, 13u8, 229u8, 138u8, 4u8, 1u8, 6u8, 221u8, 162u8,
        155u8, 140u8, 79u8, 237u8, 218u8, 247u8, 192u8, 98u8, 93u8, 44u8, 198u8, 51u8, 180u8, 29u8,
        165u8, 251u8, 12u8, 32u8, 157u8, 103u8, 58u8, 163u8, 241u8, 136u8, 83u8, 98u8, 127u8,
        147u8, 88u8, 36u8, 162u8, 110u8, 220u8, 181u8, 185u8, 216u8, 29u8, 205u8, 64u8, 17u8, 75u8,
        20u8, 217u8, 203u8, 68u8, 50u8, 21u8, 68u8, 101u8, 105u8, 4u8, 23u8, 240u8, 174u8, 235u8,
        89u8, 133u8, 146u8, 89u8, 39u8, 33u8, 141u8, 223u8, 190u8, 128u8, 65u8, 96u8, 30u8, 69u8,
        15u8, 177u8, 204u8, 212u8,
    ],
    vk_gamma_g2: [
        23u8, 66u8, 106u8, 151u8, 36u8, 212u8, 194u8, 37u8, 170u8, 228u8, 109u8, 125u8, 168u8,
        49u8, 204u8, 188u8, 161u8, 46u8, 181u8, 243u8, 189u8, 129u8, 173u8, 68u8, 237u8, 141u8,
        189u8, 52u8, 7u8, 126u8, 177u8, 177u8, 17u8, 244u8, 29u8, 192u8, 88u8, 236u8, 21u8, 176u8,
        165u8, 15u8, 122u8, 173u8, 168u8, 48u8, 194u8, 218u8, 61u8, 234u8, 125u8, 230u8, 45u8,
        160u8, 90u8, 43u8, 29u8, 32u8, 36u8, 169u8, 121u8, 215u8, 204u8, 246u8, 44u8, 184u8, 88u8,
        70u8, 255u8, 146u8, 49u8, 38u8, 61u8, 61u8, 55u8, 207u8, 117u8, 186u8, 192u8, 241u8, 140u8,
        3u8, 158u8, 60u8, 134u8, 234u8, 132u8, 165u8, 66u8, 181u8, 126u8, 253u8, 154u8, 187u8,
        251u8, 68u8, 41u8, 78u8, 131u8, 182u8, 168u8, 232u8, 103u8, 59u8, 185u8, 11u8, 203u8,
        150u8, 108u8, 187u8, 46u8, 252u8, 42u8, 41u8, 49u8, 139u8, 76u8, 151u8, 177u8, 255u8,
        122u8, 107u8, 238u8, 234u8, 206u8, 211u8, 244u8, 167u8,
    ],
    vk_delta_g2: [
        10u8, 223u8, 241u8, 242u8, 149u8, 101u8, 229u8, 171u8, 28u8, 233u8, 176u8, 212u8, 154u8,
        94u8, 30u8, 199u8, 87u8, 208u8, 176u8, 172u8, 196u8, 3u8, 121u8, 82u8, 78u8, 120u8, 194u8,
        100u8, 1u8, 84u8, 250u8, 10u8, 41u8, 243u8, 243u8, 76u8, 37u8, 22u8, 41u8, 105u8, 46u8,
        168u8, 164u8, 254u8, 243u8, 233u8, 209u8, 146u8, 158u8, 8u8, 246u8, 67u8, 186u8, 118u8,
        131u8, 205u8, 209u8, 112u8, 114u8, 146u8, 9u8, 95u8, 153u8, 72u8, 39u8, 93u8, 94u8, 102u8,
        130u8, 161u8, 6u8, 216u8, 79u8, 189u8, 44u8, 216u8, 155u8, 113u8, 62u8, 108u8, 133u8,
        133u8, 38u8, 105u8, 34u8, 244u8, 133u8, 107u8, 191u8, 183u8, 44u8, 118u8, 241u8, 31u8,
        76u8, 57u8, 42u8, 168u8, 69u8, 207u8, 15u8, 128u8, 66u8, 165u8, 221u8, 88u8, 187u8, 233u8,
        154u8, 220u8, 155u8, 185u8, 239u8, 236u8, 121u8, 32u8, 5u8, 107u8, 220u8, 196u8, 138u8,
        121u8, 51u8, 43u8, 101u8, 101u8, 168u8, 190u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [254u8, 98u8, 223u8, 240u8, 57u8, 118u8, 98u8, 203u8, 37u8, 216u8, 154u8, 201u8, 222u8, 151u8, 108u8, 195u8, 210u8, 58u8, 223u8, 210u8, 183u8, 167u8, 47u8, 95u8, 138u8, 216u8, 103u8, 29u8, 103u8, 125u8, 166u8, 5u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_74f38f79a2f0b0e0")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00fe62dff0397662cb25d89ac9de976cc3d23adfd2b7a72f5f8ad8671d677da605\x00=======END GROTH16 VK SETUP V1=======\x00";
