// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        33u8, 56u8, 105u8, 190u8, 103u8, 95u8, 210u8, 221u8, 240u8, 239u8, 0u8, 177u8, 74u8, 14u8,
        91u8, 104u8, 36u8, 43u8, 137u8, 76u8, 14u8, 61u8, 51u8, 82u8, 18u8, 138u8, 222u8, 4u8,
        32u8, 37u8, 89u8, 33u8, 3u8, 91u8, 153u8, 121u8, 178u8, 127u8, 253u8, 73u8, 101u8, 33u8,
        48u8, 34u8, 88u8, 120u8, 123u8, 67u8, 176u8, 134u8, 104u8, 204u8, 156u8, 36u8, 119u8,
        140u8, 0u8, 188u8, 106u8, 220u8, 183u8, 50u8, 229u8, 223u8,
    ],
    [
        47u8, 113u8, 182u8, 91u8, 222u8, 192u8, 54u8, 159u8, 83u8, 42u8, 110u8, 126u8, 163u8, 84u8,
        207u8, 218u8, 19u8, 128u8, 182u8, 6u8, 87u8, 252u8, 30u8, 51u8, 210u8, 71u8, 38u8, 232u8,
        255u8, 145u8, 228u8, 29u8, 0u8, 230u8, 177u8, 36u8, 152u8, 251u8, 251u8, 107u8, 62u8, 39u8,
        184u8, 26u8, 175u8, 120u8, 0u8, 15u8, 161u8, 146u8, 168u8, 115u8, 0u8, 203u8, 78u8, 136u8,
        156u8, 182u8, 144u8, 241u8, 182u8, 79u8, 149u8, 47u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        27u8, 249u8, 70u8, 200u8, 3u8, 243u8, 132u8, 72u8, 83u8, 191u8, 87u8, 247u8, 103u8, 143u8,
        35u8, 103u8, 73u8, 122u8, 199u8, 180u8, 112u8, 66u8, 134u8, 190u8, 154u8, 136u8, 82u8,
        202u8, 179u8, 17u8, 193u8, 214u8, 16u8, 228u8, 204u8, 91u8, 208u8, 205u8, 50u8, 92u8,
        197u8, 244u8, 72u8, 215u8, 201u8, 52u8, 31u8, 63u8, 210u8, 0u8, 62u8, 111u8, 28u8, 35u8,
        127u8, 229u8, 201u8, 145u8, 41u8, 166u8, 248u8, 45u8, 209u8, 22u8,
    ],
    vk_beta_g2: [
        37u8, 52u8, 83u8, 98u8, 121u8, 248u8, 113u8, 38u8, 226u8, 75u8, 96u8, 118u8, 89u8, 53u8,
        122u8, 50u8, 12u8, 152u8, 147u8, 221u8, 58u8, 210u8, 109u8, 236u8, 11u8, 52u8, 189u8,
        163u8, 90u8, 165u8, 72u8, 252u8, 9u8, 230u8, 78u8, 81u8, 99u8, 31u8, 70u8, 8u8, 98u8,
        152u8, 13u8, 145u8, 238u8, 143u8, 64u8, 18u8, 214u8, 97u8, 36u8, 159u8, 185u8, 135u8,
        226u8, 120u8, 212u8, 70u8, 146u8, 131u8, 151u8, 215u8, 237u8, 160u8, 46u8, 176u8, 152u8,
        135u8, 75u8, 70u8, 234u8, 218u8, 163u8, 186u8, 96u8, 94u8, 23u8, 25u8, 110u8, 216u8, 134u8,
        2u8, 85u8, 144u8, 97u8, 218u8, 196u8, 201u8, 53u8, 60u8, 164u8, 133u8, 198u8, 83u8, 242u8,
        182u8, 34u8, 193u8, 54u8, 100u8, 38u8, 93u8, 65u8, 46u8, 95u8, 215u8, 249u8, 144u8, 32u8,
        185u8, 241u8, 68u8, 117u8, 76u8, 52u8, 69u8, 124u8, 177u8, 179u8, 130u8, 149u8, 6u8, 32u8,
        234u8, 213u8, 50u8, 113u8, 3u8,
    ],
    vk_gamma_g2: [
        31u8, 13u8, 36u8, 236u8, 94u8, 64u8, 94u8, 208u8, 184u8, 109u8, 20u8, 218u8, 78u8, 145u8,
        138u8, 242u8, 93u8, 200u8, 135u8, 8u8, 82u8, 177u8, 218u8, 38u8, 20u8, 34u8, 108u8, 183u8,
        186u8, 191u8, 235u8, 162u8, 11u8, 207u8, 201u8, 95u8, 142u8, 212u8, 198u8, 12u8, 26u8,
        10u8, 101u8, 151u8, 24u8, 217u8, 142u8, 106u8, 239u8, 60u8, 252u8, 240u8, 143u8, 74u8,
        154u8, 152u8, 80u8, 214u8, 241u8, 69u8, 246u8, 58u8, 72u8, 18u8, 13u8, 58u8, 52u8, 234u8,
        28u8, 103u8, 51u8, 186u8, 175u8, 210u8, 15u8, 212u8, 183u8, 191u8, 123u8, 10u8, 92u8, 56u8,
        117u8, 167u8, 218u8, 129u8, 172u8, 222u8, 170u8, 202u8, 59u8, 250u8, 146u8, 222u8, 97u8,
        36u8, 42u8, 185u8, 139u8, 16u8, 160u8, 247u8, 38u8, 208u8, 93u8, 11u8, 169u8, 51u8, 227u8,
        202u8, 151u8, 143u8, 0u8, 156u8, 96u8, 169u8, 181u8, 165u8, 63u8, 98u8, 2u8, 215u8, 185u8,
        106u8, 236u8, 202u8, 145u8, 216u8,
    ],
    vk_delta_g2: [
        28u8, 182u8, 33u8, 157u8, 39u8, 34u8, 250u8, 94u8, 129u8, 219u8, 244u8, 52u8, 242u8, 72u8,
        145u8, 233u8, 42u8, 101u8, 44u8, 40u8, 98u8, 168u8, 253u8, 237u8, 237u8, 120u8, 27u8,
        133u8, 122u8, 151u8, 53u8, 252u8, 44u8, 78u8, 253u8, 208u8, 21u8, 250u8, 35u8, 87u8, 201u8,
        167u8, 173u8, 178u8, 180u8, 128u8, 124u8, 131u8, 69u8, 102u8, 11u8, 116u8, 147u8, 76u8,
        193u8, 153u8, 24u8, 38u8, 144u8, 41u8, 127u8, 205u8, 212u8, 200u8, 11u8, 142u8, 111u8,
        10u8, 22u8, 199u8, 160u8, 173u8, 15u8, 104u8, 205u8, 116u8, 219u8, 1u8, 154u8, 217u8,
        109u8, 212u8, 177u8, 196u8, 82u8, 31u8, 224u8, 189u8, 240u8, 251u8, 224u8, 147u8, 107u8,
        114u8, 245u8, 41u8, 41u8, 234u8, 97u8, 90u8, 9u8, 190u8, 36u8, 181u8, 88u8, 201u8, 222u8,
        172u8, 194u8, 156u8, 84u8, 241u8, 20u8, 141u8, 24u8, 187u8, 15u8, 126u8, 9u8, 189u8, 144u8,
        34u8, 130u8, 63u8, 4u8, 151u8, 160u8, 77u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [174u8, 160u8, 196u8, 116u8, 228u8, 198u8, 116u8, 153u8, 196u8, 95u8, 17u8, 243u8, 13u8, 45u8, 3u8, 229u8, 62u8, 229u8, 221u8, 124u8, 107u8, 121u8, 64u8, 160u8, 246u8, 28u8, 254u8, 250u8, 46u8, 97u8, 227u8, 142u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_16e9a5c73e142dc7")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00aea0c474e4c67499c45f11f30d2d03e53ee5dd7c6b7940a0f61cfefa2e61e38e\x00=======END GROTH16 VK SETUP V1=======\x00";
