// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        24u8, 253u8, 172u8, 76u8, 94u8, 220u8, 186u8, 25u8, 65u8, 49u8, 69u8, 96u8, 121u8, 204u8,
        171u8, 23u8, 92u8, 220u8, 98u8, 151u8, 245u8, 58u8, 68u8, 1u8, 59u8, 146u8, 105u8, 152u8,
        110u8, 63u8, 192u8, 27u8, 15u8, 3u8, 178u8, 48u8, 5u8, 100u8, 99u8, 199u8, 97u8, 151u8,
        143u8, 77u8, 160u8, 64u8, 165u8, 62u8, 55u8, 240u8, 121u8, 38u8, 237u8, 195u8, 254u8,
        127u8, 136u8, 206u8, 156u8, 171u8, 70u8, 165u8, 223u8, 239u8,
    ],
    [
        35u8, 176u8, 34u8, 106u8, 4u8, 209u8, 157u8, 130u8, 94u8, 104u8, 32u8, 216u8, 164u8, 162u8,
        58u8, 56u8, 4u8, 202u8, 39u8, 81u8, 9u8, 174u8, 113u8, 232u8, 206u8, 169u8, 120u8, 217u8,
        4u8, 42u8, 57u8, 11u8, 11u8, 112u8, 252u8, 107u8, 67u8, 54u8, 230u8, 105u8, 76u8, 87u8,
        127u8, 142u8, 96u8, 162u8, 144u8, 201u8, 218u8, 184u8, 68u8, 0u8, 81u8, 129u8, 202u8,
        236u8, 184u8, 114u8, 235u8, 52u8, 12u8, 75u8, 32u8, 148u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        17u8, 139u8, 74u8, 40u8, 35u8, 116u8, 188u8, 100u8, 232u8, 45u8, 176u8, 254u8, 220u8, 45u8,
        203u8, 155u8, 204u8, 134u8, 227u8, 108u8, 156u8, 161u8, 120u8, 58u8, 252u8, 60u8, 27u8,
        184u8, 185u8, 64u8, 206u8, 156u8, 44u8, 12u8, 65u8, 241u8, 215u8, 146u8, 134u8, 236u8,
        163u8, 238u8, 25u8, 236u8, 111u8, 215u8, 36u8, 253u8, 212u8, 91u8, 65u8, 99u8, 109u8,
        204u8, 177u8, 250u8, 59u8, 254u8, 234u8, 191u8, 95u8, 72u8, 121u8, 233u8,
    ],
    vk_beta_g2: [
        15u8, 3u8, 34u8, 97u8, 5u8, 242u8, 166u8, 173u8, 198u8, 197u8, 157u8, 218u8, 115u8, 194u8,
        173u8, 221u8, 122u8, 39u8, 47u8, 47u8, 198u8, 160u8, 143u8, 83u8, 183u8, 119u8, 153u8,
        251u8, 214u8, 50u8, 37u8, 254u8, 16u8, 179u8, 43u8, 214u8, 153u8, 237u8, 145u8, 64u8,
        107u8, 132u8, 27u8, 93u8, 38u8, 212u8, 164u8, 96u8, 167u8, 133u8, 235u8, 211u8, 6u8, 48u8,
        78u8, 219u8, 245u8, 207u8, 135u8, 114u8, 251u8, 15u8, 60u8, 108u8, 34u8, 185u8, 55u8,
        205u8, 13u8, 253u8, 34u8, 123u8, 219u8, 145u8, 223u8, 72u8, 36u8, 22u8, 52u8, 117u8, 5u8,
        44u8, 157u8, 54u8, 149u8, 168u8, 164u8, 241u8, 116u8, 185u8, 71u8, 208u8, 21u8, 189u8,
        254u8, 78u8, 27u8, 159u8, 36u8, 116u8, 58u8, 40u8, 150u8, 211u8, 121u8, 245u8, 241u8, 41u8,
        164u8, 207u8, 60u8, 116u8, 73u8, 203u8, 56u8, 170u8, 29u8, 132u8, 24u8, 167u8, 181u8,
        165u8, 71u8, 219u8, 236u8, 35u8, 211u8, 88u8,
    ],
    vk_gamma_g2: [
        3u8, 25u8, 240u8, 229u8, 14u8, 195u8, 20u8, 94u8, 71u8, 241u8, 236u8, 99u8, 1u8, 8u8,
        184u8, 97u8, 86u8, 57u8, 100u8, 164u8, 148u8, 145u8, 165u8, 35u8, 237u8, 192u8, 133u8,
        24u8, 201u8, 62u8, 187u8, 187u8, 17u8, 231u8, 100u8, 154u8, 156u8, 24u8, 201u8, 22u8, 87u8,
        90u8, 208u8, 39u8, 229u8, 133u8, 102u8, 64u8, 53u8, 49u8, 162u8, 53u8, 64u8, 194u8, 29u8,
        9u8, 126u8, 218u8, 155u8, 221u8, 11u8, 17u8, 172u8, 191u8, 11u8, 109u8, 53u8, 95u8, 231u8,
        17u8, 73u8, 169u8, 37u8, 66u8, 203u8, 124u8, 157u8, 220u8, 208u8, 115u8, 166u8, 238u8,
        127u8, 189u8, 65u8, 106u8, 101u8, 120u8, 49u8, 17u8, 13u8, 182u8, 135u8, 230u8, 110u8,
        187u8, 44u8, 90u8, 242u8, 162u8, 250u8, 133u8, 171u8, 59u8, 145u8, 151u8, 248u8, 116u8,
        182u8, 133u8, 215u8, 31u8, 215u8, 17u8, 137u8, 102u8, 13u8, 42u8, 100u8, 192u8, 191u8,
        28u8, 197u8, 173u8, 182u8, 74u8, 219u8, 178u8,
    ],
    vk_delta_g2: [
        42u8, 26u8, 148u8, 171u8, 237u8, 192u8, 223u8, 120u8, 173u8, 150u8, 99u8, 128u8, 197u8,
        66u8, 171u8, 255u8, 43u8, 214u8, 245u8, 140u8, 2u8, 143u8, 187u8, 146u8, 219u8, 65u8,
        184u8, 111u8, 173u8, 196u8, 249u8, 254u8, 25u8, 204u8, 64u8, 172u8, 27u8, 236u8, 21u8,
        229u8, 218u8, 131u8, 123u8, 185u8, 81u8, 199u8, 245u8, 255u8, 80u8, 19u8, 108u8, 214u8,
        83u8, 178u8, 234u8, 50u8, 192u8, 80u8, 218u8, 97u8, 89u8, 19u8, 38u8, 91u8, 37u8, 20u8,
        88u8, 139u8, 198u8, 253u8, 41u8, 17u8, 197u8, 26u8, 252u8, 198u8, 57u8, 244u8, 59u8, 41u8,
        46u8, 169u8, 176u8, 162u8, 86u8, 15u8, 209u8, 91u8, 220u8, 165u8, 15u8, 77u8, 109u8, 139u8,
        117u8, 135u8, 40u8, 165u8, 170u8, 22u8, 23u8, 51u8, 221u8, 251u8, 169u8, 226u8, 75u8, 42u8,
        27u8, 173u8, 69u8, 34u8, 111u8, 187u8, 250u8, 0u8, 224u8, 220u8, 52u8, 188u8, 186u8, 84u8,
        106u8, 43u8, 62u8, 207u8, 243u8, 149u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [4u8, 190u8, 90u8, 173u8, 65u8, 60u8, 252u8, 118u8, 72u8, 255u8, 29u8, 69u8, 89u8, 175u8, 106u8, 165u8, 73u8, 201u8, 237u8, 60u8, 95u8, 243u8, 127u8, 76u8, 22u8, 199u8, 65u8, 31u8, 195u8, 177u8, 124u8, 140u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_e60792e71b1b822d")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0004be5aad413cfc7648ff1d4559af6aa549c9ed3c5ff37f4c16c7411fc3b17c8c\x00=======END GROTH16 VK SETUP V1=======\x00";
