// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        35u8, 152u8, 232u8, 37u8, 178u8, 79u8, 101u8, 163u8, 127u8, 30u8, 37u8, 60u8, 232u8, 147u8,
        70u8, 56u8, 212u8, 41u8, 80u8, 9u8, 13u8, 233u8, 190u8, 192u8, 86u8, 64u8, 155u8, 120u8,
        194u8, 86u8, 240u8, 213u8, 5u8, 112u8, 152u8, 31u8, 167u8, 200u8, 122u8, 133u8, 44u8,
        141u8, 29u8, 104u8, 146u8, 129u8, 196u8, 115u8, 197u8, 203u8, 33u8, 129u8, 121u8, 207u8,
        68u8, 193u8, 132u8, 250u8, 55u8, 2u8, 113u8, 207u8, 39u8, 9u8,
    ],
    [
        37u8, 13u8, 178u8, 186u8, 99u8, 35u8, 244u8, 117u8, 235u8, 185u8, 50u8, 165u8, 212u8,
        219u8, 3u8, 137u8, 68u8, 140u8, 164u8, 191u8, 128u8, 181u8, 171u8, 80u8, 207u8, 35u8,
        232u8, 53u8, 69u8, 219u8, 122u8, 23u8, 32u8, 235u8, 245u8, 181u8, 116u8, 205u8, 10u8,
        186u8, 33u8, 72u8, 39u8, 55u8, 170u8, 98u8, 39u8, 155u8, 228u8, 92u8, 248u8, 246u8, 203u8,
        180u8, 34u8, 240u8, 255u8, 1u8, 225u8, 71u8, 253u8, 210u8, 48u8, 140u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        30u8, 37u8, 6u8, 44u8, 163u8, 115u8, 102u8, 60u8, 173u8, 124u8, 135u8, 26u8, 222u8, 43u8,
        92u8, 247u8, 105u8, 246u8, 7u8, 140u8, 242u8, 115u8, 246u8, 231u8, 169u8, 189u8, 7u8,
        106u8, 54u8, 101u8, 113u8, 109u8, 7u8, 205u8, 103u8, 223u8, 236u8, 251u8, 99u8, 12u8, 58u8,
        207u8, 195u8, 131u8, 172u8, 193u8, 38u8, 65u8, 178u8, 213u8, 219u8, 190u8, 128u8, 62u8,
        197u8, 30u8, 74u8, 149u8, 251u8, 204u8, 121u8, 190u8, 172u8, 203u8,
    ],
    vk_beta_g2: [
        31u8, 47u8, 173u8, 202u8, 109u8, 135u8, 180u8, 83u8, 75u8, 220u8, 235u8, 13u8, 65u8, 175u8,
        72u8, 236u8, 79u8, 139u8, 181u8, 34u8, 160u8, 251u8, 220u8, 5u8, 102u8, 103u8, 206u8,
        159u8, 126u8, 226u8, 158u8, 122u8, 27u8, 24u8, 173u8, 158u8, 26u8, 67u8, 222u8, 126u8,
        143u8, 68u8, 203u8, 71u8, 55u8, 220u8, 140u8, 156u8, 154u8, 169u8, 230u8, 120u8, 230u8,
        196u8, 37u8, 215u8, 100u8, 87u8, 38u8, 89u8, 72u8, 243u8, 118u8, 213u8, 44u8, 49u8, 212u8,
        250u8, 224u8, 245u8, 188u8, 25u8, 170u8, 238u8, 155u8, 91u8, 184u8, 183u8, 116u8, 71u8,
        72u8, 62u8, 214u8, 178u8, 106u8, 124u8, 1u8, 114u8, 65u8, 181u8, 252u8, 234u8, 159u8, 65u8,
        52u8, 178u8, 41u8, 25u8, 173u8, 100u8, 51u8, 152u8, 20u8, 83u8, 253u8, 129u8, 1u8, 233u8,
        127u8, 43u8, 41u8, 54u8, 9u8, 102u8, 80u8, 79u8, 9u8, 134u8, 227u8, 155u8, 163u8, 18u8,
        6u8, 204u8, 241u8, 89u8, 229u8, 128u8,
    ],
    vk_gamma_g2: [
        12u8, 225u8, 195u8, 89u8, 200u8, 172u8, 66u8, 97u8, 123u8, 141u8, 97u8, 242u8, 239u8,
        155u8, 86u8, 38u8, 252u8, 31u8, 125u8, 170u8, 79u8, 213u8, 19u8, 11u8, 177u8, 221u8, 244u8,
        12u8, 238u8, 29u8, 198u8, 152u8, 40u8, 70u8, 112u8, 185u8, 177u8, 25u8, 232u8, 11u8, 230u8,
        190u8, 249u8, 246u8, 202u8, 88u8, 160u8, 11u8, 93u8, 141u8, 241u8, 81u8, 72u8, 173u8, 79u8,
        150u8, 114u8, 216u8, 97u8, 73u8, 155u8, 40u8, 160u8, 194u8, 36u8, 38u8, 139u8, 232u8, 14u8,
        60u8, 232u8, 251u8, 192u8, 16u8, 216u8, 208u8, 15u8, 146u8, 162u8, 247u8, 119u8, 211u8,
        106u8, 225u8, 131u8, 182u8, 223u8, 194u8, 43u8, 75u8, 223u8, 255u8, 178u8, 243u8, 182u8,
        100u8, 20u8, 89u8, 31u8, 227u8, 232u8, 116u8, 251u8, 65u8, 95u8, 111u8, 3u8, 12u8, 250u8,
        208u8, 239u8, 100u8, 221u8, 63u8, 41u8, 241u8, 241u8, 162u8, 96u8, 181u8, 126u8, 101u8,
        191u8, 118u8, 158u8, 39u8, 210u8, 57u8,
    ],
    vk_delta_g2: [
        31u8, 233u8, 219u8, 22u8, 65u8, 149u8, 155u8, 59u8, 4u8, 154u8, 113u8, 91u8, 134u8, 120u8,
        211u8, 49u8, 241u8, 168u8, 101u8, 82u8, 152u8, 145u8, 169u8, 45u8, 223u8, 35u8, 122u8,
        13u8, 223u8, 129u8, 98u8, 76u8, 5u8, 77u8, 97u8, 179u8, 99u8, 65u8, 109u8, 70u8, 29u8,
        112u8, 253u8, 118u8, 132u8, 241u8, 162u8, 165u8, 230u8, 100u8, 0u8, 149u8, 207u8, 201u8,
        230u8, 70u8, 147u8, 15u8, 77u8, 157u8, 213u8, 65u8, 85u8, 88u8, 19u8, 37u8, 93u8, 11u8,
        110u8, 151u8, 157u8, 168u8, 15u8, 252u8, 220u8, 232u8, 221u8, 38u8, 24u8, 26u8, 127u8,
        254u8, 88u8, 241u8, 80u8, 112u8, 192u8, 114u8, 216u8, 128u8, 205u8, 191u8, 72u8, 7u8, 17u8,
        177u8, 5u8, 180u8, 186u8, 227u8, 130u8, 102u8, 193u8, 151u8, 76u8, 237u8, 61u8, 16u8,
        145u8, 119u8, 85u8, 102u8, 153u8, 202u8, 221u8, 210u8, 120u8, 14u8, 5u8, 213u8, 22u8, 21u8,
        76u8, 153u8, 138u8, 86u8, 84u8, 72u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [174u8, 202u8, 224u8, 82u8, 174u8, 183u8, 9u8, 239u8, 70u8, 86u8, 214u8, 218u8, 17u8, 11u8, 209u8, 64u8, 61u8, 33u8, 188u8, 88u8, 145u8, 230u8, 6u8, 145u8, 238u8, 156u8, 188u8, 14u8, 187u8, 70u8, 220u8, 185u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_a6720909017d09c9")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00aecae052aeb709ef4656d6da110bd1403d21bc5891e60691ee9cbc0ebb46dcb9\x00=======END GROTH16 VK SETUP V1=======\x00";
