// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        13u8, 49u8, 81u8, 27u8, 177u8, 84u8, 210u8, 227u8, 208u8, 192u8, 254u8, 216u8, 115u8,
        164u8, 10u8, 90u8, 107u8, 122u8, 168u8, 146u8, 128u8, 190u8, 97u8, 178u8, 3u8, 242u8,
        133u8, 115u8, 206u8, 31u8, 29u8, 101u8, 6u8, 65u8, 184u8, 193u8, 61u8, 236u8, 129u8, 84u8,
        193u8, 62u8, 71u8, 83u8, 199u8, 199u8, 248u8, 50u8, 22u8, 147u8, 43u8, 197u8, 28u8, 109u8,
        167u8, 73u8, 218u8, 54u8, 39u8, 196u8, 22u8, 180u8, 162u8, 117u8,
    ],
    [
        15u8, 155u8, 19u8, 241u8, 72u8, 243u8, 102u8, 46u8, 91u8, 207u8, 69u8, 250u8, 164u8, 87u8,
        130u8, 31u8, 67u8, 150u8, 233u8, 246u8, 10u8, 103u8, 197u8, 178u8, 160u8, 255u8, 101u8,
        65u8, 220u8, 225u8, 18u8, 121u8, 3u8, 153u8, 92u8, 68u8, 29u8, 81u8, 113u8, 123u8, 244u8,
        224u8, 147u8, 124u8, 39u8, 190u8, 205u8, 97u8, 179u8, 201u8, 128u8, 46u8, 124u8, 192u8,
        239u8, 93u8, 16u8, 169u8, 86u8, 226u8, 221u8, 35u8, 68u8, 29u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        3u8, 69u8, 203u8, 72u8, 253u8, 18u8, 79u8, 43u8, 113u8, 119u8, 53u8, 150u8, 31u8, 185u8,
        67u8, 114u8, 217u8, 5u8, 135u8, 234u8, 31u8, 157u8, 161u8, 58u8, 168u8, 44u8, 73u8, 140u8,
        187u8, 3u8, 186u8, 80u8, 11u8, 70u8, 121u8, 27u8, 14u8, 81u8, 74u8, 113u8, 39u8, 196u8,
        94u8, 198u8, 120u8, 81u8, 76u8, 175u8, 109u8, 15u8, 173u8, 242u8, 112u8, 120u8, 231u8,
        229u8, 72u8, 214u8, 210u8, 144u8, 102u8, 67u8, 223u8, 120u8,
    ],
    vk_beta_g2: [
        40u8, 0u8, 143u8, 48u8, 188u8, 184u8, 86u8, 79u8, 55u8, 235u8, 127u8, 48u8, 2u8, 106u8,
        71u8, 96u8, 183u8, 60u8, 152u8, 101u8, 26u8, 203u8, 109u8, 235u8, 41u8, 80u8, 18u8, 9u8,
        99u8, 113u8, 65u8, 177u8, 18u8, 131u8, 92u8, 216u8, 10u8, 246u8, 200u8, 171u8, 226u8,
        205u8, 73u8, 137u8, 89u8, 141u8, 137u8, 28u8, 227u8, 212u8, 184u8, 202u8, 150u8, 182u8,
        193u8, 128u8, 85u8, 157u8, 57u8, 218u8, 181u8, 130u8, 67u8, 113u8, 8u8, 90u8, 19u8, 246u8,
        21u8, 227u8, 1u8, 134u8, 160u8, 129u8, 55u8, 207u8, 169u8, 56u8, 40u8, 26u8, 21u8, 217u8,
        30u8, 98u8, 92u8, 23u8, 144u8, 192u8, 13u8, 202u8, 84u8, 156u8, 212u8, 187u8, 224u8, 201u8,
        34u8, 184u8, 70u8, 234u8, 4u8, 48u8, 238u8, 17u8, 229u8, 118u8, 96u8, 13u8, 37u8, 159u8,
        56u8, 157u8, 190u8, 25u8, 78u8, 181u8, 118u8, 176u8, 229u8, 217u8, 37u8, 92u8, 187u8, 48u8,
        99u8, 193u8, 184u8, 71u8,
    ],
    vk_gamma_g2: [
        36u8, 103u8, 103u8, 220u8, 188u8, 227u8, 3u8, 162u8, 160u8, 78u8, 16u8, 192u8, 153u8, 15u8,
        249u8, 198u8, 96u8, 81u8, 173u8, 146u8, 12u8, 240u8, 164u8, 17u8, 33u8, 29u8, 8u8, 35u8,
        250u8, 192u8, 58u8, 161u8, 6u8, 172u8, 64u8, 157u8, 193u8, 30u8, 126u8, 58u8, 208u8, 241u8,
        26u8, 0u8, 1u8, 110u8, 177u8, 205u8, 178u8, 184u8, 205u8, 172u8, 94u8, 59u8, 15u8, 214u8,
        166u8, 187u8, 68u8, 244u8, 120u8, 25u8, 226u8, 59u8, 38u8, 238u8, 134u8, 145u8, 8u8, 26u8,
        153u8, 98u8, 223u8, 17u8, 183u8, 200u8, 166u8, 117u8, 141u8, 62u8, 91u8, 133u8, 219u8,
        136u8, 168u8, 102u8, 150u8, 218u8, 220u8, 237u8, 174u8, 64u8, 26u8, 44u8, 218u8, 254u8,
        33u8, 237u8, 189u8, 158u8, 88u8, 115u8, 35u8, 176u8, 6u8, 25u8, 225u8, 125u8, 173u8, 229u8,
        113u8, 0u8, 37u8, 110u8, 78u8, 202u8, 59u8, 155u8, 28u8, 87u8, 126u8, 198u8, 64u8, 204u8,
        3u8, 155u8, 137u8, 148u8,
    ],
    vk_delta_g2: [
        21u8, 0u8, 200u8, 4u8, 60u8, 118u8, 77u8, 127u8, 135u8, 179u8, 244u8, 127u8, 30u8, 176u8,
        111u8, 192u8, 66u8, 253u8, 179u8, 101u8, 52u8, 186u8, 41u8, 67u8, 31u8, 165u8, 153u8,
        253u8, 221u8, 164u8, 195u8, 173u8, 34u8, 133u8, 13u8, 84u8, 141u8, 148u8, 135u8, 149u8,
        83u8, 114u8, 100u8, 216u8, 195u8, 47u8, 21u8, 228u8, 27u8, 3u8, 210u8, 54u8, 213u8, 255u8,
        75u8, 244u8, 112u8, 210u8, 181u8, 253u8, 89u8, 222u8, 29u8, 122u8, 0u8, 99u8, 60u8, 83u8,
        126u8, 8u8, 215u8, 62u8, 35u8, 23u8, 85u8, 189u8, 154u8, 231u8, 114u8, 214u8, 174u8, 74u8,
        71u8, 199u8, 112u8, 67u8, 242u8, 35u8, 133u8, 208u8, 205u8, 241u8, 189u8, 102u8, 200u8,
        43u8, 32u8, 139u8, 101u8, 107u8, 82u8, 42u8, 23u8, 20u8, 37u8, 230u8, 144u8, 211u8, 79u8,
        211u8, 3u8, 33u8, 104u8, 134u8, 116u8, 112u8, 163u8, 174u8, 26u8, 129u8, 129u8, 113u8,
        238u8, 109u8, 151u8, 63u8, 20u8, 225u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [132u8, 117u8, 25u8, 222u8, 139u8, 27u8, 173u8, 13u8, 79u8, 113u8, 95u8, 170u8, 106u8, 152u8, 32u8, 38u8, 89u8, 12u8, 17u8, 79u8, 58u8, 153u8, 6u8, 160u8, 225u8, 229u8, 109u8, 21u8, 55u8, 207u8, 169u8, 136u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_99271899ec59f0b6")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00847519de8b1bad0d4f715faa6a982026590c114f3a9906a0e1e56d1537cfa988\x00=======END GROTH16 VK SETUP V1=======\x00";
