// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        14u8, 85u8, 50u8, 48u8, 101u8, 35u8, 2u8, 37u8, 86u8, 255u8, 236u8, 185u8, 130u8, 52u8,
        55u8, 8u8, 203u8, 108u8, 7u8, 30u8, 89u8, 180u8, 179u8, 217u8, 60u8, 58u8, 51u8, 61u8,
        110u8, 249u8, 243u8, 42u8, 42u8, 163u8, 242u8, 58u8, 159u8, 246u8, 69u8, 77u8, 66u8, 156u8,
        172u8, 174u8, 85u8, 233u8, 139u8, 62u8, 117u8, 49u8, 176u8, 248u8, 109u8, 169u8, 236u8,
        254u8, 233u8, 171u8, 208u8, 83u8, 36u8, 59u8, 10u8, 202u8,
    ],
    [
        17u8, 179u8, 168u8, 221u8, 32u8, 8u8, 128u8, 234u8, 254u8, 172u8, 188u8, 153u8, 233u8,
        112u8, 20u8, 137u8, 28u8, 115u8, 195u8, 168u8, 217u8, 70u8, 31u8, 116u8, 121u8, 15u8, 48u8,
        215u8, 132u8, 107u8, 35u8, 73u8, 28u8, 109u8, 4u8, 209u8, 210u8, 243u8, 122u8, 188u8, 21u8,
        197u8, 254u8, 55u8, 216u8, 7u8, 116u8, 83u8, 142u8, 161u8, 196u8, 201u8, 191u8, 193u8,
        223u8, 124u8, 52u8, 119u8, 6u8, 233u8, 90u8, 124u8, 253u8, 164u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        38u8, 101u8, 205u8, 171u8, 246u8, 1u8, 61u8, 2u8, 207u8, 175u8, 121u8, 91u8, 27u8, 134u8,
        249u8, 68u8, 144u8, 118u8, 248u8, 219u8, 249u8, 138u8, 218u8, 201u8, 33u8, 247u8, 117u8,
        133u8, 142u8, 173u8, 9u8, 109u8, 36u8, 198u8, 42u8, 37u8, 71u8, 83u8, 176u8, 13u8, 196u8,
        234u8, 119u8, 228u8, 97u8, 114u8, 37u8, 243u8, 232u8, 179u8, 193u8, 152u8, 101u8, 12u8,
        15u8, 209u8, 211u8, 121u8, 201u8, 159u8, 195u8, 210u8, 47u8, 221u8,
    ],
    vk_beta_g2: [
        38u8, 111u8, 42u8, 11u8, 75u8, 86u8, 98u8, 115u8, 171u8, 56u8, 149u8, 89u8, 177u8, 63u8,
        29u8, 253u8, 34u8, 176u8, 141u8, 186u8, 6u8, 164u8, 189u8, 27u8, 137u8, 128u8, 166u8,
        238u8, 178u8, 27u8, 55u8, 136u8, 9u8, 62u8, 37u8, 179u8, 241u8, 253u8, 114u8, 224u8, 148u8,
        196u8, 24u8, 193u8, 178u8, 72u8, 205u8, 86u8, 156u8, 154u8, 96u8, 218u8, 85u8, 169u8, 34u8,
        115u8, 194u8, 235u8, 205u8, 88u8, 135u8, 216u8, 138u8, 38u8, 36u8, 118u8, 201u8, 178u8,
        120u8, 131u8, 231u8, 30u8, 33u8, 36u8, 138u8, 244u8, 167u8, 125u8, 126u8, 2u8, 164u8, 50u8,
        59u8, 83u8, 52u8, 27u8, 200u8, 172u8, 76u8, 121u8, 139u8, 242u8, 109u8, 127u8, 157u8, 33u8,
        32u8, 29u8, 207u8, 171u8, 5u8, 248u8, 206u8, 166u8, 73u8, 162u8, 52u8, 128u8, 1u8, 230u8,
        215u8, 115u8, 13u8, 120u8, 3u8, 16u8, 19u8, 81u8, 47u8, 60u8, 123u8, 162u8, 175u8, 203u8,
        169u8, 148u8, 209u8, 76u8,
    ],
    vk_gamma_g2: [
        36u8, 136u8, 236u8, 84u8, 196u8, 124u8, 47u8, 31u8, 61u8, 38u8, 12u8, 154u8, 173u8, 185u8,
        133u8, 224u8, 139u8, 29u8, 11u8, 72u8, 169u8, 114u8, 181u8, 217u8, 44u8, 119u8, 24u8,
        107u8, 186u8, 181u8, 35u8, 45u8, 12u8, 209u8, 255u8, 198u8, 250u8, 224u8, 115u8, 40u8,
        237u8, 1u8, 84u8, 204u8, 103u8, 109u8, 158u8, 156u8, 21u8, 108u8, 249u8, 108u8, 221u8,
        54u8, 251u8, 184u8, 171u8, 63u8, 66u8, 48u8, 39u8, 36u8, 126u8, 58u8, 36u8, 225u8, 162u8,
        207u8, 198u8, 142u8, 108u8, 72u8, 146u8, 80u8, 199u8, 220u8, 124u8, 254u8, 174u8, 108u8,
        226u8, 27u8, 72u8, 0u8, 223u8, 171u8, 63u8, 214u8, 29u8, 177u8, 223u8, 78u8, 60u8, 204u8,
        49u8, 121u8, 3u8, 57u8, 202u8, 22u8, 74u8, 236u8, 149u8, 64u8, 255u8, 55u8, 92u8, 27u8,
        22u8, 17u8, 129u8, 189u8, 97u8, 194u8, 28u8, 113u8, 235u8, 142u8, 154u8, 23u8, 163u8, 4u8,
        203u8, 132u8, 15u8, 201u8, 104u8, 55u8,
    ],
    vk_delta_g2: [
        27u8, 228u8, 72u8, 117u8, 50u8, 220u8, 203u8, 249u8, 46u8, 35u8, 197u8, 23u8, 243u8, 167u8,
        23u8, 68u8, 222u8, 28u8, 141u8, 152u8, 35u8, 248u8, 230u8, 194u8, 86u8, 90u8, 96u8, 53u8,
        154u8, 88u8, 199u8, 88u8, 19u8, 202u8, 101u8, 233u8, 68u8, 242u8, 239u8, 76u8, 74u8, 220u8,
        60u8, 226u8, 0u8, 65u8, 252u8, 245u8, 88u8, 182u8, 34u8, 183u8, 63u8, 191u8, 167u8, 205u8,
        36u8, 68u8, 114u8, 208u8, 126u8, 19u8, 154u8, 60u8, 3u8, 204u8, 131u8, 104u8, 226u8, 56u8,
        67u8, 150u8, 144u8, 123u8, 99u8, 7u8, 86u8, 202u8, 66u8, 178u8, 251u8, 12u8, 40u8, 152u8,
        142u8, 64u8, 205u8, 133u8, 147u8, 117u8, 201u8, 46u8, 47u8, 203u8, 202u8, 3u8, 34u8, 188u8,
        174u8, 156u8, 33u8, 63u8, 26u8, 250u8, 237u8, 186u8, 73u8, 179u8, 176u8, 170u8, 163u8,
        62u8, 100u8, 14u8, 227u8, 255u8, 27u8, 33u8, 225u8, 207u8, 54u8, 232u8, 4u8, 134u8, 53u8,
        238u8, 66u8, 239u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [64u8, 189u8, 116u8, 239u8, 249u8, 134u8, 94u8, 83u8, 190u8, 62u8, 234u8, 235u8, 174u8, 232u8, 216u8, 28u8, 4u8, 184u8, 163u8, 182u8, 209u8, 96u8, 122u8, 105u8, 104u8, 178u8, 66u8, 132u8, 128u8, 94u8, 125u8, 204u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_644e98c0284feed6")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0040bd74eff9865e53be3eeaebaee8d81c04b8a3b6d1607a6968b24284805e7dcc\x00=======END GROTH16 VK SETUP V1=======\x00";
