// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        0u8, 160u8, 160u8, 253u8, 128u8, 6u8, 41u8, 52u8, 189u8, 74u8, 54u8, 229u8, 18u8, 19u8,
        83u8, 203u8, 67u8, 105u8, 243u8, 177u8, 159u8, 99u8, 207u8, 129u8, 19u8, 59u8, 200u8, 37u8,
        211u8, 169u8, 52u8, 89u8, 26u8, 45u8, 58u8, 34u8, 248u8, 97u8, 8u8, 190u8, 167u8, 198u8,
        115u8, 128u8, 16u8, 100u8, 22u8, 9u8, 8u8, 182u8, 139u8, 78u8, 67u8, 202u8, 25u8, 244u8,
        204u8, 182u8, 250u8, 58u8, 234u8, 13u8, 95u8, 156u8,
    ],
    [
        43u8, 237u8, 11u8, 133u8, 39u8, 12u8, 38u8, 161u8, 169u8, 212u8, 10u8, 135u8, 123u8, 64u8,
        133u8, 88u8, 72u8, 147u8, 170u8, 95u8, 110u8, 194u8, 228u8, 17u8, 10u8, 177u8, 25u8, 183u8,
        176u8, 130u8, 216u8, 57u8, 28u8, 65u8, 166u8, 26u8, 32u8, 179u8, 18u8, 94u8, 27u8, 157u8,
        121u8, 44u8, 82u8, 53u8, 81u8, 195u8, 54u8, 123u8, 173u8, 78u8, 128u8, 179u8, 48u8, 177u8,
        249u8, 25u8, 76u8, 160u8, 31u8, 55u8, 172u8, 131u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        30u8, 67u8, 135u8, 6u8, 186u8, 46u8, 190u8, 134u8, 206u8, 246u8, 183u8, 217u8, 43u8, 103u8,
        142u8, 119u8, 4u8, 102u8, 147u8, 26u8, 249u8, 69u8, 105u8, 30u8, 200u8, 61u8, 216u8, 161u8,
        42u8, 26u8, 207u8, 119u8, 2u8, 215u8, 233u8, 107u8, 144u8, 106u8, 120u8, 35u8, 120u8, 25u8,
        148u8, 157u8, 74u8, 175u8, 166u8, 17u8, 62u8, 20u8, 253u8, 91u8, 214u8, 38u8, 203u8, 24u8,
        198u8, 3u8, 207u8, 155u8, 119u8, 240u8, 161u8, 226u8,
    ],
    vk_beta_g2: [
        28u8, 37u8, 62u8, 225u8, 10u8, 243u8, 239u8, 23u8, 96u8, 176u8, 98u8, 2u8, 106u8, 49u8,
        202u8, 66u8, 222u8, 161u8, 16u8, 250u8, 180u8, 53u8, 90u8, 82u8, 129u8, 59u8, 213u8, 97u8,
        184u8, 32u8, 59u8, 6u8, 35u8, 251u8, 222u8, 203u8, 28u8, 125u8, 201u8, 114u8, 109u8, 84u8,
        124u8, 53u8, 178u8, 124u8, 42u8, 25u8, 82u8, 229u8, 245u8, 1u8, 102u8, 145u8, 51u8, 135u8,
        230u8, 137u8, 143u8, 103u8, 101u8, 246u8, 119u8, 76u8, 5u8, 3u8, 41u8, 234u8, 215u8, 36u8,
        51u8, 143u8, 145u8, 246u8, 243u8, 49u8, 223u8, 50u8, 249u8, 99u8, 158u8, 132u8, 186u8,
        147u8, 217u8, 150u8, 251u8, 15u8, 113u8, 192u8, 82u8, 190u8, 234u8, 15u8, 164u8, 15u8,
        28u8, 111u8, 16u8, 32u8, 106u8, 174u8, 186u8, 169u8, 238u8, 126u8, 123u8, 93u8, 62u8,
        196u8, 104u8, 72u8, 93u8, 126u8, 232u8, 221u8, 107u8, 138u8, 73u8, 159u8, 176u8, 203u8,
        185u8, 65u8, 117u8, 223u8, 216u8, 130u8,
    ],
    vk_gamma_g2: [
        19u8, 100u8, 155u8, 131u8, 204u8, 146u8, 175u8, 166u8, 59u8, 84u8, 204u8, 210u8, 235u8,
        254u8, 21u8, 44u8, 209u8, 249u8, 243u8, 55u8, 179u8, 2u8, 171u8, 41u8, 214u8, 70u8, 44u8,
        45u8, 100u8, 121u8, 43u8, 7u8, 8u8, 186u8, 33u8, 126u8, 109u8, 129u8, 218u8, 188u8, 50u8,
        21u8, 83u8, 8u8, 191u8, 240u8, 238u8, 162u8, 103u8, 2u8, 86u8, 192u8, 142u8, 14u8, 100u8,
        26u8, 68u8, 176u8, 163u8, 7u8, 76u8, 223u8, 146u8, 125u8, 1u8, 250u8, 150u8, 45u8, 78u8,
        246u8, 10u8, 188u8, 99u8, 198u8, 227u8, 19u8, 217u8, 176u8, 223u8, 139u8, 170u8, 44u8,
        169u8, 71u8, 45u8, 71u8, 147u8, 238u8, 61u8, 20u8, 7u8, 26u8, 49u8, 6u8, 222u8, 253u8,
        29u8, 111u8, 56u8, 243u8, 233u8, 93u8, 130u8, 251u8, 42u8, 224u8, 119u8, 147u8, 219u8,
        95u8, 140u8, 104u8, 27u8, 133u8, 168u8, 150u8, 38u8, 158u8, 146u8, 61u8, 247u8, 152u8,
        202u8, 212u8, 179u8, 59u8, 46u8, 184u8,
    ],
    vk_delta_g2: [
        41u8, 26u8, 140u8, 76u8, 4u8, 236u8, 75u8, 101u8, 74u8, 158u8, 200u8, 176u8, 63u8, 168u8,
        99u8, 155u8, 245u8, 197u8, 253u8, 34u8, 181u8, 211u8, 123u8, 209u8, 217u8, 68u8, 36u8,
        14u8, 148u8, 45u8, 59u8, 37u8, 22u8, 235u8, 124u8, 15u8, 44u8, 164u8, 46u8, 27u8, 202u8,
        108u8, 161u8, 115u8, 155u8, 125u8, 166u8, 71u8, 38u8, 183u8, 116u8, 37u8, 26u8, 159u8,
        192u8, 174u8, 29u8, 202u8, 254u8, 145u8, 145u8, 126u8, 29u8, 3u8, 11u8, 208u8, 16u8, 99u8,
        89u8, 197u8, 57u8, 184u8, 56u8, 253u8, 39u8, 40u8, 205u8, 100u8, 87u8, 152u8, 222u8, 22u8,
        167u8, 135u8, 164u8, 198u8, 245u8, 119u8, 225u8, 180u8, 249u8, 229u8, 66u8, 77u8, 49u8,
        108u8, 15u8, 165u8, 35u8, 103u8, 35u8, 12u8, 82u8, 128u8, 75u8, 175u8, 101u8, 9u8, 9u8,
        238u8, 99u8, 76u8, 56u8, 161u8, 60u8, 130u8, 11u8, 9u8, 92u8, 152u8, 129u8, 72u8, 190u8,
        120u8, 14u8, 169u8, 123u8, 79u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [254u8, 130u8, 253u8, 59u8, 89u8, 226u8, 246u8, 49u8, 154u8, 139u8, 174u8, 227u8, 251u8, 214u8, 240u8, 88u8, 118u8, 146u8, 245u8, 59u8, 229u8, 73u8, 3u8, 195u8, 46u8, 52u8, 160u8, 33u8, 110u8, 211u8, 125u8, 59u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_64b44a34f53a76b7")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00fe82fd3b59e2f6319a8baee3fbd6f0587692f53be54903c32e34a0216ed37d3b\x00=======END GROTH16 VK SETUP V1=======\x00";
