// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        27u8, 99u8, 39u8, 149u8, 114u8, 40u8, 12u8, 3u8, 104u8, 161u8, 106u8, 248u8, 55u8, 145u8,
        240u8, 34u8, 98u8, 126u8, 224u8, 2u8, 97u8, 78u8, 153u8, 236u8, 49u8, 188u8, 76u8, 142u8,
        49u8, 73u8, 242u8, 234u8, 4u8, 220u8, 247u8, 136u8, 73u8, 10u8, 250u8, 112u8, 110u8, 53u8,
        253u8, 159u8, 188u8, 66u8, 112u8, 19u8, 21u8, 24u8, 192u8, 220u8, 253u8, 242u8, 31u8, 53u8,
        121u8, 244u8, 59u8, 83u8, 2u8, 237u8, 37u8, 77u8,
    ],
    [
        0u8, 190u8, 61u8, 135u8, 223u8, 174u8, 9u8, 2u8, 229u8, 35u8, 161u8, 144u8, 37u8, 165u8,
        227u8, 18u8, 96u8, 140u8, 65u8, 205u8, 237u8, 241u8, 115u8, 117u8, 66u8, 38u8, 78u8, 96u8,
        155u8, 14u8, 5u8, 115u8, 34u8, 209u8, 14u8, 195u8, 34u8, 214u8, 19u8, 231u8, 74u8, 198u8,
        213u8, 107u8, 81u8, 87u8, 106u8, 124u8, 186u8, 97u8, 219u8, 39u8, 202u8, 86u8, 57u8, 38u8,
        133u8, 96u8, 56u8, 94u8, 29u8, 141u8, 201u8, 53u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        28u8, 223u8, 74u8, 240u8, 136u8, 176u8, 39u8, 28u8, 130u8, 193u8, 95u8, 130u8, 178u8, 28u8,
        171u8, 204u8, 146u8, 32u8, 52u8, 174u8, 39u8, 220u8, 191u8, 20u8, 189u8, 236u8, 233u8,
        95u8, 112u8, 192u8, 48u8, 148u8, 43u8, 205u8, 39u8, 142u8, 21u8, 240u8, 127u8, 23u8, 142u8,
        227u8, 124u8, 128u8, 51u8, 144u8, 21u8, 59u8, 32u8, 38u8, 159u8, 180u8, 195u8, 211u8,
        178u8, 49u8, 244u8, 68u8, 12u8, 24u8, 97u8, 128u8, 74u8, 211u8,
    ],
    vk_beta_g2: [
        27u8, 158u8, 156u8, 164u8, 166u8, 168u8, 177u8, 218u8, 235u8, 112u8, 38u8, 178u8, 12u8,
        175u8, 17u8, 17u8, 186u8, 36u8, 174u8, 34u8, 69u8, 62u8, 145u8, 12u8, 233u8, 246u8, 215u8,
        99u8, 193u8, 187u8, 140u8, 117u8, 5u8, 106u8, 254u8, 60u8, 207u8, 239u8, 144u8, 21u8, 92u8,
        203u8, 236u8, 200u8, 178u8, 164u8, 156u8, 68u8, 218u8, 40u8, 11u8, 77u8, 164u8, 39u8, 88u8,
        217u8, 14u8, 54u8, 85u8, 40u8, 207u8, 232u8, 181u8, 19u8, 45u8, 17u8, 193u8, 139u8, 44u8,
        202u8, 66u8, 252u8, 31u8, 78u8, 137u8, 163u8, 134u8, 5u8, 40u8, 27u8, 230u8, 29u8, 82u8,
        136u8, 95u8, 157u8, 176u8, 206u8, 88u8, 13u8, 55u8, 87u8, 242u8, 205u8, 101u8, 106u8, 16u8,
        69u8, 211u8, 171u8, 138u8, 232u8, 242u8, 227u8, 60u8, 76u8, 6u8, 34u8, 90u8, 84u8, 222u8,
        149u8, 153u8, 157u8, 252u8, 32u8, 93u8, 230u8, 124u8, 36u8, 174u8, 125u8, 177u8, 24u8,
        144u8, 180u8, 25u8, 85u8,
    ],
    vk_gamma_g2: [
        46u8, 86u8, 4u8, 55u8, 190u8, 162u8, 205u8, 113u8, 58u8, 239u8, 227u8, 177u8, 1u8, 103u8,
        88u8, 183u8, 23u8, 245u8, 185u8, 119u8, 255u8, 78u8, 191u8, 166u8, 80u8, 214u8, 130u8,
        13u8, 14u8, 157u8, 240u8, 28u8, 34u8, 73u8, 133u8, 230u8, 224u8, 240u8, 250u8, 72u8, 177u8,
        186u8, 110u8, 8u8, 101u8, 61u8, 156u8, 228u8, 33u8, 114u8, 128u8, 77u8, 203u8, 195u8,
        145u8, 163u8, 145u8, 21u8, 12u8, 169u8, 198u8, 110u8, 56u8, 170u8, 36u8, 69u8, 163u8,
        155u8, 14u8, 207u8, 125u8, 75u8, 197u8, 9u8, 86u8, 234u8, 158u8, 244u8, 244u8, 92u8, 82u8,
        153u8, 235u8, 53u8, 88u8, 240u8, 88u8, 126u8, 190u8, 255u8, 149u8, 242u8, 29u8, 160u8,
        90u8, 14u8, 18u8, 119u8, 43u8, 205u8, 117u8, 149u8, 248u8, 203u8, 92u8, 159u8, 236u8, 98u8,
        63u8, 11u8, 146u8, 196u8, 206u8, 68u8, 154u8, 99u8, 110u8, 0u8, 51u8, 14u8, 9u8, 43u8,
        174u8, 70u8, 6u8, 19u8, 57u8, 118u8,
    ],
    vk_delta_g2: [
        3u8, 155u8, 70u8, 91u8, 25u8, 243u8, 189u8, 205u8, 104u8, 128u8, 175u8, 61u8, 191u8, 85u8,
        41u8, 186u8, 97u8, 206u8, 77u8, 40u8, 64u8, 226u8, 78u8, 0u8, 184u8, 161u8, 84u8, 100u8,
        129u8, 57u8, 179u8, 137u8, 8u8, 203u8, 87u8, 174u8, 213u8, 191u8, 77u8, 139u8, 154u8,
        104u8, 124u8, 157u8, 76u8, 36u8, 117u8, 169u8, 245u8, 205u8, 231u8, 16u8, 31u8, 129u8,
        64u8, 97u8, 209u8, 1u8, 91u8, 100u8, 116u8, 100u8, 112u8, 93u8, 0u8, 77u8, 110u8, 41u8,
        254u8, 44u8, 90u8, 205u8, 246u8, 184u8, 80u8, 31u8, 76u8, 241u8, 154u8, 147u8, 41u8, 31u8,
        15u8, 184u8, 50u8, 168u8, 251u8, 12u8, 155u8, 145u8, 197u8, 125u8, 218u8, 177u8, 184u8,
        24u8, 19u8, 8u8, 7u8, 213u8, 182u8, 66u8, 157u8, 118u8, 123u8, 32u8, 43u8, 231u8, 46u8,
        216u8, 236u8, 126u8, 166u8, 77u8, 90u8, 248u8, 46u8, 132u8, 170u8, 143u8, 95u8, 176u8,
        239u8, 90u8, 219u8, 33u8, 39u8, 59u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [193u8, 185u8, 114u8, 190u8, 199u8, 178u8, 23u8, 62u8, 181u8, 229u8, 101u8, 67u8, 6u8, 148u8, 128u8, 116u8, 136u8, 194u8, 150u8, 73u8, 123u8, 28u8, 66u8, 242u8, 42u8, 73u8, 212u8, 159u8, 180u8, 5u8, 105u8, 121u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_ea370524565b5479")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00c1b972bec7b2173eb5e565430694807488c296497b1c42f22a49d49fb4056979\x00=======END GROTH16 VK SETUP V1=======\x00";
