// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        43u8, 62u8, 134u8, 90u8, 112u8, 118u8, 83u8, 19u8, 165u8, 148u8, 37u8, 229u8, 52u8, 108u8,
        61u8, 114u8, 168u8, 211u8, 110u8, 55u8, 231u8, 251u8, 94u8, 219u8, 78u8, 173u8, 17u8, 47u8,
        106u8, 96u8, 108u8, 184u8, 30u8, 241u8, 123u8, 93u8, 31u8, 102u8, 183u8, 23u8, 228u8,
        224u8, 215u8, 117u8, 9u8, 73u8, 225u8, 232u8, 129u8, 147u8, 41u8, 213u8, 154u8, 9u8, 21u8,
        112u8, 214u8, 244u8, 154u8, 121u8, 148u8, 224u8, 202u8, 69u8,
    ],
    [
        46u8, 37u8, 26u8, 247u8, 7u8, 241u8, 155u8, 237u8, 102u8, 158u8, 223u8, 55u8, 200u8, 229u8,
        241u8, 118u8, 130u8, 190u8, 27u8, 244u8, 188u8, 50u8, 130u8, 238u8, 255u8, 252u8, 100u8,
        226u8, 51u8, 233u8, 164u8, 127u8, 26u8, 132u8, 216u8, 254u8, 166u8, 2u8, 128u8, 154u8,
        65u8, 72u8, 73u8, 84u8, 88u8, 97u8, 184u8, 179u8, 171u8, 106u8, 96u8, 206u8, 250u8, 176u8,
        182u8, 47u8, 186u8, 218u8, 106u8, 199u8, 239u8, 144u8, 108u8, 6u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        27u8, 25u8, 165u8, 201u8, 211u8, 183u8, 122u8, 35u8, 252u8, 1u8, 176u8, 58u8, 153u8, 204u8,
        195u8, 156u8, 87u8, 190u8, 70u8, 66u8, 238u8, 7u8, 43u8, 50u8, 79u8, 148u8, 198u8, 222u8,
        43u8, 239u8, 102u8, 32u8, 23u8, 121u8, 137u8, 221u8, 241u8, 168u8, 128u8, 247u8, 70u8,
        78u8, 198u8, 99u8, 172u8, 196u8, 34u8, 76u8, 6u8, 59u8, 221u8, 10u8, 147u8, 34u8, 219u8,
        202u8, 53u8, 49u8, 237u8, 183u8, 85u8, 240u8, 111u8, 84u8,
    ],
    vk_beta_g2: [
        27u8, 141u8, 166u8, 199u8, 43u8, 59u8, 55u8, 135u8, 28u8, 244u8, 245u8, 48u8, 44u8, 158u8,
        235u8, 237u8, 186u8, 221u8, 250u8, 146u8, 154u8, 197u8, 228u8, 112u8, 173u8, 214u8, 218u8,
        199u8, 52u8, 247u8, 76u8, 81u8, 22u8, 250u8, 75u8, 17u8, 28u8, 220u8, 235u8, 62u8, 112u8,
        97u8, 34u8, 208u8, 67u8, 2u8, 0u8, 64u8, 223u8, 136u8, 253u8, 82u8, 207u8, 125u8, 65u8,
        219u8, 113u8, 190u8, 40u8, 245u8, 73u8, 170u8, 17u8, 137u8, 41u8, 239u8, 102u8, 26u8, 53u8,
        204u8, 253u8, 17u8, 93u8, 86u8, 77u8, 222u8, 230u8, 43u8, 91u8, 141u8, 5u8, 156u8, 23u8,
        166u8, 129u8, 170u8, 125u8, 200u8, 106u8, 180u8, 114u8, 240u8, 222u8, 228u8, 19u8, 201u8,
        2u8, 28u8, 236u8, 121u8, 143u8, 79u8, 66u8, 21u8, 204u8, 156u8, 24u8, 23u8, 101u8, 218u8,
        39u8, 202u8, 216u8, 93u8, 233u8, 164u8, 102u8, 20u8, 99u8, 65u8, 177u8, 186u8, 62u8, 34u8,
        22u8, 233u8, 100u8, 230u8,
    ],
    vk_gamma_g2: [
        14u8, 63u8, 151u8, 102u8, 100u8, 3u8, 105u8, 124u8, 169u8, 52u8, 185u8, 13u8, 205u8, 193u8,
        166u8, 130u8, 209u8, 28u8, 85u8, 120u8, 14u8, 182u8, 122u8, 234u8, 8u8, 19u8, 233u8, 145u8,
        92u8, 219u8, 25u8, 35u8, 31u8, 205u8, 126u8, 239u8, 229u8, 147u8, 87u8, 217u8, 238u8, 0u8,
        72u8, 179u8, 227u8, 242u8, 110u8, 208u8, 75u8, 163u8, 174u8, 212u8, 224u8, 144u8, 0u8,
        204u8, 250u8, 241u8, 84u8, 156u8, 104u8, 225u8, 80u8, 170u8, 33u8, 70u8, 99u8, 33u8, 26u8,
        185u8, 35u8, 218u8, 160u8, 43u8, 1u8, 186u8, 192u8, 158u8, 185u8, 8u8, 99u8, 22u8, 134u8,
        150u8, 109u8, 83u8, 174u8, 139u8, 105u8, 220u8, 203u8, 77u8, 23u8, 230u8, 231u8, 10u8,
        17u8, 139u8, 242u8, 1u8, 122u8, 118u8, 156u8, 26u8, 97u8, 46u8, 91u8, 135u8, 14u8, 171u8,
        224u8, 161u8, 254u8, 151u8, 123u8, 60u8, 2u8, 57u8, 9u8, 80u8, 138u8, 71u8, 177u8, 72u8,
        62u8, 45u8, 249u8, 98u8,
    ],
    vk_delta_g2: [
        4u8, 65u8, 93u8, 113u8, 81u8, 110u8, 254u8, 244u8, 89u8, 255u8, 128u8, 24u8, 12u8, 143u8,
        122u8, 84u8, 227u8, 102u8, 41u8, 112u8, 171u8, 55u8, 216u8, 167u8, 170u8, 132u8, 231u8,
        248u8, 186u8, 240u8, 195u8, 211u8, 14u8, 36u8, 51u8, 153u8, 94u8, 48u8, 141u8, 189u8,
        182u8, 61u8, 7u8, 45u8, 58u8, 26u8, 89u8, 164u8, 190u8, 85u8, 66u8, 188u8, 217u8, 22u8,
        28u8, 15u8, 250u8, 176u8, 75u8, 9u8, 54u8, 32u8, 190u8, 87u8, 35u8, 227u8, 131u8, 77u8,
        87u8, 73u8, 198u8, 140u8, 31u8, 211u8, 246u8, 232u8, 191u8, 163u8, 51u8, 193u8, 194u8,
        34u8, 100u8, 150u8, 73u8, 201u8, 156u8, 206u8, 192u8, 196u8, 27u8, 89u8, 60u8, 250u8, 9u8,
        137u8, 21u8, 195u8, 15u8, 115u8, 36u8, 199u8, 26u8, 66u8, 48u8, 200u8, 90u8, 245u8, 178u8,
        72u8, 153u8, 94u8, 80u8, 245u8, 161u8, 84u8, 63u8, 251u8, 125u8, 6u8, 116u8, 57u8, 61u8,
        26u8, 155u8, 3u8, 130u8, 144u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [138u8, 220u8, 100u8, 211u8, 136u8, 102u8, 25u8, 227u8, 184u8, 230u8, 91u8, 59u8, 12u8, 152u8, 234u8, 172u8, 97u8, 191u8, 223u8, 188u8, 138u8, 81u8, 170u8, 107u8, 160u8, 81u8, 102u8, 184u8, 83u8, 254u8, 179u8, 40u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_1bee9d64218811b1")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x008adc64d3886619e3b8e65b3b0c98eaac61bfdfbc8a51aa6ba05166b853feb328\x00=======END GROTH16 VK SETUP V1=======\x00";
