// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        39u8, 53u8, 240u8, 119u8, 229u8, 220u8, 68u8, 179u8, 185u8, 223u8, 226u8, 241u8, 128u8,
        230u8, 53u8, 85u8, 105u8, 221u8, 39u8, 247u8, 81u8, 34u8, 74u8, 241u8, 22u8, 247u8, 199u8,
        106u8, 16u8, 85u8, 29u8, 202u8, 30u8, 143u8, 236u8, 176u8, 0u8, 95u8, 49u8, 229u8, 252u8,
        128u8, 51u8, 94u8, 47u8, 100u8, 27u8, 88u8, 104u8, 215u8, 100u8, 152u8, 185u8, 251u8, 10u8,
        120u8, 12u8, 182u8, 47u8, 159u8, 148u8, 118u8, 6u8, 58u8,
    ],
    [
        11u8, 173u8, 112u8, 91u8, 236u8, 114u8, 168u8, 237u8, 62u8, 48u8, 180u8, 183u8, 219u8, 4u8,
        179u8, 117u8, 144u8, 128u8, 168u8, 49u8, 252u8, 126u8, 174u8, 215u8, 184u8, 117u8, 249u8,
        207u8, 232u8, 30u8, 252u8, 42u8, 37u8, 196u8, 29u8, 232u8, 115u8, 24u8, 52u8, 254u8, 72u8,
        239u8, 157u8, 237u8, 161u8, 193u8, 65u8, 33u8, 30u8, 74u8, 23u8, 27u8, 138u8, 175u8, 224u8,
        220u8, 224u8, 233u8, 5u8, 224u8, 120u8, 241u8, 17u8, 253u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        18u8, 189u8, 142u8, 117u8, 76u8, 87u8, 220u8, 235u8, 202u8, 43u8, 194u8, 129u8, 118u8,
        67u8, 54u8, 131u8, 131u8, 82u8, 125u8, 126u8, 236u8, 129u8, 132u8, 191u8, 220u8, 24u8,
        121u8, 28u8, 184u8, 246u8, 73u8, 136u8, 11u8, 185u8, 99u8, 160u8, 98u8, 14u8, 130u8, 9u8,
        207u8, 149u8, 133u8, 73u8, 175u8, 64u8, 169u8, 233u8, 0u8, 191u8, 206u8, 214u8, 151u8,
        214u8, 66u8, 4u8, 234u8, 63u8, 113u8, 77u8, 46u8, 114u8, 55u8, 168u8,
    ],
    vk_beta_g2: [
        10u8, 214u8, 8u8, 147u8, 194u8, 183u8, 26u8, 116u8, 36u8, 36u8, 237u8, 241u8, 80u8, 48u8,
        232u8, 76u8, 170u8, 199u8, 151u8, 47u8, 32u8, 14u8, 216u8, 18u8, 149u8, 87u8, 162u8, 42u8,
        132u8, 167u8, 36u8, 220u8, 22u8, 180u8, 45u8, 141u8, 194u8, 199u8, 6u8, 10u8, 248u8, 192u8,
        215u8, 60u8, 172u8, 128u8, 255u8, 47u8, 151u8, 243u8, 174u8, 98u8, 123u8, 185u8, 252u8,
        53u8, 190u8, 48u8, 115u8, 5u8, 139u8, 126u8, 14u8, 18u8, 33u8, 238u8, 81u8, 198u8, 48u8,
        79u8, 231u8, 156u8, 1u8, 133u8, 117u8, 221u8, 80u8, 221u8, 96u8, 195u8, 73u8, 167u8, 244u8,
        195u8, 16u8, 242u8, 46u8, 228u8, 31u8, 184u8, 87u8, 90u8, 199u8, 135u8, 170u8, 122u8, 31u8,
        164u8, 148u8, 253u8, 9u8, 78u8, 192u8, 34u8, 177u8, 32u8, 172u8, 244u8, 91u8, 138u8, 118u8,
        195u8, 118u8, 189u8, 135u8, 139u8, 185u8, 86u8, 236u8, 29u8, 18u8, 104u8, 134u8, 15u8,
        133u8, 63u8, 135u8, 100u8,
    ],
    vk_gamma_g2: [
        22u8, 122u8, 116u8, 75u8, 240u8, 57u8, 128u8, 6u8, 185u8, 109u8, 45u8, 27u8, 21u8, 177u8,
        72u8, 190u8, 234u8, 191u8, 78u8, 152u8, 177u8, 126u8, 37u8, 101u8, 48u8, 185u8, 66u8,
        142u8, 128u8, 134u8, 3u8, 120u8, 36u8, 152u8, 111u8, 176u8, 240u8, 84u8, 19u8, 152u8,
        220u8, 229u8, 124u8, 138u8, 38u8, 11u8, 133u8, 209u8, 119u8, 3u8, 233u8, 40u8, 255u8,
        209u8, 226u8, 125u8, 116u8, 161u8, 102u8, 229u8, 50u8, 97u8, 80u8, 161u8, 25u8, 35u8,
        173u8, 66u8, 51u8, 20u8, 60u8, 62u8, 58u8, 87u8, 133u8, 51u8, 100u8, 185u8, 237u8, 145u8,
        145u8, 119u8, 95u8, 244u8, 126u8, 69u8, 60u8, 126u8, 215u8, 248u8, 227u8, 129u8, 120u8,
        156u8, 56u8, 81u8, 16u8, 111u8, 235u8, 105u8, 237u8, 132u8, 208u8, 185u8, 8u8, 226u8,
        118u8, 217u8, 236u8, 107u8, 6u8, 108u8, 200u8, 173u8, 201u8, 79u8, 188u8, 89u8, 113u8,
        11u8, 94u8, 253u8, 171u8, 208u8, 227u8, 86u8, 200u8, 152u8,
    ],
    vk_delta_g2: [
        17u8, 98u8, 237u8, 53u8, 212u8, 219u8, 232u8, 140u8, 98u8, 225u8, 133u8, 1u8, 73u8, 171u8,
        55u8, 71u8, 214u8, 168u8, 237u8, 94u8, 141u8, 51u8, 161u8, 186u8, 51u8, 101u8, 173u8,
        141u8, 82u8, 230u8, 42u8, 161u8, 2u8, 91u8, 23u8, 160u8, 162u8, 59u8, 49u8, 189u8, 185u8,
        181u8, 9u8, 206u8, 67u8, 178u8, 74u8, 122u8, 120u8, 15u8, 48u8, 184u8, 18u8, 38u8, 66u8,
        33u8, 13u8, 3u8, 246u8, 105u8, 245u8, 74u8, 215u8, 4u8, 6u8, 19u8, 105u8, 123u8, 220u8,
        64u8, 31u8, 17u8, 145u8, 56u8, 50u8, 34u8, 231u8, 36u8, 160u8, 37u8, 12u8, 42u8, 71u8,
        155u8, 144u8, 157u8, 240u8, 153u8, 56u8, 249u8, 58u8, 154u8, 84u8, 49u8, 169u8, 50u8, 13u8,
        66u8, 194u8, 117u8, 17u8, 71u8, 109u8, 20u8, 240u8, 226u8, 119u8, 204u8, 203u8, 97u8,
        241u8, 133u8, 226u8, 222u8, 185u8, 78u8, 0u8, 155u8, 2u8, 6u8, 56u8, 134u8, 97u8, 183u8,
        71u8, 206u8, 144u8, 116u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [168u8, 14u8, 177u8, 54u8, 171u8, 138u8, 202u8, 241u8, 84u8, 10u8, 160u8, 206u8, 78u8, 68u8, 219u8, 124u8, 122u8, 6u8, 96u8, 108u8, 215u8, 16u8, 139u8, 158u8, 3u8, 215u8, 230u8, 30u8, 106u8, 222u8, 192u8, 154u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_713cdb44a418620b")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00a80eb136ab8acaf1540aa0ce4e44db7c7a06606cd7108b9e03d7e61e6adec09a\x00=======END GROTH16 VK SETUP V1=======\x00";
