// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        45u8, 3u8, 1u8, 153u8, 155u8, 233u8, 85u8, 79u8, 227u8, 100u8, 119u8, 98u8, 121u8, 224u8,
        141u8, 82u8, 58u8, 182u8, 204u8, 141u8, 153u8, 34u8, 231u8, 131u8, 7u8, 87u8, 39u8, 15u8,
        208u8, 145u8, 111u8, 82u8, 19u8, 250u8, 186u8, 172u8, 219u8, 247u8, 70u8, 31u8, 8u8, 190u8,
        160u8, 165u8, 42u8, 180u8, 213u8, 126u8, 173u8, 133u8, 179u8, 211u8, 204u8, 127u8, 188u8,
        124u8, 178u8, 180u8, 204u8, 46u8, 11u8, 20u8, 78u8, 42u8,
    ],
    [
        3u8, 210u8, 222u8, 235u8, 96u8, 83u8, 132u8, 102u8, 73u8, 153u8, 252u8, 184u8, 161u8,
        184u8, 121u8, 15u8, 179u8, 41u8, 46u8, 183u8, 88u8, 57u8, 124u8, 145u8, 1u8, 246u8, 123u8,
        123u8, 129u8, 253u8, 142u8, 8u8, 4u8, 70u8, 217u8, 49u8, 121u8, 1u8, 128u8, 220u8, 105u8,
        172u8, 182u8, 63u8, 178u8, 77u8, 240u8, 121u8, 224u8, 107u8, 217u8, 166u8, 100u8, 223u8,
        100u8, 84u8, 139u8, 130u8, 224u8, 21u8, 141u8, 250u8, 215u8, 118u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        31u8, 211u8, 93u8, 224u8, 4u8, 22u8, 67u8, 205u8, 5u8, 36u8, 200u8, 160u8, 70u8, 88u8,
        137u8, 112u8, 105u8, 219u8, 167u8, 50u8, 92u8, 77u8, 180u8, 89u8, 110u8, 56u8, 56u8, 164u8,
        122u8, 232u8, 160u8, 22u8, 34u8, 147u8, 191u8, 66u8, 32u8, 244u8, 176u8, 208u8, 224u8,
        89u8, 17u8, 92u8, 213u8, 195u8, 255u8, 54u8, 67u8, 50u8, 34u8, 54u8, 47u8, 109u8, 67u8,
        60u8, 208u8, 53u8, 156u8, 179u8, 34u8, 201u8, 161u8, 115u8,
    ],
    vk_beta_g2: [
        31u8, 228u8, 16u8, 205u8, 87u8, 123u8, 14u8, 251u8, 63u8, 129u8, 172u8, 222u8, 204u8,
        202u8, 73u8, 115u8, 106u8, 105u8, 108u8, 141u8, 160u8, 240u8, 181u8, 69u8, 129u8, 15u8,
        163u8, 176u8, 46u8, 108u8, 226u8, 127u8, 37u8, 117u8, 17u8, 141u8, 118u8, 78u8, 52u8,
        243u8, 120u8, 1u8, 166u8, 108u8, 56u8, 199u8, 107u8, 39u8, 175u8, 238u8, 236u8, 161u8,
        116u8, 103u8, 139u8, 53u8, 74u8, 217u8, 76u8, 243u8, 135u8, 226u8, 54u8, 217u8, 3u8, 89u8,
        57u8, 195u8, 83u8, 228u8, 74u8, 126u8, 171u8, 227u8, 28u8, 36u8, 209u8, 108u8, 175u8, 65u8,
        153u8, 79u8, 139u8, 65u8, 48u8, 136u8, 27u8, 198u8, 84u8, 72u8, 69u8, 43u8, 31u8, 35u8,
        125u8, 89u8, 17u8, 147u8, 14u8, 32u8, 247u8, 120u8, 68u8, 94u8, 250u8, 247u8, 57u8, 173u8,
        151u8, 82u8, 40u8, 174u8, 33u8, 253u8, 156u8, 153u8, 122u8, 16u8, 57u8, 136u8, 210u8,
        249u8, 202u8, 213u8, 45u8, 156u8, 44u8, 164u8,
    ],
    vk_gamma_g2: [
        40u8, 33u8, 168u8, 197u8, 129u8, 115u8, 94u8, 192u8, 123u8, 212u8, 84u8, 63u8, 52u8, 38u8,
        160u8, 12u8, 207u8, 203u8, 229u8, 191u8, 104u8, 82u8, 22u8, 34u8, 136u8, 188u8, 224u8,
        215u8, 143u8, 27u8, 42u8, 154u8, 41u8, 146u8, 56u8, 95u8, 192u8, 236u8, 41u8, 75u8, 242u8,
        205u8, 18u8, 44u8, 36u8, 96u8, 245u8, 130u8, 166u8, 62u8, 153u8, 7u8, 186u8, 47u8, 91u8,
        117u8, 174u8, 182u8, 0u8, 42u8, 11u8, 64u8, 253u8, 201u8, 5u8, 165u8, 110u8, 40u8, 3u8,
        103u8, 176u8, 53u8, 83u8, 119u8, 65u8, 79u8, 125u8, 249u8, 84u8, 30u8, 90u8, 220u8, 53u8,
        156u8, 20u8, 230u8, 197u8, 65u8, 67u8, 26u8, 22u8, 18u8, 79u8, 45u8, 12u8, 13u8, 43u8,
        106u8, 103u8, 23u8, 8u8, 101u8, 222u8, 220u8, 166u8, 141u8, 161u8, 216u8, 114u8, 206u8,
        196u8, 176u8, 254u8, 183u8, 128u8, 194u8, 217u8, 36u8, 103u8, 206u8, 50u8, 101u8, 189u8,
        17u8, 75u8, 210u8, 113u8, 139u8,
    ],
    vk_delta_g2: [
        25u8, 158u8, 127u8, 239u8, 207u8, 249u8, 157u8, 214u8, 46u8, 94u8, 223u8, 96u8, 6u8, 22u8,
        157u8, 216u8, 150u8, 13u8, 151u8, 105u8, 228u8, 7u8, 8u8, 232u8, 134u8, 208u8, 148u8,
        153u8, 77u8, 47u8, 94u8, 161u8, 18u8, 24u8, 181u8, 189u8, 101u8, 164u8, 219u8, 1u8, 71u8,
        179u8, 113u8, 234u8, 80u8, 116u8, 45u8, 225u8, 1u8, 57u8, 125u8, 244u8, 143u8, 51u8, 64u8,
        120u8, 96u8, 165u8, 11u8, 211u8, 58u8, 75u8, 119u8, 190u8, 5u8, 181u8, 255u8, 161u8, 171u8,
        158u8, 67u8, 91u8, 115u8, 212u8, 97u8, 121u8, 95u8, 89u8, 140u8, 19u8, 78u8, 31u8, 50u8,
        88u8, 57u8, 128u8, 248u8, 181u8, 226u8, 125u8, 224u8, 110u8, 43u8, 207u8, 117u8, 229u8,
        39u8, 99u8, 68u8, 105u8, 205u8, 75u8, 210u8, 165u8, 56u8, 120u8, 75u8, 221u8, 229u8, 237u8,
        217u8, 127u8, 59u8, 114u8, 78u8, 175u8, 65u8, 68u8, 5u8, 12u8, 84u8, 241u8, 34u8, 154u8,
        144u8, 149u8, 160u8, 85u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [40u8, 6u8, 175u8, 246u8, 188u8, 123u8, 211u8, 66u8, 51u8, 162u8, 255u8, 66u8, 164u8, 46u8, 85u8, 36u8, 198u8, 128u8, 147u8, 9u8, 68u8, 195u8, 252u8, 132u8, 214u8, 213u8, 142u8, 119u8, 60u8, 3u8, 60u8, 181u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_223bfd98b7b318c7")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x002806aff6bc7bd34233a2ff42a42e5524c680930944c3fc84d6d58e773c033cb5\x00=======END GROTH16 VK SETUP V1=======\x00";
