// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        7u8, 17u8, 159u8, 93u8, 244u8, 143u8, 42u8, 41u8, 133u8, 233u8, 84u8, 229u8, 27u8, 234u8,
        228u8, 93u8, 166u8, 211u8, 39u8, 56u8, 31u8, 67u8, 17u8, 120u8, 43u8, 154u8, 231u8, 28u8,
        172u8, 43u8, 32u8, 83u8, 6u8, 213u8, 31u8, 182u8, 53u8, 50u8, 105u8, 161u8, 104u8, 30u8,
        201u8, 162u8, 39u8, 75u8, 135u8, 177u8, 223u8, 204u8, 120u8, 176u8, 253u8, 106u8, 126u8,
        4u8, 239u8, 7u8, 195u8, 11u8, 27u8, 197u8, 223u8, 63u8,
    ],
    [
        19u8, 248u8, 160u8, 195u8, 102u8, 123u8, 118u8, 238u8, 186u8, 223u8, 32u8, 187u8, 49u8,
        192u8, 196u8, 103u8, 232u8, 200u8, 226u8, 208u8, 7u8, 180u8, 131u8, 249u8, 25u8, 180u8,
        231u8, 35u8, 255u8, 60u8, 164u8, 121u8, 20u8, 231u8, 0u8, 233u8, 188u8, 86u8, 127u8, 4u8,
        144u8, 183u8, 163u8, 18u8, 144u8, 148u8, 25u8, 176u8, 226u8, 36u8, 70u8, 124u8, 234u8,
        85u8, 71u8, 26u8, 228u8, 125u8, 124u8, 177u8, 50u8, 11u8, 38u8, 90u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        21u8, 192u8, 89u8, 144u8, 45u8, 106u8, 173u8, 10u8, 107u8, 172u8, 81u8, 17u8, 111u8, 218u8,
        253u8, 2u8, 92u8, 62u8, 74u8, 45u8, 120u8, 207u8, 196u8, 115u8, 252u8, 154u8, 180u8, 76u8,
        154u8, 115u8, 121u8, 152u8, 31u8, 133u8, 88u8, 174u8, 12u8, 98u8, 115u8, 78u8, 175u8,
        238u8, 100u8, 137u8, 177u8, 108u8, 230u8, 227u8, 213u8, 174u8, 25u8, 207u8, 21u8, 127u8,
        73u8, 30u8, 105u8, 12u8, 233u8, 150u8, 75u8, 34u8, 112u8, 106u8,
    ],
    vk_beta_g2: [
        27u8, 250u8, 66u8, 157u8, 31u8, 133u8, 216u8, 110u8, 1u8, 21u8, 254u8, 7u8, 47u8, 33u8,
        80u8, 44u8, 127u8, 144u8, 106u8, 215u8, 175u8, 199u8, 47u8, 228u8, 152u8, 99u8, 224u8, 6u8,
        230u8, 236u8, 103u8, 141u8, 23u8, 166u8, 82u8, 143u8, 53u8, 119u8, 207u8, 74u8, 187u8,
        250u8, 55u8, 13u8, 79u8, 98u8, 222u8, 59u8, 88u8, 236u8, 94u8, 12u8, 214u8, 40u8, 161u8,
        4u8, 26u8, 18u8, 137u8, 191u8, 160u8, 20u8, 23u8, 228u8, 7u8, 165u8, 118u8, 176u8, 159u8,
        100u8, 151u8, 222u8, 165u8, 79u8, 161u8, 58u8, 48u8, 106u8, 103u8, 205u8, 136u8, 204u8,
        234u8, 83u8, 211u8, 76u8, 230u8, 203u8, 90u8, 184u8, 21u8, 185u8, 149u8, 80u8, 196u8, 71u8,
        30u8, 9u8, 255u8, 88u8, 62u8, 69u8, 55u8, 29u8, 243u8, 59u8, 128u8, 57u8, 185u8, 182u8,
        104u8, 8u8, 135u8, 248u8, 12u8, 124u8, 74u8, 210u8, 139u8, 76u8, 76u8, 189u8, 59u8, 70u8,
        26u8, 83u8, 14u8, 173u8,
    ],
    vk_gamma_g2: [
        27u8, 96u8, 206u8, 192u8, 136u8, 13u8, 65u8, 172u8, 21u8, 96u8, 24u8, 74u8, 215u8, 6u8,
        164u8, 149u8, 96u8, 54u8, 44u8, 71u8, 27u8, 101u8, 198u8, 188u8, 205u8, 80u8, 47u8, 120u8,
        4u8, 174u8, 41u8, 142u8, 29u8, 136u8, 170u8, 177u8, 119u8, 44u8, 191u8, 95u8, 233u8, 223u8,
        51u8, 241u8, 248u8, 62u8, 58u8, 231u8, 121u8, 47u8, 84u8, 29u8, 21u8, 151u8, 201u8, 68u8,
        27u8, 74u8, 68u8, 188u8, 140u8, 179u8, 34u8, 100u8, 21u8, 189u8, 171u8, 234u8, 160u8,
        185u8, 138u8, 0u8, 23u8, 223u8, 77u8, 241u8, 154u8, 225u8, 69u8, 163u8, 89u8, 172u8, 249u8,
        248u8, 176u8, 212u8, 45u8, 240u8, 141u8, 78u8, 190u8, 69u8, 93u8, 239u8, 57u8, 235u8, 33u8,
        151u8, 41u8, 110u8, 237u8, 171u8, 243u8, 5u8, 62u8, 114u8, 214u8, 231u8, 31u8, 139u8,
        115u8, 123u8, 179u8, 246u8, 191u8, 171u8, 24u8, 146u8, 76u8, 14u8, 88u8, 121u8, 119u8,
        118u8, 64u8, 205u8, 16u8, 250u8,
    ],
    vk_delta_g2: [
        33u8, 171u8, 208u8, 253u8, 93u8, 244u8, 123u8, 190u8, 151u8, 23u8, 186u8, 82u8, 126u8,
        182u8, 144u8, 81u8, 179u8, 10u8, 84u8, 173u8, 138u8, 210u8, 2u8, 189u8, 220u8, 107u8, 22u8,
        108u8, 223u8, 50u8, 23u8, 64u8, 18u8, 199u8, 249u8, 245u8, 161u8, 221u8, 194u8, 216u8,
        131u8, 40u8, 138u8, 203u8, 157u8, 125u8, 67u8, 89u8, 82u8, 243u8, 89u8, 94u8, 144u8, 13u8,
        254u8, 121u8, 11u8, 73u8, 155u8, 229u8, 100u8, 102u8, 78u8, 90u8, 14u8, 81u8, 63u8, 164u8,
        212u8, 112u8, 130u8, 228u8, 65u8, 118u8, 204u8, 24u8, 145u8, 94u8, 83u8, 232u8, 60u8,
        151u8, 246u8, 165u8, 59u8, 173u8, 196u8, 87u8, 32u8, 45u8, 138u8, 181u8, 235u8, 252u8,
        18u8, 163u8, 36u8, 72u8, 39u8, 70u8, 151u8, 85u8, 78u8, 143u8, 110u8, 205u8, 64u8, 251u8,
        134u8, 24u8, 103u8, 5u8, 233u8, 102u8, 139u8, 230u8, 49u8, 237u8, 175u8, 76u8, 63u8, 161u8,
        213u8, 119u8, 218u8, 60u8, 120u8, 248u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [109u8, 131u8, 238u8, 240u8, 177u8, 111u8, 3u8, 184u8, 242u8, 178u8, 164u8, 105u8, 68u8, 29u8, 103u8, 38u8, 75u8, 195u8, 73u8, 50u8, 216u8, 178u8, 97u8, 243u8, 68u8, 245u8, 187u8, 57u8, 242u8, 154u8, 31u8, 190u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_53e5d3165c272f6b")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x006d83eef0b16f03b8f2b2a469441d67264bc34932d8b261f344f5bb39f29a1fbe\x00=======END GROTH16 VK SETUP V1=======\x00";
