// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        25u8, 63u8, 160u8, 140u8, 34u8, 131u8, 27u8, 167u8, 93u8, 182u8, 121u8, 225u8, 212u8, 79u8,
        189u8, 109u8, 246u8, 78u8, 149u8, 178u8, 120u8, 116u8, 122u8, 141u8, 121u8, 189u8, 151u8,
        119u8, 22u8, 145u8, 60u8, 131u8, 33u8, 199u8, 167u8, 152u8, 72u8, 130u8, 63u8, 166u8, 86u8,
        118u8, 183u8, 99u8, 174u8, 48u8, 111u8, 29u8, 168u8, 25u8, 151u8, 76u8, 197u8, 173u8,
        250u8, 131u8, 235u8, 201u8, 47u8, 227u8, 172u8, 238u8, 66u8, 84u8,
    ],
    [
        31u8, 250u8, 72u8, 22u8, 202u8, 176u8, 199u8, 80u8, 201u8, 205u8, 57u8, 170u8, 109u8,
        168u8, 225u8, 86u8, 100u8, 162u8, 212u8, 242u8, 153u8, 113u8, 176u8, 187u8, 136u8, 215u8,
        96u8, 58u8, 114u8, 110u8, 209u8, 185u8, 43u8, 182u8, 239u8, 255u8, 181u8, 177u8, 206u8,
        6u8, 141u8, 98u8, 96u8, 218u8, 150u8, 35u8, 137u8, 26u8, 114u8, 109u8, 86u8, 173u8, 85u8,
        43u8, 218u8, 12u8, 218u8, 215u8, 153u8, 0u8, 74u8, 117u8, 139u8, 107u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        27u8, 200u8, 111u8, 175u8, 36u8, 150u8, 69u8, 219u8, 44u8, 8u8, 231u8, 174u8, 242u8, 90u8,
        183u8, 28u8, 190u8, 70u8, 91u8, 50u8, 175u8, 108u8, 45u8, 222u8, 5u8, 85u8, 95u8, 51u8,
        20u8, 32u8, 106u8, 232u8, 30u8, 109u8, 194u8, 79u8, 142u8, 155u8, 59u8, 48u8, 167u8, 114u8,
        89u8, 37u8, 171u8, 90u8, 100u8, 111u8, 25u8, 229u8, 38u8, 254u8, 113u8, 192u8, 193u8, 0u8,
        116u8, 143u8, 67u8, 131u8, 143u8, 176u8, 168u8, 168u8,
    ],
    vk_beta_g2: [
        47u8, 88u8, 176u8, 45u8, 111u8, 27u8, 78u8, 34u8, 196u8, 132u8, 90u8, 4u8, 14u8, 144u8,
        158u8, 64u8, 54u8, 235u8, 93u8, 85u8, 158u8, 37u8, 2u8, 83u8, 154u8, 214u8, 169u8, 22u8,
        59u8, 130u8, 198u8, 30u8, 20u8, 192u8, 136u8, 251u8, 187u8, 113u8, 186u8, 7u8, 100u8, 28u8,
        59u8, 247u8, 216u8, 118u8, 130u8, 193u8, 65u8, 174u8, 107u8, 26u8, 73u8, 106u8, 202u8,
        164u8, 124u8, 230u8, 150u8, 12u8, 134u8, 168u8, 130u8, 94u8, 47u8, 59u8, 160u8, 101u8,
        160u8, 59u8, 69u8, 58u8, 232u8, 19u8, 116u8, 147u8, 190u8, 14u8, 122u8, 68u8, 41u8, 112u8,
        8u8, 115u8, 97u8, 141u8, 113u8, 130u8, 218u8, 104u8, 172u8, 249u8, 150u8, 181u8, 83u8,
        48u8, 39u8, 102u8, 156u8, 238u8, 23u8, 209u8, 86u8, 104u8, 216u8, 70u8, 21u8, 2u8, 100u8,
        228u8, 198u8, 67u8, 67u8, 81u8, 253u8, 200u8, 17u8, 26u8, 208u8, 71u8, 125u8, 235u8, 237u8,
        210u8, 58u8, 198u8, 154u8, 104u8,
    ],
    vk_gamma_g2: [
        24u8, 45u8, 194u8, 80u8, 114u8, 66u8, 226u8, 171u8, 231u8, 186u8, 195u8, 36u8, 22u8, 225u8,
        87u8, 165u8, 40u8, 200u8, 183u8, 250u8, 6u8, 99u8, 251u8, 64u8, 59u8, 123u8, 121u8, 138u8,
        31u8, 111u8, 126u8, 200u8, 24u8, 157u8, 147u8, 68u8, 169u8, 102u8, 47u8, 164u8, 150u8,
        44u8, 176u8, 119u8, 87u8, 35u8, 90u8, 137u8, 39u8, 211u8, 234u8, 10u8, 63u8, 151u8, 252u8,
        130u8, 78u8, 159u8, 36u8, 13u8, 198u8, 169u8, 253u8, 154u8, 5u8, 234u8, 188u8, 110u8, 21u8,
        39u8, 187u8, 229u8, 120u8, 166u8, 189u8, 185u8, 199u8, 230u8, 157u8, 128u8, 74u8, 108u8,
        41u8, 216u8, 158u8, 160u8, 133u8, 39u8, 217u8, 50u8, 217u8, 88u8, 30u8, 203u8, 238u8, 80u8,
        1u8, 45u8, 96u8, 144u8, 82u8, 251u8, 224u8, 242u8, 59u8, 68u8, 240u8, 68u8, 198u8, 168u8,
        108u8, 84u8, 213u8, 255u8, 116u8, 19u8, 157u8, 108u8, 216u8, 103u8, 255u8, 153u8, 200u8,
        209u8, 47u8, 137u8, 85u8, 175u8,
    ],
    vk_delta_g2: [
        28u8, 75u8, 133u8, 24u8, 222u8, 90u8, 43u8, 173u8, 92u8, 35u8, 151u8, 81u8, 200u8, 7u8,
        255u8, 218u8, 205u8, 155u8, 251u8, 103u8, 244u8, 96u8, 226u8, 74u8, 65u8, 111u8, 191u8,
        60u8, 206u8, 189u8, 203u8, 22u8, 8u8, 74u8, 192u8, 57u8, 32u8, 123u8, 80u8, 61u8, 90u8,
        109u8, 2u8, 179u8, 148u8, 183u8, 56u8, 161u8, 156u8, 179u8, 180u8, 199u8, 81u8, 44u8,
        115u8, 135u8, 134u8, 8u8, 212u8, 179u8, 194u8, 231u8, 16u8, 42u8, 33u8, 63u8, 5u8, 8u8,
        119u8, 247u8, 127u8, 172u8, 94u8, 191u8, 176u8, 133u8, 227u8, 207u8, 133u8, 161u8, 187u8,
        96u8, 97u8, 251u8, 83u8, 135u8, 58u8, 215u8, 114u8, 147u8, 49u8, 194u8, 12u8, 146u8, 213u8,
        196u8, 12u8, 164u8, 113u8, 232u8, 172u8, 193u8, 177u8, 190u8, 194u8, 16u8, 174u8, 178u8,
        115u8, 90u8, 146u8, 209u8, 11u8, 205u8, 141u8, 202u8, 204u8, 52u8, 202u8, 144u8, 17u8,
        170u8, 197u8, 97u8, 245u8, 81u8, 253u8, 135u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [148u8, 201u8, 84u8, 233u8, 95u8, 210u8, 199u8, 15u8, 175u8, 235u8, 234u8, 133u8, 140u8, 233u8, 108u8, 225u8, 170u8, 164u8, 229u8, 172u8, 92u8, 53u8, 122u8, 64u8, 183u8, 215u8, 193u8, 143u8, 224u8, 80u8, 246u8, 115u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_e79303aa0b7d6ea8")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0094c954e95fd2c70fafebea858ce96ce1aaa4e5ac5c357a40b7d7c18fe050f673\x00=======END GROTH16 VK SETUP V1=======\x00";
