// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        10u8, 170u8, 86u8, 249u8, 201u8, 220u8, 34u8, 54u8, 184u8, 227u8, 119u8, 151u8, 92u8, 63u8,
        129u8, 211u8, 176u8, 243u8, 123u8, 117u8, 223u8, 157u8, 57u8, 239u8, 123u8, 69u8, 132u8,
        169u8, 53u8, 151u8, 248u8, 215u8, 41u8, 173u8, 106u8, 190u8, 44u8, 207u8, 41u8, 137u8,
        201u8, 18u8, 135u8, 66u8, 132u8, 150u8, 218u8, 117u8, 210u8, 163u8, 247u8, 108u8, 149u8,
        97u8, 114u8, 3u8, 214u8, 111u8, 9u8, 68u8, 85u8, 55u8, 186u8, 11u8,
    ],
    [
        44u8, 161u8, 98u8, 177u8, 235u8, 146u8, 20u8, 167u8, 131u8, 42u8, 242u8, 152u8, 169u8,
        184u8, 239u8, 127u8, 171u8, 65u8, 227u8, 128u8, 193u8, 5u8, 176u8, 182u8, 97u8, 233u8,
        49u8, 67u8, 154u8, 94u8, 164u8, 210u8, 45u8, 28u8, 164u8, 206u8, 136u8, 185u8, 222u8, 12u8,
        96u8, 45u8, 162u8, 47u8, 37u8, 23u8, 26u8, 10u8, 147u8, 77u8, 64u8, 252u8, 152u8, 84u8,
        21u8, 224u8, 17u8, 154u8, 245u8, 215u8, 226u8, 91u8, 251u8, 101u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        21u8, 70u8, 89u8, 255u8, 129u8, 20u8, 11u8, 181u8, 190u8, 60u8, 222u8, 243u8, 57u8, 195u8,
        8u8, 188u8, 31u8, 149u8, 180u8, 82u8, 136u8, 53u8, 51u8, 251u8, 63u8, 141u8, 254u8, 200u8,
        97u8, 62u8, 210u8, 175u8, 45u8, 231u8, 211u8, 86u8, 59u8, 148u8, 253u8, 160u8, 63u8, 120u8,
        242u8, 248u8, 225u8, 59u8, 250u8, 178u8, 10u8, 143u8, 188u8, 252u8, 98u8, 253u8, 114u8,
        40u8, 77u8, 190u8, 59u8, 28u8, 104u8, 75u8, 46u8, 219u8,
    ],
    vk_beta_g2: [
        17u8, 138u8, 171u8, 104u8, 17u8, 188u8, 250u8, 175u8, 41u8, 247u8, 234u8, 110u8, 7u8,
        182u8, 175u8, 71u8, 246u8, 134u8, 74u8, 86u8, 202u8, 200u8, 155u8, 43u8, 219u8, 132u8,
        194u8, 65u8, 182u8, 69u8, 96u8, 86u8, 6u8, 159u8, 128u8, 143u8, 44u8, 208u8, 205u8, 96u8,
        128u8, 106u8, 253u8, 132u8, 252u8, 186u8, 70u8, 206u8, 234u8, 156u8, 148u8, 146u8, 173u8,
        244u8, 29u8, 210u8, 180u8, 29u8, 194u8, 58u8, 105u8, 75u8, 65u8, 179u8, 29u8, 78u8, 221u8,
        137u8, 62u8, 132u8, 107u8, 72u8, 147u8, 132u8, 150u8, 161u8, 102u8, 32u8, 191u8, 150u8,
        162u8, 248u8, 196u8, 130u8, 161u8, 74u8, 244u8, 243u8, 156u8, 191u8, 159u8, 20u8, 147u8,
        11u8, 152u8, 183u8, 21u8, 86u8, 115u8, 254u8, 94u8, 5u8, 16u8, 228u8, 245u8, 255u8, 73u8,
        200u8, 149u8, 42u8, 207u8, 55u8, 207u8, 58u8, 244u8, 249u8, 170u8, 202u8, 190u8, 39u8,
        131u8, 85u8, 141u8, 63u8, 176u8, 96u8, 225u8, 185u8,
    ],
    vk_gamma_g2: [
        39u8, 147u8, 90u8, 69u8, 35u8, 153u8, 129u8, 171u8, 164u8, 96u8, 249u8, 246u8, 157u8,
        165u8, 221u8, 1u8, 172u8, 216u8, 18u8, 95u8, 140u8, 247u8, 47u8, 30u8, 159u8, 47u8, 30u8,
        105u8, 42u8, 193u8, 201u8, 201u8, 23u8, 42u8, 189u8, 175u8, 89u8, 223u8, 3u8, 216u8, 238u8,
        133u8, 40u8, 76u8, 122u8, 169u8, 221u8, 217u8, 218u8, 255u8, 84u8, 95u8, 82u8, 229u8, 25u8,
        15u8, 88u8, 212u8, 36u8, 32u8, 170u8, 226u8, 15u8, 249u8, 1u8, 70u8, 21u8, 7u8, 222u8,
        110u8, 160u8, 16u8, 232u8, 100u8, 84u8, 207u8, 78u8, 37u8, 248u8, 44u8, 226u8, 25u8, 86u8,
        63u8, 107u8, 60u8, 41u8, 235u8, 118u8, 248u8, 139u8, 128u8, 107u8, 178u8, 133u8, 77u8,
        18u8, 24u8, 197u8, 71u8, 152u8, 20u8, 131u8, 103u8, 44u8, 144u8, 69u8, 128u8, 54u8, 74u8,
        142u8, 191u8, 156u8, 198u8, 7u8, 35u8, 249u8, 122u8, 70u8, 30u8, 104u8, 49u8, 139u8, 23u8,
        116u8, 33u8, 136u8, 188u8,
    ],
    vk_delta_g2: [
        6u8, 32u8, 38u8, 50u8, 56u8, 55u8, 3u8, 154u8, 102u8, 44u8, 210u8, 16u8, 217u8, 226u8,
        114u8, 95u8, 55u8, 91u8, 41u8, 97u8, 69u8, 23u8, 99u8, 68u8, 224u8, 146u8, 109u8, 97u8,
        10u8, 52u8, 36u8, 82u8, 38u8, 108u8, 62u8, 44u8, 8u8, 6u8, 77u8, 221u8, 175u8, 103u8,
        190u8, 2u8, 63u8, 40u8, 171u8, 95u8, 197u8, 63u8, 79u8, 125u8, 68u8, 147u8, 20u8, 169u8,
        42u8, 98u8, 63u8, 141u8, 230u8, 45u8, 56u8, 98u8, 39u8, 219u8, 141u8, 25u8, 189u8, 49u8,
        237u8, 109u8, 2u8, 161u8, 211u8, 75u8, 176u8, 141u8, 53u8, 11u8, 204u8, 0u8, 189u8, 61u8,
        180u8, 123u8, 180u8, 131u8, 198u8, 215u8, 21u8, 154u8, 18u8, 186u8, 234u8, 228u8, 21u8,
        133u8, 73u8, 114u8, 155u8, 152u8, 90u8, 224u8, 91u8, 181u8, 179u8, 113u8, 173u8, 107u8,
        76u8, 205u8, 183u8, 222u8, 83u8, 120u8, 23u8, 39u8, 52u8, 234u8, 252u8, 174u8, 95u8, 226u8,
        50u8, 27u8, 129u8, 110u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [175u8, 156u8, 155u8, 169u8, 0u8, 21u8, 239u8, 235u8, 13u8, 20u8, 232u8, 118u8, 5u8, 135u8, 160u8, 82u8, 215u8, 37u8, 57u8, 223u8, 220u8, 11u8, 133u8, 169u8, 132u8, 170u8, 16u8, 229u8, 46u8, 173u8, 48u8, 106u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_4616ae63c83619cf")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00af9c9ba90015efeb0d14e8760587a052d72539dfdc0b85a984aa10e52ead306a\x00=======END GROTH16 VK SETUP V1=======\x00";
