// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        38u8, 189u8, 119u8, 204u8, 181u8, 238u8, 19u8, 100u8, 113u8, 85u8, 15u8, 251u8, 220u8,
        131u8, 204u8, 222u8, 189u8, 94u8, 114u8, 36u8, 54u8, 226u8, 99u8, 189u8, 248u8, 98u8,
        222u8, 199u8, 158u8, 140u8, 142u8, 78u8, 6u8, 3u8, 178u8, 117u8, 227u8, 15u8, 135u8, 82u8,
        250u8, 69u8, 38u8, 96u8, 227u8, 208u8, 147u8, 19u8, 243u8, 140u8, 80u8, 143u8, 54u8, 101u8,
        87u8, 151u8, 148u8, 3u8, 148u8, 184u8, 36u8, 95u8, 182u8, 7u8,
    ],
    [
        40u8, 196u8, 226u8, 129u8, 44u8, 0u8, 223u8, 218u8, 201u8, 94u8, 22u8, 34u8, 105u8, 230u8,
        144u8, 238u8, 248u8, 228u8, 8u8, 33u8, 119u8, 0u8, 126u8, 80u8, 247u8, 130u8, 10u8, 52u8,
        139u8, 92u8, 137u8, 24u8, 42u8, 196u8, 48u8, 4u8, 210u8, 28u8, 233u8, 166u8, 92u8, 184u8,
        63u8, 191u8, 175u8, 146u8, 180u8, 87u8, 105u8, 192u8, 214u8, 110u8, 10u8, 146u8, 34u8,
        169u8, 103u8, 24u8, 95u8, 239u8, 92u8, 241u8, 57u8, 10u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        3u8, 81u8, 124u8, 43u8, 223u8, 68u8, 152u8, 174u8, 142u8, 139u8, 9u8, 53u8, 213u8, 33u8,
        44u8, 49u8, 4u8, 97u8, 244u8, 24u8, 82u8, 49u8, 111u8, 216u8, 15u8, 218u8, 59u8, 20u8,
        182u8, 81u8, 195u8, 186u8, 20u8, 192u8, 78u8, 95u8, 91u8, 12u8, 241u8, 67u8, 78u8, 40u8,
        26u8, 233u8, 26u8, 231u8, 18u8, 224u8, 38u8, 119u8, 89u8, 255u8, 17u8, 222u8, 114u8, 171u8,
        213u8, 171u8, 28u8, 141u8, 175u8, 118u8, 245u8, 59u8,
    ],
    vk_beta_g2: [
        7u8, 222u8, 223u8, 218u8, 179u8, 15u8, 106u8, 58u8, 47u8, 215u8, 16u8, 6u8, 254u8, 89u8,
        0u8, 239u8, 236u8, 4u8, 96u8, 244u8, 198u8, 124u8, 251u8, 174u8, 27u8, 70u8, 225u8, 46u8,
        27u8, 65u8, 57u8, 89u8, 2u8, 50u8, 213u8, 250u8, 141u8, 16u8, 191u8, 132u8, 215u8, 114u8,
        175u8, 235u8, 42u8, 24u8, 46u8, 190u8, 111u8, 42u8, 178u8, 247u8, 116u8, 203u8, 17u8,
        254u8, 57u8, 163u8, 90u8, 192u8, 226u8, 17u8, 153u8, 138u8, 18u8, 40u8, 114u8, 82u8, 62u8,
        40u8, 219u8, 159u8, 160u8, 25u8, 25u8, 1u8, 177u8, 24u8, 165u8, 91u8, 136u8, 9u8, 246u8,
        143u8, 203u8, 105u8, 168u8, 62u8, 166u8, 34u8, 237u8, 7u8, 43u8, 32u8, 10u8, 59u8, 2u8,
        75u8, 60u8, 125u8, 107u8, 158u8, 206u8, 212u8, 108u8, 193u8, 52u8, 15u8, 203u8, 112u8,
        205u8, 201u8, 159u8, 53u8, 89u8, 181u8, 235u8, 240u8, 15u8, 113u8, 144u8, 75u8, 178u8,
        155u8, 192u8, 47u8, 37u8, 131u8,
    ],
    vk_gamma_g2: [
        7u8, 207u8, 234u8, 254u8, 179u8, 75u8, 21u8, 21u8, 39u8, 184u8, 165u8, 50u8, 76u8, 140u8,
        11u8, 53u8, 12u8, 74u8, 248u8, 233u8, 86u8, 11u8, 8u8, 74u8, 133u8, 163u8, 209u8, 6u8,
        103u8, 79u8, 46u8, 67u8, 10u8, 135u8, 108u8, 182u8, 196u8, 100u8, 45u8, 84u8, 49u8, 147u8,
        44u8, 86u8, 120u8, 179u8, 204u8, 85u8, 100u8, 70u8, 186u8, 207u8, 216u8, 151u8, 114u8,
        90u8, 109u8, 120u8, 160u8, 132u8, 17u8, 166u8, 227u8, 180u8, 21u8, 145u8, 164u8, 31u8,
        251u8, 222u8, 42u8, 177u8, 180u8, 30u8, 98u8, 129u8, 116u8, 239u8, 183u8, 109u8, 11u8,
        248u8, 189u8, 230u8, 165u8, 122u8, 220u8, 225u8, 253u8, 254u8, 198u8, 72u8, 169u8, 52u8,
        64u8, 25u8, 42u8, 193u8, 244u8, 131u8, 198u8, 98u8, 110u8, 43u8, 18u8, 45u8, 32u8, 222u8,
        51u8, 144u8, 156u8, 57u8, 62u8, 21u8, 142u8, 123u8, 141u8, 197u8, 53u8, 226u8, 226u8, 11u8,
        210u8, 31u8, 179u8, 219u8, 27u8, 187u8,
    ],
    vk_delta_g2: [
        30u8, 1u8, 182u8, 131u8, 91u8, 58u8, 57u8, 80u8, 16u8, 235u8, 78u8, 11u8, 129u8, 192u8,
        89u8, 236u8, 201u8, 163u8, 31u8, 104u8, 22u8, 34u8, 58u8, 97u8, 32u8, 4u8, 160u8, 35u8,
        23u8, 31u8, 194u8, 91u8, 4u8, 9u8, 96u8, 79u8, 167u8, 214u8, 65u8, 178u8, 170u8, 48u8,
        194u8, 109u8, 223u8, 236u8, 228u8, 38u8, 219u8, 250u8, 133u8, 51u8, 92u8, 181u8, 200u8,
        92u8, 65u8, 166u8, 192u8, 181u8, 66u8, 111u8, 203u8, 108u8, 3u8, 209u8, 246u8, 85u8, 99u8,
        47u8, 187u8, 161u8, 118u8, 72u8, 128u8, 210u8, 230u8, 45u8, 73u8, 239u8, 150u8, 50u8,
        135u8, 88u8, 8u8, 156u8, 51u8, 10u8, 111u8, 79u8, 32u8, 199u8, 238u8, 198u8, 184u8, 112u8,
        41u8, 168u8, 180u8, 168u8, 235u8, 99u8, 34u8, 20u8, 76u8, 25u8, 153u8, 14u8, 179u8, 6u8,
        35u8, 150u8, 95u8, 52u8, 38u8, 82u8, 95u8, 176u8, 95u8, 149u8, 71u8, 148u8, 156u8, 242u8,
        202u8, 80u8, 44u8, 245u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [137u8, 227u8, 204u8, 217u8, 175u8, 65u8, 191u8, 105u8, 127u8, 66u8, 103u8, 135u8, 241u8, 154u8, 33u8, 75u8, 145u8, 70u8, 251u8, 29u8, 10u8, 57u8, 147u8, 193u8, 152u8, 78u8, 219u8, 151u8, 77u8, 82u8, 40u8, 141u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_592a48336352a0db")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0089e3ccd9af41bf697f426787f19a214b9146fb1d0a3993c1984edb974d52288d\x00=======END GROTH16 VK SETUP V1=======\x00";
