// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        10u8, 109u8, 243u8, 41u8, 106u8, 104u8, 181u8, 197u8, 101u8, 119u8, 148u8, 122u8, 84u8,
        75u8, 70u8, 23u8, 129u8, 201u8, 136u8, 78u8, 173u8, 26u8, 8u8, 158u8, 66u8, 62u8, 59u8,
        214u8, 195u8, 8u8, 187u8, 24u8, 32u8, 88u8, 225u8, 25u8, 179u8, 255u8, 33u8, 127u8, 171u8,
        75u8, 156u8, 125u8, 85u8, 43u8, 196u8, 87u8, 97u8, 33u8, 50u8, 241u8, 25u8, 145u8, 160u8,
        247u8, 112u8, 30u8, 163u8, 139u8, 151u8, 172u8, 250u8, 218u8,
    ],
    [
        15u8, 114u8, 80u8, 24u8, 145u8, 133u8, 24u8, 253u8, 159u8, 121u8, 154u8, 4u8, 111u8, 238u8,
        6u8, 196u8, 251u8, 19u8, 221u8, 7u8, 11u8, 249u8, 228u8, 79u8, 131u8, 172u8, 10u8, 159u8,
        69u8, 133u8, 221u8, 126u8, 18u8, 211u8, 38u8, 204u8, 143u8, 123u8, 20u8, 103u8, 122u8,
        237u8, 4u8, 52u8, 183u8, 70u8, 153u8, 159u8, 87u8, 235u8, 208u8, 150u8, 243u8, 138u8,
        139u8, 208u8, 83u8, 44u8, 86u8, 54u8, 154u8, 155u8, 36u8, 68u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        30u8, 211u8, 46u8, 8u8, 53u8, 61u8, 180u8, 217u8, 152u8, 4u8, 156u8, 160u8, 131u8, 227u8,
        112u8, 252u8, 102u8, 139u8, 186u8, 211u8, 120u8, 111u8, 102u8, 10u8, 195u8, 77u8, 213u8,
        218u8, 109u8, 161u8, 111u8, 173u8, 41u8, 119u8, 39u8, 104u8, 30u8, 165u8, 221u8, 53u8,
        142u8, 104u8, 239u8, 40u8, 73u8, 33u8, 0u8, 35u8, 46u8, 111u8, 57u8, 205u8, 159u8, 29u8,
        241u8, 137u8, 81u8, 82u8, 141u8, 88u8, 118u8, 69u8, 91u8, 37u8,
    ],
    vk_beta_g2: [
        43u8, 67u8, 212u8, 89u8, 196u8, 235u8, 85u8, 132u8, 44u8, 214u8, 207u8, 54u8, 141u8, 48u8,
        21u8, 250u8, 17u8, 91u8, 91u8, 215u8, 17u8, 113u8, 132u8, 67u8, 166u8, 80u8, 87u8, 55u8,
        119u8, 140u8, 129u8, 1u8, 37u8, 57u8, 60u8, 94u8, 19u8, 8u8, 223u8, 189u8, 51u8, 40u8,
        50u8, 83u8, 226u8, 8u8, 246u8, 15u8, 220u8, 42u8, 112u8, 201u8, 70u8, 16u8, 131u8, 125u8,
        62u8, 110u8, 215u8, 210u8, 190u8, 224u8, 25u8, 141u8, 6u8, 231u8, 252u8, 5u8, 253u8, 114u8,
        42u8, 67u8, 166u8, 8u8, 31u8, 186u8, 123u8, 200u8, 98u8, 126u8, 150u8, 23u8, 63u8, 6u8,
        123u8, 155u8, 16u8, 58u8, 154u8, 150u8, 207u8, 18u8, 214u8, 142u8, 68u8, 2u8, 16u8, 98u8,
        97u8, 224u8, 96u8, 154u8, 29u8, 182u8, 181u8, 70u8, 226u8, 87u8, 123u8, 169u8, 189u8, 12u8,
        70u8, 43u8, 218u8, 20u8, 18u8, 180u8, 53u8, 60u8, 188u8, 98u8, 158u8, 122u8, 63u8, 251u8,
        180u8, 144u8,
    ],
    vk_gamma_g2: [
        12u8, 10u8, 238u8, 60u8, 6u8, 149u8, 175u8, 98u8, 100u8, 3u8, 35u8, 159u8, 151u8, 15u8,
        98u8, 52u8, 90u8, 228u8, 78u8, 223u8, 107u8, 93u8, 117u8, 149u8, 44u8, 144u8, 57u8, 96u8,
        141u8, 226u8, 48u8, 75u8, 4u8, 35u8, 185u8, 64u8, 47u8, 74u8, 162u8, 101u8, 96u8, 135u8,
        207u8, 242u8, 39u8, 181u8, 117u8, 244u8, 153u8, 210u8, 150u8, 24u8, 5u8, 205u8, 170u8,
        187u8, 36u8, 180u8, 53u8, 0u8, 245u8, 14u8, 209u8, 41u8, 18u8, 29u8, 216u8, 107u8, 44u8,
        184u8, 3u8, 71u8, 102u8, 49u8, 249u8, 167u8, 97u8, 7u8, 72u8, 192u8, 88u8, 106u8, 173u8,
        85u8, 69u8, 2u8, 200u8, 47u8, 207u8, 93u8, 228u8, 157u8, 209u8, 174u8, 65u8, 147u8, 33u8,
        6u8, 60u8, 197u8, 198u8, 14u8, 95u8, 29u8, 61u8, 172u8, 218u8, 209u8, 134u8, 186u8, 50u8,
        166u8, 46u8, 67u8, 200u8, 248u8, 27u8, 75u8, 84u8, 50u8, 69u8, 101u8, 85u8, 214u8, 142u8,
        186u8, 74u8, 189u8,
    ],
    vk_delta_g2: [
        20u8, 52u8, 197u8, 37u8, 254u8, 23u8, 179u8, 193u8, 238u8, 5u8, 196u8, 143u8, 39u8, 223u8,
        230u8, 51u8, 201u8, 33u8, 166u8, 225u8, 69u8, 82u8, 219u8, 53u8, 218u8, 0u8, 174u8, 120u8,
        138u8, 30u8, 145u8, 211u8, 27u8, 104u8, 18u8, 249u8, 173u8, 117u8, 0u8, 193u8, 100u8,
        118u8, 74u8, 61u8, 248u8, 102u8, 10u8, 169u8, 100u8, 50u8, 126u8, 229u8, 2u8, 42u8, 146u8,
        114u8, 44u8, 82u8, 97u8, 70u8, 51u8, 54u8, 248u8, 42u8, 45u8, 29u8, 147u8, 250u8, 43u8,
        148u8, 4u8, 221u8, 78u8, 140u8, 229u8, 17u8, 240u8, 241u8, 146u8, 174u8, 235u8, 46u8,
        147u8, 103u8, 106u8, 52u8, 243u8, 193u8, 127u8, 182u8, 164u8, 69u8, 252u8, 27u8, 183u8,
        221u8, 28u8, 24u8, 192u8, 246u8, 75u8, 245u8, 137u8, 114u8, 229u8, 244u8, 173u8, 172u8,
        5u8, 93u8, 131u8, 197u8, 137u8, 87u8, 98u8, 232u8, 54u8, 165u8, 169u8, 138u8, 207u8, 39u8,
        145u8, 57u8, 231u8, 15u8, 232u8, 32u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [126u8, 249u8, 135u8, 150u8, 107u8, 13u8, 251u8, 165u8, 216u8, 110u8, 171u8, 124u8, 103u8, 6u8, 139u8, 224u8, 13u8, 190u8, 88u8, 29u8, 130u8, 61u8, 69u8, 205u8, 187u8, 246u8, 211u8, 56u8, 191u8, 172u8, 182u8, 64u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_61df402049824236")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x007ef987966b0dfba5d86eab7c67068be00dbe581d823d45cdbbf6d338bfacb640\x00=======END GROTH16 VK SETUP V1=======\x00";
