// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        41u8, 27u8, 252u8, 26u8, 240u8, 248u8, 111u8, 127u8, 202u8, 12u8, 174u8, 64u8, 93u8, 86u8,
        50u8, 67u8, 250u8, 113u8, 28u8, 237u8, 176u8, 184u8, 203u8, 122u8, 3u8, 201u8, 160u8,
        146u8, 11u8, 216u8, 26u8, 23u8, 30u8, 195u8, 159u8, 188u8, 253u8, 237u8, 68u8, 215u8,
        220u8, 240u8, 68u8, 8u8, 203u8, 127u8, 139u8, 27u8, 227u8, 214u8, 123u8, 18u8, 243u8, 68u8,
        173u8, 116u8, 163u8, 39u8, 28u8, 103u8, 140u8, 161u8, 167u8, 159u8,
    ],
    [
        1u8, 141u8, 202u8, 167u8, 81u8, 219u8, 72u8, 243u8, 238u8, 95u8, 39u8, 137u8, 114u8, 212u8,
        209u8, 214u8, 107u8, 178u8, 244u8, 195u8, 220u8, 189u8, 113u8, 130u8, 119u8, 151u8, 37u8,
        234u8, 184u8, 35u8, 32u8, 238u8, 12u8, 32u8, 176u8, 60u8, 123u8, 81u8, 41u8, 199u8, 137u8,
        111u8, 153u8, 1u8, 206u8, 188u8, 118u8, 36u8, 103u8, 50u8, 172u8, 0u8, 138u8, 165u8, 188u8,
        114u8, 187u8, 44u8, 90u8, 118u8, 7u8, 121u8, 59u8, 30u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        12u8, 181u8, 27u8, 58u8, 211u8, 240u8, 74u8, 194u8, 203u8, 159u8, 159u8, 150u8, 164u8,
        151u8, 220u8, 80u8, 200u8, 153u8, 222u8, 218u8, 11u8, 9u8, 224u8, 154u8, 83u8, 171u8,
        205u8, 78u8, 155u8, 201u8, 96u8, 3u8, 11u8, 122u8, 160u8, 104u8, 123u8, 137u8, 118u8, 57u8,
        36u8, 193u8, 214u8, 5u8, 133u8, 1u8, 129u8, 34u8, 13u8, 116u8, 154u8, 17u8, 244u8, 77u8,
        70u8, 63u8, 100u8, 232u8, 182u8, 25u8, 4u8, 155u8, 167u8, 211u8,
    ],
    vk_beta_g2: [
        29u8, 242u8, 58u8, 66u8, 118u8, 162u8, 36u8, 119u8, 92u8, 163u8, 240u8, 226u8, 78u8, 197u8,
        31u8, 29u8, 4u8, 133u8, 119u8, 155u8, 251u8, 92u8, 131u8, 20u8, 56u8, 211u8, 248u8, 185u8,
        212u8, 27u8, 172u8, 57u8, 18u8, 123u8, 242u8, 228u8, 66u8, 216u8, 1u8, 73u8, 127u8, 141u8,
        125u8, 179u8, 143u8, 121u8, 116u8, 0u8, 21u8, 224u8, 215u8, 135u8, 249u8, 108u8, 86u8,
        117u8, 213u8, 53u8, 98u8, 207u8, 133u8, 147u8, 36u8, 57u8, 7u8, 221u8, 149u8, 123u8, 246u8,
        205u8, 86u8, 235u8, 20u8, 194u8, 190u8, 235u8, 99u8, 56u8, 58u8, 226u8, 42u8, 195u8, 16u8,
        54u8, 42u8, 28u8, 26u8, 15u8, 230u8, 196u8, 125u8, 112u8, 186u8, 24u8, 123u8, 254u8, 26u8,
        81u8, 49u8, 244u8, 148u8, 148u8, 119u8, 174u8, 117u8, 125u8, 84u8, 228u8, 56u8, 186u8,
        37u8, 133u8, 165u8, 149u8, 161u8, 142u8, 80u8, 167u8, 50u8, 223u8, 89u8, 136u8, 205u8,
        147u8, 86u8, 16u8, 6u8, 80u8,
    ],
    vk_gamma_g2: [
        28u8, 92u8, 208u8, 135u8, 219u8, 200u8, 247u8, 235u8, 23u8, 230u8, 66u8, 58u8, 208u8,
        138u8, 137u8, 29u8, 5u8, 42u8, 179u8, 108u8, 99u8, 48u8, 90u8, 35u8, 150u8, 242u8, 97u8,
        177u8, 65u8, 223u8, 135u8, 97u8, 38u8, 57u8, 185u8, 229u8, 78u8, 119u8, 103u8, 183u8,
        251u8, 183u8, 194u8, 217u8, 205u8, 207u8, 192u8, 81u8, 93u8, 12u8, 224u8, 243u8, 78u8,
        126u8, 254u8, 241u8, 37u8, 228u8, 129u8, 200u8, 20u8, 20u8, 112u8, 173u8, 35u8, 131u8,
        213u8, 150u8, 132u8, 180u8, 162u8, 76u8, 42u8, 181u8, 88u8, 213u8, 240u8, 27u8, 227u8,
        214u8, 10u8, 53u8, 187u8, 56u8, 202u8, 71u8, 67u8, 197u8, 229u8, 141u8, 129u8, 139u8,
        165u8, 111u8, 13u8, 76u8, 27u8, 228u8, 231u8, 219u8, 186u8, 234u8, 60u8, 117u8, 76u8,
        122u8, 177u8, 23u8, 221u8, 31u8, 0u8, 114u8, 171u8, 187u8, 217u8, 255u8, 231u8, 91u8, 17u8,
        100u8, 172u8, 236u8, 251u8, 30u8, 73u8, 45u8, 63u8, 222u8,
    ],
    vk_delta_g2: [
        24u8, 30u8, 206u8, 17u8, 152u8, 214u8, 164u8, 194u8, 196u8, 119u8, 99u8, 254u8, 183u8,
        89u8, 52u8, 177u8, 204u8, 114u8, 215u8, 172u8, 211u8, 78u8, 90u8, 169u8, 224u8, 157u8,
        221u8, 4u8, 170u8, 91u8, 146u8, 17u8, 48u8, 59u8, 85u8, 92u8, 185u8, 86u8, 166u8, 96u8,
        237u8, 99u8, 202u8, 94u8, 145u8, 143u8, 84u8, 195u8, 95u8, 43u8, 7u8, 2u8, 1u8, 91u8, 10u8,
        30u8, 94u8, 38u8, 233u8, 142u8, 120u8, 172u8, 133u8, 146u8, 4u8, 252u8, 111u8, 108u8, 39u8,
        217u8, 160u8, 144u8, 211u8, 47u8, 224u8, 42u8, 31u8, 110u8, 216u8, 67u8, 52u8, 164u8,
        135u8, 243u8, 108u8, 177u8, 89u8, 212u8, 202u8, 175u8, 120u8, 166u8, 205u8, 206u8, 255u8,
        192u8, 34u8, 217u8, 125u8, 132u8, 15u8, 42u8, 152u8, 181u8, 80u8, 123u8, 254u8, 96u8,
        130u8, 64u8, 200u8, 231u8, 76u8, 25u8, 204u8, 112u8, 245u8, 215u8, 148u8, 195u8, 60u8,
        166u8, 28u8, 47u8, 150u8, 11u8, 160u8, 191u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [66u8, 30u8, 128u8, 26u8, 75u8, 176u8, 243u8, 155u8, 94u8, 137u8, 33u8, 204u8, 132u8, 119u8, 180u8, 8u8, 211u8, 105u8, 90u8, 130u8, 129u8, 36u8, 172u8, 108u8, 10u8, 25u8, 89u8, 72u8, 6u8, 171u8, 200u8, 107u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_219bf30de70a8136")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00421e801a4bb0f39b5e8921cc8477b408d3695a828124ac6c0a19594806abc86b\x00=======END GROTH16 VK SETUP V1=======\x00";
