// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        26u8, 185u8, 131u8, 254u8, 208u8, 56u8, 80u8, 41u8, 20u8, 98u8, 140u8, 7u8, 123u8, 136u8,
        147u8, 108u8, 107u8, 48u8, 166u8, 10u8, 181u8, 21u8, 43u8, 110u8, 171u8, 150u8, 160u8,
        48u8, 206u8, 241u8, 168u8, 224u8, 2u8, 166u8, 70u8, 215u8, 47u8, 183u8, 193u8, 94u8, 96u8,
        18u8, 110u8, 59u8, 60u8, 74u8, 105u8, 105u8, 176u8, 249u8, 206u8, 3u8, 24u8, 44u8, 63u8,
        181u8, 31u8, 8u8, 123u8, 69u8, 71u8, 154u8, 218u8, 217u8,
    ],
    [
        19u8, 53u8, 105u8, 59u8, 223u8, 157u8, 199u8, 166u8, 124u8, 33u8, 40u8, 90u8, 186u8, 100u8,
        213u8, 4u8, 255u8, 242u8, 159u8, 236u8, 0u8, 200u8, 99u8, 107u8, 73u8, 114u8, 122u8, 37u8,
        209u8, 70u8, 46u8, 91u8, 26u8, 26u8, 40u8, 7u8, 244u8, 225u8, 34u8, 187u8, 251u8, 27u8,
        6u8, 23u8, 36u8, 46u8, 40u8, 210u8, 143u8, 199u8, 230u8, 244u8, 189u8, 247u8, 64u8, 108u8,
        208u8, 76u8, 115u8, 176u8, 202u8, 113u8, 202u8, 26u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        7u8, 131u8, 205u8, 182u8, 50u8, 65u8, 211u8, 249u8, 89u8, 29u8, 90u8, 10u8, 27u8, 142u8,
        225u8, 181u8, 161u8, 51u8, 170u8, 84u8, 147u8, 52u8, 167u8, 231u8, 106u8, 231u8, 36u8,
        130u8, 222u8, 130u8, 128u8, 98u8, 27u8, 206u8, 140u8, 105u8, 240u8, 238u8, 91u8, 233u8,
        166u8, 227u8, 208u8, 208u8, 190u8, 203u8, 217u8, 181u8, 24u8, 107u8, 204u8, 183u8, 222u8,
        106u8, 45u8, 49u8, 8u8, 95u8, 245u8, 223u8, 87u8, 65u8, 167u8, 148u8,
    ],
    vk_beta_g2: [
        12u8, 44u8, 78u8, 169u8, 176u8, 18u8, 167u8, 252u8, 73u8, 237u8, 81u8, 44u8, 221u8, 165u8,
        59u8, 106u8, 24u8, 180u8, 116u8, 141u8, 88u8, 243u8, 195u8, 210u8, 17u8, 67u8, 45u8, 172u8,
        124u8, 159u8, 87u8, 70u8, 28u8, 146u8, 135u8, 163u8, 14u8, 177u8, 56u8, 237u8, 176u8, 7u8,
        96u8, 211u8, 152u8, 106u8, 122u8, 167u8, 150u8, 101u8, 138u8, 171u8, 255u8, 255u8, 195u8,
        44u8, 212u8, 97u8, 58u8, 27u8, 193u8, 121u8, 131u8, 150u8, 16u8, 177u8, 29u8, 253u8, 179u8,
        174u8, 207u8, 69u8, 77u8, 104u8, 72u8, 93u8, 213u8, 76u8, 217u8, 243u8, 204u8, 142u8,
        229u8, 167u8, 121u8, 129u8, 25u8, 180u8, 105u8, 122u8, 104u8, 208u8, 244u8, 164u8, 100u8,
        97u8, 14u8, 112u8, 245u8, 72u8, 96u8, 29u8, 59u8, 196u8, 14u8, 13u8, 244u8, 144u8, 168u8,
        98u8, 115u8, 137u8, 77u8, 83u8, 194u8, 24u8, 217u8, 194u8, 215u8, 148u8, 226u8, 123u8,
        169u8, 58u8, 50u8, 88u8, 152u8, 49u8,
    ],
    vk_gamma_g2: [
        19u8, 204u8, 153u8, 157u8, 67u8, 75u8, 239u8, 5u8, 223u8, 38u8, 10u8, 243u8, 157u8, 115u8,
        114u8, 166u8, 197u8, 215u8, 177u8, 50u8, 131u8, 96u8, 155u8, 239u8, 19u8, 93u8, 129u8,
        131u8, 64u8, 53u8, 142u8, 140u8, 33u8, 3u8, 249u8, 33u8, 48u8, 147u8, 31u8, 31u8, 195u8,
        254u8, 21u8, 142u8, 237u8, 107u8, 14u8, 33u8, 73u8, 212u8, 251u8, 106u8, 83u8, 114u8,
        166u8, 217u8, 110u8, 86u8, 40u8, 69u8, 152u8, 161u8, 197u8, 167u8, 32u8, 57u8, 33u8, 177u8,
        131u8, 43u8, 24u8, 93u8, 106u8, 160u8, 137u8, 82u8, 40u8, 183u8, 122u8, 229u8, 247u8, 0u8,
        35u8, 14u8, 244u8, 158u8, 192u8, 98u8, 17u8, 110u8, 39u8, 237u8, 158u8, 147u8, 39u8, 208u8,
        45u8, 224u8, 212u8, 79u8, 40u8, 235u8, 63u8, 248u8, 107u8, 28u8, 247u8, 195u8, 117u8,
        151u8, 23u8, 127u8, 88u8, 240u8, 178u8, 136u8, 69u8, 46u8, 150u8, 171u8, 243u8, 160u8, 8u8,
        25u8, 175u8, 226u8, 36u8, 107u8,
    ],
    vk_delta_g2: [
        11u8, 58u8, 104u8, 182u8, 133u8, 92u8, 165u8, 46u8, 118u8, 46u8, 76u8, 187u8, 199u8, 171u8,
        176u8, 48u8, 229u8, 203u8, 120u8, 19u8, 201u8, 69u8, 68u8, 159u8, 169u8, 162u8, 68u8,
        151u8, 19u8, 106u8, 152u8, 163u8, 46u8, 26u8, 222u8, 144u8, 50u8, 135u8, 49u8, 221u8, 70u8,
        111u8, 72u8, 253u8, 42u8, 134u8, 22u8, 97u8, 100u8, 47u8, 53u8, 115u8, 0u8, 10u8, 9u8,
        103u8, 107u8, 81u8, 107u8, 25u8, 216u8, 81u8, 34u8, 72u8, 2u8, 68u8, 1u8, 152u8, 136u8,
        162u8, 225u8, 246u8, 41u8, 232u8, 174u8, 184u8, 205u8, 10u8, 87u8, 182u8, 51u8, 222u8,
        199u8, 136u8, 172u8, 42u8, 172u8, 197u8, 8u8, 196u8, 90u8, 194u8, 240u8, 122u8, 245u8,
        159u8, 1u8, 150u8, 193u8, 199u8, 66u8, 174u8, 134u8, 27u8, 89u8, 164u8, 2u8, 169u8, 144u8,
        192u8, 48u8, 133u8, 65u8, 82u8, 112u8, 234u8, 153u8, 139u8, 155u8, 70u8, 178u8, 223u8,
        64u8, 75u8, 219u8, 51u8, 212u8, 209u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [160u8, 109u8, 197u8, 209u8, 236u8, 253u8, 66u8, 129u8, 115u8, 241u8, 37u8, 202u8, 248u8, 65u8, 10u8, 95u8, 187u8, 38u8, 168u8, 24u8, 97u8, 165u8, 120u8, 181u8, 75u8, 104u8, 31u8, 80u8, 52u8, 66u8, 190u8, 200u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_cbae2abb0c98614a")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00a06dc5d1ecfd428173f125caf8410a5fbb26a81861a578b54b681f503442bec8\x00=======END GROTH16 VK SETUP V1=======\x00";
