// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        36u8, 2u8, 43u8, 171u8, 39u8, 15u8, 164u8, 197u8, 135u8, 152u8, 150u8, 64u8, 28u8, 229u8,
        250u8, 71u8, 233u8, 59u8, 190u8, 242u8, 54u8, 110u8, 68u8, 91u8, 49u8, 25u8, 59u8, 42u8,
        219u8, 169u8, 180u8, 123u8, 44u8, 243u8, 113u8, 214u8, 55u8, 100u8, 183u8, 27u8, 91u8,
        207u8, 6u8, 175u8, 154u8, 54u8, 56u8, 100u8, 37u8, 142u8, 5u8, 177u8, 114u8, 170u8, 75u8,
        142u8, 155u8, 13u8, 17u8, 139u8, 207u8, 143u8, 67u8, 251u8,
    ],
    [
        42u8, 173u8, 231u8, 144u8, 74u8, 96u8, 80u8, 67u8, 216u8, 154u8, 73u8, 199u8, 72u8, 22u8,
        117u8, 6u8, 158u8, 192u8, 22u8, 45u8, 18u8, 152u8, 183u8, 129u8, 70u8, 206u8, 44u8, 51u8,
        205u8, 38u8, 236u8, 223u8, 20u8, 5u8, 42u8, 77u8, 63u8, 80u8, 88u8, 218u8, 27u8, 40u8,
        231u8, 14u8, 54u8, 40u8, 207u8, 190u8, 142u8, 58u8, 117u8, 198u8, 13u8, 16u8, 247u8, 37u8,
        239u8, 143u8, 161u8, 227u8, 47u8, 37u8, 246u8, 145u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        2u8, 89u8, 130u8, 18u8, 139u8, 50u8, 171u8, 102u8, 102u8, 251u8, 89u8, 225u8, 131u8, 127u8,
        218u8, 151u8, 68u8, 223u8, 38u8, 46u8, 164u8, 224u8, 222u8, 106u8, 2u8, 64u8, 50u8, 14u8,
        86u8, 108u8, 170u8, 103u8, 20u8, 181u8, 94u8, 41u8, 229u8, 81u8, 60u8, 176u8, 252u8, 26u8,
        238u8, 82u8, 106u8, 209u8, 11u8, 22u8, 166u8, 131u8, 91u8, 99u8, 46u8, 220u8, 157u8, 123u8,
        20u8, 134u8, 167u8, 41u8, 150u8, 187u8, 62u8, 88u8,
    ],
    vk_beta_g2: [
        16u8, 223u8, 60u8, 101u8, 247u8, 71u8, 176u8, 220u8, 34u8, 145u8, 80u8, 104u8, 105u8, 50u8,
        158u8, 206u8, 134u8, 247u8, 94u8, 135u8, 135u8, 225u8, 50u8, 11u8, 134u8, 76u8, 208u8,
        198u8, 218u8, 45u8, 92u8, 252u8, 28u8, 243u8, 181u8, 183u8, 45u8, 69u8, 92u8, 223u8, 44u8,
        177u8, 18u8, 247u8, 11u8, 11u8, 38u8, 189u8, 196u8, 164u8, 68u8, 154u8, 251u8, 116u8, 26u8,
        36u8, 4u8, 195u8, 79u8, 82u8, 153u8, 158u8, 114u8, 147u8, 11u8, 186u8, 35u8, 10u8, 197u8,
        150u8, 106u8, 81u8, 44u8, 98u8, 217u8, 109u8, 197u8, 108u8, 155u8, 250u8, 122u8, 48u8,
        69u8, 91u8, 114u8, 117u8, 84u8, 30u8, 247u8, 184u8, 66u8, 87u8, 220u8, 44u8, 23u8, 223u8,
        41u8, 68u8, 72u8, 71u8, 123u8, 176u8, 226u8, 22u8, 64u8, 176u8, 50u8, 133u8, 134u8, 200u8,
        146u8, 255u8, 113u8, 174u8, 147u8, 52u8, 44u8, 229u8, 99u8, 53u8, 101u8, 201u8, 1u8, 223u8,
        139u8, 45u8, 49u8, 107u8,
    ],
    vk_gamma_g2: [
        36u8, 120u8, 249u8, 116u8, 162u8, 99u8, 127u8, 123u8, 39u8, 3u8, 219u8, 40u8, 190u8, 218u8,
        57u8, 139u8, 188u8, 122u8, 126u8, 208u8, 228u8, 159u8, 159u8, 152u8, 188u8, 48u8, 214u8,
        99u8, 122u8, 81u8, 83u8, 98u8, 26u8, 23u8, 206u8, 131u8, 172u8, 77u8, 167u8, 247u8, 2u8,
        163u8, 205u8, 185u8, 171u8, 119u8, 169u8, 208u8, 191u8, 40u8, 153u8, 139u8, 14u8, 147u8,
        189u8, 125u8, 234u8, 207u8, 251u8, 81u8, 200u8, 216u8, 47u8, 118u8, 27u8, 85u8, 212u8,
        191u8, 21u8, 17u8, 48u8, 220u8, 12u8, 123u8, 246u8, 85u8, 78u8, 178u8, 0u8, 54u8, 45u8,
        65u8, 177u8, 11u8, 150u8, 19u8, 182u8, 73u8, 191u8, 207u8, 72u8, 91u8, 155u8, 174u8, 54u8,
        137u8, 25u8, 245u8, 88u8, 179u8, 174u8, 197u8, 131u8, 62u8, 23u8, 182u8, 155u8, 85u8, 4u8,
        12u8, 223u8, 140u8, 124u8, 76u8, 165u8, 54u8, 226u8, 27u8, 147u8, 128u8, 247u8, 207u8,
        124u8, 248u8, 31u8, 122u8, 54u8, 150u8,
    ],
    vk_delta_g2: [
        45u8, 212u8, 12u8, 131u8, 233u8, 125u8, 193u8, 124u8, 31u8, 118u8, 182u8, 93u8, 162u8,
        180u8, 173u8, 58u8, 176u8, 130u8, 25u8, 37u8, 110u8, 184u8, 20u8, 175u8, 64u8, 33u8, 216u8,
        197u8, 117u8, 134u8, 65u8, 63u8, 19u8, 41u8, 181u8, 96u8, 63u8, 0u8, 146u8, 122u8, 24u8,
        172u8, 194u8, 234u8, 142u8, 138u8, 206u8, 245u8, 169u8, 94u8, 178u8, 172u8, 95u8, 162u8,
        159u8, 15u8, 125u8, 169u8, 9u8, 18u8, 201u8, 226u8, 235u8, 196u8, 33u8, 180u8, 222u8, 7u8,
        38u8, 214u8, 202u8, 13u8, 8u8, 161u8, 57u8, 62u8, 137u8, 214u8, 165u8, 107u8, 88u8, 24u8,
        49u8, 25u8, 191u8, 48u8, 244u8, 225u8, 54u8, 128u8, 230u8, 197u8, 211u8, 89u8, 165u8, 4u8,
        2u8, 87u8, 14u8, 224u8, 164u8, 154u8, 219u8, 123u8, 56u8, 103u8, 87u8, 11u8, 219u8, 169u8,
        244u8, 148u8, 179u8, 253u8, 55u8, 199u8, 138u8, 152u8, 83u8, 254u8, 25u8, 24u8, 4u8, 59u8,
        94u8, 121u8, 120u8, 11u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [233u8, 113u8, 24u8, 135u8, 102u8, 199u8, 163u8, 61u8, 42u8, 20u8, 59u8, 72u8, 229u8, 34u8, 175u8, 171u8, 201u8, 183u8, 9u8, 166u8, 205u8, 177u8, 78u8, 179u8, 38u8, 165u8, 223u8, 79u8, 197u8, 198u8, 217u8, 12u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_b9d4551f96961b27")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00e971188766c7a33d2a143b48e522afabc9b709a6cdb14eb326a5df4fc5c6d90c\x00=======END GROTH16 VK SETUP V1=======\x00";
