// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        29u8, 97u8, 170u8, 76u8, 95u8, 6u8, 36u8, 94u8, 189u8, 37u8, 241u8, 129u8, 214u8, 150u8,
        119u8, 134u8, 32u8, 34u8, 120u8, 231u8, 67u8, 40u8, 11u8, 195u8, 70u8, 208u8, 122u8, 158u8,
        129u8, 87u8, 45u8, 60u8, 32u8, 249u8, 200u8, 90u8, 19u8, 186u8, 68u8, 234u8, 40u8, 165u8,
        115u8, 143u8, 34u8, 221u8, 157u8, 4u8, 168u8, 125u8, 10u8, 223u8, 16u8, 98u8, 134u8, 28u8,
        110u8, 124u8, 15u8, 212u8, 178u8, 59u8, 242u8, 47u8,
    ],
    [
        18u8, 13u8, 247u8, 10u8, 231u8, 237u8, 196u8, 212u8, 213u8, 75u8, 188u8, 14u8, 192u8, 76u8,
        85u8, 236u8, 158u8, 237u8, 20u8, 247u8, 63u8, 214u8, 156u8, 237u8, 50u8, 1u8, 16u8, 125u8,
        34u8, 251u8, 123u8, 174u8, 4u8, 82u8, 228u8, 26u8, 252u8, 174u8, 206u8, 53u8, 133u8, 240u8,
        141u8, 186u8, 74u8, 240u8, 149u8, 113u8, 183u8, 104u8, 18u8, 97u8, 191u8, 15u8, 13u8,
        117u8, 56u8, 116u8, 21u8, 127u8, 218u8, 180u8, 4u8, 39u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        15u8, 133u8, 23u8, 129u8, 210u8, 196u8, 78u8, 11u8, 41u8, 251u8, 117u8, 192u8, 210u8, 27u8,
        224u8, 241u8, 5u8, 54u8, 141u8, 200u8, 32u8, 190u8, 186u8, 93u8, 191u8, 162u8, 174u8,
        171u8, 67u8, 213u8, 61u8, 219u8, 7u8, 145u8, 181u8, 112u8, 227u8, 198u8, 238u8, 107u8,
        127u8, 14u8, 12u8, 25u8, 247u8, 238u8, 180u8, 157u8, 8u8, 141u8, 89u8, 141u8, 242u8, 178u8,
        192u8, 67u8, 13u8, 159u8, 49u8, 2u8, 10u8, 56u8, 158u8, 89u8,
    ],
    vk_beta_g2: [
        1u8, 253u8, 128u8, 204u8, 94u8, 29u8, 213u8, 173u8, 200u8, 229u8, 219u8, 227u8, 70u8,
        140u8, 113u8, 170u8, 151u8, 213u8, 122u8, 66u8, 99u8, 31u8, 233u8, 118u8, 166u8, 52u8,
        188u8, 108u8, 71u8, 102u8, 78u8, 83u8, 10u8, 224u8, 200u8, 61u8, 223u8, 24u8, 172u8, 63u8,
        235u8, 217u8, 63u8, 35u8, 118u8, 192u8, 181u8, 55u8, 204u8, 5u8, 20u8, 3u8, 56u8, 210u8,
        6u8, 111u8, 166u8, 13u8, 20u8, 37u8, 59u8, 236u8, 0u8, 50u8, 46u8, 198u8, 95u8, 241u8,
        207u8, 131u8, 255u8, 234u8, 169u8, 150u8, 117u8, 171u8, 29u8, 41u8, 90u8, 18u8, 127u8,
        91u8, 24u8, 127u8, 165u8, 233u8, 34u8, 172u8, 255u8, 25u8, 68u8, 147u8, 118u8, 174u8,
        248u8, 46u8, 34u8, 80u8, 172u8, 19u8, 141u8, 28u8, 252u8, 28u8, 86u8, 38u8, 6u8, 251u8,
        180u8, 197u8, 170u8, 112u8, 43u8, 252u8, 244u8, 234u8, 29u8, 43u8, 251u8, 217u8, 210u8,
        187u8, 44u8, 121u8, 138u8, 175u8, 159u8, 81u8,
    ],
    vk_gamma_g2: [
        41u8, 66u8, 183u8, 207u8, 168u8, 16u8, 27u8, 20u8, 155u8, 68u8, 67u8, 15u8, 43u8, 76u8,
        41u8, 117u8, 16u8, 186u8, 139u8, 235u8, 134u8, 47u8, 95u8, 173u8, 242u8, 100u8, 90u8, 75u8,
        149u8, 54u8, 159u8, 214u8, 33u8, 41u8, 16u8, 64u8, 201u8, 112u8, 5u8, 158u8, 230u8, 156u8,
        226u8, 98u8, 243u8, 139u8, 23u8, 174u8, 129u8, 73u8, 178u8, 191u8, 27u8, 42u8, 210u8, 44u8,
        210u8, 166u8, 252u8, 46u8, 115u8, 59u8, 164u8, 194u8, 10u8, 51u8, 20u8, 70u8, 48u8, 50u8,
        86u8, 9u8, 118u8, 7u8, 186u8, 243u8, 9u8, 148u8, 167u8, 111u8, 154u8, 10u8, 235u8, 66u8,
        157u8, 216u8, 180u8, 39u8, 46u8, 56u8, 239u8, 97u8, 235u8, 115u8, 246u8, 87u8, 12u8, 196u8,
        48u8, 68u8, 13u8, 182u8, 184u8, 187u8, 213u8, 43u8, 224u8, 108u8, 80u8, 159u8, 236u8, 92u8,
        163u8, 34u8, 134u8, 156u8, 180u8, 132u8, 76u8, 205u8, 242u8, 120u8, 216u8, 207u8, 117u8,
        116u8, 182u8, 75u8,
    ],
    vk_delta_g2: [
        38u8, 35u8, 228u8, 180u8, 71u8, 144u8, 91u8, 240u8, 134u8, 63u8, 234u8, 194u8, 179u8, 41u8,
        178u8, 8u8, 66u8, 167u8, 184u8, 43u8, 65u8, 151u8, 172u8, 182u8, 42u8, 31u8, 19u8, 78u8,
        221u8, 204u8, 230u8, 56u8, 31u8, 40u8, 140u8, 89u8, 194u8, 195u8, 138u8, 164u8, 254u8,
        122u8, 8u8, 140u8, 29u8, 88u8, 78u8, 111u8, 23u8, 101u8, 214u8, 20u8, 147u8, 128u8, 239u8,
        205u8, 49u8, 60u8, 110u8, 152u8, 37u8, 99u8, 225u8, 27u8, 27u8, 91u8, 162u8, 175u8, 7u8,
        206u8, 100u8, 167u8, 44u8, 75u8, 245u8, 42u8, 217u8, 178u8, 84u8, 222u8, 74u8, 207u8,
        170u8, 141u8, 119u8, 96u8, 23u8, 224u8, 31u8, 126u8, 72u8, 47u8, 15u8, 14u8, 61u8, 24u8,
        8u8, 220u8, 203u8, 156u8, 127u8, 197u8, 239u8, 69u8, 166u8, 183u8, 44u8, 84u8, 24u8, 211u8,
        187u8, 160u8, 97u8, 202u8, 103u8, 27u8, 109u8, 75u8, 74u8, 245u8, 202u8, 151u8, 137u8,
        60u8, 54u8, 141u8, 66u8, 46u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [57u8, 10u8, 106u8, 173u8, 35u8, 52u8, 208u8, 201u8, 12u8, 215u8, 129u8, 135u8, 192u8, 71u8, 228u8, 9u8, 21u8, 169u8, 84u8, 204u8, 87u8, 219u8, 169u8, 139u8, 124u8, 200u8, 244u8, 56u8, 159u8, 249u8, 91u8, 45u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_f86eb7bf4d75bb75")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00390a6aad2334d0c90cd78187c047e40915a954cc57dba98b7cc8f4389ff95b2d\x00=======END GROTH16 VK SETUP V1=======\x00";
