// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        9u8, 26u8, 142u8, 107u8, 34u8, 25u8, 28u8, 224u8, 60u8, 193u8, 62u8, 41u8, 92u8, 222u8,
        54u8, 95u8, 30u8, 157u8, 146u8, 150u8, 132u8, 112u8, 52u8, 8u8, 253u8, 20u8, 215u8, 124u8,
        228u8, 252u8, 97u8, 156u8, 10u8, 202u8, 86u8, 190u8, 157u8, 53u8, 93u8, 161u8, 76u8, 138u8,
        25u8, 144u8, 151u8, 179u8, 89u8, 245u8, 106u8, 253u8, 98u8, 104u8, 213u8, 229u8, 168u8,
        101u8, 17u8, 177u8, 214u8, 32u8, 88u8, 158u8, 111u8, 243u8,
    ],
    [
        39u8, 42u8, 207u8, 114u8, 202u8, 80u8, 207u8, 181u8, 254u8, 229u8, 103u8, 249u8, 250u8,
        139u8, 19u8, 219u8, 66u8, 111u8, 255u8, 183u8, 147u8, 114u8, 100u8, 100u8, 183u8, 93u8,
        102u8, 235u8, 6u8, 191u8, 237u8, 248u8, 35u8, 140u8, 166u8, 85u8, 201u8, 73u8, 208u8,
        100u8, 145u8, 0u8, 187u8, 160u8, 13u8, 83u8, 80u8, 10u8, 241u8, 195u8, 165u8, 93u8, 53u8,
        119u8, 123u8, 21u8, 121u8, 32u8, 242u8, 222u8, 114u8, 98u8, 193u8, 94u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        48u8, 97u8, 159u8, 32u8, 249u8, 78u8, 98u8, 124u8, 226u8, 203u8, 84u8, 121u8, 70u8, 231u8,
        19u8, 67u8, 204u8, 241u8, 217u8, 193u8, 152u8, 98u8, 201u8, 251u8, 213u8, 212u8, 217u8,
        33u8, 153u8, 37u8, 190u8, 74u8, 24u8, 130u8, 119u8, 27u8, 178u8, 250u8, 240u8, 205u8,
        213u8, 66u8, 224u8, 219u8, 105u8, 23u8, 44u8, 27u8, 241u8, 124u8, 24u8, 254u8, 56u8, 57u8,
        96u8, 112u8, 97u8, 11u8, 116u8, 10u8, 146u8, 115u8, 137u8, 154u8,
    ],
    vk_beta_g2: [
        29u8, 59u8, 204u8, 51u8, 205u8, 112u8, 33u8, 45u8, 22u8, 53u8, 196u8, 145u8, 212u8, 86u8,
        17u8, 198u8, 55u8, 106u8, 123u8, 198u8, 21u8, 171u8, 142u8, 154u8, 178u8, 182u8, 214u8,
        106u8, 216u8, 222u8, 16u8, 117u8, 17u8, 15u8, 42u8, 238u8, 240u8, 160u8, 216u8, 171u8,
        22u8, 55u8, 145u8, 141u8, 21u8, 157u8, 60u8, 6u8, 176u8, 202u8, 222u8, 36u8, 192u8, 236u8,
        176u8, 82u8, 141u8, 86u8, 115u8, 106u8, 17u8, 178u8, 38u8, 155u8, 7u8, 146u8, 175u8, 31u8,
        176u8, 135u8, 212u8, 135u8, 184u8, 243u8, 131u8, 208u8, 178u8, 140u8, 204u8, 56u8, 59u8,
        119u8, 81u8, 158u8, 29u8, 126u8, 42u8, 9u8, 31u8, 10u8, 101u8, 15u8, 17u8, 59u8, 93u8,
        172u8, 36u8, 85u8, 204u8, 172u8, 17u8, 223u8, 244u8, 86u8, 15u8, 244u8, 123u8, 209u8, 23u8,
        91u8, 165u8, 217u8, 252u8, 159u8, 141u8, 189u8, 209u8, 113u8, 13u8, 63u8, 161u8, 181u8,
        72u8, 195u8, 56u8, 45u8, 4u8, 22u8,
    ],
    vk_gamma_g2: [
        10u8, 142u8, 223u8, 101u8, 93u8, 176u8, 55u8, 59u8, 252u8, 186u8, 13u8, 59u8, 190u8, 33u8,
        84u8, 134u8, 234u8, 248u8, 103u8, 211u8, 146u8, 234u8, 93u8, 47u8, 1u8, 167u8, 29u8, 172u8,
        6u8, 78u8, 153u8, 139u8, 7u8, 136u8, 67u8, 239u8, 73u8, 187u8, 138u8, 118u8, 41u8, 83u8,
        203u8, 203u8, 104u8, 170u8, 221u8, 110u8, 110u8, 121u8, 79u8, 210u8, 229u8, 138u8, 62u8,
        196u8, 83u8, 126u8, 52u8, 38u8, 90u8, 101u8, 100u8, 20u8, 14u8, 178u8, 8u8, 83u8, 95u8,
        65u8, 251u8, 5u8, 10u8, 192u8, 191u8, 52u8, 187u8, 77u8, 172u8, 241u8, 134u8, 249u8, 152u8,
        76u8, 149u8, 4u8, 135u8, 40u8, 4u8, 158u8, 224u8, 204u8, 122u8, 148u8, 86u8, 15u8, 4u8,
        133u8, 87u8, 16u8, 239u8, 130u8, 137u8, 36u8, 144u8, 255u8, 220u8, 15u8, 137u8, 147u8,
        141u8, 180u8, 145u8, 18u8, 16u8, 86u8, 102u8, 56u8, 204u8, 171u8, 231u8, 102u8, 170u8,
        161u8, 133u8, 100u8, 105u8, 250u8,
    ],
    vk_delta_g2: [
        40u8, 168u8, 75u8, 5u8, 254u8, 150u8, 180u8, 165u8, 222u8, 93u8, 244u8, 99u8, 128u8, 188u8,
        139u8, 88u8, 2u8, 229u8, 25u8, 182u8, 114u8, 154u8, 205u8, 69u8, 4u8, 253u8, 217u8, 61u8,
        185u8, 39u8, 219u8, 181u8, 15u8, 163u8, 107u8, 6u8, 25u8, 29u8, 239u8, 9u8, 135u8, 66u8,
        88u8, 179u8, 35u8, 34u8, 145u8, 210u8, 197u8, 71u8, 118u8, 181u8, 60u8, 251u8, 199u8,
        190u8, 120u8, 17u8, 103u8, 228u8, 186u8, 4u8, 105u8, 13u8, 8u8, 235u8, 149u8, 44u8, 110u8,
        188u8, 161u8, 146u8, 214u8, 184u8, 186u8, 6u8, 20u8, 167u8, 27u8, 65u8, 26u8, 96u8, 39u8,
        109u8, 147u8, 232u8, 19u8, 174u8, 140u8, 210u8, 247u8, 225u8, 208u8, 56u8, 174u8, 187u8,
        5u8, 115u8, 235u8, 165u8, 221u8, 128u8, 188u8, 131u8, 240u8, 69u8, 100u8, 42u8, 3u8, 46u8,
        231u8, 101u8, 135u8, 1u8, 33u8, 250u8, 244u8, 114u8, 134u8, 171u8, 1u8, 144u8, 141u8,
        140u8, 234u8, 236u8, 2u8, 220u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [196u8, 148u8, 132u8, 208u8, 20u8, 196u8, 111u8, 192u8, 122u8, 168u8, 156u8, 162u8, 57u8, 69u8, 129u8, 137u8, 20u8, 208u8, 24u8, 255u8, 189u8, 165u8, 245u8, 136u8, 178u8, 13u8, 144u8, 112u8, 21u8, 56u8, 141u8, 17u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_9dc9f6ea237c5f85")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00c49484d014c46fc07aa89ca23945818914d018ffbda5f588b20d907015388d11\x00=======END GROTH16 VK SETUP V1=======\x00";
