// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        35u8, 210u8, 205u8, 37u8, 248u8, 223u8, 3u8, 63u8, 61u8, 4u8, 46u8, 224u8, 172u8, 66u8,
        253u8, 126u8, 35u8, 179u8, 19u8, 156u8, 166u8, 205u8, 55u8, 121u8, 166u8, 19u8, 93u8,
        227u8, 194u8, 6u8, 17u8, 205u8, 36u8, 183u8, 147u8, 197u8, 193u8, 99u8, 124u8, 21u8, 230u8,
        149u8, 188u8, 45u8, 251u8, 124u8, 31u8, 29u8, 33u8, 146u8, 135u8, 88u8, 238u8, 61u8, 178u8,
        136u8, 73u8, 143u8, 126u8, 187u8, 217u8, 120u8, 61u8, 159u8,
    ],
    [
        12u8, 56u8, 235u8, 188u8, 96u8, 193u8, 211u8, 33u8, 74u8, 233u8, 238u8, 12u8, 68u8, 107u8,
        112u8, 22u8, 73u8, 197u8, 181u8, 148u8, 49u8, 78u8, 164u8, 71u8, 252u8, 168u8, 217u8, 40u8,
        170u8, 99u8, 164u8, 122u8, 2u8, 23u8, 51u8, 32u8, 1u8, 234u8, 179u8, 188u8, 223u8, 63u8,
        254u8, 195u8, 227u8, 203u8, 27u8, 167u8, 6u8, 203u8, 202u8, 190u8, 49u8, 240u8, 39u8, 92u8,
        200u8, 58u8, 127u8, 249u8, 134u8, 171u8, 161u8, 77u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        7u8, 34u8, 75u8, 111u8, 46u8, 227u8, 141u8, 67u8, 221u8, 93u8, 39u8, 20u8, 78u8, 136u8,
        64u8, 123u8, 182u8, 70u8, 247u8, 36u8, 12u8, 219u8, 250u8, 139u8, 207u8, 71u8, 210u8,
        204u8, 208u8, 174u8, 228u8, 178u8, 16u8, 134u8, 5u8, 160u8, 247u8, 63u8, 83u8, 135u8, 0u8,
        29u8, 174u8, 53u8, 246u8, 218u8, 160u8, 91u8, 116u8, 150u8, 178u8, 210u8, 17u8, 203u8,
        232u8, 250u8, 245u8, 53u8, 51u8, 233u8, 186u8, 112u8, 118u8, 141u8,
    ],
    vk_beta_g2: [
        28u8, 213u8, 68u8, 150u8, 84u8, 171u8, 92u8, 4u8, 149u8, 218u8, 39u8, 92u8, 219u8, 58u8,
        243u8, 147u8, 30u8, 182u8, 254u8, 99u8, 10u8, 112u8, 95u8, 125u8, 237u8, 5u8, 195u8, 233u8,
        248u8, 36u8, 204u8, 240u8, 44u8, 3u8, 25u8, 138u8, 112u8, 246u8, 121u8, 209u8, 10u8, 94u8,
        4u8, 9u8, 8u8, 33u8, 186u8, 239u8, 160u8, 240u8, 250u8, 169u8, 80u8, 85u8, 250u8, 235u8,
        80u8, 105u8, 193u8, 225u8, 88u8, 234u8, 16u8, 142u8, 32u8, 85u8, 138u8, 173u8, 249u8,
        162u8, 101u8, 157u8, 115u8, 102u8, 17u8, 14u8, 212u8, 115u8, 168u8, 83u8, 17u8, 9u8, 168u8,
        81u8, 116u8, 250u8, 222u8, 26u8, 20u8, 3u8, 63u8, 183u8, 73u8, 66u8, 110u8, 35u8, 17u8,
        203u8, 204u8, 156u8, 191u8, 141u8, 110u8, 206u8, 66u8, 176u8, 161u8, 72u8, 11u8, 221u8,
        73u8, 97u8, 155u8, 9u8, 46u8, 85u8, 21u8, 155u8, 168u8, 48u8, 160u8, 59u8, 32u8, 98u8,
        187u8, 97u8, 79u8, 95u8,
    ],
    vk_gamma_g2: [
        42u8, 15u8, 21u8, 60u8, 188u8, 94u8, 92u8, 226u8, 58u8, 23u8, 122u8, 147u8, 166u8, 38u8,
        70u8, 9u8, 86u8, 12u8, 66u8, 183u8, 149u8, 48u8, 165u8, 200u8, 211u8, 255u8, 245u8, 197u8,
        130u8, 152u8, 200u8, 95u8, 5u8, 226u8, 146u8, 154u8, 183u8, 199u8, 230u8, 127u8, 118u8,
        5u8, 163u8, 203u8, 188u8, 226u8, 230u8, 220u8, 245u8, 95u8, 159u8, 65u8, 56u8, 144u8,
        148u8, 97u8, 216u8, 120u8, 55u8, 32u8, 85u8, 98u8, 212u8, 169u8, 17u8, 162u8, 250u8, 106u8,
        115u8, 90u8, 169u8, 152u8, 32u8, 184u8, 191u8, 58u8, 126u8, 109u8, 212u8, 18u8, 174u8,
        23u8, 23u8, 169u8, 16u8, 7u8, 36u8, 155u8, 160u8, 200u8, 71u8, 143u8, 196u8, 70u8, 1u8,
        33u8, 16u8, 202u8, 178u8, 50u8, 66u8, 143u8, 175u8, 84u8, 189u8, 200u8, 1u8, 188u8, 21u8,
        154u8, 77u8, 26u8, 19u8, 225u8, 232u8, 142u8, 121u8, 227u8, 8u8, 34u8, 49u8, 40u8, 3u8,
        33u8, 248u8, 68u8, 29u8, 59u8,
    ],
    vk_delta_g2: [
        21u8, 9u8, 54u8, 165u8, 0u8, 43u8, 222u8, 188u8, 170u8, 210u8, 40u8, 36u8, 91u8, 148u8,
        236u8, 239u8, 220u8, 138u8, 162u8, 159u8, 150u8, 148u8, 149u8, 39u8, 187u8, 59u8, 100u8,
        116u8, 26u8, 118u8, 232u8, 93u8, 35u8, 153u8, 101u8, 212u8, 238u8, 141u8, 48u8, 106u8,
        146u8, 1u8, 234u8, 214u8, 171u8, 111u8, 191u8, 137u8, 33u8, 46u8, 209u8, 47u8, 44u8, 108u8,
        151u8, 77u8, 60u8, 36u8, 203u8, 236u8, 203u8, 178u8, 243u8, 231u8, 12u8, 101u8, 189u8,
        238u8, 231u8, 193u8, 252u8, 239u8, 102u8, 85u8, 248u8, 19u8, 96u8, 164u8, 7u8, 238u8,
        255u8, 106u8, 49u8, 74u8, 233u8, 167u8, 109u8, 36u8, 117u8, 62u8, 221u8, 100u8, 59u8, 37u8,
        222u8, 145u8, 20u8, 145u8, 36u8, 188u8, 161u8, 162u8, 198u8, 128u8, 230u8, 85u8, 242u8,
        208u8, 137u8, 128u8, 188u8, 130u8, 14u8, 246u8, 18u8, 75u8, 187u8, 148u8, 190u8, 30u8,
        209u8, 20u8, 204u8, 123u8, 154u8, 9u8, 111u8, 170u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [30u8, 180u8, 36u8, 130u8, 179u8, 250u8, 53u8, 189u8, 15u8, 197u8, 129u8, 250u8, 31u8, 179u8, 65u8, 138u8, 67u8, 128u8, 117u8, 166u8, 189u8, 221u8, 173u8, 181u8, 8u8, 98u8, 118u8, 48u8, 95u8, 32u8, 0u8, 187u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_01918681d3b91e22")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x001eb42482b3fa35bd0fc581fa1fb3418a438075a6bdddadb5086276305f2000bb\x00=======END GROTH16 VK SETUP V1=======\x00";
