// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        39u8, 83u8, 121u8, 123u8, 248u8, 35u8, 163u8, 221u8, 134u8, 15u8, 99u8, 197u8, 13u8, 29u8,
        92u8, 233u8, 31u8, 90u8, 214u8, 94u8, 133u8, 9u8, 127u8, 56u8, 135u8, 203u8, 241u8, 155u8,
        226u8, 208u8, 254u8, 193u8, 8u8, 163u8, 110u8, 148u8, 117u8, 62u8, 234u8, 233u8, 216u8,
        115u8, 188u8, 101u8, 74u8, 35u8, 6u8, 79u8, 111u8, 55u8, 239u8, 3u8, 97u8, 101u8, 226u8,
        159u8, 160u8, 113u8, 207u8, 249u8, 43u8, 94u8, 182u8, 147u8,
    ],
    [
        7u8, 38u8, 215u8, 61u8, 253u8, 139u8, 200u8, 89u8, 106u8, 177u8, 207u8, 185u8, 192u8, 65u8,
        130u8, 39u8, 74u8, 103u8, 144u8, 75u8, 47u8, 120u8, 23u8, 126u8, 168u8, 222u8, 58u8, 237u8,
        242u8, 93u8, 19u8, 64u8, 44u8, 57u8, 209u8, 108u8, 125u8, 57u8, 35u8, 193u8, 92u8, 87u8,
        202u8, 98u8, 68u8, 8u8, 13u8, 95u8, 119u8, 143u8, 199u8, 145u8, 4u8, 195u8, 228u8, 33u8,
        4u8, 95u8, 231u8, 30u8, 5u8, 26u8, 48u8, 96u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        4u8, 24u8, 8u8, 18u8, 33u8, 136u8, 201u8, 119u8, 119u8, 3u8, 216u8, 78u8, 220u8, 127u8,
        188u8, 120u8, 176u8, 203u8, 129u8, 99u8, 133u8, 55u8, 167u8, 230u8, 187u8, 148u8, 2u8,
        185u8, 48u8, 222u8, 250u8, 46u8, 34u8, 144u8, 131u8, 250u8, 83u8, 247u8, 89u8, 136u8,
        107u8, 37u8, 143u8, 249u8, 196u8, 150u8, 227u8, 150u8, 243u8, 242u8, 154u8, 59u8, 193u8,
        199u8, 191u8, 20u8, 125u8, 68u8, 114u8, 246u8, 74u8, 150u8, 200u8, 243u8,
    ],
    vk_beta_g2: [
        3u8, 51u8, 237u8, 139u8, 216u8, 206u8, 90u8, 126u8, 118u8, 222u8, 197u8, 67u8, 154u8, 98u8,
        71u8, 30u8, 229u8, 104u8, 43u8, 31u8, 53u8, 241u8, 194u8, 228u8, 37u8, 246u8, 0u8, 67u8,
        186u8, 133u8, 34u8, 93u8, 36u8, 236u8, 161u8, 15u8, 72u8, 69u8, 18u8, 156u8, 185u8, 243u8,
        244u8, 149u8, 215u8, 45u8, 115u8, 8u8, 95u8, 115u8, 189u8, 253u8, 116u8, 196u8, 226u8, 8u8,
        65u8, 6u8, 68u8, 39u8, 162u8, 197u8, 2u8, 29u8, 25u8, 142u8, 121u8, 52u8, 182u8, 97u8,
        164u8, 43u8, 87u8, 171u8, 125u8, 142u8, 82u8, 169u8, 202u8, 10u8, 149u8, 228u8, 18u8, 49u8,
        86u8, 80u8, 62u8, 52u8, 123u8, 44u8, 216u8, 120u8, 198u8, 57u8, 239u8, 6u8, 15u8, 119u8,
        252u8, 110u8, 162u8, 40u8, 8u8, 247u8, 24u8, 40u8, 97u8, 6u8, 249u8, 35u8, 151u8, 22u8,
        68u8, 179u8, 127u8, 33u8, 54u8, 71u8, 46u8, 233u8, 231u8, 223u8, 90u8, 2u8, 22u8, 13u8,
        240u8, 57u8,
    ],
    vk_gamma_g2: [
        45u8, 119u8, 113u8, 232u8, 231u8, 200u8, 26u8, 18u8, 148u8, 64u8, 14u8, 179u8, 234u8, 45u8,
        36u8, 10u8, 218u8, 43u8, 253u8, 46u8, 226u8, 145u8, 32u8, 33u8, 97u8, 145u8, 241u8, 68u8,
        103u8, 203u8, 133u8, 37u8, 27u8, 196u8, 46u8, 0u8, 216u8, 215u8, 153u8, 115u8, 134u8, 74u8,
        0u8, 22u8, 201u8, 35u8, 114u8, 40u8, 12u8, 215u8, 229u8, 118u8, 63u8, 223u8, 195u8, 191u8,
        111u8, 234u8, 119u8, 118u8, 38u8, 90u8, 126u8, 85u8, 21u8, 149u8, 61u8, 108u8, 231u8,
        206u8, 108u8, 12u8, 215u8, 129u8, 132u8, 135u8, 8u8, 3u8, 56u8, 168u8, 21u8, 253u8, 208u8,
        136u8, 176u8, 1u8, 246u8, 88u8, 87u8, 20u8, 105u8, 163u8, 119u8, 6u8, 135u8, 156u8, 21u8,
        90u8, 100u8, 85u8, 112u8, 29u8, 104u8, 192u8, 112u8, 249u8, 134u8, 91u8, 87u8, 20u8, 29u8,
        100u8, 60u8, 76u8, 215u8, 223u8, 225u8, 85u8, 76u8, 55u8, 6u8, 218u8, 186u8, 232u8, 52u8,
        65u8, 255u8, 76u8,
    ],
    vk_delta_g2: [
        31u8, 91u8, 245u8, 237u8, 51u8, 88u8, 219u8, 40u8, 48u8, 133u8, 63u8, 196u8, 117u8, 70u8,
        115u8, 185u8, 182u8, 75u8, 207u8, 1u8, 70u8, 19u8, 255u8, 107u8, 103u8, 13u8, 212u8, 38u8,
        229u8, 50u8, 152u8, 165u8, 8u8, 31u8, 102u8, 102u8, 78u8, 224u8, 199u8, 207u8, 29u8, 63u8,
        25u8, 78u8, 186u8, 39u8, 216u8, 170u8, 174u8, 223u8, 166u8, 226u8, 172u8, 59u8, 8u8, 16u8,
        159u8, 20u8, 43u8, 98u8, 62u8, 229u8, 57u8, 69u8, 2u8, 155u8, 93u8, 245u8, 117u8, 188u8,
        75u8, 17u8, 55u8, 72u8, 30u8, 150u8, 215u8, 27u8, 62u8, 47u8, 197u8, 115u8, 188u8, 255u8,
        76u8, 153u8, 84u8, 126u8, 88u8, 152u8, 179u8, 240u8, 172u8, 1u8, 210u8, 249u8, 8u8, 221u8,
        3u8, 180u8, 235u8, 234u8, 143u8, 231u8, 91u8, 140u8, 116u8, 132u8, 184u8, 171u8, 75u8,
        80u8, 224u8, 252u8, 230u8, 232u8, 203u8, 9u8, 201u8, 175u8, 166u8, 87u8, 153u8, 58u8,
        196u8, 13u8, 51u8, 8u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [201u8, 51u8, 56u8, 64u8, 44u8, 220u8, 143u8, 216u8, 236u8, 47u8, 112u8, 242u8, 222u8, 159u8, 162u8, 158u8, 227u8, 227u8, 91u8, 6u8, 76u8, 168u8, 3u8, 248u8, 173u8, 77u8, 24u8, 7u8, 14u8, 72u8, 97u8, 254u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_5efe14f15dcf98bd")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00c93338402cdc8fd8ec2f70f2de9fa29ee3e35b064ca803f8ad4d18070e4861fe\x00=======END GROTH16 VK SETUP V1=======\x00";
