// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        11u8, 30u8, 18u8, 92u8, 16u8, 146u8, 124u8, 172u8, 94u8, 175u8, 146u8, 50u8, 193u8, 9u8,
        39u8, 132u8, 23u8, 245u8, 68u8, 52u8, 117u8, 22u8, 29u8, 71u8, 8u8, 87u8, 122u8, 73u8,
        33u8, 208u8, 159u8, 229u8, 32u8, 117u8, 178u8, 203u8, 153u8, 207u8, 240u8, 78u8, 32u8,
        167u8, 24u8, 128u8, 94u8, 90u8, 167u8, 202u8, 228u8, 19u8, 200u8, 193u8, 177u8, 218u8,
        84u8, 141u8, 36u8, 32u8, 141u8, 220u8, 68u8, 213u8, 103u8, 231u8,
    ],
    [
        44u8, 92u8, 68u8, 18u8, 110u8, 209u8, 134u8, 181u8, 20u8, 182u8, 243u8, 144u8, 249u8,
        243u8, 128u8, 152u8, 53u8, 112u8, 169u8, 2u8, 253u8, 149u8, 146u8, 33u8, 25u8, 212u8, 77u8,
        199u8, 208u8, 221u8, 224u8, 229u8, 43u8, 161u8, 238u8, 155u8, 38u8, 63u8, 151u8, 226u8,
        208u8, 243u8, 113u8, 201u8, 174u8, 211u8, 6u8, 19u8, 117u8, 253u8, 227u8, 22u8, 227u8,
        190u8, 201u8, 161u8, 162u8, 17u8, 82u8, 11u8, 87u8, 55u8, 4u8, 62u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        24u8, 16u8, 82u8, 115u8, 243u8, 244u8, 162u8, 49u8, 43u8, 116u8, 145u8, 27u8, 134u8, 148u8,
        249u8, 73u8, 31u8, 9u8, 115u8, 150u8, 52u8, 47u8, 147u8, 60u8, 136u8, 84u8, 157u8, 62u8,
        140u8, 68u8, 35u8, 163u8, 37u8, 190u8, 159u8, 174u8, 48u8, 3u8, 216u8, 155u8, 220u8, 251u8,
        203u8, 0u8, 247u8, 171u8, 43u8, 237u8, 11u8, 63u8, 214u8, 61u8, 66u8, 54u8, 117u8, 192u8,
        82u8, 90u8, 196u8, 46u8, 59u8, 69u8, 15u8, 169u8,
    ],
    vk_beta_g2: [
        48u8, 35u8, 145u8, 83u8, 179u8, 59u8, 235u8, 26u8, 218u8, 176u8, 150u8, 220u8, 127u8,
        176u8, 156u8, 200u8, 78u8, 102u8, 174u8, 200u8, 111u8, 59u8, 208u8, 109u8, 13u8, 23u8,
        221u8, 58u8, 115u8, 155u8, 145u8, 187u8, 9u8, 230u8, 223u8, 168u8, 211u8, 173u8, 28u8,
        198u8, 154u8, 202u8, 153u8, 78u8, 182u8, 17u8, 134u8, 43u8, 187u8, 163u8, 141u8, 176u8,
        7u8, 199u8, 8u8, 185u8, 166u8, 178u8, 188u8, 186u8, 27u8, 57u8, 18u8, 236u8, 33u8, 80u8,
        248u8, 23u8, 18u8, 28u8, 153u8, 244u8, 72u8, 103u8, 221u8, 134u8, 181u8, 67u8, 247u8,
        206u8, 200u8, 185u8, 190u8, 153u8, 230u8, 116u8, 24u8, 109u8, 249u8, 14u8, 126u8, 28u8,
        75u8, 206u8, 238u8, 239u8, 5u8, 31u8, 230u8, 174u8, 101u8, 134u8, 95u8, 139u8, 100u8, 15u8,
        170u8, 180u8, 175u8, 105u8, 215u8, 80u8, 217u8, 189u8, 169u8, 194u8, 86u8, 159u8, 163u8,
        225u8, 240u8, 253u8, 1u8, 91u8, 26u8, 56u8, 83u8, 88u8,
    ],
    vk_gamma_g2: [
        42u8, 251u8, 75u8, 35u8, 219u8, 253u8, 101u8, 247u8, 99u8, 173u8, 124u8, 177u8, 143u8,
        253u8, 144u8, 62u8, 203u8, 133u8, 132u8, 42u8, 231u8, 145u8, 249u8, 124u8, 5u8, 251u8,
        239u8, 91u8, 205u8, 38u8, 88u8, 97u8, 16u8, 11u8, 199u8, 47u8, 44u8, 211u8, 209u8, 196u8,
        41u8, 11u8, 211u8, 185u8, 121u8, 82u8, 116u8, 183u8, 194u8, 82u8, 164u8, 224u8, 249u8,
        169u8, 17u8, 214u8, 18u8, 172u8, 161u8, 139u8, 62u8, 204u8, 126u8, 63u8, 8u8, 79u8, 1u8,
        37u8, 90u8, 171u8, 8u8, 115u8, 91u8, 183u8, 176u8, 83u8, 230u8, 134u8, 160u8, 33u8, 56u8,
        143u8, 203u8, 100u8, 71u8, 33u8, 31u8, 159u8, 128u8, 137u8, 147u8, 186u8, 114u8, 217u8,
        175u8, 27u8, 5u8, 112u8, 94u8, 43u8, 44u8, 44u8, 136u8, 140u8, 221u8, 89u8, 166u8, 163u8,
        40u8, 141u8, 5u8, 104u8, 233u8, 38u8, 138u8, 90u8, 81u8, 86u8, 233u8, 145u8, 250u8, 109u8,
        136u8, 61u8, 133u8, 180u8, 127u8, 12u8,
    ],
    vk_delta_g2: [
        27u8, 221u8, 86u8, 72u8, 5u8, 223u8, 74u8, 90u8, 165u8, 246u8, 51u8, 221u8, 140u8, 224u8,
        140u8, 160u8, 126u8, 169u8, 181u8, 160u8, 252u8, 60u8, 6u8, 7u8, 255u8, 129u8, 206u8,
        166u8, 20u8, 174u8, 56u8, 61u8, 45u8, 161u8, 62u8, 70u8, 143u8, 49u8, 12u8, 244u8, 239u8,
        48u8, 21u8, 90u8, 230u8, 171u8, 57u8, 35u8, 78u8, 70u8, 227u8, 175u8, 89u8, 215u8, 152u8,
        186u8, 80u8, 209u8, 81u8, 118u8, 94u8, 48u8, 242u8, 98u8, 34u8, 241u8, 32u8, 185u8, 17u8,
        179u8, 8u8, 8u8, 101u8, 37u8, 120u8, 126u8, 161u8, 193u8, 147u8, 58u8, 80u8, 24u8, 15u8,
        28u8, 36u8, 70u8, 92u8, 89u8, 176u8, 27u8, 76u8, 204u8, 203u8, 137u8, 238u8, 187u8, 38u8,
        162u8, 199u8, 54u8, 7u8, 121u8, 183u8, 42u8, 58u8, 229u8, 43u8, 230u8, 170u8, 122u8, 15u8,
        12u8, 96u8, 49u8, 231u8, 20u8, 71u8, 91u8, 167u8, 182u8, 156u8, 136u8, 148u8, 246u8, 131u8,
        207u8, 163u8, 65u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [232u8, 16u8, 213u8, 41u8, 98u8, 244u8, 85u8, 139u8, 11u8, 213u8, 11u8, 118u8, 138u8, 137u8, 73u8, 7u8, 89u8, 225u8, 90u8, 6u8, 35u8, 212u8, 194u8, 196u8, 51u8, 24u8, 245u8, 65u8, 184u8, 204u8, 97u8, 255u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_a1b71f47042dbc9c")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00e810d52962f4558b0bd50b768a89490759e15a0623d4c2c43318f541b8cc61ff\x00=======END GROTH16 VK SETUP V1=======\x00";
