// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        5u8, 16u8, 183u8, 175u8, 194u8, 135u8, 87u8, 2u8, 178u8, 61u8, 78u8, 149u8, 211u8, 154u8,
        211u8, 241u8, 93u8, 55u8, 186u8, 135u8, 135u8, 126u8, 28u8, 87u8, 230u8, 242u8, 120u8,
        59u8, 108u8, 26u8, 50u8, 41u8, 24u8, 68u8, 70u8, 142u8, 231u8, 50u8, 163u8, 185u8, 109u8,
        52u8, 115u8, 9u8, 253u8, 10u8, 177u8, 146u8, 55u8, 142u8, 165u8, 57u8, 24u8, 163u8, 255u8,
        53u8, 27u8, 127u8, 27u8, 23u8, 158u8, 42u8, 122u8, 8u8,
    ],
    [
        10u8, 175u8, 217u8, 191u8, 104u8, 153u8, 254u8, 109u8, 126u8, 59u8, 230u8, 136u8, 224u8,
        209u8, 169u8, 151u8, 45u8, 196u8, 165u8, 55u8, 163u8, 254u8, 174u8, 127u8, 73u8, 117u8,
        229u8, 153u8, 159u8, 34u8, 149u8, 146u8, 43u8, 148u8, 181u8, 195u8, 44u8, 236u8, 240u8,
        137u8, 3u8, 183u8, 32u8, 232u8, 62u8, 49u8, 76u8, 189u8, 127u8, 16u8, 20u8, 133u8, 26u8,
        84u8, 69u8, 172u8, 217u8, 23u8, 28u8, 180u8, 224u8, 95u8, 63u8, 116u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        41u8, 40u8, 139u8, 236u8, 162u8, 230u8, 74u8, 200u8, 231u8, 249u8, 57u8, 130u8, 0u8, 41u8,
        91u8, 247u8, 161u8, 1u8, 121u8, 52u8, 118u8, 229u8, 202u8, 131u8, 200u8, 112u8, 186u8,
        231u8, 240u8, 78u8, 228u8, 17u8, 32u8, 62u8, 134u8, 74u8, 214u8, 76u8, 221u8, 217u8, 124u8,
        237u8, 21u8, 22u8, 104u8, 63u8, 142u8, 240u8, 173u8, 2u8, 165u8, 186u8, 173u8, 129u8,
        136u8, 218u8, 249u8, 133u8, 67u8, 124u8, 73u8, 235u8, 53u8, 11u8,
    ],
    vk_beta_g2: [
        30u8, 231u8, 52u8, 141u8, 71u8, 159u8, 157u8, 192u8, 10u8, 106u8, 131u8, 177u8, 183u8,
        30u8, 253u8, 57u8, 104u8, 61u8, 227u8, 249u8, 97u8, 31u8, 28u8, 206u8, 86u8, 255u8, 95u8,
        44u8, 173u8, 117u8, 243u8, 63u8, 12u8, 114u8, 91u8, 14u8, 156u8, 190u8, 133u8, 221u8, 68u8,
        186u8, 161u8, 52u8, 237u8, 224u8, 187u8, 4u8, 206u8, 227u8, 89u8, 228u8, 219u8, 126u8,
        193u8, 117u8, 211u8, 67u8, 189u8, 6u8, 5u8, 146u8, 36u8, 37u8, 2u8, 240u8, 118u8, 194u8,
        27u8, 134u8, 60u8, 113u8, 225u8, 203u8, 186u8, 97u8, 47u8, 216u8, 219u8, 43u8, 50u8, 8u8,
        137u8, 60u8, 43u8, 211u8, 248u8, 25u8, 67u8, 90u8, 232u8, 105u8, 95u8, 11u8, 213u8, 148u8,
        32u8, 90u8, 54u8, 250u8, 154u8, 7u8, 147u8, 57u8, 174u8, 85u8, 54u8, 178u8, 39u8, 233u8,
        87u8, 219u8, 224u8, 11u8, 88u8, 90u8, 189u8, 107u8, 157u8, 196u8, 54u8, 202u8, 57u8, 59u8,
        183u8, 184u8, 88u8, 47u8,
    ],
    vk_gamma_g2: [
        34u8, 34u8, 4u8, 141u8, 166u8, 31u8, 22u8, 166u8, 124u8, 43u8, 163u8, 159u8, 200u8, 154u8,
        189u8, 163u8, 242u8, 159u8, 113u8, 158u8, 46u8, 206u8, 137u8, 79u8, 3u8, 121u8, 18u8,
        224u8, 50u8, 54u8, 232u8, 224u8, 47u8, 99u8, 127u8, 250u8, 8u8, 200u8, 149u8, 152u8, 57u8,
        231u8, 39u8, 103u8, 63u8, 243u8, 58u8, 17u8, 159u8, 143u8, 18u8, 103u8, 214u8, 221u8, 51u8,
        133u8, 20u8, 20u8, 162u8, 225u8, 12u8, 118u8, 0u8, 131u8, 1u8, 25u8, 82u8, 66u8, 88u8,
        18u8, 117u8, 41u8, 190u8, 85u8, 54u8, 88u8, 222u8, 207u8, 209u8, 230u8, 63u8, 240u8, 86u8,
        182u8, 155u8, 242u8, 27u8, 231u8, 248u8, 218u8, 206u8, 35u8, 108u8, 206u8, 225u8, 52u8,
        42u8, 229u8, 94u8, 173u8, 99u8, 203u8, 70u8, 50u8, 243u8, 202u8, 187u8, 107u8, 199u8,
        107u8, 131u8, 139u8, 23u8, 88u8, 117u8, 149u8, 97u8, 114u8, 109u8, 42u8, 18u8, 46u8, 133u8,
        172u8, 161u8, 174u8, 245u8, 76u8,
    ],
    vk_delta_g2: [
        48u8, 57u8, 201u8, 60u8, 66u8, 117u8, 189u8, 58u8, 97u8, 188u8, 52u8, 246u8, 25u8, 189u8,
        206u8, 85u8, 65u8, 96u8, 213u8, 53u8, 217u8, 103u8, 99u8, 116u8, 97u8, 41u8, 58u8, 39u8,
        105u8, 200u8, 237u8, 222u8, 24u8, 103u8, 206u8, 249u8, 38u8, 161u8, 232u8, 62u8, 20u8,
        38u8, 81u8, 165u8, 17u8, 218u8, 71u8, 139u8, 166u8, 114u8, 81u8, 92u8, 190u8, 189u8, 246u8,
        117u8, 20u8, 230u8, 137u8, 181u8, 59u8, 75u8, 73u8, 33u8, 35u8, 180u8, 236u8, 137u8, 127u8,
        42u8, 50u8, 87u8, 94u8, 214u8, 248u8, 53u8, 181u8, 89u8, 3u8, 226u8, 102u8, 128u8, 173u8,
        196u8, 160u8, 65u8, 68u8, 133u8, 15u8, 205u8, 233u8, 28u8, 1u8, 192u8, 83u8, 94u8, 4u8,
        160u8, 83u8, 50u8, 9u8, 70u8, 217u8, 168u8, 129u8, 164u8, 31u8, 130u8, 20u8, 170u8, 202u8,
        217u8, 109u8, 153u8, 214u8, 157u8, 144u8, 200u8, 9u8, 22u8, 234u8, 96u8, 116u8, 189u8,
        96u8, 30u8, 67u8, 16u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [174u8, 102u8, 153u8, 161u8, 157u8, 129u8, 10u8, 126u8, 14u8, 246u8, 99u8, 223u8, 243u8, 252u8, 50u8, 224u8, 184u8, 228u8, 189u8, 234u8, 233u8, 8u8, 156u8, 88u8, 55u8, 70u8, 249u8, 90u8, 227u8, 176u8, 225u8, 233u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_6fd05ccfa4cf0916")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00ae6699a19d810a7e0ef663dff3fc32e0b8e4bdeae9089c583746f95ae3b0e1e9\x00=======END GROTH16 VK SETUP V1=======\x00";
