// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        1u8, 247u8, 62u8, 7u8, 153u8, 162u8, 71u8, 197u8, 234u8, 229u8, 87u8, 241u8, 90u8, 66u8,
        231u8, 112u8, 142u8, 71u8, 28u8, 225u8, 14u8, 221u8, 107u8, 253u8, 252u8, 204u8, 75u8,
        185u8, 60u8, 1u8, 72u8, 15u8, 31u8, 12u8, 73u8, 216u8, 122u8, 125u8, 131u8, 125u8, 254u8,
        191u8, 136u8, 173u8, 49u8, 241u8, 125u8, 111u8, 116u8, 65u8, 3u8, 31u8, 45u8, 39u8, 170u8,
        115u8, 195u8, 21u8, 167u8, 96u8, 234u8, 112u8, 32u8, 248u8,
    ],
    [
        18u8, 112u8, 147u8, 188u8, 129u8, 101u8, 101u8, 216u8, 156u8, 48u8, 61u8, 252u8, 234u8,
        184u8, 82u8, 159u8, 230u8, 8u8, 218u8, 224u8, 27u8, 112u8, 56u8, 159u8, 85u8, 60u8, 131u8,
        125u8, 230u8, 141u8, 83u8, 60u8, 47u8, 134u8, 229u8, 147u8, 85u8, 47u8, 196u8, 85u8, 150u8,
        62u8, 123u8, 120u8, 97u8, 244u8, 147u8, 252u8, 87u8, 204u8, 111u8, 220u8, 35u8, 249u8,
        137u8, 53u8, 130u8, 34u8, 53u8, 193u8, 247u8, 205u8, 96u8, 143u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        34u8, 56u8, 78u8, 25u8, 140u8, 90u8, 1u8, 210u8, 167u8, 21u8, 32u8, 95u8, 11u8, 244u8,
        140u8, 92u8, 186u8, 92u8, 204u8, 87u8, 11u8, 120u8, 42u8, 34u8, 12u8, 228u8, 105u8, 170u8,
        2u8, 99u8, 99u8, 225u8, 11u8, 246u8, 81u8, 228u8, 255u8, 195u8, 43u8, 48u8, 106u8, 119u8,
        216u8, 195u8, 52u8, 136u8, 72u8, 83u8, 147u8, 191u8, 41u8, 120u8, 37u8, 167u8, 83u8, 47u8,
        79u8, 45u8, 19u8, 75u8, 250u8, 52u8, 117u8, 104u8,
    ],
    vk_beta_g2: [
        12u8, 71u8, 62u8, 39u8, 233u8, 58u8, 126u8, 197u8, 215u8, 213u8, 199u8, 69u8, 39u8, 190u8,
        7u8, 203u8, 243u8, 127u8, 179u8, 190u8, 213u8, 193u8, 249u8, 105u8, 61u8, 125u8, 88u8,
        117u8, 237u8, 72u8, 90u8, 17u8, 19u8, 148u8, 107u8, 141u8, 138u8, 173u8, 199u8, 173u8,
        251u8, 215u8, 176u8, 130u8, 45u8, 186u8, 183u8, 53u8, 12u8, 1u8, 193u8, 59u8, 57u8, 126u8,
        97u8, 193u8, 181u8, 143u8, 202u8, 48u8, 202u8, 224u8, 3u8, 126u8, 45u8, 216u8, 118u8, 99u8,
        232u8, 195u8, 46u8, 144u8, 136u8, 49u8, 130u8, 224u8, 203u8, 49u8, 32u8, 201u8, 179u8,
        69u8, 253u8, 25u8, 167u8, 150u8, 42u8, 244u8, 139u8, 108u8, 42u8, 55u8, 52u8, 20u8, 93u8,
        12u8, 1u8, 172u8, 38u8, 15u8, 172u8, 149u8, 31u8, 37u8, 179u8, 248u8, 160u8, 232u8, 106u8,
        148u8, 235u8, 24u8, 94u8, 20u8, 14u8, 199u8, 120u8, 226u8, 205u8, 103u8, 240u8, 252u8,
        206u8, 53u8, 141u8, 81u8, 43u8, 92u8,
    ],
    vk_gamma_g2: [
        47u8, 220u8, 222u8, 139u8, 150u8, 30u8, 73u8, 196u8, 149u8, 251u8, 217u8, 247u8, 142u8,
        19u8, 129u8, 144u8, 126u8, 112u8, 178u8, 99u8, 142u8, 4u8, 116u8, 29u8, 165u8, 43u8, 51u8,
        164u8, 231u8, 140u8, 29u8, 44u8, 42u8, 87u8, 176u8, 204u8, 243u8, 122u8, 182u8, 254u8,
        198u8, 209u8, 12u8, 127u8, 27u8, 157u8, 232u8, 73u8, 47u8, 199u8, 2u8, 98u8, 81u8, 204u8,
        76u8, 113u8, 178u8, 138u8, 35u8, 116u8, 213u8, 154u8, 45u8, 151u8, 3u8, 105u8, 66u8, 118u8,
        174u8, 70u8, 63u8, 155u8, 217u8, 121u8, 71u8, 79u8, 188u8, 232u8, 243u8, 216u8, 19u8,
        212u8, 242u8, 77u8, 150u8, 97u8, 33u8, 193u8, 216u8, 4u8, 248u8, 169u8, 1u8, 51u8, 46u8,
        130u8, 43u8, 103u8, 55u8, 73u8, 219u8, 87u8, 20u8, 204u8, 253u8, 234u8, 95u8, 218u8, 85u8,
        252u8, 174u8, 103u8, 116u8, 186u8, 82u8, 125u8, 205u8, 105u8, 151u8, 243u8, 59u8, 217u8,
        201u8, 192u8, 149u8, 108u8, 157u8, 189u8,
    ],
    vk_delta_g2: [
        17u8, 84u8, 176u8, 51u8, 16u8, 244u8, 149u8, 84u8, 157u8, 98u8, 95u8, 173u8, 129u8, 193u8,
        49u8, 95u8, 107u8, 236u8, 250u8, 51u8, 183u8, 229u8, 178u8, 247u8, 127u8, 15u8, 155u8,
        88u8, 76u8, 161u8, 23u8, 46u8, 47u8, 248u8, 158u8, 16u8, 65u8, 168u8, 73u8, 22u8, 192u8,
        189u8, 4u8, 237u8, 241u8, 213u8, 6u8, 247u8, 25u8, 91u8, 173u8, 196u8, 197u8, 44u8, 254u8,
        81u8, 9u8, 84u8, 50u8, 157u8, 91u8, 101u8, 204u8, 207u8, 38u8, 154u8, 88u8, 61u8, 104u8,
        133u8, 211u8, 217u8, 172u8, 12u8, 145u8, 255u8, 125u8, 97u8, 219u8, 85u8, 93u8, 95u8, 33u8,
        102u8, 97u8, 3u8, 42u8, 1u8, 191u8, 52u8, 143u8, 67u8, 20u8, 95u8, 7u8, 98u8, 8u8, 164u8,
        60u8, 109u8, 210u8, 145u8, 54u8, 176u8, 117u8, 148u8, 13u8, 37u8, 55u8, 202u8, 102u8, 89u8,
        45u8, 6u8, 131u8, 210u8, 167u8, 113u8, 11u8, 35u8, 52u8, 140u8, 13u8, 69u8, 212u8, 153u8,
        210u8, 99u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [50u8, 173u8, 199u8, 79u8, 199u8, 226u8, 89u8, 57u8, 137u8, 130u8, 101u8, 42u8, 167u8, 65u8, 35u8, 24u8, 216u8, 73u8, 227u8, 61u8, 110u8, 173u8, 36u8, 181u8, 1u8, 24u8, 159u8, 242u8, 211u8, 185u8, 239u8, 196u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_e2301878e1a2a2a2")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0032adc74fc7e259398982652aa7412318d849e33d6ead24b501189ff2d3b9efc4\x00=======END GROTH16 VK SETUP V1=======\x00";
