// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        10u8, 65u8, 184u8, 213u8, 101u8, 204u8, 35u8, 53u8, 41u8, 25u8, 169u8, 172u8, 88u8, 154u8,
        82u8, 59u8, 90u8, 19u8, 10u8, 238u8, 45u8, 202u8, 20u8, 1u8, 110u8, 102u8, 157u8, 229u8,
        105u8, 90u8, 191u8, 0u8, 11u8, 124u8, 113u8, 90u8, 150u8, 105u8, 237u8, 252u8, 47u8, 131u8,
        102u8, 33u8, 255u8, 158u8, 26u8, 53u8, 216u8, 2u8, 83u8, 46u8, 176u8, 36u8, 157u8, 117u8,
        241u8, 247u8, 229u8, 107u8, 202u8, 227u8, 192u8, 37u8,
    ],
    [
        37u8, 21u8, 154u8, 151u8, 134u8, 155u8, 118u8, 66u8, 93u8, 110u8, 107u8, 42u8, 112u8, 12u8,
        208u8, 202u8, 127u8, 10u8, 55u8, 33u8, 147u8, 116u8, 9u8, 195u8, 105u8, 225u8, 13u8, 217u8,
        255u8, 88u8, 19u8, 56u8, 13u8, 228u8, 13u8, 50u8, 110u8, 216u8, 198u8, 141u8, 153u8, 153u8,
        181u8, 27u8, 192u8, 199u8, 186u8, 34u8, 26u8, 66u8, 171u8, 117u8, 202u8, 214u8, 137u8,
        197u8, 70u8, 116u8, 177u8, 48u8, 48u8, 189u8, 224u8, 253u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        11u8, 183u8, 81u8, 31u8, 103u8, 180u8, 106u8, 40u8, 184u8, 63u8, 234u8, 222u8, 214u8,
        166u8, 123u8, 102u8, 139u8, 179u8, 102u8, 68u8, 94u8, 134u8, 103u8, 113u8, 189u8, 14u8,
        11u8, 67u8, 73u8, 103u8, 238u8, 241u8, 37u8, 67u8, 99u8, 179u8, 132u8, 73u8, 163u8, 34u8,
        216u8, 255u8, 44u8, 250u8, 93u8, 133u8, 102u8, 85u8, 197u8, 140u8, 121u8, 192u8, 100u8,
        244u8, 21u8, 240u8, 210u8, 165u8, 117u8, 115u8, 126u8, 126u8, 151u8, 69u8,
    ],
    vk_beta_g2: [
        8u8, 23u8, 104u8, 191u8, 62u8, 36u8, 241u8, 197u8, 82u8, 104u8, 19u8, 50u8, 171u8, 69u8,
        171u8, 214u8, 104u8, 160u8, 45u8, 170u8, 65u8, 34u8, 219u8, 197u8, 99u8, 180u8, 154u8,
        39u8, 184u8, 192u8, 240u8, 153u8, 16u8, 61u8, 12u8, 95u8, 238u8, 166u8, 22u8, 175u8, 6u8,
        53u8, 219u8, 119u8, 209u8, 59u8, 250u8, 175u8, 73u8, 223u8, 74u8, 167u8, 96u8, 42u8, 146u8,
        139u8, 242u8, 243u8, 117u8, 222u8, 104u8, 197u8, 104u8, 159u8, 31u8, 157u8, 121u8, 11u8,
        93u8, 85u8, 152u8, 120u8, 254u8, 84u8, 132u8, 134u8, 184u8, 235u8, 225u8, 205u8, 26u8,
        160u8, 211u8, 166u8, 151u8, 112u8, 76u8, 230u8, 230u8, 161u8, 3u8, 75u8, 195u8, 231u8,
        90u8, 89u8, 41u8, 167u8, 51u8, 250u8, 126u8, 159u8, 189u8, 52u8, 46u8, 73u8, 26u8, 62u8,
        26u8, 237u8, 79u8, 130u8, 186u8, 31u8, 170u8, 124u8, 18u8, 62u8, 103u8, 225u8, 153u8, 69u8,
        243u8, 49u8, 238u8, 19u8, 109u8, 33u8,
    ],
    vk_gamma_g2: [
        29u8, 27u8, 55u8, 35u8, 81u8, 46u8, 186u8, 117u8, 149u8, 206u8, 221u8, 33u8, 177u8, 221u8,
        4u8, 172u8, 241u8, 112u8, 88u8, 240u8, 133u8, 132u8, 52u8, 98u8, 220u8, 0u8, 172u8, 233u8,
        72u8, 42u8, 78u8, 218u8, 2u8, 112u8, 14u8, 105u8, 41u8, 68u8, 228u8, 11u8, 133u8, 213u8,
        141u8, 174u8, 129u8, 117u8, 230u8, 241u8, 240u8, 23u8, 181u8, 75u8, 197u8, 84u8, 49u8,
        48u8, 90u8, 198u8, 130u8, 12u8, 172u8, 242u8, 9u8, 97u8, 18u8, 141u8, 83u8, 55u8, 59u8,
        207u8, 14u8, 49u8, 180u8, 179u8, 121u8, 20u8, 244u8, 243u8, 27u8, 220u8, 236u8, 184u8,
        252u8, 150u8, 214u8, 161u8, 139u8, 4u8, 124u8, 227u8, 45u8, 234u8, 147u8, 148u8, 16u8,
        147u8, 20u8, 170u8, 33u8, 31u8, 185u8, 213u8, 135u8, 50u8, 149u8, 24u8, 186u8, 138u8, 41u8,
        12u8, 152u8, 136u8, 113u8, 188u8, 1u8, 34u8, 38u8, 35u8, 226u8, 26u8, 3u8, 247u8, 167u8,
        108u8, 3u8, 55u8, 218u8, 210u8,
    ],
    vk_delta_g2: [
        8u8, 232u8, 241u8, 229u8, 11u8, 118u8, 230u8, 20u8, 109u8, 71u8, 207u8, 113u8, 128u8,
        188u8, 230u8, 213u8, 149u8, 71u8, 134u8, 233u8, 38u8, 128u8, 70u8, 182u8, 78u8, 44u8, 88u8,
        51u8, 164u8, 125u8, 143u8, 90u8, 15u8, 169u8, 26u8, 224u8, 47u8, 16u8, 157u8, 117u8, 148u8,
        95u8, 207u8, 25u8, 40u8, 11u8, 154u8, 10u8, 11u8, 219u8, 220u8, 35u8, 40u8, 150u8, 45u8,
        155u8, 150u8, 74u8, 57u8, 155u8, 243u8, 252u8, 87u8, 21u8, 38u8, 95u8, 188u8, 47u8, 191u8,
        96u8, 118u8, 77u8, 154u8, 174u8, 43u8, 221u8, 196u8, 215u8, 111u8, 247u8, 157u8, 215u8,
        117u8, 16u8, 119u8, 217u8, 249u8, 157u8, 54u8, 2u8, 29u8, 96u8, 80u8, 178u8, 228u8, 24u8,
        43u8, 74u8, 91u8, 116u8, 224u8, 196u8, 96u8, 21u8, 10u8, 126u8, 49u8, 252u8, 32u8, 23u8,
        191u8, 219u8, 214u8, 30u8, 86u8, 54u8, 208u8, 1u8, 162u8, 92u8, 47u8, 124u8, 44u8, 247u8,
        203u8, 90u8, 236u8, 165u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [254u8, 119u8, 18u8, 135u8, 137u8, 230u8, 73u8, 173u8, 10u8, 196u8, 97u8, 38u8, 46u8, 66u8, 130u8, 194u8, 136u8, 125u8, 106u8, 195u8, 75u8, 68u8, 98u8, 44u8, 145u8, 61u8, 75u8, 88u8, 34u8, 107u8, 68u8, 103u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_060399ccdda8564b")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00fe77128789e649ad0ac461262e4282c2887d6ac34b44622c913d4b58226b4467\x00=======END GROTH16 VK SETUP V1=======\x00";
