// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        32u8, 250u8, 200u8, 205u8, 75u8, 99u8, 23u8, 254u8, 188u8, 44u8, 22u8, 112u8, 39u8, 248u8,
        121u8, 233u8, 5u8, 127u8, 46u8, 35u8, 132u8, 3u8, 104u8, 60u8, 172u8, 247u8, 224u8, 139u8,
        48u8, 54u8, 145u8, 4u8, 41u8, 237u8, 84u8, 199u8, 118u8, 249u8, 227u8, 172u8, 47u8, 104u8,
        230u8, 24u8, 99u8, 177u8, 215u8, 176u8, 157u8, 79u8, 139u8, 176u8, 27u8, 114u8, 70u8, 91u8,
        193u8, 190u8, 19u8, 15u8, 249u8, 133u8, 176u8, 8u8,
    ],
    [
        38u8, 149u8, 84u8, 180u8, 44u8, 173u8, 248u8, 30u8, 87u8, 172u8, 221u8, 143u8, 111u8, 73u8,
        2u8, 116u8, 8u8, 58u8, 206u8, 141u8, 145u8, 215u8, 25u8, 50u8, 216u8, 5u8, 77u8, 155u8,
        90u8, 184u8, 80u8, 19u8, 37u8, 38u8, 226u8, 2u8, 158u8, 155u8, 198u8, 196u8, 0u8, 38u8,
        226u8, 174u8, 16u8, 47u8, 130u8, 91u8, 75u8, 85u8, 108u8, 249u8, 112u8, 234u8, 53u8, 138u8,
        150u8, 255u8, 247u8, 189u8, 253u8, 192u8, 40u8, 202u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        14u8, 171u8, 220u8, 62u8, 116u8, 22u8, 57u8, 114u8, 194u8, 142u8, 25u8, 200u8, 44u8, 186u8,
        32u8, 160u8, 91u8, 172u8, 220u8, 71u8, 4u8, 113u8, 201u8, 14u8, 104u8, 68u8, 81u8, 32u8,
        24u8, 50u8, 187u8, 157u8, 32u8, 99u8, 100u8, 117u8, 101u8, 44u8, 221u8, 141u8, 239u8,
        142u8, 186u8, 67u8, 24u8, 4u8, 124u8, 62u8, 96u8, 11u8, 144u8, 234u8, 195u8, 198u8, 228u8,
        74u8, 44u8, 32u8, 157u8, 198u8, 229u8, 102u8, 68u8, 108u8,
    ],
    vk_beta_g2: [
        19u8, 124u8, 247u8, 180u8, 254u8, 107u8, 23u8, 217u8, 92u8, 96u8, 230u8, 148u8, 240u8,
        142u8, 12u8, 199u8, 234u8, 61u8, 10u8, 31u8, 168u8, 186u8, 214u8, 235u8, 34u8, 198u8,
        194u8, 23u8, 153u8, 98u8, 152u8, 191u8, 12u8, 38u8, 50u8, 235u8, 51u8, 102u8, 131u8, 9u8,
        124u8, 134u8, 166u8, 205u8, 237u8, 111u8, 89u8, 84u8, 154u8, 229u8, 144u8, 0u8, 175u8,
        219u8, 23u8, 133u8, 237u8, 98u8, 119u8, 115u8, 212u8, 91u8, 160u8, 16u8, 24u8, 123u8,
        190u8, 13u8, 167u8, 148u8, 49u8, 163u8, 33u8, 158u8, 175u8, 77u8, 79u8, 213u8, 100u8,
        253u8, 75u8, 28u8, 254u8, 133u8, 167u8, 158u8, 205u8, 210u8, 138u8, 72u8, 128u8, 7u8, 43u8,
        227u8, 243u8, 247u8, 26u8, 64u8, 89u8, 215u8, 205u8, 231u8, 153u8, 89u8, 188u8, 116u8,
        207u8, 170u8, 217u8, 244u8, 203u8, 218u8, 211u8, 45u8, 215u8, 110u8, 180u8, 229u8, 104u8,
        197u8, 217u8, 70u8, 150u8, 250u8, 153u8, 198u8, 189u8, 42u8,
    ],
    vk_gamma_g2: [
        20u8, 188u8, 136u8, 43u8, 228u8, 144u8, 140u8, 84u8, 101u8, 4u8, 0u8, 206u8, 185u8, 194u8,
        48u8, 107u8, 247u8, 8u8, 38u8, 92u8, 170u8, 90u8, 81u8, 98u8, 199u8, 254u8, 205u8, 16u8,
        18u8, 220u8, 67u8, 167u8, 4u8, 28u8, 55u8, 129u8, 53u8, 194u8, 239u8, 181u8, 45u8, 184u8,
        72u8, 189u8, 60u8, 124u8, 216u8, 32u8, 172u8, 68u8, 68u8, 65u8, 47u8, 101u8, 105u8, 118u8,
        46u8, 10u8, 60u8, 54u8, 11u8, 28u8, 221u8, 135u8, 32u8, 108u8, 97u8, 242u8, 254u8, 141u8,
        208u8, 164u8, 155u8, 170u8, 128u8, 75u8, 81u8, 214u8, 233u8, 209u8, 158u8, 4u8, 40u8, 85u8,
        240u8, 43u8, 167u8, 210u8, 228u8, 169u8, 49u8, 130u8, 169u8, 229u8, 11u8, 233u8, 2u8,
        133u8, 36u8, 151u8, 21u8, 32u8, 20u8, 101u8, 34u8, 122u8, 134u8, 37u8, 23u8, 118u8, 61u8,
        205u8, 172u8, 9u8, 67u8, 249u8, 125u8, 29u8, 116u8, 96u8, 151u8, 253u8, 222u8, 141u8, 28u8,
        123u8, 135u8, 174u8,
    ],
    vk_delta_g2: [
        11u8, 252u8, 83u8, 159u8, 238u8, 156u8, 56u8, 225u8, 18u8, 177u8, 42u8, 72u8, 131u8, 23u8,
        154u8, 119u8, 131u8, 3u8, 62u8, 167u8, 11u8, 41u8, 100u8, 254u8, 49u8, 175u8, 3u8, 117u8,
        255u8, 248u8, 132u8, 43u8, 29u8, 81u8, 119u8, 21u8, 223u8, 41u8, 193u8, 147u8, 87u8, 203u8,
        209u8, 95u8, 118u8, 96u8, 126u8, 120u8, 6u8, 169u8, 114u8, 23u8, 142u8, 176u8, 204u8, 66u8,
        241u8, 140u8, 252u8, 181u8, 81u8, 220u8, 58u8, 29u8, 4u8, 213u8, 94u8, 193u8, 21u8, 16u8,
        169u8, 129u8, 183u8, 39u8, 235u8, 212u8, 25u8, 195u8, 99u8, 51u8, 63u8, 142u8, 55u8, 54u8,
        9u8, 202u8, 22u8, 31u8, 143u8, 61u8, 178u8, 104u8, 226u8, 94u8, 63u8, 98u8, 18u8, 251u8,
        33u8, 234u8, 248u8, 138u8, 63u8, 16u8, 69u8, 10u8, 23u8, 13u8, 166u8, 73u8, 106u8, 213u8,
        42u8, 11u8, 184u8, 69u8, 4u8, 125u8, 43u8, 21u8, 14u8, 188u8, 78u8, 171u8, 19u8, 149u8,
        58u8, 30u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [148u8, 189u8, 220u8, 237u8, 158u8, 70u8, 160u8, 224u8, 196u8, 251u8, 246u8, 188u8, 89u8, 198u8, 208u8, 131u8, 225u8, 213u8, 119u8, 166u8, 11u8, 244u8, 216u8, 82u8, 1u8, 41u8, 244u8, 21u8, 5u8, 244u8, 241u8, 221u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_17feff4e0709fec6")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0094bddced9e46a0e0c4fbf6bc59c6d083e1d577a60bf4d8520129f41505f4f1dd\x00=======END GROTH16 VK SETUP V1=======\x00";
