// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        21u8, 55u8, 125u8, 159u8, 92u8, 205u8, 109u8, 37u8, 185u8, 1u8, 19u8, 16u8, 60u8, 114u8,
        23u8, 171u8, 136u8, 253u8, 92u8, 43u8, 167u8, 156u8, 23u8, 194u8, 18u8, 36u8, 2u8, 54u8,
        89u8, 57u8, 251u8, 152u8, 44u8, 91u8, 155u8, 1u8, 48u8, 144u8, 207u8, 11u8, 96u8, 55u8,
        241u8, 229u8, 134u8, 187u8, 220u8, 173u8, 82u8, 205u8, 87u8, 43u8, 222u8, 114u8, 81u8,
        146u8, 6u8, 102u8, 224u8, 113u8, 165u8, 117u8, 242u8, 247u8,
    ],
    [
        46u8, 195u8, 136u8, 105u8, 23u8, 93u8, 227u8, 148u8, 168u8, 10u8, 224u8, 231u8, 74u8,
        217u8, 241u8, 186u8, 72u8, 152u8, 170u8, 207u8, 147u8, 171u8, 10u8, 58u8, 42u8, 138u8,
        241u8, 220u8, 119u8, 212u8, 151u8, 211u8, 37u8, 169u8, 157u8, 209u8, 215u8, 134u8, 106u8,
        203u8, 18u8, 47u8, 110u8, 77u8, 6u8, 98u8, 177u8, 189u8, 165u8, 20u8, 137u8, 113u8, 228u8,
        147u8, 97u8, 250u8, 170u8, 148u8, 179u8, 218u8, 93u8, 53u8, 181u8, 243u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        46u8, 159u8, 107u8, 3u8, 237u8, 22u8, 228u8, 180u8, 115u8, 252u8, 38u8, 30u8, 51u8, 134u8,
        81u8, 192u8, 241u8, 254u8, 144u8, 12u8, 123u8, 8u8, 148u8, 37u8, 164u8, 107u8, 113u8,
        100u8, 229u8, 209u8, 126u8, 222u8, 37u8, 18u8, 101u8, 27u8, 36u8, 39u8, 196u8, 126u8,
        179u8, 126u8, 105u8, 216u8, 78u8, 135u8, 2u8, 68u8, 251u8, 76u8, 147u8, 227u8, 37u8, 62u8,
        199u8, 243u8, 78u8, 203u8, 18u8, 72u8, 233u8, 203u8, 89u8, 106u8,
    ],
    vk_beta_g2: [
        1u8, 1u8, 58u8, 207u8, 59u8, 232u8, 113u8, 25u8, 23u8, 121u8, 27u8, 154u8, 194u8, 101u8,
        255u8, 16u8, 58u8, 44u8, 117u8, 218u8, 156u8, 0u8, 114u8, 40u8, 29u8, 10u8, 159u8, 208u8,
        74u8, 90u8, 238u8, 91u8, 45u8, 199u8, 46u8, 19u8, 179u8, 193u8, 103u8, 87u8, 191u8, 86u8,
        83u8, 92u8, 16u8, 243u8, 97u8, 220u8, 82u8, 107u8, 180u8, 81u8, 58u8, 126u8, 151u8, 109u8,
        248u8, 125u8, 129u8, 102u8, 254u8, 126u8, 192u8, 81u8, 18u8, 91u8, 68u8, 158u8, 68u8,
        100u8, 52u8, 181u8, 8u8, 71u8, 106u8, 46u8, 210u8, 197u8, 131u8, 35u8, 26u8, 239u8, 190u8,
        11u8, 176u8, 40u8, 111u8, 113u8, 141u8, 2u8, 207u8, 72u8, 185u8, 109u8, 192u8, 107u8, 24u8,
        36u8, 135u8, 214u8, 215u8, 239u8, 97u8, 129u8, 189u8, 8u8, 68u8, 101u8, 10u8, 5u8, 180u8,
        253u8, 199u8, 131u8, 119u8, 76u8, 108u8, 23u8, 30u8, 113u8, 39u8, 205u8, 76u8, 49u8, 88u8,
        156u8, 235u8, 39u8,
    ],
    vk_gamma_g2: [
        32u8, 19u8, 115u8, 196u8, 79u8, 65u8, 227u8, 224u8, 218u8, 196u8, 33u8, 225u8, 166u8,
        133u8, 167u8, 162u8, 74u8, 168u8, 188u8, 204u8, 137u8, 91u8, 146u8, 127u8, 244u8, 111u8,
        198u8, 132u8, 248u8, 165u8, 106u8, 120u8, 9u8, 191u8, 203u8, 103u8, 236u8, 157u8, 173u8,
        16u8, 47u8, 69u8, 117u8, 107u8, 115u8, 10u8, 222u8, 179u8, 196u8, 151u8, 178u8, 252u8,
        98u8, 112u8, 241u8, 26u8, 90u8, 164u8, 211u8, 173u8, 32u8, 193u8, 33u8, 18u8, 37u8, 122u8,
        26u8, 97u8, 228u8, 211u8, 121u8, 60u8, 3u8, 32u8, 170u8, 6u8, 190u8, 1u8, 7u8, 80u8, 99u8,
        209u8, 181u8, 149u8, 94u8, 2u8, 212u8, 65u8, 28u8, 204u8, 133u8, 120u8, 56u8, 74u8, 209u8,
        17u8, 29u8, 52u8, 101u8, 70u8, 164u8, 236u8, 124u8, 136u8, 220u8, 91u8, 168u8, 214u8, 19u8,
        35u8, 165u8, 75u8, 239u8, 82u8, 190u8, 70u8, 238u8, 131u8, 30u8, 11u8, 96u8, 100u8, 10u8,
        207u8, 228u8, 127u8, 56u8, 29u8,
    ],
    vk_delta_g2: [
        3u8, 171u8, 243u8, 254u8, 226u8, 237u8, 60u8, 241u8, 244u8, 93u8, 77u8, 231u8, 133u8,
        171u8, 2u8, 54u8, 251u8, 117u8, 253u8, 113u8, 128u8, 128u8, 87u8, 237u8, 51u8, 171u8,
        232u8, 224u8, 149u8, 203u8, 44u8, 254u8, 34u8, 13u8, 100u8, 222u8, 31u8, 185u8, 179u8,
        104u8, 234u8, 76u8, 106u8, 40u8, 99u8, 37u8, 49u8, 175u8, 220u8, 174u8, 72u8, 176u8, 132u8,
        62u8, 188u8, 244u8, 207u8, 59u8, 206u8, 248u8, 174u8, 198u8, 68u8, 9u8, 35u8, 72u8, 214u8,
        72u8, 89u8, 232u8, 208u8, 157u8, 57u8, 216u8, 24u8, 94u8, 175u8, 170u8, 250u8, 13u8, 11u8,
        121u8, 93u8, 169u8, 244u8, 123u8, 28u8, 65u8, 27u8, 6u8, 224u8, 49u8, 188u8, 239u8, 233u8,
        135u8, 40u8, 129u8, 90u8, 141u8, 220u8, 169u8, 193u8, 126u8, 201u8, 133u8, 193u8, 130u8,
        87u8, 184u8, 118u8, 77u8, 182u8, 242u8, 21u8, 125u8, 116u8, 46u8, 170u8, 10u8, 27u8, 82u8,
        158u8, 70u8, 207u8, 166u8, 33u8, 14u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [91u8, 85u8, 31u8, 215u8, 244u8, 62u8, 197u8, 19u8, 208u8, 155u8, 251u8, 160u8, 158u8, 0u8, 228u8, 120u8, 66u8, 172u8, 112u8, 235u8, 211u8, 171u8, 255u8, 46u8, 143u8, 196u8, 122u8, 159u8, 127u8, 128u8, 215u8, 119u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_0fb754d622e616b1")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x005b551fd7f43ec513d09bfba09e00e47842ac70ebd3abff2e8fc47a9f7f80d777\x00=======END GROTH16 VK SETUP V1=======\x00";
