// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        45u8, 141u8, 49u8, 191u8, 253u8, 149u8, 5u8, 227u8, 92u8, 148u8, 211u8, 88u8, 17u8, 107u8,
        117u8, 255u8, 252u8, 218u8, 174u8, 191u8, 201u8, 98u8, 89u8, 215u8, 54u8, 30u8, 118u8,
        230u8, 214u8, 178u8, 17u8, 83u8, 34u8, 77u8, 25u8, 68u8, 128u8, 169u8, 30u8, 88u8, 140u8,
        34u8, 201u8, 133u8, 186u8, 131u8, 123u8, 147u8, 226u8, 180u8, 168u8, 218u8, 105u8, 41u8,
        39u8, 178u8, 57u8, 47u8, 176u8, 240u8, 96u8, 127u8, 64u8, 154u8,
    ],
    [
        19u8, 237u8, 83u8, 84u8, 97u8, 180u8, 95u8, 85u8, 2u8, 225u8, 149u8, 250u8, 173u8, 132u8,
        50u8, 131u8, 158u8, 16u8, 207u8, 52u8, 234u8, 231u8, 136u8, 10u8, 51u8, 208u8, 203u8,
        226u8, 24u8, 42u8, 38u8, 221u8, 9u8, 236u8, 226u8, 71u8, 200u8, 208u8, 120u8, 58u8, 168u8,
        143u8, 63u8, 210u8, 122u8, 114u8, 136u8, 65u8, 146u8, 112u8, 180u8, 175u8, 215u8, 228u8,
        140u8, 232u8, 181u8, 111u8, 47u8, 25u8, 57u8, 161u8, 131u8, 102u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        23u8, 225u8, 32u8, 44u8, 214u8, 193u8, 33u8, 244u8, 194u8, 135u8, 215u8, 88u8, 252u8,
        121u8, 140u8, 182u8, 172u8, 126u8, 31u8, 222u8, 215u8, 80u8, 220u8, 46u8, 152u8, 184u8,
        64u8, 62u8, 27u8, 52u8, 117u8, 146u8, 27u8, 157u8, 103u8, 227u8, 197u8, 153u8, 136u8,
        241u8, 59u8, 248u8, 88u8, 235u8, 41u8, 104u8, 116u8, 100u8, 203u8, 195u8, 255u8, 223u8,
        77u8, 90u8, 123u8, 180u8, 187u8, 241u8, 220u8, 46u8, 169u8, 29u8, 205u8, 75u8,
    ],
    vk_beta_g2: [
        33u8, 70u8, 184u8, 240u8, 118u8, 61u8, 110u8, 141u8, 21u8, 197u8, 249u8, 121u8, 240u8,
        89u8, 43u8, 123u8, 224u8, 246u8, 95u8, 59u8, 155u8, 147u8, 204u8, 121u8, 191u8, 10u8, 42u8,
        254u8, 85u8, 132u8, 54u8, 219u8, 40u8, 245u8, 115u8, 172u8, 89u8, 219u8, 44u8, 64u8, 13u8,
        37u8, 223u8, 207u8, 45u8, 19u8, 131u8, 62u8, 206u8, 234u8, 254u8, 38u8, 238u8, 97u8, 98u8,
        162u8, 171u8, 244u8, 250u8, 193u8, 230u8, 73u8, 128u8, 216u8, 17u8, 183u8, 153u8, 238u8,
        77u8, 199u8, 187u8, 248u8, 106u8, 148u8, 127u8, 103u8, 247u8, 196u8, 30u8, 138u8, 241u8,
        64u8, 207u8, 88u8, 14u8, 4u8, 8u8, 89u8, 100u8, 169u8, 122u8, 110u8, 226u8, 230u8, 165u8,
        250u8, 0u8, 186u8, 86u8, 132u8, 21u8, 146u8, 72u8, 77u8, 252u8, 35u8, 23u8, 169u8, 167u8,
        7u8, 52u8, 132u8, 231u8, 60u8, 165u8, 245u8, 75u8, 67u8, 121u8, 151u8, 171u8, 182u8, 69u8,
        160u8, 106u8, 196u8, 207u8, 5u8,
    ],
    vk_gamma_g2: [
        43u8, 241u8, 160u8, 45u8, 77u8, 83u8, 137u8, 64u8, 167u8, 42u8, 162u8, 32u8, 145u8, 72u8,
        110u8, 163u8, 134u8, 221u8, 36u8, 158u8, 87u8, 201u8, 247u8, 116u8, 130u8, 51u8, 41u8,
        150u8, 45u8, 227u8, 132u8, 77u8, 22u8, 209u8, 196u8, 81u8, 141u8, 233u8, 88u8, 47u8, 155u8,
        41u8, 183u8, 44u8, 162u8, 2u8, 189u8, 197u8, 188u8, 60u8, 247u8, 122u8, 14u8, 131u8, 77u8,
        208u8, 76u8, 105u8, 103u8, 132u8, 179u8, 142u8, 96u8, 46u8, 25u8, 165u8, 52u8, 124u8,
        170u8, 27u8, 29u8, 68u8, 169u8, 12u8, 53u8, 116u8, 250u8, 163u8, 55u8, 157u8, 102u8, 206u8,
        151u8, 225u8, 14u8, 213u8, 99u8, 211u8, 151u8, 18u8, 78u8, 55u8, 130u8, 4u8, 57u8, 56u8,
        3u8, 216u8, 181u8, 130u8, 14u8, 115u8, 69u8, 78u8, 37u8, 200u8, 130u8, 104u8, 70u8, 53u8,
        40u8, 223u8, 142u8, 147u8, 10u8, 175u8, 118u8, 83u8, 217u8, 114u8, 80u8, 120u8, 83u8, 81u8,
        139u8, 12u8, 134u8, 5u8,
    ],
    vk_delta_g2: [
        47u8, 226u8, 97u8, 108u8, 183u8, 47u8, 156u8, 109u8, 53u8, 225u8, 31u8, 22u8, 229u8, 6u8,
        232u8, 71u8, 60u8, 44u8, 53u8, 237u8, 100u8, 138u8, 111u8, 117u8, 43u8, 248u8, 1u8, 251u8,
        48u8, 20u8, 141u8, 85u8, 6u8, 11u8, 3u8, 75u8, 229u8, 243u8, 149u8, 2u8, 94u8, 68u8, 114u8,
        45u8, 217u8, 218u8, 122u8, 142u8, 11u8, 223u8, 15u8, 149u8, 77u8, 52u8, 93u8, 65u8, 195u8,
        56u8, 99u8, 143u8, 190u8, 203u8, 253u8, 90u8, 3u8, 10u8, 21u8, 217u8, 197u8, 87u8, 22u8,
        108u8, 66u8, 219u8, 191u8, 83u8, 250u8, 9u8, 104u8, 110u8, 237u8, 68u8, 239u8, 130u8, 96u8,
        219u8, 215u8, 180u8, 74u8, 179u8, 93u8, 0u8, 201u8, 145u8, 9u8, 97u8, 21u8, 188u8, 109u8,
        135u8, 101u8, 235u8, 114u8, 39u8, 175u8, 0u8, 159u8, 61u8, 31u8, 197u8, 96u8, 74u8, 18u8,
        116u8, 112u8, 160u8, 209u8, 142u8, 249u8, 172u8, 110u8, 56u8, 65u8, 195u8, 6u8, 8u8, 221u8,
        101u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [50u8, 133u8, 238u8, 35u8, 134u8, 143u8, 193u8, 236u8, 74u8, 234u8, 58u8, 88u8, 84u8, 14u8, 87u8, 13u8, 35u8, 128u8, 70u8, 69u8, 183u8, 83u8, 236u8, 191u8, 198u8, 199u8, 80u8, 104u8, 146u8, 213u8, 155u8, 62u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_4a5fb638ba2ad8ca")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x003285ee23868fc1ec4aea3a58540e570d23804645b753ecbfc6c7506892d59b3e\x00=======END GROTH16 VK SETUP V1=======\x00";
