// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        2u8, 180u8, 237u8, 183u8, 49u8, 97u8, 13u8, 109u8, 149u8, 205u8, 155u8, 4u8, 127u8, 84u8,
        30u8, 181u8, 159u8, 63u8, 184u8, 41u8, 244u8, 234u8, 101u8, 78u8, 30u8, 99u8, 219u8, 75u8,
        69u8, 156u8, 60u8, 26u8, 34u8, 191u8, 69u8, 95u8, 251u8, 193u8, 121u8, 162u8, 101u8, 110u8,
        58u8, 231u8, 226u8, 210u8, 224u8, 91u8, 32u8, 93u8, 27u8, 168u8, 2u8, 135u8, 187u8, 34u8,
        113u8, 209u8, 236u8, 139u8, 75u8, 64u8, 27u8, 127u8,
    ],
    [
        3u8, 140u8, 31u8, 121u8, 229u8, 182u8, 219u8, 164u8, 79u8, 131u8, 122u8, 114u8, 88u8,
        170u8, 112u8, 118u8, 254u8, 251u8, 254u8, 234u8, 50u8, 165u8, 221u8, 224u8, 29u8, 232u8,
        15u8, 55u8, 14u8, 242u8, 89u8, 115u8, 46u8, 174u8, 2u8, 12u8, 198u8, 66u8, 14u8, 52u8,
        141u8, 40u8, 149u8, 135u8, 201u8, 86u8, 24u8, 58u8, 148u8, 98u8, 146u8, 79u8, 252u8, 220u8,
        141u8, 103u8, 82u8, 211u8, 238u8, 129u8, 192u8, 92u8, 78u8, 217u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        37u8, 171u8, 166u8, 65u8, 133u8, 109u8, 214u8, 184u8, 30u8, 244u8, 106u8, 170u8, 245u8,
        163u8, 103u8, 123u8, 72u8, 151u8, 241u8, 112u8, 108u8, 41u8, 82u8, 245u8, 173u8, 40u8,
        183u8, 139u8, 215u8, 231u8, 175u8, 104u8, 0u8, 170u8, 61u8, 238u8, 49u8, 242u8, 209u8,
        34u8, 41u8, 60u8, 27u8, 195u8, 36u8, 20u8, 166u8, 110u8, 97u8, 42u8, 26u8, 62u8, 144u8,
        72u8, 54u8, 53u8, 241u8, 128u8, 147u8, 249u8, 13u8, 7u8, 237u8, 90u8,
    ],
    vk_beta_g2: [
        40u8, 78u8, 204u8, 6u8, 198u8, 239u8, 53u8, 32u8, 129u8, 104u8, 152u8, 210u8, 52u8, 224u8,
        213u8, 36u8, 63u8, 160u8, 137u8, 61u8, 56u8, 49u8, 142u8, 192u8, 251u8, 188u8, 112u8, 66u8,
        93u8, 187u8, 30u8, 43u8, 7u8, 19u8, 243u8, 81u8, 21u8, 4u8, 92u8, 166u8, 86u8, 35u8, 231u8,
        111u8, 191u8, 100u8, 164u8, 251u8, 140u8, 110u8, 86u8, 190u8, 226u8, 8u8, 195u8, 178u8,
        10u8, 14u8, 204u8, 63u8, 90u8, 250u8, 222u8, 181u8, 42u8, 55u8, 196u8, 186u8, 239u8, 114u8,
        100u8, 230u8, 174u8, 108u8, 9u8, 36u8, 229u8, 85u8, 113u8, 88u8, 27u8, 114u8, 23u8, 193u8,
        66u8, 125u8, 47u8, 210u8, 141u8, 196u8, 144u8, 86u8, 196u8, 230u8, 78u8, 179u8, 0u8, 156u8,
        215u8, 167u8, 140u8, 89u8, 208u8, 76u8, 6u8, 162u8, 101u8, 21u8, 114u8, 26u8, 250u8, 65u8,
        23u8, 41u8, 124u8, 128u8, 67u8, 249u8, 48u8, 189u8, 244u8, 237u8, 72u8, 71u8, 188u8, 85u8,
        60u8, 66u8,
    ],
    vk_gamma_g2: [
        6u8, 107u8, 153u8, 75u8, 75u8, 49u8, 50u8, 112u8, 148u8, 215u8, 204u8, 5u8, 75u8, 102u8,
        38u8, 43u8, 66u8, 210u8, 203u8, 183u8, 228u8, 47u8, 149u8, 190u8, 209u8, 146u8, 123u8,
        61u8, 201u8, 12u8, 84u8, 13u8, 22u8, 46u8, 111u8, 3u8, 253u8, 47u8, 166u8, 25u8, 121u8,
        89u8, 221u8, 120u8, 62u8, 229u8, 21u8, 152u8, 67u8, 39u8, 73u8, 134u8, 83u8, 71u8, 192u8,
        193u8, 220u8, 133u8, 160u8, 96u8, 252u8, 124u8, 52u8, 109u8, 19u8, 27u8, 185u8, 176u8,
        10u8, 128u8, 200u8, 245u8, 15u8, 92u8, 214u8, 61u8, 133u8, 182u8, 235u8, 35u8, 161u8,
        254u8, 229u8, 19u8, 183u8, 107u8, 157u8, 204u8, 5u8, 159u8, 129u8, 156u8, 211u8, 242u8,
        136u8, 104u8, 20u8, 21u8, 202u8, 173u8, 41u8, 28u8, 191u8, 206u8, 6u8, 88u8, 12u8, 78u8,
        121u8, 164u8, 34u8, 144u8, 67u8, 45u8, 7u8, 49u8, 93u8, 136u8, 191u8, 119u8, 217u8, 158u8,
        175u8, 18u8, 7u8, 3u8, 85u8, 186u8,
    ],
    vk_delta_g2: [
        4u8, 1u8, 215u8, 189u8, 159u8, 181u8, 207u8, 139u8, 174u8, 112u8, 55u8, 205u8, 198u8,
        155u8, 155u8, 93u8, 31u8, 84u8, 255u8, 42u8, 95u8, 242u8, 43u8, 207u8, 149u8, 242u8, 63u8,
        243u8, 201u8, 147u8, 101u8, 85u8, 6u8, 25u8, 111u8, 187u8, 242u8, 125u8, 41u8, 37u8, 69u8,
        135u8, 181u8, 196u8, 19u8, 5u8, 85u8, 194u8, 248u8, 145u8, 124u8, 29u8, 195u8, 39u8, 73u8,
        127u8, 168u8, 163u8, 172u8, 134u8, 55u8, 62u8, 250u8, 242u8, 47u8, 99u8, 188u8, 157u8,
        235u8, 248u8, 25u8, 233u8, 35u8, 172u8, 5u8, 69u8, 132u8, 35u8, 119u8, 24u8, 139u8, 94u8,
        138u8, 214u8, 195u8, 141u8, 12u8, 118u8, 213u8, 155u8, 194u8, 197u8, 176u8, 107u8, 203u8,
        92u8, 35u8, 223u8, 180u8, 244u8, 177u8, 158u8, 223u8, 147u8, 178u8, 98u8, 92u8, 179u8,
        167u8, 249u8, 252u8, 149u8, 48u8, 212u8, 67u8, 239u8, 176u8, 9u8, 116u8, 95u8, 56u8, 177u8,
        38u8, 96u8, 192u8, 127u8, 132u8, 254u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [58u8, 19u8, 109u8, 218u8, 24u8, 181u8, 14u8, 34u8, 151u8, 199u8, 58u8, 105u8, 251u8, 88u8, 138u8, 101u8, 195u8, 221u8, 69u8, 122u8, 193u8, 18u8, 177u8, 253u8, 61u8, 4u8, 106u8, 138u8, 241u8, 94u8, 216u8, 244u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_29097a930761cc91")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x003a136dda18b50e2297c73a69fb588a65c3dd457ac112b1fd3d046a8af15ed8f4\x00=======END GROTH16 VK SETUP V1=======\x00";
