// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        9u8, 98u8, 106u8, 184u8, 100u8, 218u8, 128u8, 148u8, 251u8, 94u8, 185u8, 45u8, 16u8, 65u8,
        212u8, 96u8, 176u8, 14u8, 144u8, 72u8, 197u8, 144u8, 240u8, 226u8, 110u8, 71u8, 20u8, 38u8,
        242u8, 109u8, 200u8, 128u8, 9u8, 28u8, 139u8, 59u8, 235u8, 156u8, 222u8, 248u8, 27u8, 46u8,
        65u8, 67u8, 6u8, 224u8, 152u8, 165u8, 126u8, 121u8, 105u8, 76u8, 93u8, 147u8, 242u8, 180u8,
        159u8, 172u8, 250u8, 169u8, 82u8, 90u8, 108u8, 88u8,
    ],
    [
        19u8, 180u8, 135u8, 174u8, 64u8, 110u8, 104u8, 54u8, 123u8, 2u8, 239u8, 184u8, 31u8, 57u8,
        169u8, 247u8, 25u8, 17u8, 52u8, 232u8, 24u8, 41u8, 67u8, 86u8, 112u8, 191u8, 167u8, 178u8,
        28u8, 138u8, 12u8, 173u8, 9u8, 28u8, 220u8, 21u8, 159u8, 80u8, 240u8, 184u8, 170u8, 49u8,
        7u8, 30u8, 170u8, 249u8, 177u8, 206u8, 200u8, 147u8, 136u8, 225u8, 128u8, 224u8, 63u8,
        236u8, 175u8, 189u8, 174u8, 110u8, 46u8, 56u8, 215u8, 79u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        30u8, 203u8, 39u8, 228u8, 76u8, 255u8, 45u8, 124u8, 103u8, 22u8, 166u8, 83u8, 248u8, 154u8,
        116u8, 152u8, 85u8, 81u8, 80u8, 104u8, 215u8, 39u8, 250u8, 101u8, 60u8, 64u8, 106u8, 100u8,
        231u8, 229u8, 30u8, 42u8, 16u8, 18u8, 80u8, 86u8, 90u8, 205u8, 197u8, 164u8, 253u8, 39u8,
        48u8, 53u8, 62u8, 249u8, 35u8, 1u8, 150u8, 147u8, 133u8, 189u8, 183u8, 63u8, 99u8, 199u8,
        242u8, 13u8, 28u8, 23u8, 166u8, 161u8, 174u8, 61u8,
    ],
    vk_beta_g2: [
        17u8, 65u8, 23u8, 255u8, 207u8, 219u8, 115u8, 250u8, 73u8, 75u8, 189u8, 172u8, 251u8,
        126u8, 89u8, 50u8, 102u8, 76u8, 173u8, 156u8, 73u8, 62u8, 165u8, 178u8, 175u8, 205u8, 50u8,
        238u8, 27u8, 150u8, 112u8, 215u8, 37u8, 94u8, 3u8, 84u8, 167u8, 15u8, 150u8, 191u8, 125u8,
        199u8, 243u8, 25u8, 132u8, 135u8, 62u8, 106u8, 167u8, 6u8, 142u8, 36u8, 142u8, 163u8, 6u8,
        175u8, 226u8, 164u8, 134u8, 186u8, 195u8, 191u8, 60u8, 105u8, 7u8, 179u8, 67u8, 183u8,
        38u8, 32u8, 85u8, 72u8, 225u8, 130u8, 107u8, 232u8, 15u8, 118u8, 39u8, 141u8, 121u8, 202u8,
        142u8, 95u8, 210u8, 243u8, 113u8, 157u8, 61u8, 21u8, 133u8, 81u8, 37u8, 125u8, 3u8, 92u8,
        42u8, 178u8, 173u8, 147u8, 220u8, 10u8, 188u8, 12u8, 85u8, 155u8, 68u8, 184u8, 1u8, 236u8,
        159u8, 135u8, 134u8, 211u8, 22u8, 173u8, 234u8, 213u8, 20u8, 128u8, 162u8, 117u8, 23u8,
        249u8, 107u8, 115u8, 33u8, 232u8,
    ],
    vk_gamma_g2: [
        30u8, 189u8, 171u8, 237u8, 154u8, 250u8, 131u8, 237u8, 231u8, 75u8, 37u8, 9u8, 104u8,
        142u8, 216u8, 11u8, 46u8, 48u8, 62u8, 183u8, 183u8, 42u8, 141u8, 10u8, 244u8, 214u8, 94u8,
        12u8, 161u8, 84u8, 252u8, 117u8, 46u8, 171u8, 182u8, 33u8, 40u8, 35u8, 235u8, 247u8, 239u8,
        251u8, 122u8, 254u8, 63u8, 154u8, 143u8, 193u8, 252u8, 191u8, 188u8, 251u8, 47u8, 11u8,
        53u8, 80u8, 196u8, 130u8, 89u8, 193u8, 244u8, 193u8, 61u8, 77u8, 20u8, 234u8, 127u8, 183u8,
        62u8, 17u8, 120u8, 80u8, 190u8, 37u8, 173u8, 182u8, 20u8, 214u8, 137u8, 170u8, 136u8, 92u8,
        252u8, 201u8, 65u8, 76u8, 73u8, 30u8, 104u8, 215u8, 24u8, 20u8, 95u8, 149u8, 182u8, 147u8,
        16u8, 35u8, 90u8, 227u8, 181u8, 176u8, 141u8, 66u8, 66u8, 104u8, 138u8, 248u8, 96u8, 185u8,
        153u8, 92u8, 91u8, 11u8, 195u8, 41u8, 91u8, 60u8, 126u8, 149u8, 75u8, 118u8, 220u8, 69u8,
        243u8, 34u8, 37u8, 139u8,
    ],
    vk_delta_g2: [
        13u8, 38u8, 250u8, 179u8, 33u8, 241u8, 60u8, 59u8, 32u8, 124u8, 139u8, 179u8, 35u8, 97u8,
        121u8, 46u8, 96u8, 22u8, 118u8, 193u8, 55u8, 10u8, 0u8, 218u8, 254u8, 181u8, 251u8, 226u8,
        9u8, 92u8, 43u8, 242u8, 43u8, 123u8, 56u8, 178u8, 254u8, 146u8, 134u8, 224u8, 231u8, 49u8,
        31u8, 176u8, 9u8, 177u8, 197u8, 45u8, 216u8, 60u8, 4u8, 146u8, 114u8, 189u8, 3u8, 72u8,
        18u8, 206u8, 236u8, 16u8, 28u8, 68u8, 7u8, 151u8, 42u8, 2u8, 16u8, 221u8, 77u8, 39u8, 52u8,
        188u8, 7u8, 61u8, 190u8, 242u8, 50u8, 139u8, 215u8, 25u8, 231u8, 154u8, 23u8, 73u8, 86u8,
        124u8, 200u8, 60u8, 187u8, 198u8, 237u8, 205u8, 12u8, 1u8, 36u8, 87u8, 38u8, 123u8, 188u8,
        175u8, 41u8, 249u8, 167u8, 252u8, 82u8, 234u8, 92u8, 178u8, 74u8, 7u8, 217u8, 138u8, 14u8,
        92u8, 180u8, 159u8, 29u8, 147u8, 89u8, 144u8, 38u8, 48u8, 143u8, 244u8, 159u8, 133u8, 55u8,
        46u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [242u8, 20u8, 51u8, 16u8, 89u8, 191u8, 241u8, 60u8, 97u8, 232u8, 125u8, 105u8, 1u8, 232u8, 246u8, 74u8, 152u8, 57u8, 255u8, 39u8, 211u8, 169u8, 238u8, 60u8, 112u8, 53u8, 43u8, 97u8, 251u8, 230u8, 56u8, 114u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_cab38adbc98e2728")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00f214331059bff13c61e87d6901e8f64a9839ff27d3a9ee3c70352b61fbe63872\x00=======END GROTH16 VK SETUP V1=======\x00";
