// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        34u8, 64u8, 107u8, 152u8, 3u8, 196u8, 104u8, 70u8, 253u8, 232u8, 17u8, 216u8, 148u8, 118u8,
        3u8, 183u8, 124u8, 201u8, 224u8, 234u8, 162u8, 46u8, 26u8, 232u8, 101u8, 72u8, 137u8,
        234u8, 110u8, 149u8, 29u8, 116u8, 28u8, 199u8, 54u8, 36u8, 147u8, 25u8, 133u8, 38u8, 250u8,
        95u8, 150u8, 101u8, 11u8, 16u8, 253u8, 109u8, 166u8, 174u8, 99u8, 14u8, 249u8, 80u8, 121u8,
        155u8, 178u8, 2u8, 41u8, 133u8, 106u8, 213u8, 16u8, 205u8,
    ],
    [
        3u8, 91u8, 228u8, 212u8, 15u8, 125u8, 94u8, 67u8, 140u8, 211u8, 191u8, 53u8, 181u8, 233u8,
        137u8, 223u8, 90u8, 36u8, 238u8, 168u8, 250u8, 9u8, 151u8, 215u8, 130u8, 232u8, 126u8,
        202u8, 216u8, 229u8, 62u8, 18u8, 22u8, 145u8, 145u8, 121u8, 187u8, 8u8, 44u8, 168u8, 158u8,
        182u8, 195u8, 216u8, 17u8, 231u8, 109u8, 39u8, 85u8, 116u8, 240u8, 237u8, 224u8, 243u8,
        178u8, 120u8, 5u8, 227u8, 148u8, 166u8, 66u8, 172u8, 113u8, 90u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        39u8, 170u8, 203u8, 144u8, 189u8, 30u8, 186u8, 141u8, 0u8, 234u8, 249u8, 190u8, 158u8,
        168u8, 100u8, 205u8, 132u8, 124u8, 109u8, 188u8, 38u8, 148u8, 43u8, 226u8, 63u8, 110u8,
        3u8, 100u8, 193u8, 51u8, 207u8, 118u8, 10u8, 219u8, 127u8, 141u8, 173u8, 115u8, 69u8,
        135u8, 204u8, 175u8, 4u8, 129u8, 177u8, 184u8, 30u8, 33u8, 16u8, 70u8, 113u8, 234u8, 239u8,
        31u8, 220u8, 169u8, 45u8, 130u8, 165u8, 216u8, 16u8, 166u8, 240u8, 30u8,
    ],
    vk_beta_g2: [
        33u8, 52u8, 238u8, 128u8, 206u8, 13u8, 55u8, 128u8, 99u8, 71u8, 251u8, 250u8, 19u8, 31u8,
        0u8, 101u8, 248u8, 185u8, 197u8, 143u8, 159u8, 193u8, 104u8, 89u8, 127u8, 50u8, 220u8,
        171u8, 156u8, 102u8, 252u8, 4u8, 43u8, 200u8, 30u8, 67u8, 252u8, 74u8, 228u8, 159u8, 227u8,
        23u8, 154u8, 109u8, 34u8, 241u8, 219u8, 95u8, 169u8, 205u8, 191u8, 14u8, 136u8, 93u8, 7u8,
        197u8, 64u8, 109u8, 57u8, 187u8, 150u8, 44u8, 141u8, 216u8, 18u8, 232u8, 249u8, 180u8,
        183u8, 23u8, 193u8, 65u8, 13u8, 234u8, 119u8, 135u8, 177u8, 179u8, 21u8, 44u8, 193u8, 84u8,
        243u8, 230u8, 173u8, 18u8, 133u8, 123u8, 113u8, 80u8, 210u8, 186u8, 206u8, 205u8, 169u8,
        2u8, 7u8, 243u8, 68u8, 181u8, 65u8, 192u8, 35u8, 1u8, 179u8, 107u8, 112u8, 242u8, 79u8,
        34u8, 154u8, 95u8, 5u8, 166u8, 248u8, 141u8, 231u8, 166u8, 153u8, 249u8, 102u8, 43u8, 75u8,
        125u8, 188u8, 27u8, 49u8, 143u8,
    ],
    vk_gamma_g2: [
        19u8, 9u8, 175u8, 148u8, 60u8, 210u8, 65u8, 69u8, 7u8, 141u8, 251u8, 80u8, 242u8, 218u8,
        156u8, 177u8, 220u8, 31u8, 242u8, 168u8, 144u8, 200u8, 223u8, 104u8, 221u8, 67u8, 64u8,
        23u8, 236u8, 217u8, 19u8, 30u8, 3u8, 178u8, 244u8, 247u8, 173u8, 203u8, 58u8, 221u8, 119u8,
        193u8, 151u8, 130u8, 26u8, 192u8, 51u8, 118u8, 236u8, 8u8, 48u8, 6u8, 183u8, 164u8, 153u8,
        108u8, 132u8, 164u8, 190u8, 178u8, 136u8, 246u8, 27u8, 65u8, 10u8, 134u8, 2u8, 45u8, 5u8,
        235u8, 33u8, 58u8, 180u8, 160u8, 21u8, 175u8, 179u8, 244u8, 83u8, 244u8, 180u8, 242u8,
        173u8, 162u8, 34u8, 213u8, 221u8, 132u8, 96u8, 116u8, 162u8, 102u8, 189u8, 62u8, 84u8, 5u8,
        27u8, 155u8, 134u8, 160u8, 120u8, 143u8, 145u8, 26u8, 170u8, 234u8, 130u8, 207u8, 102u8,
        166u8, 167u8, 173u8, 196u8, 181u8, 214u8, 74u8, 222u8, 108u8, 110u8, 104u8, 93u8, 17u8,
        37u8, 94u8, 21u8, 75u8, 242u8, 115u8,
    ],
    vk_delta_g2: [
        20u8, 196u8, 153u8, 31u8, 58u8, 150u8, 206u8, 12u8, 32u8, 85u8, 25u8, 63u8, 47u8, 221u8,
        52u8, 76u8, 102u8, 177u8, 58u8, 97u8, 150u8, 53u8, 202u8, 173u8, 125u8, 181u8, 58u8, 84u8,
        33u8, 164u8, 121u8, 170u8, 19u8, 208u8, 63u8, 123u8, 177u8, 49u8, 44u8, 102u8, 173u8,
        145u8, 247u8, 120u8, 138u8, 153u8, 183u8, 8u8, 111u8, 111u8, 202u8, 156u8, 91u8, 139u8,
        238u8, 195u8, 204u8, 126u8, 23u8, 82u8, 100u8, 4u8, 71u8, 68u8, 15u8, 7u8, 145u8, 209u8,
        199u8, 202u8, 60u8, 228u8, 161u8, 37u8, 129u8, 197u8, 209u8, 182u8, 135u8, 33u8, 7u8,
        203u8, 208u8, 194u8, 175u8, 185u8, 3u8, 168u8, 14u8, 34u8, 236u8, 14u8, 226u8, 100u8,
        127u8, 211u8, 23u8, 61u8, 190u8, 216u8, 41u8, 118u8, 149u8, 250u8, 29u8, 74u8, 144u8, 78u8,
        217u8, 12u8, 169u8, 55u8, 10u8, 249u8, 115u8, 235u8, 97u8, 200u8, 226u8, 185u8, 163u8,
        36u8, 37u8, 51u8, 203u8, 44u8, 230u8, 92u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [70u8, 225u8, 58u8, 83u8, 40u8, 249u8, 0u8, 159u8, 156u8, 79u8, 19u8, 97u8, 203u8, 231u8, 72u8, 181u8, 247u8, 236u8, 80u8, 31u8, 75u8, 147u8, 32u8, 6u8, 62u8, 121u8, 223u8, 167u8, 138u8, 210u8, 57u8, 53u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_1f235c253639d6db")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0046e13a5328f9009f9c4f1361cbe748b5f7ec501f4b9320063e79dfa78ad23935\x00=======END GROTH16 VK SETUP V1=======\x00";
