// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        44u8, 180u8, 237u8, 203u8, 224u8, 114u8, 137u8, 150u8, 4u8, 162u8, 189u8, 144u8, 253u8,
        7u8, 24u8, 34u8, 92u8, 236u8, 90u8, 226u8, 166u8, 170u8, 134u8, 216u8, 78u8, 125u8, 153u8,
        224u8, 14u8, 232u8, 206u8, 2u8, 0u8, 68u8, 235u8, 129u8, 161u8, 129u8, 44u8, 182u8, 101u8,
        210u8, 104u8, 38u8, 122u8, 154u8, 97u8, 12u8, 148u8, 110u8, 17u8, 159u8, 187u8, 77u8,
        101u8, 133u8, 13u8, 7u8, 64u8, 46u8, 60u8, 80u8, 177u8, 184u8,
    ],
    [
        45u8, 41u8, 205u8, 29u8, 190u8, 192u8, 9u8, 93u8, 247u8, 205u8, 74u8, 232u8, 12u8, 75u8,
        233u8, 3u8, 255u8, 177u8, 221u8, 128u8, 4u8, 111u8, 162u8, 246u8, 219u8, 192u8, 145u8,
        45u8, 36u8, 10u8, 176u8, 3u8, 39u8, 143u8, 11u8, 233u8, 198u8, 228u8, 115u8, 26u8, 165u8,
        1u8, 12u8, 243u8, 85u8, 140u8, 89u8, 170u8, 127u8, 17u8, 27u8, 62u8, 60u8, 217u8, 16u8,
        219u8, 143u8, 191u8, 149u8, 61u8, 221u8, 234u8, 78u8, 23u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        18u8, 27u8, 44u8, 92u8, 112u8, 237u8, 172u8, 101u8, 117u8, 33u8, 178u8, 169u8, 44u8, 131u8,
        99u8, 135u8, 230u8, 88u8, 80u8, 170u8, 17u8, 63u8, 3u8, 176u8, 99u8, 183u8, 34u8, 133u8,
        183u8, 116u8, 111u8, 188u8, 42u8, 207u8, 107u8, 81u8, 37u8, 91u8, 93u8, 130u8, 163u8, 83u8,
        45u8, 130u8, 166u8, 4u8, 197u8, 0u8, 226u8, 54u8, 204u8, 34u8, 221u8, 162u8, 14u8, 57u8,
        86u8, 111u8, 29u8, 227u8, 254u8, 203u8, 67u8, 121u8,
    ],
    vk_beta_g2: [
        25u8, 214u8, 122u8, 36u8, 153u8, 62u8, 121u8, 108u8, 10u8, 251u8, 92u8, 22u8, 43u8, 33u8,
        68u8, 252u8, 95u8, 113u8, 4u8, 249u8, 251u8, 242u8, 209u8, 169u8, 138u8, 218u8, 53u8,
        125u8, 151u8, 217u8, 112u8, 103u8, 43u8, 32u8, 47u8, 204u8, 102u8, 41u8, 120u8, 248u8,
        202u8, 74u8, 216u8, 134u8, 3u8, 162u8, 207u8, 126u8, 96u8, 251u8, 20u8, 134u8, 4u8, 3u8,
        124u8, 56u8, 116u8, 123u8, 170u8, 204u8, 235u8, 255u8, 229u8, 54u8, 17u8, 254u8, 34u8,
        110u8, 80u8, 133u8, 174u8, 234u8, 43u8, 121u8, 240u8, 95u8, 159u8, 185u8, 28u8, 238u8,
        34u8, 238u8, 95u8, 226u8, 92u8, 230u8, 69u8, 1u8, 63u8, 141u8, 149u8, 198u8, 126u8, 96u8,
        105u8, 6u8, 18u8, 155u8, 14u8, 81u8, 112u8, 26u8, 218u8, 100u8, 106u8, 250u8, 93u8, 174u8,
        117u8, 243u8, 0u8, 99u8, 5u8, 230u8, 107u8, 124u8, 184u8, 182u8, 16u8, 207u8, 98u8, 188u8,
        142u8, 162u8, 135u8, 125u8, 47u8, 176u8,
    ],
    vk_gamma_g2: [
        4u8, 198u8, 44u8, 93u8, 146u8, 186u8, 103u8, 102u8, 103u8, 52u8, 30u8, 138u8, 102u8, 190u8,
        56u8, 129u8, 184u8, 51u8, 238u8, 30u8, 253u8, 45u8, 81u8, 28u8, 199u8, 159u8, 229u8, 178u8,
        74u8, 217u8, 127u8, 125u8, 0u8, 228u8, 116u8, 83u8, 12u8, 87u8, 70u8, 151u8, 101u8, 184u8,
        185u8, 59u8, 246u8, 81u8, 24u8, 163u8, 34u8, 191u8, 243u8, 115u8, 165u8, 184u8, 7u8, 138u8,
        186u8, 137u8, 147u8, 23u8, 231u8, 89u8, 28u8, 164u8, 11u8, 127u8, 202u8, 119u8, 161u8,
        47u8, 65u8, 120u8, 16u8, 71u8, 104u8, 68u8, 254u8, 227u8, 216u8, 198u8, 46u8, 175u8, 40u8,
        94u8, 217u8, 93u8, 12u8, 99u8, 182u8, 229u8, 191u8, 215u8, 86u8, 159u8, 70u8, 227u8, 30u8,
        178u8, 157u8, 201u8, 133u8, 35u8, 44u8, 193u8, 215u8, 129u8, 154u8, 198u8, 86u8, 34u8,
        208u8, 50u8, 151u8, 14u8, 192u8, 251u8, 252u8, 176u8, 81u8, 49u8, 235u8, 158u8, 68u8,
        152u8, 220u8, 237u8, 202u8, 42u8,
    ],
    vk_delta_g2: [
        37u8, 204u8, 155u8, 222u8, 254u8, 226u8, 18u8, 164u8, 116u8, 198u8, 230u8, 74u8, 130u8,
        234u8, 0u8, 166u8, 160u8, 217u8, 114u8, 139u8, 13u8, 140u8, 135u8, 47u8, 20u8, 8u8, 64u8,
        25u8, 202u8, 235u8, 196u8, 245u8, 38u8, 185u8, 149u8, 120u8, 21u8, 152u8, 109u8, 103u8,
        185u8, 139u8, 163u8, 85u8, 247u8, 54u8, 34u8, 58u8, 23u8, 6u8, 194u8, 252u8, 185u8, 8u8,
        104u8, 159u8, 214u8, 206u8, 251u8, 188u8, 77u8, 231u8, 243u8, 82u8, 24u8, 138u8, 99u8,
        179u8, 78u8, 75u8, 198u8, 127u8, 104u8, 26u8, 135u8, 189u8, 32u8, 221u8, 250u8, 242u8,
        188u8, 24u8, 121u8, 130u8, 36u8, 28u8, 102u8, 177u8, 147u8, 109u8, 103u8, 143u8, 108u8,
        78u8, 195u8, 193u8, 47u8, 199u8, 116u8, 209u8, 170u8, 21u8, 232u8, 166u8, 62u8, 198u8,
        94u8, 90u8, 152u8, 16u8, 255u8, 31u8, 156u8, 67u8, 200u8, 45u8, 1u8, 197u8, 61u8, 114u8,
        68u8, 6u8, 106u8, 19u8, 106u8, 234u8, 229u8, 18u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [244u8, 39u8, 250u8, 108u8, 109u8, 112u8, 213u8, 10u8, 92u8, 32u8, 107u8, 190u8, 26u8, 229u8, 67u8, 13u8, 82u8, 16u8, 224u8, 60u8, 41u8, 157u8, 24u8, 150u8, 203u8, 49u8, 138u8, 226u8, 233u8, 79u8, 73u8, 156u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_ae042fc82b19671c")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00f427fa6c6d70d50a5c206bbe1ae5430d5210e03c299d1896cb318ae2e94f499c\x00=======END GROTH16 VK SETUP V1=======\x00";
