// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        33u8, 71u8, 70u8, 255u8, 60u8, 7u8, 23u8, 94u8, 87u8, 112u8, 29u8, 1u8, 84u8, 115u8, 254u8,
        177u8, 251u8, 102u8, 137u8, 239u8, 206u8, 4u8, 82u8, 148u8, 221u8, 138u8, 111u8, 16u8,
        109u8, 82u8, 107u8, 249u8, 36u8, 155u8, 22u8, 94u8, 205u8, 5u8, 105u8, 130u8, 226u8, 182u8,
        104u8, 159u8, 23u8, 99u8, 104u8, 151u8, 253u8, 180u8, 168u8, 179u8, 60u8, 101u8, 69u8,
        243u8, 190u8, 33u8, 206u8, 142u8, 45u8, 110u8, 150u8, 210u8,
    ],
    [
        13u8, 131u8, 136u8, 84u8, 179u8, 178u8, 133u8, 150u8, 86u8, 177u8, 255u8, 9u8, 72u8, 25u8,
        250u8, 56u8, 93u8, 62u8, 202u8, 162u8, 175u8, 207u8, 223u8, 223u8, 54u8, 178u8, 153u8,
        153u8, 123u8, 248u8, 196u8, 244u8, 7u8, 180u8, 251u8, 55u8, 67u8, 225u8, 96u8, 49u8, 151u8,
        11u8, 34u8, 153u8, 251u8, 56u8, 166u8, 98u8, 174u8, 17u8, 101u8, 75u8, 104u8, 81u8, 165u8,
        182u8, 101u8, 246u8, 170u8, 47u8, 85u8, 32u8, 227u8, 172u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        20u8, 227u8, 159u8, 109u8, 10u8, 235u8, 206u8, 5u8, 225u8, 120u8, 168u8, 204u8, 166u8,
        175u8, 158u8, 154u8, 190u8, 248u8, 92u8, 203u8, 108u8, 23u8, 117u8, 43u8, 184u8, 101u8,
        136u8, 99u8, 156u8, 38u8, 121u8, 122u8, 28u8, 142u8, 217u8, 107u8, 44u8, 136u8, 15u8,
        211u8, 239u8, 25u8, 157u8, 42u8, 10u8, 2u8, 163u8, 199u8, 230u8, 137u8, 217u8, 20u8, 240u8,
        95u8, 46u8, 181u8, 41u8, 167u8, 73u8, 115u8, 82u8, 133u8, 97u8, 97u8,
    ],
    vk_beta_g2: [
        13u8, 255u8, 254u8, 210u8, 161u8, 165u8, 92u8, 41u8, 37u8, 221u8, 68u8, 41u8, 223u8, 53u8,
        229u8, 145u8, 106u8, 63u8, 129u8, 179u8, 244u8, 166u8, 21u8, 196u8, 114u8, 63u8, 203u8,
        144u8, 57u8, 220u8, 149u8, 72u8, 40u8, 169u8, 67u8, 166u8, 7u8, 144u8, 156u8, 106u8, 164u8,
        7u8, 172u8, 148u8, 92u8, 85u8, 103u8, 181u8, 137u8, 230u8, 46u8, 132u8, 150u8, 62u8, 3u8,
        9u8, 148u8, 59u8, 156u8, 253u8, 99u8, 230u8, 55u8, 127u8, 42u8, 181u8, 187u8, 58u8, 62u8,
        10u8, 167u8, 244u8, 36u8, 127u8, 48u8, 254u8, 236u8, 14u8, 193u8, 247u8, 223u8, 68u8, 83u8,
        182u8, 187u8, 35u8, 137u8, 137u8, 5u8, 150u8, 219u8, 186u8, 83u8, 132u8, 21u8, 166u8, 16u8,
        198u8, 123u8, 88u8, 239u8, 251u8, 119u8, 136u8, 129u8, 184u8, 253u8, 62u8, 42u8, 132u8,
        240u8, 82u8, 19u8, 28u8, 235u8, 24u8, 159u8, 52u8, 102u8, 21u8, 163u8, 98u8, 138u8, 204u8,
        68u8, 239u8, 151u8, 227u8,
    ],
    vk_gamma_g2: [
        10u8, 12u8, 246u8, 33u8, 200u8, 213u8, 222u8, 20u8, 83u8, 118u8, 178u8, 143u8, 69u8, 151u8,
        252u8, 131u8, 234u8, 181u8, 198u8, 233u8, 247u8, 106u8, 214u8, 190u8, 61u8, 57u8, 21u8,
        63u8, 128u8, 222u8, 204u8, 16u8, 7u8, 45u8, 47u8, 65u8, 123u8, 91u8, 3u8, 143u8, 71u8,
        79u8, 142u8, 240u8, 93u8, 191u8, 208u8, 158u8, 10u8, 214u8, 131u8, 78u8, 183u8, 117u8,
        239u8, 181u8, 147u8, 249u8, 206u8, 142u8, 81u8, 88u8, 67u8, 64u8, 13u8, 32u8, 38u8, 70u8,
        189u8, 141u8, 87u8, 13u8, 6u8, 52u8, 222u8, 60u8, 255u8, 165u8, 46u8, 165u8, 77u8, 30u8,
        179u8, 151u8, 249u8, 123u8, 180u8, 174u8, 231u8, 150u8, 247u8, 197u8, 195u8, 56u8, 214u8,
        97u8, 29u8, 235u8, 147u8, 16u8, 24u8, 99u8, 154u8, 200u8, 64u8, 240u8, 212u8, 185u8, 36u8,
        196u8, 140u8, 140u8, 39u8, 27u8, 125u8, 141u8, 106u8, 66u8, 50u8, 16u8, 150u8, 171u8,
        100u8, 95u8, 174u8, 54u8, 16u8, 194u8,
    ],
    vk_delta_g2: [
        20u8, 22u8, 228u8, 244u8, 64u8, 74u8, 114u8, 251u8, 12u8, 169u8, 174u8, 93u8, 170u8, 58u8,
        129u8, 129u8, 38u8, 44u8, 163u8, 23u8, 219u8, 142u8, 15u8, 208u8, 116u8, 40u8, 215u8, 87u8,
        162u8, 225u8, 140u8, 85u8, 20u8, 190u8, 219u8, 95u8, 186u8, 56u8, 67u8, 233u8, 224u8, 79u8,
        166u8, 165u8, 67u8, 228u8, 255u8, 206u8, 237u8, 110u8, 189u8, 175u8, 133u8, 99u8, 99u8,
        92u8, 57u8, 128u8, 73u8, 77u8, 76u8, 47u8, 234u8, 58u8, 33u8, 150u8, 123u8, 5u8, 36u8,
        191u8, 61u8, 158u8, 139u8, 108u8, 178u8, 232u8, 209u8, 109u8, 232u8, 32u8, 22u8, 28u8,
        169u8, 147u8, 79u8, 116u8, 94u8, 28u8, 150u8, 84u8, 150u8, 50u8, 252u8, 8u8, 83u8, 56u8,
        6u8, 148u8, 233u8, 174u8, 129u8, 230u8, 9u8, 29u8, 1u8, 165u8, 117u8, 155u8, 162u8, 142u8,
        238u8, 14u8, 38u8, 59u8, 130u8, 188u8, 7u8, 56u8, 224u8, 239u8, 80u8, 58u8, 85u8, 130u8,
        163u8, 212u8, 64u8, 125u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [166u8, 136u8, 82u8, 105u8, 252u8, 211u8, 7u8, 241u8, 190u8, 146u8, 119u8, 15u8, 195u8, 163u8, 45u8, 237u8, 46u8, 103u8, 35u8, 13u8, 107u8, 69u8, 168u8, 17u8, 222u8, 122u8, 183u8, 92u8, 165u8, 0u8, 120u8, 151u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_dd804853b28128f3")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00a6885269fcd307f1be92770fc3a32ded2e67230d6b45a811de7ab75ca5007897\x00=======END GROTH16 VK SETUP V1=======\x00";
