// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        2u8, 74u8, 107u8, 244u8, 170u8, 2u8, 194u8, 68u8, 149u8, 147u8, 199u8, 198u8, 197u8, 150u8,
        233u8, 240u8, 169u8, 196u8, 118u8, 114u8, 106u8, 89u8, 104u8, 201u8, 143u8, 159u8, 90u8,
        71u8, 119u8, 125u8, 183u8, 207u8, 22u8, 158u8, 122u8, 49u8, 55u8, 16u8, 172u8, 55u8, 217u8,
        193u8, 0u8, 84u8, 88u8, 29u8, 199u8, 22u8, 48u8, 108u8, 242u8, 197u8, 164u8, 56u8, 21u8,
        214u8, 86u8, 98u8, 22u8, 93u8, 6u8, 144u8, 233u8, 157u8,
    ],
    [
        33u8, 83u8, 94u8, 202u8, 158u8, 39u8, 79u8, 114u8, 181u8, 176u8, 69u8, 116u8, 40u8, 194u8,
        182u8, 164u8, 221u8, 133u8, 55u8, 91u8, 183u8, 149u8, 151u8, 51u8, 46u8, 12u8, 115u8, 35u8,
        231u8, 137u8, 70u8, 205u8, 1u8, 168u8, 250u8, 43u8, 29u8, 91u8, 3u8, 37u8, 143u8, 137u8,
        159u8, 199u8, 36u8, 3u8, 212u8, 190u8, 62u8, 28u8, 225u8, 36u8, 218u8, 21u8, 151u8, 102u8,
        115u8, 216u8, 149u8, 148u8, 17u8, 221u8, 154u8, 70u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        37u8, 191u8, 7u8, 37u8, 15u8, 237u8, 179u8, 96u8, 13u8, 93u8, 127u8, 163u8, 23u8, 57u8,
        54u8, 229u8, 9u8, 159u8, 62u8, 230u8, 182u8, 244u8, 244u8, 77u8, 44u8, 198u8, 109u8, 132u8,
        255u8, 110u8, 125u8, 45u8, 36u8, 186u8, 22u8, 138u8, 241u8, 127u8, 66u8, 187u8, 71u8, 11u8,
        3u8, 196u8, 213u8, 87u8, 227u8, 245u8, 103u8, 182u8, 182u8, 61u8, 201u8, 99u8, 77u8, 138u8,
        127u8, 160u8, 210u8, 58u8, 160u8, 36u8, 195u8, 216u8,
    ],
    vk_beta_g2: [
        45u8, 131u8, 48u8, 149u8, 110u8, 171u8, 119u8, 1u8, 233u8, 142u8, 27u8, 58u8, 121u8, 25u8,
        142u8, 103u8, 192u8, 213u8, 236u8, 252u8, 23u8, 119u8, 110u8, 51u8, 71u8, 28u8, 48u8, 2u8,
        63u8, 225u8, 209u8, 236u8, 30u8, 167u8, 255u8, 235u8, 160u8, 171u8, 136u8, 38u8, 121u8,
        248u8, 171u8, 176u8, 177u8, 31u8, 149u8, 204u8, 55u8, 199u8, 140u8, 45u8, 236u8, 87u8,
        96u8, 29u8, 37u8, 170u8, 88u8, 147u8, 140u8, 248u8, 166u8, 226u8, 15u8, 193u8, 135u8,
        246u8, 100u8, 201u8, 12u8, 42u8, 189u8, 213u8, 124u8, 229u8, 142u8, 226u8, 166u8, 85u8,
        34u8, 53u8, 232u8, 140u8, 242u8, 89u8, 135u8, 172u8, 71u8, 188u8, 146u8, 169u8, 77u8, 18u8,
        242u8, 241u8, 17u8, 111u8, 130u8, 147u8, 243u8, 29u8, 78u8, 5u8, 22u8, 133u8, 159u8, 48u8,
        13u8, 196u8, 127u8, 101u8, 214u8, 141u8, 82u8, 30u8, 146u8, 213u8, 84u8, 34u8, 134u8,
        207u8, 227u8, 164u8, 135u8, 243u8, 21u8, 168u8,
    ],
    vk_gamma_g2: [
        38u8, 93u8, 15u8, 15u8, 188u8, 55u8, 159u8, 218u8, 153u8, 30u8, 50u8, 111u8, 177u8, 23u8,
        149u8, 46u8, 36u8, 96u8, 205u8, 208u8, 156u8, 51u8, 113u8, 236u8, 75u8, 232u8, 184u8, 58u8,
        24u8, 1u8, 187u8, 226u8, 21u8, 184u8, 116u8, 13u8, 6u8, 125u8, 182u8, 63u8, 18u8, 230u8,
        157u8, 92u8, 2u8, 220u8, 41u8, 81u8, 248u8, 207u8, 120u8, 139u8, 34u8, 232u8, 90u8, 237u8,
        160u8, 241u8, 202u8, 10u8, 184u8, 114u8, 232u8, 120u8, 11u8, 75u8, 124u8, 58u8, 109u8,
        129u8, 14u8, 193u8, 31u8, 175u8, 174u8, 105u8, 176u8, 201u8, 105u8, 80u8, 232u8, 213u8,
        142u8, 115u8, 44u8, 43u8, 136u8, 214u8, 132u8, 94u8, 196u8, 240u8, 111u8, 253u8, 255u8,
        69u8, 0u8, 94u8, 164u8, 114u8, 227u8, 76u8, 113u8, 36u8, 63u8, 46u8, 39u8, 26u8, 222u8,
        53u8, 108u8, 9u8, 254u8, 10u8, 98u8, 21u8, 145u8, 60u8, 15u8, 70u8, 207u8, 204u8, 2u8,
        50u8, 210u8, 42u8, 193u8, 4u8,
    ],
    vk_delta_g2: [
        45u8, 170u8, 9u8, 92u8, 151u8, 8u8, 19u8, 118u8, 181u8, 63u8, 31u8, 15u8, 228u8, 16u8,
        11u8, 254u8, 35u8, 27u8, 96u8, 220u8, 109u8, 192u8, 98u8, 32u8, 0u8, 99u8, 144u8, 216u8,
        253u8, 236u8, 112u8, 199u8, 6u8, 65u8, 134u8, 68u8, 79u8, 209u8, 91u8, 180u8, 211u8, 51u8,
        255u8, 151u8, 35u8, 242u8, 64u8, 170u8, 182u8, 70u8, 104u8, 182u8, 183u8, 78u8, 57u8, 57u8,
        220u8, 37u8, 114u8, 244u8, 216u8, 139u8, 222u8, 123u8, 28u8, 176u8, 83u8, 161u8, 170u8,
        143u8, 217u8, 46u8, 129u8, 129u8, 26u8, 109u8, 37u8, 82u8, 11u8, 213u8, 77u8, 138u8, 201u8,
        149u8, 4u8, 140u8, 204u8, 190u8, 249u8, 241u8, 204u8, 105u8, 3u8, 208u8, 124u8, 128u8,
        28u8, 182u8, 80u8, 224u8, 180u8, 20u8, 57u8, 8u8, 5u8, 201u8, 201u8, 189u8, 163u8, 62u8,
        127u8, 194u8, 153u8, 64u8, 226u8, 225u8, 3u8, 87u8, 79u8, 114u8, 64u8, 39u8, 67u8, 104u8,
        56u8, 158u8, 87u8, 108u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [121u8, 40u8, 25u8, 103u8, 228u8, 170u8, 196u8, 125u8, 193u8, 135u8, 211u8, 166u8, 85u8, 90u8, 181u8, 72u8, 0u8, 206u8, 243u8, 146u8, 142u8, 86u8, 150u8, 150u8, 157u8, 207u8, 74u8, 251u8, 105u8, 179u8, 57u8, 218u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_443059a3d520b493")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0079281967e4aac47dc187d3a6555ab54800cef3928e5696969dcf4afb69b339da\x00=======END GROTH16 VK SETUP V1=======\x00";
