// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        6u8, 9u8, 91u8, 171u8, 105u8, 63u8, 8u8, 19u8, 11u8, 15u8, 227u8, 2u8, 235u8, 39u8, 76u8,
        219u8, 154u8, 242u8, 31u8, 220u8, 49u8, 32u8, 183u8, 33u8, 43u8, 48u8, 19u8, 93u8, 79u8,
        4u8, 0u8, 245u8, 46u8, 44u8, 246u8, 65u8, 98u8, 105u8, 192u8, 90u8, 119u8, 151u8, 161u8,
        188u8, 27u8, 80u8, 39u8, 244u8, 127u8, 223u8, 58u8, 41u8, 168u8, 50u8, 5u8, 186u8, 161u8,
        86u8, 63u8, 200u8, 190u8, 88u8, 194u8, 157u8,
    ],
    [
        45u8, 20u8, 163u8, 210u8, 56u8, 143u8, 235u8, 21u8, 91u8, 9u8, 51u8, 151u8, 124u8, 227u8,
        31u8, 113u8, 17u8, 166u8, 182u8, 66u8, 15u8, 178u8, 240u8, 81u8, 223u8, 214u8, 88u8, 175u8,
        48u8, 21u8, 129u8, 92u8, 35u8, 143u8, 7u8, 161u8, 207u8, 10u8, 170u8, 161u8, 46u8, 81u8,
        234u8, 186u8, 113u8, 28u8, 118u8, 224u8, 91u8, 25u8, 19u8, 173u8, 40u8, 204u8, 54u8, 163u8,
        201u8, 244u8, 178u8, 62u8, 153u8, 86u8, 3u8, 150u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        35u8, 9u8, 174u8, 38u8, 49u8, 180u8, 58u8, 91u8, 131u8, 118u8, 38u8, 77u8, 37u8, 11u8,
        245u8, 109u8, 244u8, 220u8, 39u8, 80u8, 138u8, 236u8, 239u8, 74u8, 98u8, 155u8, 78u8, 88u8,
        154u8, 72u8, 226u8, 219u8, 42u8, 40u8, 16u8, 80u8, 168u8, 234u8, 252u8, 36u8, 1u8, 201u8,
        68u8, 72u8, 69u8, 26u8, 159u8, 226u8, 197u8, 87u8, 45u8, 191u8, 80u8, 248u8, 137u8, 140u8,
        60u8, 173u8, 241u8, 128u8, 97u8, 14u8, 116u8, 61u8,
    ],
    vk_beta_g2: [
        11u8, 12u8, 42u8, 131u8, 43u8, 47u8, 74u8, 208u8, 51u8, 35u8, 90u8, 11u8, 150u8, 75u8,
        109u8, 60u8, 178u8, 219u8, 199u8, 135u8, 105u8, 227u8, 124u8, 159u8, 187u8, 136u8, 141u8,
        203u8, 143u8, 52u8, 43u8, 21u8, 15u8, 48u8, 254u8, 142u8, 42u8, 4u8, 5u8, 200u8, 18u8,
        195u8, 222u8, 252u8, 49u8, 242u8, 86u8, 183u8, 246u8, 198u8, 115u8, 190u8, 180u8, 255u8,
        142u8, 62u8, 138u8, 223u8, 180u8, 28u8, 133u8, 54u8, 124u8, 212u8, 17u8, 186u8, 58u8, 10u8,
        56u8, 130u8, 112u8, 23u8, 115u8, 8u8, 42u8, 72u8, 193u8, 88u8, 38u8, 43u8, 135u8, 246u8,
        113u8, 55u8, 186u8, 75u8, 202u8, 49u8, 85u8, 100u8, 252u8, 31u8, 230u8, 146u8, 169u8,
        229u8, 13u8, 92u8, 233u8, 59u8, 167u8, 160u8, 15u8, 99u8, 21u8, 100u8, 111u8, 26u8, 70u8,
        35u8, 46u8, 17u8, 61u8, 252u8, 230u8, 101u8, 17u8, 79u8, 177u8, 57u8, 14u8, 239u8, 37u8,
        219u8, 184u8, 163u8, 242u8, 75u8,
    ],
    vk_gamma_g2: [
        32u8, 75u8, 198u8, 226u8, 15u8, 191u8, 133u8, 204u8, 63u8, 160u8, 97u8, 182u8, 249u8,
        191u8, 56u8, 255u8, 170u8, 207u8, 100u8, 227u8, 141u8, 245u8, 3u8, 47u8, 242u8, 152u8,
        220u8, 128u8, 230u8, 204u8, 255u8, 33u8, 36u8, 207u8, 243u8, 211u8, 74u8, 56u8, 152u8,
        35u8, 43u8, 248u8, 255u8, 215u8, 20u8, 246u8, 119u8, 79u8, 42u8, 225u8, 14u8, 45u8, 217u8,
        204u8, 3u8, 68u8, 155u8, 123u8, 43u8, 117u8, 31u8, 42u8, 64u8, 109u8, 48u8, 84u8, 27u8,
        139u8, 191u8, 77u8, 68u8, 11u8, 166u8, 217u8, 138u8, 149u8, 51u8, 235u8, 125u8, 225u8,
        243u8, 29u8, 97u8, 85u8, 130u8, 198u8, 189u8, 91u8, 208u8, 69u8, 15u8, 112u8, 112u8, 17u8,
        108u8, 138u8, 2u8, 81u8, 210u8, 234u8, 48u8, 118u8, 18u8, 154u8, 3u8, 26u8, 216u8, 133u8,
        73u8, 229u8, 32u8, 190u8, 64u8, 123u8, 189u8, 254u8, 39u8, 22u8, 67u8, 142u8, 137u8, 190u8,
        240u8, 228u8, 214u8, 195u8, 179u8, 100u8,
    ],
    vk_delta_g2: [
        43u8, 136u8, 100u8, 217u8, 191u8, 148u8, 59u8, 185u8, 116u8, 120u8, 131u8, 100u8, 230u8,
        161u8, 78u8, 24u8, 87u8, 10u8, 80u8, 21u8, 165u8, 165u8, 54u8, 21u8, 58u8, 110u8, 6u8,
        33u8, 227u8, 175u8, 7u8, 35u8, 12u8, 60u8, 134u8, 143u8, 147u8, 6u8, 183u8, 44u8, 202u8,
        252u8, 228u8, 178u8, 54u8, 15u8, 53u8, 106u8, 92u8, 182u8, 121u8, 112u8, 80u8, 72u8, 172u8,
        39u8, 249u8, 40u8, 97u8, 95u8, 183u8, 174u8, 62u8, 12u8, 19u8, 71u8, 5u8, 180u8, 118u8,
        76u8, 144u8, 229u8, 21u8, 160u8, 15u8, 101u8, 239u8, 203u8, 255u8, 181u8, 85u8, 75u8, 32u8,
        37u8, 110u8, 191u8, 82u8, 235u8, 243u8, 102u8, 89u8, 88u8, 4u8, 49u8, 24u8, 92u8, 35u8,
        196u8, 77u8, 105u8, 13u8, 41u8, 117u8, 239u8, 42u8, 239u8, 151u8, 189u8, 42u8, 100u8,
        170u8, 15u8, 172u8, 219u8, 14u8, 235u8, 215u8, 128u8, 158u8, 65u8, 70u8, 116u8, 123u8,
        24u8, 230u8, 73u8, 167u8, 210u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [9u8, 29u8, 36u8, 94u8, 22u8, 227u8, 92u8, 72u8, 145u8, 134u8, 233u8, 54u8, 98u8, 3u8, 100u8, 243u8, 240u8, 162u8, 137u8, 88u8, 102u8, 128u8, 114u8, 74u8, 156u8, 58u8, 8u8, 118u8, 245u8, 244u8, 41u8, 140u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_70e5b25055c5bed0")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00091d245e16e35c489186e936620364f3f0a289586680724a9c3a0876f5f4298c\x00=======END GROTH16 VK SETUP V1=======\x00";
