// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        41u8, 137u8, 166u8, 174u8, 49u8, 118u8, 206u8, 202u8, 46u8, 248u8, 68u8, 123u8, 203u8,
        91u8, 9u8, 209u8, 28u8, 70u8, 163u8, 228u8, 16u8, 97u8, 13u8, 166u8, 74u8, 245u8, 162u8,
        248u8, 184u8, 191u8, 151u8, 186u8, 1u8, 72u8, 125u8, 142u8, 250u8, 77u8, 74u8, 216u8,
        179u8, 17u8, 1u8, 27u8, 189u8, 59u8, 68u8, 99u8, 18u8, 219u8, 212u8, 214u8, 90u8, 58u8,
        200u8, 191u8, 118u8, 130u8, 178u8, 54u8, 240u8, 252u8, 60u8, 85u8,
    ],
    [
        43u8, 247u8, 51u8, 184u8, 227u8, 176u8, 170u8, 64u8, 209u8, 121u8, 181u8, 68u8, 86u8, 44u8,
        67u8, 238u8, 157u8, 94u8, 24u8, 240u8, 81u8, 120u8, 116u8, 86u8, 115u8, 49u8, 129u8, 105u8,
        108u8, 87u8, 75u8, 104u8, 46u8, 71u8, 187u8, 253u8, 142u8, 17u8, 199u8, 36u8, 218u8, 138u8,
        87u8, 189u8, 170u8, 48u8, 6u8, 245u8, 66u8, 245u8, 98u8, 111u8, 169u8, 111u8, 135u8, 87u8,
        93u8, 76u8, 185u8, 226u8, 236u8, 42u8, 49u8, 86u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        41u8, 125u8, 124u8, 17u8, 237u8, 109u8, 33u8, 203u8, 178u8, 94u8, 82u8, 60u8, 31u8, 156u8,
        73u8, 19u8, 191u8, 179u8, 129u8, 111u8, 206u8, 38u8, 59u8, 232u8, 17u8, 231u8, 98u8, 89u8,
        17u8, 131u8, 21u8, 20u8, 40u8, 9u8, 170u8, 224u8, 79u8, 191u8, 105u8, 79u8, 19u8, 21u8,
        115u8, 214u8, 0u8, 202u8, 52u8, 182u8, 196u8, 22u8, 131u8, 71u8, 91u8, 64u8, 173u8, 56u8,
        122u8, 215u8, 205u8, 85u8, 74u8, 53u8, 132u8, 223u8,
    ],
    vk_beta_g2: [
        45u8, 231u8, 243u8, 89u8, 237u8, 92u8, 88u8, 155u8, 220u8, 172u8, 30u8, 137u8, 81u8, 3u8,
        68u8, 84u8, 204u8, 6u8, 96u8, 164u8, 214u8, 26u8, 76u8, 55u8, 133u8, 113u8, 89u8, 105u8,
        174u8, 141u8, 5u8, 152u8, 26u8, 110u8, 156u8, 229u8, 194u8, 231u8, 107u8, 160u8, 32u8,
        32u8, 142u8, 211u8, 145u8, 63u8, 213u8, 163u8, 165u8, 204u8, 238u8, 236u8, 154u8, 0u8,
        77u8, 247u8, 232u8, 154u8, 225u8, 217u8, 236u8, 70u8, 158u8, 17u8, 5u8, 83u8, 145u8, 171u8,
        192u8, 225u8, 49u8, 2u8, 183u8, 179u8, 94u8, 80u8, 215u8, 84u8, 1u8, 208u8, 226u8, 170u8,
        184u8, 208u8, 115u8, 12u8, 177u8, 215u8, 4u8, 134u8, 11u8, 5u8, 136u8, 116u8, 206u8, 13u8,
        27u8, 139u8, 166u8, 184u8, 103u8, 227u8, 117u8, 199u8, 10u8, 79u8, 61u8, 110u8, 88u8,
        209u8, 102u8, 59u8, 228u8, 189u8, 231u8, 207u8, 250u8, 247u8, 65u8, 164u8, 106u8, 10u8,
        159u8, 232u8, 101u8, 231u8, 26u8, 87u8,
    ],
    vk_gamma_g2: [
        28u8, 151u8, 197u8, 249u8, 26u8, 122u8, 249u8, 125u8, 192u8, 80u8, 64u8, 216u8, 29u8,
        157u8, 50u8, 210u8, 168u8, 178u8, 93u8, 157u8, 19u8, 246u8, 161u8, 208u8, 227u8, 203u8,
        70u8, 62u8, 243u8, 118u8, 99u8, 245u8, 29u8, 116u8, 246u8, 249u8, 43u8, 106u8, 195u8,
        218u8, 26u8, 49u8, 90u8, 236u8, 254u8, 65u8, 104u8, 254u8, 96u8, 128u8, 45u8, 178u8, 130u8,
        106u8, 88u8, 135u8, 106u8, 106u8, 88u8, 58u8, 195u8, 69u8, 41u8, 62u8, 44u8, 157u8, 87u8,
        181u8, 61u8, 225u8, 76u8, 171u8, 192u8, 111u8, 71u8, 123u8, 203u8, 231u8, 54u8, 22u8,
        164u8, 234u8, 194u8, 41u8, 65u8, 5u8, 225u8, 92u8, 149u8, 246u8, 255u8, 201u8, 98u8, 166u8,
        234u8, 187u8, 3u8, 99u8, 185u8, 255u8, 196u8, 1u8, 223u8, 16u8, 73u8, 120u8, 243u8, 98u8,
        203u8, 74u8, 240u8, 75u8, 25u8, 11u8, 18u8, 8u8, 110u8, 92u8, 32u8, 88u8, 38u8, 0u8, 55u8,
        198u8, 136u8, 120u8, 75u8, 76u8,
    ],
    vk_delta_g2: [
        32u8, 42u8, 241u8, 175u8, 151u8, 84u8, 152u8, 22u8, 124u8, 145u8, 111u8, 255u8, 119u8,
        173u8, 26u8, 131u8, 146u8, 161u8, 132u8, 88u8, 51u8, 60u8, 41u8, 12u8, 135u8, 139u8, 30u8,
        47u8, 92u8, 16u8, 136u8, 29u8, 23u8, 197u8, 14u8, 163u8, 138u8, 200u8, 108u8, 195u8, 166u8,
        245u8, 254u8, 189u8, 125u8, 192u8, 45u8, 22u8, 13u8, 4u8, 183u8, 128u8, 17u8, 55u8, 117u8,
        172u8, 6u8, 244u8, 110u8, 209u8, 93u8, 14u8, 245u8, 81u8, 38u8, 138u8, 109u8, 98u8, 200u8,
        49u8, 240u8, 124u8, 218u8, 198u8, 9u8, 77u8, 119u8, 40u8, 110u8, 42u8, 225u8, 176u8, 114u8,
        104u8, 197u8, 48u8, 247u8, 191u8, 189u8, 42u8, 75u8, 226u8, 104u8, 214u8, 81u8, 154u8,
        33u8, 60u8, 34u8, 109u8, 132u8, 14u8, 211u8, 151u8, 116u8, 151u8, 197u8, 146u8, 30u8,
        199u8, 238u8, 215u8, 158u8, 83u8, 38u8, 203u8, 170u8, 39u8, 177u8, 236u8, 220u8, 61u8,
        185u8, 107u8, 76u8, 16u8, 227u8, 72u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [239u8, 2u8, 164u8, 217u8, 134u8, 37u8, 133u8, 178u8, 43u8, 151u8, 149u8, 121u8, 22u8, 243u8, 3u8, 76u8, 196u8, 159u8, 182u8, 7u8, 143u8, 4u8, 221u8, 44u8, 7u8, 229u8, 123u8, 68u8, 50u8, 250u8, 202u8, 120u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_87551107565219aa")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00ef02a4d9862585b22b97957916f3034cc49fb6078f04dd2c07e57b4432faca78\x00=======END GROTH16 VK SETUP V1=======\x00";
