// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        39u8, 50u8, 100u8, 252u8, 185u8, 113u8, 249u8, 233u8, 192u8, 29u8, 45u8, 38u8, 45u8, 89u8,
        110u8, 67u8, 9u8, 85u8, 113u8, 83u8, 32u8, 63u8, 218u8, 213u8, 170u8, 120u8, 139u8, 1u8,
        95u8, 1u8, 242u8, 15u8, 36u8, 77u8, 15u8, 163u8, 68u8, 72u8, 228u8, 243u8, 214u8, 77u8,
        213u8, 152u8, 203u8, 66u8, 236u8, 172u8, 113u8, 255u8, 241u8, 171u8, 35u8, 153u8, 243u8,
        67u8, 69u8, 222u8, 62u8, 36u8, 178u8, 180u8, 25u8, 34u8,
    ],
    [
        38u8, 156u8, 172u8, 135u8, 171u8, 139u8, 57u8, 74u8, 44u8, 244u8, 140u8, 240u8, 57u8,
        189u8, 201u8, 2u8, 83u8, 177u8, 103u8, 121u8, 124u8, 148u8, 45u8, 193u8, 183u8, 145u8,
        57u8, 238u8, 20u8, 216u8, 70u8, 199u8, 16u8, 100u8, 161u8, 130u8, 60u8, 181u8, 197u8, 68u8,
        78u8, 211u8, 7u8, 186u8, 208u8, 56u8, 27u8, 147u8, 195u8, 54u8, 159u8, 215u8, 80u8, 38u8,
        13u8, 164u8, 78u8, 92u8, 194u8, 61u8, 81u8, 142u8, 41u8, 86u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        38u8, 101u8, 111u8, 72u8, 140u8, 28u8, 215u8, 101u8, 135u8, 67u8, 241u8, 18u8, 70u8, 238u8,
        90u8, 27u8, 102u8, 139u8, 219u8, 190u8, 73u8, 172u8, 168u8, 4u8, 148u8, 168u8, 238u8, 86u8,
        212u8, 245u8, 37u8, 211u8, 40u8, 173u8, 183u8, 99u8, 5u8, 200u8, 32u8, 239u8, 242u8, 49u8,
        196u8, 219u8, 128u8, 170u8, 63u8, 45u8, 35u8, 130u8, 149u8, 49u8, 85u8, 172u8, 111u8,
        124u8, 138u8, 12u8, 157u8, 2u8, 241u8, 110u8, 151u8, 67u8,
    ],
    vk_beta_g2: [
        1u8, 185u8, 55u8, 34u8, 15u8, 166u8, 5u8, 254u8, 56u8, 132u8, 199u8, 10u8, 194u8, 210u8,
        49u8, 120u8, 49u8, 91u8, 26u8, 168u8, 54u8, 206u8, 166u8, 66u8, 103u8, 196u8, 53u8, 107u8,
        226u8, 183u8, 242u8, 51u8, 14u8, 45u8, 216u8, 41u8, 117u8, 228u8, 107u8, 95u8, 124u8,
        212u8, 14u8, 82u8, 245u8, 213u8, 115u8, 107u8, 244u8, 225u8, 32u8, 114u8, 4u8, 48u8, 42u8,
        98u8, 144u8, 79u8, 94u8, 62u8, 116u8, 81u8, 70u8, 72u8, 25u8, 38u8, 1u8, 125u8, 113u8,
        225u8, 227u8, 55u8, 238u8, 46u8, 33u8, 157u8, 252u8, 232u8, 62u8, 15u8, 123u8, 39u8, 59u8,
        160u8, 106u8, 78u8, 253u8, 185u8, 197u8, 7u8, 97u8, 164u8, 148u8, 92u8, 125u8, 58u8, 25u8,
        193u8, 224u8, 71u8, 233u8, 87u8, 160u8, 189u8, 146u8, 130u8, 17u8, 252u8, 155u8, 131u8,
        78u8, 62u8, 136u8, 39u8, 248u8, 176u8, 230u8, 123u8, 66u8, 183u8, 197u8, 237u8, 95u8, 21u8,
        50u8, 8u8, 13u8, 68u8,
    ],
    vk_gamma_g2: [
        11u8, 98u8, 41u8, 57u8, 92u8, 176u8, 125u8, 48u8, 151u8, 3u8, 210u8, 17u8, 176u8, 171u8,
        207u8, 81u8, 105u8, 78u8, 14u8, 83u8, 190u8, 117u8, 154u8, 28u8, 181u8, 176u8, 139u8,
        252u8, 154u8, 147u8, 210u8, 228u8, 4u8, 60u8, 160u8, 244u8, 155u8, 137u8, 151u8, 30u8,
        91u8, 170u8, 169u8, 160u8, 36u8, 168u8, 83u8, 240u8, 96u8, 188u8, 61u8, 137u8, 216u8,
        212u8, 229u8, 156u8, 65u8, 116u8, 98u8, 60u8, 71u8, 11u8, 38u8, 103u8, 42u8, 191u8, 90u8,
        218u8, 179u8, 191u8, 208u8, 179u8, 39u8, 117u8, 177u8, 195u8, 204u8, 25u8, 231u8, 65u8,
        45u8, 15u8, 125u8, 52u8, 156u8, 194u8, 18u8, 181u8, 180u8, 222u8, 41u8, 29u8, 202u8, 61u8,
        166u8, 123u8, 21u8, 189u8, 70u8, 246u8, 236u8, 26u8, 0u8, 198u8, 34u8, 130u8, 204u8, 27u8,
        93u8, 129u8, 172u8, 125u8, 144u8, 235u8, 20u8, 225u8, 91u8, 9u8, 190u8, 123u8, 174u8,
        112u8, 40u8, 171u8, 16u8, 40u8, 193u8, 197u8,
    ],
    vk_delta_g2: [
        12u8, 108u8, 105u8, 209u8, 221u8, 33u8, 18u8, 37u8, 244u8, 65u8, 69u8, 45u8, 72u8, 127u8,
        202u8, 77u8, 45u8, 215u8, 178u8, 190u8, 167u8, 55u8, 0u8, 84u8, 226u8, 174u8, 63u8, 27u8,
        75u8, 254u8, 234u8, 101u8, 47u8, 191u8, 116u8, 157u8, 118u8, 21u8, 86u8, 239u8, 112u8,
        241u8, 219u8, 72u8, 229u8, 147u8, 3u8, 21u8, 93u8, 186u8, 196u8, 120u8, 65u8, 145u8, 243u8,
        216u8, 88u8, 210u8, 73u8, 92u8, 57u8, 43u8, 133u8, 58u8, 27u8, 131u8, 86u8, 55u8, 22u8,
        91u8, 167u8, 59u8, 19u8, 107u8, 217u8, 26u8, 150u8, 72u8, 64u8, 104u8, 227u8, 142u8, 64u8,
        158u8, 57u8, 91u8, 12u8, 38u8, 200u8, 119u8, 126u8, 58u8, 25u8, 23u8, 231u8, 126u8, 29u8,
        18u8, 154u8, 138u8, 96u8, 239u8, 243u8, 45u8, 82u8, 228u8, 131u8, 17u8, 69u8, 194u8, 5u8,
        181u8, 157u8, 100u8, 237u8, 183u8, 249u8, 183u8, 200u8, 117u8, 42u8, 140u8, 80u8, 64u8,
        229u8, 89u8, 215u8, 95u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [216u8, 5u8, 40u8, 36u8, 161u8, 99u8, 212u8, 29u8, 223u8, 133u8, 64u8, 188u8, 114u8, 219u8, 254u8, 148u8, 181u8, 197u8, 43u8, 226u8, 27u8, 106u8, 15u8, 48u8, 57u8, 178u8, 240u8, 31u8, 115u8, 128u8, 100u8, 31u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_44cdf57685bcca40")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00d8052824a163d41ddf8540bc72dbfe94b5c52be21b6a0f3039b2f01f7380641f\x00=======END GROTH16 VK SETUP V1=======\x00";
