// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        30u8, 36u8, 72u8, 47u8, 227u8, 192u8, 162u8, 154u8, 170u8, 63u8, 33u8, 127u8, 226u8, 58u8,
        96u8, 94u8, 244u8, 32u8, 124u8, 232u8, 243u8, 215u8, 1u8, 104u8, 28u8, 25u8, 31u8, 95u8,
        131u8, 112u8, 160u8, 131u8, 22u8, 127u8, 199u8, 58u8, 1u8, 8u8, 226u8, 14u8, 184u8, 73u8,
        204u8, 80u8, 125u8, 52u8, 233u8, 238u8, 98u8, 237u8, 141u8, 147u8, 248u8, 70u8, 241u8,
        232u8, 148u8, 193u8, 49u8, 49u8, 184u8, 236u8, 72u8, 30u8,
    ],
    [
        28u8, 70u8, 204u8, 8u8, 76u8, 222u8, 65u8, 56u8, 216u8, 232u8, 158u8, 7u8, 85u8, 56u8,
        211u8, 255u8, 191u8, 72u8, 101u8, 113u8, 69u8, 187u8, 162u8, 52u8, 125u8, 1u8, 163u8, 93u8,
        251u8, 181u8, 8u8, 255u8, 35u8, 115u8, 138u8, 208u8, 212u8, 102u8, 158u8, 218u8, 233u8,
        156u8, 7u8, 255u8, 221u8, 138u8, 254u8, 73u8, 175u8, 205u8, 35u8, 112u8, 111u8, 27u8,
        253u8, 66u8, 237u8, 48u8, 116u8, 37u8, 130u8, 3u8, 184u8, 233u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        33u8, 217u8, 255u8, 241u8, 62u8, 191u8, 72u8, 15u8, 150u8, 247u8, 253u8, 114u8, 129u8,
        136u8, 115u8, 69u8, 61u8, 5u8, 221u8, 246u8, 242u8, 39u8, 192u8, 224u8, 194u8, 49u8, 246u8,
        178u8, 251u8, 49u8, 163u8, 92u8, 14u8, 105u8, 118u8, 207u8, 143u8, 204u8, 221u8, 220u8,
        155u8, 22u8, 204u8, 9u8, 200u8, 29u8, 109u8, 104u8, 120u8, 217u8, 79u8, 17u8, 97u8, 117u8,
        80u8, 7u8, 170u8, 0u8, 59u8, 206u8, 214u8, 250u8, 179u8, 117u8,
    ],
    vk_beta_g2: [
        48u8, 64u8, 25u8, 95u8, 68u8, 212u8, 93u8, 29u8, 95u8, 49u8, 74u8, 77u8, 165u8, 32u8,
        203u8, 92u8, 229u8, 177u8, 169u8, 134u8, 109u8, 198u8, 159u8, 185u8, 80u8, 172u8, 223u8,
        56u8, 250u8, 62u8, 151u8, 11u8, 1u8, 238u8, 66u8, 42u8, 50u8, 234u8, 217u8, 4u8, 25u8,
        167u8, 66u8, 122u8, 125u8, 81u8, 227u8, 116u8, 73u8, 175u8, 3u8, 215u8, 112u8, 165u8, 38u8,
        72u8, 239u8, 200u8, 17u8, 39u8, 231u8, 126u8, 242u8, 162u8, 31u8, 202u8, 98u8, 239u8, 0u8,
        65u8, 25u8, 229u8, 170u8, 129u8, 51u8, 155u8, 74u8, 207u8, 163u8, 81u8, 94u8, 98u8, 225u8,
        224u8, 67u8, 223u8, 169u8, 36u8, 5u8, 233u8, 180u8, 53u8, 88u8, 160u8, 97u8, 161u8, 14u8,
        103u8, 205u8, 60u8, 61u8, 74u8, 60u8, 139u8, 54u8, 25u8, 59u8, 95u8, 180u8, 134u8, 136u8,
        119u8, 147u8, 217u8, 68u8, 33u8, 240u8, 41u8, 166u8, 193u8, 216u8, 112u8, 214u8, 78u8,
        113u8, 206u8, 252u8, 213u8,
    ],
    vk_gamma_g2: [
        33u8, 44u8, 149u8, 67u8, 38u8, 13u8, 202u8, 38u8, 109u8, 232u8, 117u8, 145u8, 225u8, 176u8,
        35u8, 130u8, 43u8, 49u8, 236u8, 250u8, 36u8, 130u8, 235u8, 193u8, 64u8, 28u8, 103u8, 209u8,
        84u8, 65u8, 67u8, 129u8, 11u8, 176u8, 76u8, 242u8, 73u8, 40u8, 193u8, 187u8, 184u8, 85u8,
        173u8, 203u8, 188u8, 178u8, 131u8, 36u8, 238u8, 116u8, 110u8, 248u8, 162u8, 155u8, 186u8,
        14u8, 255u8, 135u8, 164u8, 193u8, 17u8, 169u8, 203u8, 122u8, 22u8, 128u8, 254u8, 176u8,
        211u8, 237u8, 186u8, 87u8, 60u8, 221u8, 70u8, 90u8, 44u8, 188u8, 88u8, 214u8, 7u8, 222u8,
        62u8, 148u8, 65u8, 146u8, 189u8, 238u8, 65u8, 183u8, 100u8, 194u8, 106u8, 104u8, 214u8,
        191u8, 14u8, 131u8, 196u8, 110u8, 186u8, 251u8, 50u8, 190u8, 239u8, 196u8, 92u8, 218u8,
        114u8, 50u8, 90u8, 70u8, 129u8, 37u8, 88u8, 254u8, 21u8, 215u8, 53u8, 147u8, 169u8, 122u8,
        245u8, 62u8, 55u8, 177u8, 91u8, 177u8,
    ],
    vk_delta_g2: [
        8u8, 115u8, 200u8, 185u8, 230u8, 10u8, 140u8, 178u8, 39u8, 19u8, 213u8, 150u8, 26u8, 55u8,
        244u8, 77u8, 76u8, 244u8, 243u8, 31u8, 217u8, 4u8, 6u8, 116u8, 206u8, 167u8, 67u8, 95u8,
        201u8, 150u8, 0u8, 76u8, 20u8, 127u8, 229u8, 149u8, 156u8, 223u8, 180u8, 249u8, 253u8, 6u8,
        47u8, 20u8, 160u8, 1u8, 220u8, 90u8, 167u8, 241u8, 161u8, 117u8, 252u8, 3u8, 55u8, 247u8,
        126u8, 121u8, 213u8, 38u8, 231u8, 178u8, 213u8, 26u8, 30u8, 59u8, 203u8, 83u8, 200u8,
        202u8, 254u8, 208u8, 77u8, 97u8, 77u8, 37u8, 79u8, 117u8, 24u8, 19u8, 245u8, 101u8, 114u8,
        160u8, 111u8, 244u8, 131u8, 151u8, 10u8, 202u8, 31u8, 153u8, 221u8, 218u8, 221u8, 179u8,
        18u8, 160u8, 51u8, 50u8, 127u8, 95u8, 19u8, 83u8, 111u8, 185u8, 97u8, 190u8, 232u8, 193u8,
        221u8, 190u8, 161u8, 248u8, 171u8, 244u8, 140u8, 64u8, 211u8, 195u8, 122u8, 0u8, 40u8,
        42u8, 94u8, 160u8, 182u8, 79u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [247u8, 158u8, 68u8, 229u8, 149u8, 19u8, 161u8, 38u8, 154u8, 101u8, 34u8, 223u8, 14u8, 52u8, 8u8, 250u8, 17u8, 127u8, 132u8, 204u8, 174u8, 59u8, 252u8, 212u8, 66u8, 8u8, 175u8, 27u8, 127u8, 2u8, 42u8, 195u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_e46b18667dccfb04")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00f79e44e59513a1269a6522df0e3408fa117f84ccae3bfcd44208af1b7f022ac3\x00=======END GROTH16 VK SETUP V1=======\x00";
