// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        13u8, 51u8, 66u8, 101u8, 179u8, 204u8, 130u8, 10u8, 13u8, 157u8, 255u8, 157u8, 249u8,
        146u8, 112u8, 44u8, 43u8, 74u8, 33u8, 143u8, 134u8, 130u8, 232u8, 194u8, 11u8, 44u8, 250u8,
        143u8, 13u8, 71u8, 16u8, 108u8, 42u8, 78u8, 83u8, 172u8, 172u8, 2u8, 234u8, 86u8, 154u8,
        57u8, 206u8, 233u8, 135u8, 0u8, 107u8, 40u8, 21u8, 60u8, 239u8, 122u8, 205u8, 27u8, 44u8,
        120u8, 133u8, 25u8, 115u8, 177u8, 190u8, 241u8, 221u8, 163u8,
    ],
    [
        15u8, 98u8, 10u8, 234u8, 47u8, 239u8, 229u8, 28u8, 99u8, 138u8, 124u8, 129u8, 187u8, 109u8,
        2u8, 239u8, 191u8, 46u8, 23u8, 63u8, 20u8, 237u8, 202u8, 166u8, 226u8, 210u8, 56u8, 234u8,
        139u8, 0u8, 231u8, 2u8, 35u8, 39u8, 237u8, 24u8, 237u8, 28u8, 198u8, 250u8, 254u8, 49u8,
        147u8, 42u8, 232u8, 240u8, 76u8, 255u8, 125u8, 208u8, 96u8, 206u8, 122u8, 107u8, 165u8,
        216u8, 149u8, 175u8, 58u8, 33u8, 251u8, 64u8, 253u8, 247u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        19u8, 13u8, 81u8, 120u8, 26u8, 224u8, 211u8, 195u8, 78u8, 3u8, 78u8, 35u8, 194u8, 162u8,
        162u8, 113u8, 180u8, 213u8, 192u8, 84u8, 219u8, 168u8, 56u8, 152u8, 184u8, 125u8, 27u8,
        89u8, 58u8, 224u8, 6u8, 164u8, 28u8, 138u8, 98u8, 68u8, 99u8, 80u8, 221u8, 75u8, 18u8,
        63u8, 177u8, 140u8, 181u8, 131u8, 171u8, 20u8, 222u8, 225u8, 171u8, 136u8, 51u8, 214u8,
        21u8, 210u8, 174u8, 82u8, 197u8, 64u8, 189u8, 233u8, 130u8, 34u8,
    ],
    vk_beta_g2: [
        16u8, 178u8, 165u8, 82u8, 218u8, 89u8, 159u8, 52u8, 179u8, 52u8, 118u8, 11u8, 149u8, 131u8,
        29u8, 230u8, 120u8, 103u8, 244u8, 81u8, 112u8, 72u8, 64u8, 43u8, 110u8, 127u8, 83u8, 139u8,
        173u8, 156u8, 34u8, 78u8, 0u8, 139u8, 88u8, 164u8, 223u8, 115u8, 33u8, 66u8, 125u8, 141u8,
        64u8, 162u8, 165u8, 160u8, 186u8, 56u8, 197u8, 203u8, 217u8, 132u8, 182u8, 111u8, 228u8,
        154u8, 192u8, 152u8, 168u8, 31u8, 158u8, 8u8, 168u8, 46u8, 8u8, 114u8, 41u8, 108u8, 183u8,
        183u8, 197u8, 83u8, 201u8, 33u8, 101u8, 209u8, 77u8, 114u8, 68u8, 52u8, 127u8, 140u8,
        130u8, 246u8, 237u8, 179u8, 194u8, 210u8, 26u8, 90u8, 130u8, 32u8, 111u8, 137u8, 196u8,
        230u8, 2u8, 197u8, 244u8, 52u8, 77u8, 31u8, 13u8, 198u8, 157u8, 242u8, 96u8, 101u8, 165u8,
        6u8, 114u8, 6u8, 120u8, 162u8, 7u8, 203u8, 239u8, 102u8, 130u8, 55u8, 231u8, 234u8, 215u8,
        162u8, 14u8, 87u8, 153u8, 204u8,
    ],
    vk_gamma_g2: [
        34u8, 54u8, 105u8, 160u8, 53u8, 66u8, 43u8, 182u8, 148u8, 199u8, 174u8, 231u8, 192u8,
        143u8, 152u8, 165u8, 232u8, 160u8, 214u8, 144u8, 139u8, 156u8, 142u8, 192u8, 64u8, 226u8,
        120u8, 83u8, 31u8, 73u8, 30u8, 78u8, 29u8, 187u8, 139u8, 121u8, 7u8, 43u8, 129u8, 70u8,
        160u8, 254u8, 242u8, 225u8, 66u8, 113u8, 59u8, 41u8, 126u8, 135u8, 63u8, 36u8, 211u8,
        222u8, 117u8, 182u8, 135u8, 36u8, 245u8, 14u8, 130u8, 218u8, 178u8, 11u8, 11u8, 197u8,
        136u8, 139u8, 185u8, 124u8, 102u8, 184u8, 204u8, 142u8, 130u8, 202u8, 237u8, 148u8, 87u8,
        150u8, 197u8, 197u8, 84u8, 99u8, 184u8, 39u8, 39u8, 60u8, 248u8, 111u8, 202u8, 13u8, 110u8,
        28u8, 143u8, 136u8, 43u8, 21u8, 10u8, 19u8, 73u8, 101u8, 94u8, 161u8, 28u8, 39u8, 15u8,
        176u8, 170u8, 149u8, 180u8, 216u8, 53u8, 37u8, 114u8, 104u8, 134u8, 159u8, 181u8, 128u8,
        230u8, 16u8, 233u8, 5u8, 187u8, 130u8, 92u8, 84u8,
    ],
    vk_delta_g2: [
        5u8, 37u8, 92u8, 149u8, 58u8, 32u8, 205u8, 4u8, 91u8, 131u8, 26u8, 216u8, 231u8, 159u8,
        51u8, 69u8, 171u8, 139u8, 52u8, 197u8, 161u8, 79u8, 64u8, 238u8, 186u8, 170u8, 183u8, 15u8,
        51u8, 191u8, 178u8, 79u8, 3u8, 216u8, 12u8, 217u8, 213u8, 50u8, 248u8, 237u8, 104u8, 236u8,
        183u8, 85u8, 87u8, 54u8, 252u8, 149u8, 101u8, 8u8, 95u8, 42u8, 175u8, 6u8, 95u8, 55u8,
        242u8, 30u8, 178u8, 19u8, 125u8, 37u8, 132u8, 66u8, 16u8, 12u8, 249u8, 124u8, 66u8, 246u8,
        62u8, 189u8, 117u8, 187u8, 126u8, 240u8, 166u8, 94u8, 5u8, 43u8, 205u8, 74u8, 124u8, 32u8,
        247u8, 97u8, 123u8, 23u8, 114u8, 52u8, 39u8, 90u8, 165u8, 84u8, 218u8, 65u8, 35u8, 183u8,
        3u8, 209u8, 66u8, 127u8, 52u8, 60u8, 247u8, 105u8, 218u8, 63u8, 225u8, 194u8, 85u8, 61u8,
        193u8, 102u8, 137u8, 158u8, 213u8, 165u8, 234u8, 122u8, 56u8, 2u8, 217u8, 201u8, 2u8,
        207u8, 133u8, 1u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [191u8, 228u8, 245u8, 214u8, 101u8, 43u8, 214u8, 100u8, 48u8, 219u8, 150u8, 171u8, 144u8, 106u8, 68u8, 69u8, 111u8, 169u8, 34u8, 63u8, 207u8, 119u8, 90u8, 183u8, 231u8, 126u8, 141u8, 173u8, 180u8, 25u8, 204u8, 74u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_e0600b87b09f2040")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00bfe4f5d6652bd66430db96ab906a44456fa9223fcf775ab7e77e8dadb419cc4a\x00=======END GROTH16 VK SETUP V1=======\x00";
