// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        19u8, 220u8, 237u8, 145u8, 29u8, 239u8, 232u8, 131u8, 221u8, 22u8, 150u8, 210u8, 240u8,
        38u8, 4u8, 228u8, 189u8, 222u8, 60u8, 112u8, 174u8, 246u8, 71u8, 188u8, 157u8, 179u8,
        125u8, 92u8, 182u8, 26u8, 188u8, 8u8, 7u8, 38u8, 20u8, 7u8, 63u8, 42u8, 124u8, 0u8, 117u8,
        39u8, 132u8, 239u8, 141u8, 72u8, 156u8, 245u8, 67u8, 93u8, 219u8, 215u8, 69u8, 85u8, 43u8,
        144u8, 117u8, 210u8, 167u8, 198u8, 107u8, 65u8, 75u8, 188u8,
    ],
    [
        23u8, 184u8, 116u8, 145u8, 143u8, 124u8, 145u8, 251u8, 253u8, 83u8, 105u8, 148u8, 53u8,
        90u8, 210u8, 202u8, 98u8, 22u8, 109u8, 190u8, 55u8, 147u8, 40u8, 71u8, 66u8, 85u8, 20u8,
        116u8, 182u8, 237u8, 207u8, 254u8, 21u8, 211u8, 22u8, 22u8, 193u8, 108u8, 145u8, 201u8,
        214u8, 241u8, 34u8, 4u8, 101u8, 0u8, 236u8, 216u8, 53u8, 140u8, 45u8, 201u8, 151u8, 195u8,
        143u8, 104u8, 254u8, 174u8, 1u8, 84u8, 207u8, 146u8, 94u8, 248u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        35u8, 33u8, 21u8, 213u8, 17u8, 136u8, 64u8, 149u8, 140u8, 243u8, 4u8, 72u8, 48u8, 184u8,
        229u8, 4u8, 112u8, 240u8, 145u8, 128u8, 138u8, 243u8, 191u8, 95u8, 206u8, 64u8, 176u8,
        150u8, 29u8, 211u8, 230u8, 58u8, 43u8, 199u8, 188u8, 129u8, 43u8, 226u8, 43u8, 24u8, 126u8,
        185u8, 197u8, 66u8, 250u8, 8u8, 46u8, 8u8, 19u8, 152u8, 74u8, 29u8, 180u8, 33u8, 28u8,
        83u8, 106u8, 170u8, 83u8, 27u8, 94u8, 53u8, 144u8, 50u8,
    ],
    vk_beta_g2: [
        31u8, 173u8, 12u8, 170u8, 57u8, 7u8, 190u8, 81u8, 26u8, 165u8, 158u8, 158u8, 7u8, 82u8,
        145u8, 148u8, 106u8, 71u8, 78u8, 121u8, 129u8, 218u8, 9u8, 220u8, 212u8, 180u8, 18u8, 69u8,
        116u8, 180u8, 28u8, 190u8, 45u8, 40u8, 144u8, 127u8, 239u8, 198u8, 105u8, 23u8, 117u8,
        68u8, 134u8, 248u8, 87u8, 40u8, 98u8, 134u8, 156u8, 176u8, 95u8, 131u8, 52u8, 26u8, 158u8,
        78u8, 195u8, 115u8, 154u8, 59u8, 70u8, 203u8, 151u8, 88u8, 43u8, 15u8, 103u8, 138u8, 130u8,
        109u8, 70u8, 184u8, 219u8, 224u8, 30u8, 208u8, 222u8, 253u8, 166u8, 213u8, 97u8, 83u8,
        163u8, 224u8, 176u8, 144u8, 36u8, 60u8, 235u8, 20u8, 5u8, 49u8, 28u8, 4u8, 97u8, 101u8,
        11u8, 192u8, 100u8, 108u8, 137u8, 203u8, 168u8, 231u8, 251u8, 8u8, 76u8, 29u8, 238u8, 71u8,
        208u8, 161u8, 152u8, 81u8, 42u8, 60u8, 213u8, 19u8, 32u8, 11u8, 120u8, 41u8, 33u8, 111u8,
        172u8, 186u8, 201u8, 173u8,
    ],
    vk_gamma_g2: [
        17u8, 25u8, 221u8, 198u8, 136u8, 54u8, 102u8, 166u8, 58u8, 107u8, 104u8, 82u8, 109u8,
        129u8, 192u8, 222u8, 33u8, 64u8, 222u8, 43u8, 228u8, 20u8, 214u8, 7u8, 41u8, 199u8, 72u8,
        69u8, 97u8, 130u8, 206u8, 138u8, 42u8, 250u8, 214u8, 200u8, 138u8, 27u8, 145u8, 165u8,
        141u8, 188u8, 24u8, 61u8, 0u8, 53u8, 234u8, 239u8, 176u8, 246u8, 13u8, 14u8, 79u8, 93u8,
        250u8, 172u8, 109u8, 232u8, 158u8, 202u8, 135u8, 211u8, 14u8, 149u8, 29u8, 174u8, 119u8,
        185u8, 100u8, 126u8, 196u8, 137u8, 118u8, 217u8, 113u8, 227u8, 19u8, 170u8, 129u8, 105u8,
        46u8, 179u8, 161u8, 175u8, 42u8, 45u8, 220u8, 139u8, 47u8, 104u8, 134u8, 189u8, 159u8,
        28u8, 33u8, 134u8, 6u8, 89u8, 110u8, 129u8, 56u8, 175u8, 234u8, 178u8, 154u8, 2u8, 186u8,
        94u8, 168u8, 140u8, 172u8, 225u8, 69u8, 172u8, 134u8, 126u8, 109u8, 188u8, 2u8, 110u8,
        194u8, 29u8, 7u8, 215u8, 211u8, 213u8, 124u8, 61u8,
    ],
    vk_delta_g2: [
        7u8, 8u8, 53u8, 140u8, 146u8, 77u8, 168u8, 156u8, 3u8, 166u8, 13u8, 235u8, 181u8, 88u8,
        223u8, 156u8, 189u8, 45u8, 188u8, 171u8, 159u8, 222u8, 50u8, 112u8, 240u8, 178u8, 94u8,
        31u8, 40u8, 199u8, 213u8, 80u8, 43u8, 57u8, 209u8, 157u8, 219u8, 174u8, 76u8, 0u8, 54u8,
        147u8, 72u8, 254u8, 89u8, 40u8, 224u8, 216u8, 137u8, 225u8, 107u8, 74u8, 174u8, 59u8, 27u8,
        210u8, 234u8, 121u8, 213u8, 225u8, 163u8, 236u8, 144u8, 71u8, 44u8, 210u8, 24u8, 127u8,
        52u8, 70u8, 16u8, 131u8, 13u8, 46u8, 235u8, 77u8, 167u8, 193u8, 98u8, 206u8, 58u8, 151u8,
        8u8, 121u8, 213u8, 27u8, 89u8, 176u8, 181u8, 191u8, 111u8, 182u8, 210u8, 124u8, 91u8,
        128u8, 28u8, 11u8, 29u8, 217u8, 131u8, 85u8, 37u8, 36u8, 53u8, 180u8, 54u8, 237u8, 9u8,
        108u8, 71u8, 209u8, 236u8, 192u8, 39u8, 248u8, 51u8, 130u8, 87u8, 235u8, 248u8, 146u8,
        203u8, 65u8, 248u8, 121u8, 63u8, 56u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [58u8, 77u8, 104u8, 126u8, 172u8, 244u8, 52u8, 20u8, 65u8, 149u8, 221u8, 94u8, 141u8, 25u8, 122u8, 174u8, 44u8, 207u8, 106u8, 47u8, 240u8, 30u8, 227u8, 140u8, 35u8, 212u8, 197u8, 222u8, 16u8, 199u8, 145u8, 40u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_2e6e80649f161463")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x003a4d687eacf434144195dd5e8d197aae2ccf6a2ff01ee38c23d4c5de10c79128\x00=======END GROTH16 VK SETUP V1=======\x00";
