// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        25u8, 88u8, 118u8, 224u8, 126u8, 200u8, 219u8, 164u8, 62u8, 230u8, 211u8, 171u8, 227u8,
        158u8, 139u8, 206u8, 93u8, 87u8, 32u8, 113u8, 26u8, 171u8, 174u8, 217u8, 248u8, 134u8,
        102u8, 100u8, 86u8, 21u8, 155u8, 88u8, 33u8, 115u8, 216u8, 188u8, 209u8, 132u8, 43u8,
        198u8, 76u8, 99u8, 225u8, 73u8, 168u8, 7u8, 205u8, 243u8, 97u8, 247u8, 94u8, 119u8, 208u8,
        65u8, 32u8, 5u8, 185u8, 129u8, 23u8, 147u8, 231u8, 70u8, 251u8, 208u8,
    ],
    [
        47u8, 160u8, 149u8, 221u8, 229u8, 30u8, 25u8, 35u8, 173u8, 219u8, 66u8, 107u8, 106u8,
        244u8, 31u8, 221u8, 41u8, 236u8, 212u8, 172u8, 111u8, 229u8, 17u8, 192u8, 153u8, 105u8,
        135u8, 21u8, 199u8, 230u8, 115u8, 220u8, 7u8, 162u8, 179u8, 77u8, 123u8, 132u8, 212u8,
        80u8, 161u8, 216u8, 16u8, 94u8, 29u8, 11u8, 168u8, 219u8, 10u8, 181u8, 50u8, 156u8, 52u8,
        34u8, 152u8, 171u8, 130u8, 182u8, 110u8, 72u8, 238u8, 142u8, 237u8, 148u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        41u8, 192u8, 199u8, 90u8, 118u8, 53u8, 143u8, 32u8, 74u8, 186u8, 248u8, 173u8, 155u8, 62u8,
        150u8, 71u8, 104u8, 10u8, 186u8, 255u8, 87u8, 162u8, 26u8, 182u8, 175u8, 53u8, 236u8,
        225u8, 42u8, 0u8, 70u8, 68u8, 29u8, 86u8, 25u8, 249u8, 178u8, 36u8, 207u8, 117u8, 161u8,
        239u8, 78u8, 134u8, 32u8, 157u8, 173u8, 231u8, 176u8, 55u8, 193u8, 145u8, 74u8, 73u8,
        198u8, 134u8, 44u8, 85u8, 208u8, 227u8, 216u8, 205u8, 92u8, 242u8,
    ],
    vk_beta_g2: [
        4u8, 28u8, 109u8, 170u8, 173u8, 131u8, 223u8, 120u8, 213u8, 176u8, 78u8, 95u8, 231u8,
        161u8, 29u8, 137u8, 116u8, 187u8, 24u8, 208u8, 61u8, 174u8, 131u8, 175u8, 251u8, 165u8,
        204u8, 133u8, 205u8, 207u8, 78u8, 176u8, 2u8, 136u8, 94u8, 172u8, 143u8, 66u8, 39u8, 49u8,
        152u8, 194u8, 248u8, 25u8, 209u8, 228u8, 242u8, 58u8, 186u8, 218u8, 67u8, 108u8, 76u8,
        78u8, 140u8, 83u8, 149u8, 2u8, 20u8, 211u8, 188u8, 222u8, 205u8, 90u8, 3u8, 200u8, 159u8,
        119u8, 161u8, 173u8, 134u8, 255u8, 69u8, 116u8, 35u8, 223u8, 200u8, 208u8, 205u8, 86u8,
        88u8, 252u8, 48u8, 31u8, 4u8, 235u8, 15u8, 153u8, 97u8, 84u8, 165u8, 170u8, 157u8, 41u8,
        252u8, 210u8, 37u8, 115u8, 170u8, 224u8, 54u8, 216u8, 33u8, 244u8, 189u8, 6u8, 38u8, 29u8,
        217u8, 142u8, 211u8, 132u8, 36u8, 210u8, 46u8, 149u8, 87u8, 194u8, 138u8, 120u8, 137u8,
        231u8, 124u8, 59u8, 174u8, 206u8, 151u8, 146u8,
    ],
    vk_gamma_g2: [
        36u8, 90u8, 38u8, 107u8, 36u8, 209u8, 36u8, 250u8, 167u8, 90u8, 166u8, 238u8, 195u8, 203u8,
        212u8, 165u8, 233u8, 134u8, 245u8, 5u8, 182u8, 188u8, 136u8, 32u8, 119u8, 147u8, 23u8,
        194u8, 213u8, 128u8, 54u8, 221u8, 37u8, 110u8, 174u8, 126u8, 121u8, 157u8, 4u8, 99u8,
        231u8, 52u8, 178u8, 84u8, 25u8, 20u8, 57u8, 202u8, 70u8, 27u8, 22u8, 58u8, 22u8, 22u8,
        229u8, 191u8, 131u8, 128u8, 212u8, 26u8, 136u8, 25u8, 168u8, 36u8, 11u8, 121u8, 84u8,
        154u8, 223u8, 75u8, 102u8, 148u8, 46u8, 79u8, 162u8, 41u8, 108u8, 146u8, 233u8, 50u8,
        223u8, 230u8, 142u8, 97u8, 59u8, 36u8, 166u8, 143u8, 119u8, 175u8, 165u8, 231u8, 119u8,
        203u8, 147u8, 205u8, 35u8, 71u8, 155u8, 230u8, 240u8, 208u8, 183u8, 57u8, 164u8, 96u8,
        230u8, 152u8, 107u8, 66u8, 77u8, 201u8, 232u8, 164u8, 74u8, 188u8, 212u8, 60u8, 177u8,
        92u8, 116u8, 108u8, 4u8, 120u8, 106u8, 86u8, 39u8, 12u8,
    ],
    vk_delta_g2: [
        1u8, 57u8, 22u8, 40u8, 22u8, 77u8, 51u8, 53u8, 89u8, 116u8, 65u8, 187u8, 219u8, 133u8,
        208u8, 62u8, 43u8, 83u8, 175u8, 54u8, 129u8, 254u8, 135u8, 144u8, 245u8, 206u8, 186u8,
        31u8, 16u8, 15u8, 97u8, 219u8, 3u8, 24u8, 26u8, 39u8, 237u8, 124u8, 216u8, 250u8, 161u8,
        49u8, 204u8, 127u8, 105u8, 85u8, 113u8, 192u8, 146u8, 22u8, 208u8, 195u8, 210u8, 77u8,
        246u8, 223u8, 78u8, 179u8, 154u8, 122u8, 209u8, 90u8, 242u8, 113u8, 33u8, 148u8, 62u8,
        213u8, 24u8, 86u8, 44u8, 59u8, 140u8, 58u8, 21u8, 235u8, 81u8, 108u8, 238u8, 39u8, 179u8,
        240u8, 53u8, 223u8, 111u8, 52u8, 120u8, 4u8, 131u8, 39u8, 95u8, 218u8, 224u8, 65u8, 13u8,
        29u8, 32u8, 71u8, 68u8, 247u8, 111u8, 168u8, 127u8, 176u8, 131u8, 103u8, 132u8, 31u8, 12u8,
        211u8, 187u8, 125u8, 134u8, 211u8, 134u8, 18u8, 216u8, 132u8, 160u8, 94u8, 59u8, 46u8,
        106u8, 106u8, 239u8, 2u8, 169u8, 114u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [83u8, 7u8, 121u8, 21u8, 83u8, 64u8, 160u8, 92u8, 189u8, 144u8, 222u8, 220u8, 94u8, 148u8, 197u8, 150u8, 12u8, 245u8, 16u8, 95u8, 40u8, 102u8, 189u8, 176u8, 65u8, 227u8, 165u8, 109u8, 6u8, 201u8, 187u8, 139u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_17acd48767f54b31")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00530779155340a05cbd90dedc5e94c5960cf5105f2866bdb041e3a56d06c9bb8b\x00=======END GROTH16 VK SETUP V1=======\x00";
