// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        13u8, 46u8, 76u8, 95u8, 230u8, 17u8, 186u8, 216u8, 70u8, 249u8, 159u8, 198u8, 214u8, 183u8,
        106u8, 105u8, 50u8, 133u8, 153u8, 211u8, 15u8, 111u8, 240u8, 226u8, 224u8, 44u8, 44u8,
        23u8, 35u8, 77u8, 68u8, 12u8, 24u8, 6u8, 18u8, 146u8, 59u8, 32u8, 31u8, 237u8, 11u8, 39u8,
        132u8, 88u8, 68u8, 89u8, 58u8, 73u8, 141u8, 159u8, 140u8, 145u8, 28u8, 226u8, 46u8, 159u8,
        145u8, 194u8, 143u8, 105u8, 78u8, 29u8, 4u8, 168u8,
    ],
    [
        6u8, 205u8, 72u8, 41u8, 18u8, 232u8, 191u8, 124u8, 237u8, 243u8, 92u8, 111u8, 20u8, 80u8,
        133u8, 33u8, 99u8, 202u8, 59u8, 106u8, 162u8, 67u8, 152u8, 143u8, 153u8, 57u8, 5u8, 13u8,
        18u8, 27u8, 3u8, 37u8, 45u8, 251u8, 117u8, 94u8, 208u8, 66u8, 48u8, 43u8, 104u8, 95u8,
        183u8, 250u8, 169u8, 238u8, 204u8, 231u8, 149u8, 126u8, 176u8, 143u8, 81u8, 36u8, 243u8,
        14u8, 178u8, 1u8, 169u8, 58u8, 80u8, 255u8, 82u8, 191u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        4u8, 243u8, 14u8, 87u8, 55u8, 106u8, 11u8, 253u8, 117u8, 103u8, 22u8, 195u8, 255u8, 59u8,
        105u8, 136u8, 250u8, 11u8, 88u8, 116u8, 186u8, 162u8, 124u8, 210u8, 209u8, 151u8, 9u8,
        133u8, 124u8, 141u8, 69u8, 130u8, 46u8, 196u8, 232u8, 125u8, 62u8, 53u8, 127u8, 134u8,
        208u8, 229u8, 143u8, 54u8, 191u8, 96u8, 23u8, 67u8, 162u8, 249u8, 149u8, 0u8, 54u8, 149u8,
        200u8, 55u8, 248u8, 35u8, 110u8, 79u8, 102u8, 66u8, 95u8, 236u8,
    ],
    vk_beta_g2: [
        20u8, 201u8, 5u8, 252u8, 215u8, 153u8, 194u8, 93u8, 66u8, 247u8, 36u8, 155u8, 158u8, 234u8,
        99u8, 159u8, 57u8, 44u8, 208u8, 121u8, 27u8, 24u8, 17u8, 122u8, 244u8, 86u8, 147u8, 236u8,
        181u8, 155u8, 87u8, 129u8, 47u8, 85u8, 40u8, 253u8, 189u8, 80u8, 124u8, 78u8, 246u8, 211u8,
        170u8, 48u8, 132u8, 48u8, 112u8, 120u8, 178u8, 126u8, 237u8, 178u8, 70u8, 153u8, 144u8,
        144u8, 121u8, 47u8, 59u8, 160u8, 242u8, 0u8, 247u8, 138u8, 27u8, 22u8, 148u8, 174u8, 145u8,
        191u8, 99u8, 61u8, 172u8, 138u8, 74u8, 133u8, 136u8, 94u8, 171u8, 186u8, 19u8, 215u8, 72u8,
        72u8, 192u8, 148u8, 133u8, 95u8, 255u8, 1u8, 5u8, 51u8, 38u8, 254u8, 129u8, 115u8, 41u8,
        243u8, 49u8, 109u8, 174u8, 238u8, 221u8, 126u8, 221u8, 112u8, 48u8, 21u8, 147u8, 119u8,
        94u8, 47u8, 130u8, 182u8, 146u8, 185u8, 213u8, 85u8, 108u8, 86u8, 73u8, 32u8, 0u8, 71u8,
        34u8, 243u8, 131u8, 255u8,
    ],
    vk_gamma_g2: [
        25u8, 132u8, 77u8, 155u8, 19u8, 161u8, 122u8, 238u8, 185u8, 10u8, 244u8, 75u8, 11u8, 5u8,
        213u8, 175u8, 251u8, 13u8, 150u8, 178u8, 224u8, 210u8, 130u8, 189u8, 181u8, 190u8, 44u8,
        216u8, 119u8, 19u8, 79u8, 194u8, 34u8, 181u8, 80u8, 205u8, 58u8, 181u8, 207u8, 54u8, 174u8,
        52u8, 97u8, 84u8, 64u8, 131u8, 238u8, 244u8, 204u8, 74u8, 108u8, 255u8, 54u8, 8u8, 113u8,
        182u8, 199u8, 178u8, 224u8, 44u8, 162u8, 74u8, 140u8, 145u8, 28u8, 206u8, 25u8, 142u8,
        82u8, 123u8, 122u8, 97u8, 184u8, 120u8, 116u8, 121u8, 223u8, 27u8, 250u8, 73u8, 91u8,
        164u8, 176u8, 201u8, 155u8, 227u8, 130u8, 231u8, 186u8, 192u8, 55u8, 94u8, 208u8, 146u8,
        213u8, 81u8, 31u8, 214u8, 206u8, 68u8, 72u8, 211u8, 53u8, 15u8, 182u8, 143u8, 40u8, 45u8,
        100u8, 42u8, 28u8, 110u8, 225u8, 181u8, 31u8, 172u8, 174u8, 249u8, 196u8, 156u8, 116u8,
        133u8, 35u8, 180u8, 101u8, 69u8, 171u8, 174u8,
    ],
    vk_delta_g2: [
        20u8, 52u8, 105u8, 74u8, 147u8, 41u8, 188u8, 201u8, 20u8, 26u8, 135u8, 38u8, 234u8, 249u8,
        255u8, 13u8, 231u8, 233u8, 168u8, 255u8, 13u8, 194u8, 207u8, 131u8, 140u8, 143u8, 108u8,
        221u8, 248u8, 88u8, 156u8, 206u8, 16u8, 204u8, 51u8, 115u8, 244u8, 164u8, 128u8, 11u8, 0u8,
        231u8, 70u8, 224u8, 151u8, 229u8, 69u8, 118u8, 67u8, 152u8, 57u8, 233u8, 150u8, 36u8,
        130u8, 132u8, 48u8, 32u8, 78u8, 57u8, 104u8, 253u8, 115u8, 125u8, 26u8, 64u8, 221u8, 201u8,
        71u8, 76u8, 55u8, 158u8, 59u8, 176u8, 252u8, 225u8, 120u8, 199u8, 147u8, 253u8, 42u8,
        217u8, 140u8, 85u8, 197u8, 135u8, 74u8, 249u8, 127u8, 168u8, 196u8, 152u8, 10u8, 151u8,
        51u8, 212u8, 11u8, 85u8, 38u8, 166u8, 202u8, 220u8, 241u8, 109u8, 122u8, 74u8, 12u8, 78u8,
        22u8, 61u8, 186u8, 130u8, 171u8, 131u8, 91u8, 134u8, 63u8, 184u8, 1u8, 126u8, 248u8, 136u8,
        227u8, 28u8, 112u8, 219u8, 176u8, 42u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [5u8, 55u8, 230u8, 102u8, 158u8, 109u8, 174u8, 51u8, 4u8, 100u8, 139u8, 212u8, 39u8, 191u8, 63u8, 158u8, 195u8, 229u8, 170u8, 166u8, 97u8, 52u8, 209u8, 94u8, 15u8, 241u8, 66u8, 121u8, 79u8, 46u8, 150u8, 107u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_c7896f212b2f78da")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x000537e6669e6dae3304648bd427bf3f9ec3e5aaa66134d15e0ff142794f2e966b\x00=======END GROTH16 VK SETUP V1=======\x00";
