// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        13u8, 174u8, 87u8, 3u8, 210u8, 100u8, 107u8, 42u8, 110u8, 251u8, 188u8, 113u8, 147u8,
        156u8, 141u8, 8u8, 230u8, 155u8, 142u8, 78u8, 114u8, 251u8, 41u8, 224u8, 11u8, 31u8, 233u8,
        157u8, 194u8, 57u8, 85u8, 201u8, 27u8, 53u8, 157u8, 99u8, 127u8, 121u8, 226u8, 9u8, 224u8,
        93u8, 126u8, 26u8, 179u8, 48u8, 236u8, 100u8, 150u8, 145u8, 59u8, 1u8, 27u8, 168u8, 4u8,
        167u8, 72u8, 172u8, 217u8, 139u8, 125u8, 34u8, 53u8, 24u8,
    ],
    [
        35u8, 209u8, 90u8, 43u8, 131u8, 90u8, 231u8, 119u8, 155u8, 118u8, 26u8, 36u8, 110u8, 231u8,
        211u8, 193u8, 11u8, 166u8, 180u8, 31u8, 164u8, 107u8, 45u8, 219u8, 212u8, 58u8, 190u8,
        136u8, 145u8, 173u8, 223u8, 103u8, 35u8, 104u8, 90u8, 210u8, 135u8, 26u8, 38u8, 220u8,
        190u8, 213u8, 115u8, 215u8, 96u8, 87u8, 208u8, 51u8, 113u8, 231u8, 23u8, 24u8, 53u8, 150u8,
        107u8, 68u8, 164u8, 215u8, 8u8, 238u8, 122u8, 3u8, 91u8, 56u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        30u8, 15u8, 167u8, 150u8, 69u8, 93u8, 242u8, 164u8, 30u8, 48u8, 70u8, 130u8, 127u8, 28u8,
        167u8, 198u8, 154u8, 103u8, 227u8, 210u8, 140u8, 241u8, 186u8, 239u8, 210u8, 12u8, 60u8,
        242u8, 22u8, 114u8, 194u8, 121u8, 21u8, 180u8, 19u8, 254u8, 134u8, 122u8, 35u8, 87u8, 80u8,
        57u8, 188u8, 2u8, 113u8, 253u8, 173u8, 137u8, 88u8, 71u8, 115u8, 201u8, 47u8, 122u8, 41u8,
        133u8, 202u8, 251u8, 246u8, 79u8, 199u8, 90u8, 241u8, 234u8,
    ],
    vk_beta_g2: [
        24u8, 155u8, 67u8, 252u8, 69u8, 168u8, 93u8, 79u8, 77u8, 127u8, 113u8, 166u8, 225u8, 218u8,
        188u8, 17u8, 3u8, 3u8, 108u8, 83u8, 224u8, 196u8, 104u8, 142u8, 121u8, 184u8, 148u8, 183u8,
        202u8, 34u8, 222u8, 122u8, 25u8, 112u8, 43u8, 75u8, 217u8, 123u8, 236u8, 233u8, 33u8, 48u8,
        227u8, 229u8, 66u8, 37u8, 93u8, 64u8, 4u8, 47u8, 90u8, 213u8, 179u8, 134u8, 249u8, 248u8,
        149u8, 37u8, 227u8, 114u8, 30u8, 116u8, 242u8, 127u8, 6u8, 240u8, 208u8, 176u8, 129u8,
        128u8, 112u8, 223u8, 67u8, 218u8, 200u8, 190u8, 22u8, 148u8, 154u8, 19u8, 1u8, 83u8, 106u8,
        75u8, 147u8, 40u8, 207u8, 182u8, 80u8, 231u8, 168u8, 99u8, 60u8, 124u8, 157u8, 178u8, 0u8,
        224u8, 194u8, 216u8, 62u8, 106u8, 255u8, 49u8, 209u8, 78u8, 167u8, 57u8, 250u8, 167u8,
        236u8, 100u8, 213u8, 203u8, 109u8, 56u8, 172u8, 155u8, 142u8, 17u8, 12u8, 194u8, 169u8,
        53u8, 235u8, 220u8, 184u8, 132u8,
    ],
    vk_gamma_g2: [
        11u8, 120u8, 182u8, 79u8, 245u8, 113u8, 172u8, 116u8, 227u8, 81u8, 163u8, 43u8, 88u8, 45u8,
        189u8, 128u8, 87u8, 43u8, 87u8, 174u8, 42u8, 146u8, 84u8, 122u8, 195u8, 18u8, 92u8, 145u8,
        2u8, 241u8, 141u8, 74u8, 23u8, 85u8, 240u8, 42u8, 39u8, 147u8, 178u8, 155u8, 215u8, 141u8,
        84u8, 218u8, 170u8, 135u8, 168u8, 223u8, 62u8, 63u8, 220u8, 52u8, 44u8, 167u8, 90u8, 116u8,
        147u8, 234u8, 3u8, 71u8, 153u8, 205u8, 36u8, 77u8, 17u8, 19u8, 68u8, 139u8, 187u8, 9u8,
        157u8, 206u8, 36u8, 11u8, 75u8, 175u8, 240u8, 104u8, 175u8, 199u8, 48u8, 89u8, 167u8,
        226u8, 6u8, 234u8, 11u8, 175u8, 10u8, 131u8, 93u8, 216u8, 78u8, 8u8, 10u8, 54u8, 25u8,
        104u8, 48u8, 122u8, 223u8, 54u8, 215u8, 223u8, 141u8, 169u8, 150u8, 150u8, 38u8, 29u8,
        64u8, 141u8, 168u8, 137u8, 132u8, 185u8, 182u8, 178u8, 58u8, 117u8, 23u8, 153u8, 133u8,
        96u8, 88u8, 34u8, 69u8, 13u8,
    ],
    vk_delta_g2: [
        11u8, 123u8, 8u8, 235u8, 190u8, 17u8, 1u8, 158u8, 95u8, 78u8, 123u8, 224u8, 116u8, 44u8,
        76u8, 220u8, 50u8, 48u8, 126u8, 121u8, 253u8, 249u8, 229u8, 125u8, 88u8, 25u8, 70u8, 50u8,
        148u8, 146u8, 74u8, 159u8, 19u8, 123u8, 227u8, 158u8, 210u8, 170u8, 176u8, 117u8, 8u8,
        58u8, 165u8, 103u8, 106u8, 247u8, 153u8, 238u8, 202u8, 242u8, 237u8, 87u8, 56u8, 41u8, 5u8,
        99u8, 132u8, 132u8, 106u8, 120u8, 135u8, 221u8, 124u8, 236u8, 41u8, 121u8, 69u8, 16u8,
        185u8, 222u8, 75u8, 237u8, 173u8, 5u8, 223u8, 70u8, 93u8, 77u8, 95u8, 196u8, 194u8, 148u8,
        206u8, 117u8, 226u8, 252u8, 120u8, 85u8, 106u8, 27u8, 222u8, 72u8, 35u8, 88u8, 46u8, 236u8,
        10u8, 71u8, 104u8, 126u8, 143u8, 163u8, 136u8, 123u8, 44u8, 103u8, 85u8, 47u8, 22u8, 27u8,
        14u8, 179u8, 1u8, 232u8, 217u8, 229u8, 225u8, 253u8, 107u8, 167u8, 211u8, 125u8, 22u8,
        185u8, 223u8, 170u8, 111u8, 165u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [213u8, 58u8, 181u8, 149u8, 26u8, 0u8, 134u8, 181u8, 104u8, 182u8, 46u8, 108u8, 191u8, 213u8, 91u8, 174u8, 190u8, 238u8, 75u8, 218u8, 114u8, 177u8, 248u8, 136u8, 5u8, 30u8, 121u8, 76u8, 93u8, 58u8, 106u8, 235u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_1bc207db1266996a")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00d53ab5951a0086b568b62e6cbfd55baebeee4bda72b1f888051e794c5d3a6aeb\x00=======END GROTH16 VK SETUP V1=======\x00";
