// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        36u8, 46u8, 16u8, 242u8, 106u8, 127u8, 14u8, 134u8, 158u8, 87u8, 199u8, 185u8, 198u8, 69u8,
        120u8, 41u8, 45u8, 177u8, 140u8, 94u8, 75u8, 74u8, 101u8, 200u8, 51u8, 215u8, 145u8, 132u8,
        77u8, 120u8, 187u8, 165u8, 22u8, 243u8, 33u8, 171u8, 194u8, 168u8, 172u8, 220u8, 234u8,
        49u8, 1u8, 240u8, 227u8, 15u8, 166u8, 220u8, 32u8, 107u8, 142u8, 116u8, 228u8, 170u8,
        202u8, 11u8, 57u8, 18u8, 213u8, 252u8, 166u8, 20u8, 227u8, 232u8,
    ],
    [
        8u8, 84u8, 31u8, 18u8, 124u8, 216u8, 137u8, 103u8, 48u8, 206u8, 253u8, 167u8, 205u8, 204u8,
        13u8, 95u8, 99u8, 22u8, 138u8, 254u8, 141u8, 25u8, 198u8, 254u8, 201u8, 43u8, 14u8, 125u8,
        10u8, 70u8, 55u8, 141u8, 22u8, 117u8, 92u8, 23u8, 213u8, 96u8, 183u8, 137u8, 193u8, 180u8,
        60u8, 50u8, 208u8, 41u8, 152u8, 233u8, 156u8, 247u8, 179u8, 225u8, 72u8, 239u8, 179u8,
        118u8, 207u8, 76u8, 143u8, 217u8, 120u8, 153u8, 42u8, 237u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        5u8, 109u8, 43u8, 79u8, 166u8, 75u8, 243u8, 201u8, 137u8, 209u8, 7u8, 209u8, 52u8, 102u8,
        255u8, 167u8, 253u8, 128u8, 163u8, 50u8, 150u8, 122u8, 103u8, 99u8, 131u8, 15u8, 143u8,
        177u8, 28u8, 251u8, 148u8, 182u8, 41u8, 0u8, 119u8, 30u8, 109u8, 127u8, 153u8, 181u8,
        206u8, 93u8, 123u8, 119u8, 111u8, 178u8, 178u8, 67u8, 186u8, 166u8, 98u8, 0u8, 38u8, 164u8,
        40u8, 51u8, 165u8, 241u8, 50u8, 245u8, 249u8, 147u8, 190u8, 180u8,
    ],
    vk_beta_g2: [
        24u8, 77u8, 194u8, 138u8, 2u8, 223u8, 104u8, 254u8, 48u8, 186u8, 142u8, 109u8, 111u8,
        253u8, 89u8, 234u8, 184u8, 48u8, 23u8, 111u8, 111u8, 38u8, 113u8, 156u8, 38u8, 49u8, 25u8,
        243u8, 178u8, 10u8, 160u8, 187u8, 11u8, 64u8, 58u8, 109u8, 99u8, 55u8, 34u8, 160u8, 208u8,
        211u8, 164u8, 199u8, 240u8, 172u8, 201u8, 155u8, 185u8, 77u8, 70u8, 76u8, 114u8, 123u8,
        208u8, 179u8, 111u8, 241u8, 228u8, 3u8, 134u8, 185u8, 216u8, 192u8, 7u8, 67u8, 168u8, 26u8,
        209u8, 208u8, 146u8, 192u8, 223u8, 169u8, 12u8, 115u8, 30u8, 239u8, 221u8, 48u8, 232u8,
        144u8, 248u8, 248u8, 229u8, 207u8, 79u8, 190u8, 159u8, 179u8, 94u8, 205u8, 222u8, 143u8,
        77u8, 60u8, 37u8, 118u8, 231u8, 33u8, 90u8, 231u8, 132u8, 163u8, 111u8, 21u8, 233u8, 123u8,
        101u8, 10u8, 254u8, 89u8, 165u8, 180u8, 18u8, 77u8, 206u8, 182u8, 40u8, 49u8, 12u8, 240u8,
        70u8, 65u8, 45u8, 26u8, 16u8, 216u8,
    ],
    vk_gamma_g2: [
        32u8, 89u8, 215u8, 158u8, 146u8, 213u8, 229u8, 210u8, 119u8, 204u8, 230u8, 65u8, 200u8,
        68u8, 115u8, 249u8, 139u8, 164u8, 223u8, 250u8, 199u8, 114u8, 180u8, 37u8, 219u8, 205u8,
        32u8, 220u8, 114u8, 1u8, 201u8, 178u8, 30u8, 125u8, 170u8, 81u8, 61u8, 196u8, 117u8, 154u8,
        211u8, 49u8, 197u8, 185u8, 97u8, 201u8, 4u8, 1u8, 143u8, 147u8, 255u8, 225u8, 238u8, 56u8,
        143u8, 10u8, 60u8, 173u8, 40u8, 95u8, 222u8, 226u8, 170u8, 34u8, 1u8, 93u8, 221u8, 162u8,
        220u8, 32u8, 228u8, 230u8, 207u8, 160u8, 165u8, 40u8, 163u8, 76u8, 105u8, 199u8, 100u8,
        232u8, 140u8, 169u8, 217u8, 31u8, 30u8, 215u8, 169u8, 51u8, 5u8, 92u8, 97u8, 12u8, 45u8,
        177u8, 31u8, 211u8, 233u8, 117u8, 143u8, 26u8, 207u8, 57u8, 82u8, 136u8, 152u8, 220u8,
        136u8, 148u8, 17u8, 168u8, 108u8, 78u8, 109u8, 25u8, 96u8, 115u8, 42u8, 173u8, 239u8, 43u8,
        18u8, 65u8, 240u8, 68u8, 219u8, 6u8,
    ],
    vk_delta_g2: [
        47u8, 97u8, 14u8, 108u8, 65u8, 112u8, 128u8, 66u8, 233u8, 128u8, 50u8, 90u8, 29u8, 225u8,
        172u8, 103u8, 46u8, 12u8, 217u8, 188u8, 59u8, 97u8, 141u8, 54u8, 143u8, 125u8, 5u8, 135u8,
        165u8, 187u8, 41u8, 201u8, 11u8, 146u8, 222u8, 86u8, 200u8, 156u8, 2u8, 213u8, 150u8, 18u8,
        25u8, 123u8, 112u8, 176u8, 185u8, 208u8, 231u8, 17u8, 164u8, 236u8, 240u8, 35u8, 88u8,
        121u8, 139u8, 48u8, 26u8, 41u8, 159u8, 85u8, 78u8, 15u8, 24u8, 204u8, 4u8, 53u8, 124u8,
        85u8, 231u8, 46u8, 78u8, 46u8, 152u8, 38u8, 152u8, 43u8, 6u8, 91u8, 9u8, 238u8, 208u8,
        29u8, 220u8, 53u8, 21u8, 184u8, 231u8, 83u8, 226u8, 229u8, 221u8, 51u8, 73u8, 232u8, 19u8,
        109u8, 16u8, 201u8, 138u8, 165u8, 184u8, 45u8, 164u8, 124u8, 94u8, 231u8, 1u8, 115u8,
        186u8, 51u8, 248u8, 41u8, 103u8, 6u8, 255u8, 33u8, 198u8, 17u8, 73u8, 161u8, 54u8, 132u8,
        121u8, 80u8, 106u8, 149u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [195u8, 197u8, 109u8, 237u8, 212u8, 188u8, 198u8, 107u8, 145u8, 67u8, 33u8, 195u8, 137u8, 132u8, 40u8, 125u8, 232u8, 234u8, 78u8, 95u8, 72u8, 45u8, 75u8, 193u8, 24u8, 85u8, 70u8, 223u8, 58u8, 220u8, 216u8, 102u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_286c8b17e5e10f76")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00c3c56dedd4bcc66b914321c38984287de8ea4e5f482d4bc1185546df3adcd866\x00=======END GROTH16 VK SETUP V1=======\x00";
