// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        30u8, 95u8, 202u8, 46u8, 186u8, 32u8, 23u8, 70u8, 1u8, 133u8, 39u8, 251u8, 215u8, 180u8,
        69u8, 169u8, 240u8, 74u8, 121u8, 126u8, 121u8, 223u8, 195u8, 181u8, 103u8, 231u8, 195u8,
        68u8, 71u8, 68u8, 81u8, 137u8, 40u8, 199u8, 229u8, 18u8, 117u8, 128u8, 124u8, 98u8, 83u8,
        45u8, 237u8, 199u8, 235u8, 72u8, 29u8, 81u8, 155u8, 0u8, 139u8, 14u8, 30u8, 188u8, 235u8,
        4u8, 128u8, 68u8, 66u8, 214u8, 210u8, 242u8, 81u8, 254u8,
    ],
    [
        3u8, 63u8, 96u8, 53u8, 45u8, 103u8, 45u8, 81u8, 139u8, 219u8, 86u8, 243u8, 17u8, 151u8,
        9u8, 66u8, 4u8, 79u8, 52u8, 128u8, 140u8, 118u8, 56u8, 97u8, 49u8, 99u8, 95u8, 136u8,
        231u8, 16u8, 78u8, 219u8, 5u8, 11u8, 250u8, 157u8, 152u8, 112u8, 88u8, 154u8, 122u8, 21u8,
        54u8, 176u8, 220u8, 108u8, 27u8, 157u8, 226u8, 19u8, 0u8, 243u8, 171u8, 162u8, 187u8,
        140u8, 232u8, 245u8, 145u8, 207u8, 203u8, 104u8, 201u8, 107u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        28u8, 202u8, 253u8, 171u8, 183u8, 65u8, 106u8, 200u8, 237u8, 67u8, 152u8, 24u8, 137u8,
        23u8, 143u8, 174u8, 123u8, 19u8, 136u8, 36u8, 132u8, 138u8, 158u8, 240u8, 112u8, 4u8, 52u8,
        248u8, 86u8, 9u8, 6u8, 3u8, 46u8, 147u8, 195u8, 27u8, 199u8, 83u8, 175u8, 179u8, 80u8,
        128u8, 163u8, 126u8, 173u8, 143u8, 160u8, 174u8, 180u8, 227u8, 202u8, 50u8, 87u8, 112u8,
        164u8, 80u8, 216u8, 224u8, 110u8, 31u8, 44u8, 129u8, 221u8, 241u8,
    ],
    vk_beta_g2: [
        33u8, 254u8, 241u8, 30u8, 252u8, 145u8, 196u8, 109u8, 37u8, 13u8, 179u8, 3u8, 66u8, 178u8,
        182u8, 187u8, 137u8, 107u8, 158u8, 240u8, 29u8, 55u8, 202u8, 175u8, 148u8, 99u8, 86u8,
        13u8, 136u8, 72u8, 71u8, 147u8, 7u8, 165u8, 216u8, 222u8, 58u8, 8u8, 173u8, 191u8, 126u8,
        51u8, 104u8, 70u8, 206u8, 94u8, 125u8, 7u8, 175u8, 167u8, 93u8, 49u8, 185u8, 159u8, 10u8,
        186u8, 118u8, 147u8, 17u8, 196u8, 137u8, 237u8, 42u8, 223u8, 43u8, 60u8, 14u8, 135u8,
        246u8, 127u8, 90u8, 119u8, 7u8, 37u8, 230u8, 237u8, 59u8, 240u8, 152u8, 226u8, 211u8,
        124u8, 169u8, 208u8, 175u8, 122u8, 124u8, 166u8, 159u8, 11u8, 52u8, 58u8, 124u8, 174u8,
        253u8, 133u8, 1u8, 114u8, 239u8, 104u8, 160u8, 64u8, 165u8, 27u8, 233u8, 173u8, 135u8,
        105u8, 2u8, 14u8, 207u8, 8u8, 178u8, 64u8, 55u8, 21u8, 139u8, 254u8, 164u8, 126u8, 34u8,
        156u8, 255u8, 189u8, 206u8, 21u8, 158u8, 151u8,
    ],
    vk_gamma_g2: [
        34u8, 246u8, 187u8, 181u8, 112u8, 54u8, 117u8, 62u8, 156u8, 230u8, 52u8, 76u8, 246u8, 91u8,
        224u8, 143u8, 163u8, 177u8, 137u8, 0u8, 149u8, 155u8, 188u8, 225u8, 66u8, 3u8, 67u8, 73u8,
        21u8, 141u8, 134u8, 95u8, 31u8, 98u8, 115u8, 124u8, 82u8, 33u8, 180u8, 44u8, 36u8, 82u8,
        73u8, 111u8, 245u8, 239u8, 1u8, 243u8, 147u8, 249u8, 180u8, 113u8, 154u8, 145u8, 192u8,
        216u8, 218u8, 173u8, 1u8, 138u8, 85u8, 176u8, 246u8, 194u8, 26u8, 202u8, 148u8, 113u8,
        232u8, 245u8, 114u8, 167u8, 81u8, 1u8, 111u8, 79u8, 81u8, 149u8, 10u8, 7u8, 149u8, 62u8,
        127u8, 178u8, 97u8, 0u8, 158u8, 139u8, 160u8, 106u8, 132u8, 140u8, 122u8, 77u8, 162u8,
        224u8, 26u8, 153u8, 169u8, 184u8, 46u8, 88u8, 200u8, 137u8, 255u8, 33u8, 180u8, 182u8,
        138u8, 107u8, 60u8, 129u8, 85u8, 194u8, 132u8, 126u8, 255u8, 99u8, 114u8, 254u8, 21u8,
        205u8, 16u8, 143u8, 69u8, 244u8, 85u8, 104u8,
    ],
    vk_delta_g2: [
        25u8, 131u8, 38u8, 215u8, 53u8, 174u8, 177u8, 98u8, 249u8, 150u8, 18u8, 131u8, 203u8,
        165u8, 196u8, 88u8, 27u8, 117u8, 113u8, 107u8, 151u8, 249u8, 94u8, 239u8, 227u8, 222u8,
        48u8, 72u8, 136u8, 48u8, 138u8, 119u8, 38u8, 67u8, 26u8, 160u8, 141u8, 146u8, 134u8, 255u8,
        123u8, 220u8, 85u8, 231u8, 152u8, 56u8, 26u8, 110u8, 190u8, 24u8, 187u8, 20u8, 244u8,
        192u8, 158u8, 222u8, 13u8, 184u8, 119u8, 137u8, 42u8, 122u8, 135u8, 181u8, 40u8, 21u8,
        138u8, 163u8, 94u8, 103u8, 171u8, 72u8, 233u8, 192u8, 200u8, 191u8, 195u8, 253u8, 204u8,
        57u8, 65u8, 22u8, 13u8, 65u8, 168u8, 135u8, 123u8, 164u8, 33u8, 160u8, 237u8, 201u8, 251u8,
        56u8, 9u8, 68u8, 38u8, 211u8, 243u8, 42u8, 231u8, 123u8, 102u8, 109u8, 200u8, 31u8, 47u8,
        48u8, 50u8, 213u8, 242u8, 158u8, 203u8, 63u8, 59u8, 139u8, 78u8, 198u8, 169u8, 64u8, 75u8,
        140u8, 136u8, 87u8, 160u8, 117u8, 70u8, 67u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [188u8, 236u8, 33u8, 42u8, 180u8, 97u8, 188u8, 54u8, 232u8, 244u8, 237u8, 196u8, 84u8, 76u8, 53u8, 16u8, 142u8, 168u8, 64u8, 200u8, 116u8, 116u8, 154u8, 62u8, 55u8, 77u8, 63u8, 29u8, 254u8, 6u8, 253u8, 95u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_0eb9b966c73ec291")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00bcec212ab461bc36e8f4edc4544c35108ea840c874749a3e374d3f1dfe06fd5f\x00=======END GROTH16 VK SETUP V1=======\x00";
