// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        20u8, 15u8, 147u8, 124u8, 27u8, 152u8, 167u8, 165u8, 173u8, 97u8, 95u8, 53u8, 211u8, 111u8,
        150u8, 111u8, 70u8, 137u8, 113u8, 47u8, 88u8, 128u8, 192u8, 179u8, 93u8, 128u8, 107u8,
        45u8, 57u8, 152u8, 184u8, 104u8, 3u8, 232u8, 110u8, 100u8, 103u8, 136u8, 37u8, 164u8,
        198u8, 33u8, 245u8, 13u8, 92u8, 119u8, 170u8, 85u8, 147u8, 92u8, 220u8, 25u8, 176u8, 237u8,
        38u8, 208u8, 55u8, 224u8, 99u8, 55u8, 161u8, 203u8, 235u8, 174u8,
    ],
    [
        4u8, 104u8, 206u8, 224u8, 72u8, 13u8, 237u8, 249u8, 152u8, 254u8, 17u8, 145u8, 83u8, 181u8,
        142u8, 233u8, 191u8, 105u8, 117u8, 57u8, 43u8, 41u8, 181u8, 142u8, 12u8, 107u8, 53u8, 0u8,
        203u8, 217u8, 139u8, 56u8, 14u8, 170u8, 186u8, 176u8, 249u8, 245u8, 175u8, 86u8, 126u8,
        165u8, 89u8, 1u8, 207u8, 177u8, 254u8, 30u8, 32u8, 19u8, 144u8, 212u8, 79u8, 250u8, 140u8,
        5u8, 141u8, 239u8, 74u8, 53u8, 77u8, 5u8, 82u8, 129u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        40u8, 103u8, 245u8, 131u8, 11u8, 235u8, 147u8, 114u8, 185u8, 65u8, 236u8, 180u8, 48u8,
        65u8, 76u8, 242u8, 54u8, 106u8, 41u8, 84u8, 166u8, 195u8, 205u8, 198u8, 221u8, 193u8, 85u8,
        116u8, 65u8, 225u8, 192u8, 52u8, 5u8, 32u8, 185u8, 150u8, 47u8, 106u8, 114u8, 55u8, 32u8,
        157u8, 156u8, 206u8, 202u8, 105u8, 47u8, 164u8, 51u8, 37u8, 38u8, 88u8, 170u8, 172u8,
        226u8, 14u8, 17u8, 182u8, 174u8, 252u8, 71u8, 164u8, 88u8, 22u8,
    ],
    vk_beta_g2: [
        33u8, 48u8, 210u8, 246u8, 126u8, 11u8, 216u8, 237u8, 45u8, 163u8, 239u8, 10u8, 227u8,
        221u8, 224u8, 71u8, 42u8, 209u8, 80u8, 111u8, 13u8, 172u8, 153u8, 64u8, 105u8, 160u8,
        190u8, 147u8, 194u8, 9u8, 203u8, 222u8, 45u8, 106u8, 78u8, 194u8, 71u8, 232u8, 159u8,
        108u8, 174u8, 191u8, 169u8, 189u8, 90u8, 112u8, 151u8, 67u8, 102u8, 30u8, 245u8, 0u8,
        189u8, 6u8, 139u8, 163u8, 81u8, 216u8, 120u8, 202u8, 158u8, 252u8, 243u8, 204u8, 5u8,
        169u8, 98u8, 190u8, 116u8, 13u8, 45u8, 198u8, 226u8, 81u8, 180u8, 137u8, 240u8, 65u8,
        147u8, 218u8, 55u8, 155u8, 163u8, 88u8, 240u8, 132u8, 18u8, 191u8, 209u8, 25u8, 64u8, 40u8,
        86u8, 99u8, 73u8, 201u8, 28u8, 154u8, 204u8, 241u8, 86u8, 9u8, 244u8, 132u8, 131u8, 125u8,
        204u8, 214u8, 166u8, 241u8, 210u8, 221u8, 7u8, 4u8, 90u8, 8u8, 65u8, 232u8, 138u8, 148u8,
        220u8, 176u8, 209u8, 110u8, 184u8, 67u8, 72u8, 28u8,
    ],
    vk_gamma_g2: [
        45u8, 119u8, 18u8, 93u8, 160u8, 188u8, 97u8, 203u8, 94u8, 245u8, 235u8, 166u8, 54u8, 1u8,
        206u8, 129u8, 176u8, 131u8, 172u8, 48u8, 153u8, 109u8, 127u8, 0u8, 245u8, 60u8, 128u8,
        69u8, 106u8, 60u8, 219u8, 181u8, 1u8, 56u8, 93u8, 215u8, 70u8, 216u8, 23u8, 116u8, 150u8,
        81u8, 5u8, 159u8, 174u8, 194u8, 223u8, 215u8, 98u8, 245u8, 140u8, 159u8, 67u8, 157u8,
        213u8, 167u8, 228u8, 193u8, 124u8, 134u8, 70u8, 1u8, 165u8, 142u8, 44u8, 76u8, 110u8,
        160u8, 157u8, 187u8, 74u8, 210u8, 253u8, 2u8, 17u8, 214u8, 98u8, 5u8, 162u8, 3u8, 142u8,
        119u8, 42u8, 24u8, 248u8, 196u8, 122u8, 164u8, 25u8, 197u8, 94u8, 14u8, 33u8, 164u8, 220u8,
        190u8, 18u8, 8u8, 122u8, 218u8, 75u8, 183u8, 200u8, 116u8, 170u8, 251u8, 58u8, 178u8,
        224u8, 243u8, 58u8, 38u8, 27u8, 126u8, 13u8, 36u8, 175u8, 236u8, 207u8, 78u8, 246u8, 108u8,
        39u8, 55u8, 195u8, 131u8, 213u8, 201u8,
    ],
    vk_delta_g2: [
        47u8, 170u8, 0u8, 104u8, 133u8, 110u8, 230u8, 227u8, 204u8, 204u8, 28u8, 64u8, 20u8, 191u8,
        176u8, 237u8, 141u8, 61u8, 130u8, 210u8, 18u8, 91u8, 13u8, 219u8, 23u8, 33u8, 224u8, 121u8,
        102u8, 40u8, 244u8, 228u8, 1u8, 149u8, 214u8, 62u8, 172u8, 177u8, 124u8, 208u8, 19u8,
        219u8, 244u8, 173u8, 245u8, 157u8, 92u8, 109u8, 174u8, 110u8, 126u8, 238u8, 173u8, 107u8,
        26u8, 133u8, 153u8, 140u8, 136u8, 202u8, 17u8, 175u8, 22u8, 208u8, 34u8, 108u8, 91u8,
        141u8, 75u8, 123u8, 9u8, 165u8, 186u8, 82u8, 225u8, 250u8, 245u8, 232u8, 54u8, 166u8,
        115u8, 223u8, 59u8, 6u8, 109u8, 114u8, 102u8, 77u8, 138u8, 237u8, 238u8, 129u8, 245u8,
        122u8, 164u8, 88u8, 24u8, 171u8, 238u8, 73u8, 63u8, 61u8, 218u8, 37u8, 188u8, 72u8, 242u8,
        196u8, 132u8, 48u8, 194u8, 15u8, 205u8, 162u8, 97u8, 68u8, 33u8, 29u8, 127u8, 135u8, 117u8,
        97u8, 195u8, 72u8, 234u8, 12u8, 241u8, 23u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [11u8, 235u8, 232u8, 145u8, 9u8, 119u8, 41u8, 135u8, 224u8, 181u8, 99u8, 157u8, 135u8, 156u8, 43u8, 60u8, 19u8, 216u8, 246u8, 12u8, 143u8, 81u8, 226u8, 86u8, 141u8, 88u8, 5u8, 1u8, 46u8, 66u8, 48u8, 132u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_adde99d451ca9813")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x000bebe89109772987e0b5639d879c2b3c13d8f60c8f51e2568d5805012e423084\x00=======END GROTH16 VK SETUP V1=======\x00";
