// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        39u8, 189u8, 98u8, 212u8, 151u8, 104u8, 217u8, 176u8, 184u8, 11u8, 56u8, 235u8, 161u8,
        242u8, 102u8, 95u8, 212u8, 83u8, 212u8, 173u8, 148u8, 75u8, 57u8, 116u8, 239u8, 107u8,
        241u8, 239u8, 231u8, 240u8, 133u8, 79u8, 23u8, 51u8, 49u8, 178u8, 17u8, 133u8, 169u8,
        172u8, 166u8, 193u8, 7u8, 161u8, 89u8, 33u8, 182u8, 8u8, 102u8, 67u8, 80u8, 145u8, 222u8,
        226u8, 34u8, 22u8, 98u8, 243u8, 79u8, 108u8, 52u8, 146u8, 222u8, 102u8,
    ],
    [
        19u8, 230u8, 203u8, 122u8, 172u8, 44u8, 156u8, 245u8, 23u8, 177u8, 112u8, 121u8, 71u8,
        245u8, 17u8, 88u8, 232u8, 155u8, 103u8, 218u8, 163u8, 105u8, 178u8, 0u8, 193u8, 30u8,
        144u8, 31u8, 23u8, 139u8, 18u8, 154u8, 27u8, 137u8, 3u8, 143u8, 243u8, 153u8, 24u8, 143u8,
        90u8, 64u8, 37u8, 172u8, 75u8, 88u8, 142u8, 181u8, 124u8, 240u8, 190u8, 223u8, 27u8, 43u8,
        215u8, 79u8, 69u8, 202u8, 236u8, 89u8, 229u8, 142u8, 183u8, 249u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        14u8, 74u8, 111u8, 2u8, 193u8, 22u8, 234u8, 44u8, 107u8, 222u8, 70u8, 128u8, 126u8, 218u8,
        62u8, 202u8, 126u8, 122u8, 145u8, 221u8, 126u8, 13u8, 243u8, 196u8, 246u8, 248u8, 21u8,
        98u8, 208u8, 12u8, 0u8, 183u8, 33u8, 43u8, 42u8, 173u8, 195u8, 207u8, 151u8, 72u8, 129u8,
        194u8, 249u8, 63u8, 254u8, 127u8, 167u8, 66u8, 110u8, 85u8, 210u8, 49u8, 57u8, 135u8, 58u8,
        37u8, 166u8, 133u8, 169u8, 3u8, 22u8, 227u8, 221u8, 42u8,
    ],
    vk_beta_g2: [
        45u8, 63u8, 165u8, 71u8, 113u8, 161u8, 34u8, 71u8, 9u8, 65u8, 29u8, 72u8, 181u8, 169u8,
        243u8, 189u8, 74u8, 8u8, 101u8, 44u8, 252u8, 7u8, 182u8, 7u8, 129u8, 248u8, 179u8, 3u8,
        83u8, 224u8, 164u8, 111u8, 34u8, 125u8, 4u8, 219u8, 119u8, 62u8, 53u8, 150u8, 29u8, 164u8,
        185u8, 18u8, 162u8, 7u8, 89u8, 248u8, 4u8, 47u8, 138u8, 211u8, 230u8, 255u8, 73u8, 172u8,
        236u8, 141u8, 224u8, 90u8, 167u8, 18u8, 146u8, 108u8, 28u8, 18u8, 85u8, 187u8, 233u8,
        197u8, 234u8, 113u8, 34u8, 101u8, 120u8, 123u8, 42u8, 40u8, 203u8, 122u8, 176u8, 219u8,
        129u8, 188u8, 156u8, 35u8, 38u8, 8u8, 17u8, 111u8, 0u8, 178u8, 30u8, 103u8, 233u8, 79u8,
        19u8, 250u8, 214u8, 198u8, 218u8, 141u8, 159u8, 159u8, 151u8, 180u8, 13u8, 103u8, 207u8,
        208u8, 23u8, 169u8, 152u8, 190u8, 10u8, 230u8, 186u8, 252u8, 242u8, 71u8, 120u8, 59u8,
        102u8, 6u8, 212u8, 62u8, 10u8, 113u8,
    ],
    vk_gamma_g2: [
        20u8, 75u8, 11u8, 151u8, 102u8, 127u8, 95u8, 135u8, 70u8, 96u8, 168u8, 121u8, 27u8, 62u8,
        146u8, 98u8, 53u8, 104u8, 138u8, 51u8, 250u8, 212u8, 14u8, 87u8, 17u8, 231u8, 162u8, 140u8,
        159u8, 153u8, 130u8, 9u8, 30u8, 54u8, 32u8, 242u8, 211u8, 52u8, 83u8, 218u8, 1u8, 48u8,
        127u8, 113u8, 72u8, 183u8, 188u8, 186u8, 56u8, 19u8, 86u8, 217u8, 156u8, 8u8, 59u8, 108u8,
        165u8, 17u8, 119u8, 27u8, 55u8, 24u8, 0u8, 1u8, 3u8, 116u8, 190u8, 49u8, 225u8, 12u8, 40u8,
        123u8, 21u8, 110u8, 85u8, 1u8, 104u8, 167u8, 156u8, 179u8, 57u8, 35u8, 38u8, 193u8, 196u8,
        152u8, 166u8, 28u8, 65u8, 202u8, 105u8, 219u8, 236u8, 167u8, 53u8, 198u8, 8u8, 245u8,
        207u8, 118u8, 199u8, 6u8, 233u8, 191u8, 148u8, 55u8, 96u8, 200u8, 80u8, 236u8, 86u8, 109u8,
        239u8, 125u8, 153u8, 224u8, 244u8, 32u8, 73u8, 235u8, 164u8, 95u8, 102u8, 140u8, 18u8,
        101u8, 83u8, 196u8,
    ],
    vk_delta_g2: [
        29u8, 44u8, 113u8, 135u8, 18u8, 50u8, 90u8, 253u8, 204u8, 37u8, 111u8, 228u8, 83u8, 122u8,
        138u8, 99u8, 175u8, 116u8, 10u8, 56u8, 52u8, 79u8, 11u8, 227u8, 74u8, 48u8, 76u8, 222u8,
        113u8, 109u8, 248u8, 116u8, 18u8, 25u8, 184u8, 51u8, 52u8, 145u8, 133u8, 2u8, 118u8, 131u8,
        69u8, 70u8, 158u8, 182u8, 219u8, 49u8, 143u8, 178u8, 10u8, 215u8, 209u8, 143u8, 52u8,
        133u8, 17u8, 149u8, 93u8, 144u8, 241u8, 50u8, 191u8, 135u8, 22u8, 199u8, 85u8, 23u8, 31u8,
        229u8, 21u8, 81u8, 62u8, 211u8, 252u8, 196u8, 28u8, 227u8, 163u8, 73u8, 165u8, 208u8, 66u8,
        135u8, 176u8, 18u8, 188u8, 26u8, 241u8, 76u8, 53u8, 215u8, 231u8, 53u8, 141u8, 88u8, 32u8,
        210u8, 16u8, 136u8, 67u8, 247u8, 46u8, 17u8, 254u8, 212u8, 96u8, 137u8, 43u8, 116u8, 125u8,
        224u8, 67u8, 245u8, 52u8, 172u8, 19u8, 81u8, 50u8, 225u8, 55u8, 129u8, 139u8, 27u8, 20u8,
        16u8, 8u8, 24u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [194u8, 152u8, 49u8, 150u8, 110u8, 29u8, 57u8, 85u8, 38u8, 197u8, 7u8, 4u8, 171u8, 33u8, 132u8, 56u8, 38u8, 136u8, 168u8, 170u8, 138u8, 26u8, 45u8, 191u8, 7u8, 81u8, 230u8, 159u8, 62u8, 17u8, 115u8, 71u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_9d567a5e2f5c552c")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00c29831966e1d395526c50704ab2184382688a8aa8a1a2dbf0751e69f3e117347\x00=======END GROTH16 VK SETUP V1=======\x00";
