// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        30u8, 18u8, 32u8, 227u8, 44u8, 66u8, 189u8, 134u8, 243u8, 14u8, 208u8, 72u8, 183u8, 91u8,
        242u8, 201u8, 89u8, 29u8, 62u8, 41u8, 171u8, 67u8, 6u8, 101u8, 145u8, 104u8, 190u8, 215u8,
        69u8, 173u8, 155u8, 234u8, 16u8, 4u8, 52u8, 60u8, 6u8, 7u8, 167u8, 234u8, 74u8, 202u8,
        28u8, 169u8, 173u8, 7u8, 114u8, 236u8, 210u8, 145u8, 72u8, 21u8, 119u8, 40u8, 226u8, 179u8,
        0u8, 215u8, 87u8, 71u8, 188u8, 252u8, 115u8, 57u8,
    ],
    [
        46u8, 6u8, 139u8, 221u8, 242u8, 162u8, 73u8, 189u8, 25u8, 151u8, 196u8, 254u8, 100u8,
        128u8, 107u8, 166u8, 238u8, 224u8, 115u8, 106u8, 76u8, 105u8, 64u8, 173u8, 115u8, 112u8,
        135u8, 168u8, 101u8, 134u8, 251u8, 142u8, 13u8, 93u8, 238u8, 22u8, 229u8, 75u8, 21u8,
        243u8, 233u8, 154u8, 120u8, 170u8, 45u8, 70u8, 166u8, 240u8, 242u8, 114u8, 132u8, 205u8,
        77u8, 67u8, 9u8, 101u8, 58u8, 28u8, 15u8, 32u8, 152u8, 153u8, 34u8, 18u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        9u8, 11u8, 105u8, 41u8, 150u8, 81u8, 181u8, 33u8, 154u8, 63u8, 48u8, 239u8, 195u8, 24u8,
        138u8, 19u8, 160u8, 163u8, 19u8, 92u8, 114u8, 116u8, 17u8, 248u8, 84u8, 239u8, 32u8, 197u8,
        85u8, 171u8, 43u8, 204u8, 10u8, 98u8, 74u8, 194u8, 60u8, 57u8, 2u8, 39u8, 105u8, 78u8,
        25u8, 247u8, 187u8, 56u8, 247u8, 7u8, 189u8, 62u8, 198u8, 116u8, 228u8, 146u8, 232u8,
        198u8, 139u8, 57u8, 11u8, 210u8, 146u8, 140u8, 167u8, 112u8,
    ],
    vk_beta_g2: [
        44u8, 176u8, 64u8, 242u8, 129u8, 170u8, 207u8, 110u8, 59u8, 231u8, 17u8, 63u8, 232u8, 81u8,
        204u8, 175u8, 241u8, 57u8, 220u8, 28u8, 241u8, 81u8, 207u8, 89u8, 110u8, 23u8, 175u8,
        122u8, 195u8, 207u8, 115u8, 21u8, 23u8, 170u8, 99u8, 119u8, 133u8, 106u8, 62u8, 103u8,
        185u8, 135u8, 56u8, 142u8, 69u8, 102u8, 55u8, 97u8, 127u8, 221u8, 253u8, 96u8, 15u8, 243u8,
        245u8, 184u8, 3u8, 225u8, 216u8, 120u8, 3u8, 127u8, 141u8, 52u8, 28u8, 128u8, 199u8, 26u8,
        81u8, 90u8, 85u8, 138u8, 77u8, 62u8, 123u8, 116u8, 171u8, 4u8, 79u8, 168u8, 44u8, 112u8,
        161u8, 234u8, 142u8, 32u8, 30u8, 182u8, 216u8, 189u8, 255u8, 26u8, 217u8, 11u8, 96u8,
        174u8, 9u8, 11u8, 153u8, 159u8, 253u8, 148u8, 105u8, 75u8, 227u8, 56u8, 116u8, 76u8, 128u8,
        65u8, 145u8, 199u8, 42u8, 200u8, 110u8, 50u8, 47u8, 57u8, 174u8, 97u8, 180u8, 99u8, 69u8,
        51u8, 168u8, 131u8, 221u8, 10u8,
    ],
    vk_gamma_g2: [
        24u8, 41u8, 67u8, 74u8, 2u8, 2u8, 158u8, 142u8, 143u8, 205u8, 68u8, 235u8, 32u8, 89u8,
        112u8, 20u8, 8u8, 5u8, 243u8, 90u8, 117u8, 18u8, 36u8, 131u8, 134u8, 108u8, 250u8, 98u8,
        134u8, 107u8, 98u8, 60u8, 40u8, 157u8, 15u8, 105u8, 199u8, 207u8, 135u8, 253u8, 14u8, 29u8,
        162u8, 123u8, 161u8, 218u8, 49u8, 27u8, 249u8, 109u8, 102u8, 120u8, 150u8, 255u8, 20u8,
        209u8, 154u8, 49u8, 238u8, 34u8, 134u8, 204u8, 228u8, 135u8, 25u8, 9u8, 121u8, 16u8, 252u8,
        198u8, 22u8, 5u8, 168u8, 64u8, 205u8, 253u8, 173u8, 72u8, 1u8, 206u8, 112u8, 73u8, 128u8,
        128u8, 61u8, 101u8, 152u8, 22u8, 40u8, 33u8, 189u8, 100u8, 54u8, 178u8, 124u8, 151u8, 30u8,
        249u8, 55u8, 229u8, 208u8, 227u8, 60u8, 1u8, 0u8, 144u8, 58u8, 208u8, 76u8, 186u8, 49u8,
        205u8, 187u8, 148u8, 79u8, 100u8, 129u8, 113u8, 182u8, 169u8, 119u8, 183u8, 118u8, 94u8,
        211u8, 168u8, 105u8, 19u8,
    ],
    vk_delta_g2: [
        34u8, 157u8, 118u8, 51u8, 118u8, 114u8, 104u8, 207u8, 26u8, 26u8, 57u8, 211u8, 60u8, 52u8,
        179u8, 194u8, 98u8, 52u8, 14u8, 194u8, 85u8, 71u8, 34u8, 253u8, 48u8, 118u8, 189u8, 156u8,
        26u8, 61u8, 125u8, 37u8, 16u8, 169u8, 220u8, 253u8, 39u8, 225u8, 131u8, 6u8, 34u8, 209u8,
        132u8, 253u8, 182u8, 158u8, 37u8, 212u8, 26u8, 6u8, 41u8, 189u8, 143u8, 173u8, 232u8,
        233u8, 76u8, 7u8, 91u8, 55u8, 12u8, 118u8, 53u8, 21u8, 32u8, 24u8, 148u8, 149u8, 159u8,
        16u8, 175u8, 253u8, 209u8, 231u8, 108u8, 194u8, 236u8, 210u8, 221u8, 89u8, 146u8, 53u8,
        6u8, 252u8, 2u8, 46u8, 103u8, 108u8, 165u8, 148u8, 175u8, 160u8, 178u8, 199u8, 53u8, 170u8,
        43u8, 29u8, 75u8, 252u8, 70u8, 111u8, 136u8, 208u8, 63u8, 193u8, 124u8, 8u8, 195u8, 216u8,
        70u8, 8u8, 96u8, 181u8, 95u8, 206u8, 177u8, 30u8, 233u8, 51u8, 230u8, 248u8, 36u8, 190u8,
        182u8, 90u8, 90u8, 238u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [178u8, 169u8, 53u8, 187u8, 133u8, 174u8, 171u8, 39u8, 45u8, 49u8, 185u8, 123u8, 215u8, 203u8, 214u8, 245u8, 126u8, 179u8, 32u8, 79u8, 232u8, 42u8, 239u8, 98u8, 128u8, 211u8, 140u8, 188u8, 174u8, 35u8, 177u8, 38u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_f1ed3bf01a966a3f")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00b2a935bb85aeab272d31b97bd7cbd6f57eb3204fe82aef6280d38cbcae23b126\x00=======END GROTH16 VK SETUP V1=======\x00";
