// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        35u8, 167u8, 12u8, 166u8, 88u8, 247u8, 39u8, 238u8, 203u8, 60u8, 37u8, 188u8, 103u8, 94u8,
        239u8, 75u8, 125u8, 212u8, 87u8, 205u8, 57u8, 196u8, 193u8, 245u8, 232u8, 48u8, 41u8, 27u8,
        253u8, 51u8, 242u8, 186u8, 17u8, 255u8, 182u8, 45u8, 19u8, 185u8, 236u8, 24u8, 233u8, 37u8,
        57u8, 160u8, 161u8, 30u8, 238u8, 73u8, 15u8, 153u8, 168u8, 65u8, 48u8, 74u8, 188u8, 190u8,
        226u8, 74u8, 157u8, 57u8, 202u8, 91u8, 1u8, 202u8,
    ],
    [
        7u8, 110u8, 56u8, 35u8, 142u8, 153u8, 120u8, 215u8, 131u8, 23u8, 250u8, 182u8, 109u8,
        157u8, 30u8, 242u8, 171u8, 34u8, 192u8, 213u8, 149u8, 173u8, 198u8, 53u8, 245u8, 190u8,
        171u8, 5u8, 231u8, 177u8, 166u8, 38u8, 37u8, 144u8, 215u8, 241u8, 129u8, 101u8, 71u8, 66u8,
        239u8, 159u8, 106u8, 82u8, 117u8, 87u8, 148u8, 178u8, 47u8, 242u8, 219u8, 43u8, 98u8,
        114u8, 101u8, 59u8, 136u8, 135u8, 198u8, 74u8, 128u8, 225u8, 159u8, 138u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        28u8, 210u8, 229u8, 41u8, 110u8, 90u8, 110u8, 50u8, 95u8, 220u8, 183u8, 217u8, 139u8,
        244u8, 149u8, 8u8, 84u8, 34u8, 181u8, 185u8, 216u8, 78u8, 126u8, 159u8, 115u8, 228u8,
        240u8, 26u8, 104u8, 5u8, 239u8, 129u8, 36u8, 108u8, 127u8, 196u8, 201u8, 48u8, 120u8, 76u8,
        61u8, 168u8, 198u8, 149u8, 114u8, 235u8, 13u8, 28u8, 98u8, 42u8, 218u8, 86u8, 124u8, 142u8,
        38u8, 84u8, 181u8, 121u8, 156u8, 56u8, 194u8, 123u8, 219u8, 224u8,
    ],
    vk_beta_g2: [
        30u8, 26u8, 208u8, 38u8, 214u8, 150u8, 85u8, 112u8, 137u8, 196u8, 201u8, 49u8, 145u8,
        104u8, 35u8, 218u8, 253u8, 250u8, 60u8, 253u8, 2u8, 218u8, 199u8, 240u8, 108u8, 252u8,
        234u8, 219u8, 29u8, 74u8, 246u8, 213u8, 21u8, 123u8, 150u8, 37u8, 110u8, 212u8, 57u8, 74u8,
        26u8, 243u8, 104u8, 162u8, 240u8, 26u8, 160u8, 96u8, 93u8, 100u8, 172u8, 161u8, 250u8,
        169u8, 29u8, 56u8, 167u8, 9u8, 162u8, 225u8, 34u8, 53u8, 155u8, 117u8, 10u8, 209u8, 40u8,
        14u8, 34u8, 95u8, 115u8, 151u8, 202u8, 215u8, 61u8, 157u8, 39u8, 208u8, 111u8, 212u8,
        168u8, 171u8, 201u8, 176u8, 38u8, 62u8, 172u8, 120u8, 157u8, 27u8, 34u8, 0u8, 4u8, 171u8,
        150u8, 109u8, 23u8, 59u8, 53u8, 220u8, 150u8, 179u8, 161u8, 120u8, 226u8, 181u8, 35u8, 3u8,
        245u8, 101u8, 182u8, 218u8, 120u8, 5u8, 155u8, 64u8, 58u8, 6u8, 110u8, 81u8, 252u8, 119u8,
        222u8, 249u8, 16u8, 190u8, 101u8, 159u8,
    ],
    vk_gamma_g2: [
        42u8, 140u8, 102u8, 96u8, 91u8, 92u8, 219u8, 111u8, 235u8, 117u8, 22u8, 164u8, 107u8,
        232u8, 32u8, 114u8, 129u8, 214u8, 193u8, 182u8, 212u8, 59u8, 0u8, 144u8, 78u8, 57u8, 207u8,
        101u8, 202u8, 157u8, 215u8, 229u8, 34u8, 140u8, 241u8, 106u8, 179u8, 116u8, 137u8, 29u8,
        150u8, 113u8, 229u8, 14u8, 28u8, 60u8, 217u8, 178u8, 146u8, 30u8, 232u8, 226u8, 205u8,
        148u8, 181u8, 63u8, 160u8, 72u8, 18u8, 64u8, 240u8, 187u8, 15u8, 133u8, 7u8, 136u8, 24u8,
        17u8, 121u8, 165u8, 197u8, 45u8, 56u8, 80u8, 150u8, 108u8, 246u8, 233u8, 206u8, 58u8,
        157u8, 145u8, 243u8, 161u8, 99u8, 189u8, 130u8, 205u8, 8u8, 214u8, 77u8, 16u8, 254u8, 12u8,
        94u8, 93u8, 26u8, 61u8, 212u8, 98u8, 200u8, 139u8, 149u8, 39u8, 153u8, 159u8, 110u8, 9u8,
        244u8, 6u8, 206u8, 201u8, 224u8, 145u8, 96u8, 14u8, 143u8, 90u8, 35u8, 7u8, 204u8, 101u8,
        179u8, 176u8, 225u8, 181u8, 247u8, 90u8,
    ],
    vk_delta_g2: [
        10u8, 87u8, 72u8, 175u8, 145u8, 27u8, 88u8, 146u8, 240u8, 145u8, 63u8, 103u8, 169u8, 101u8,
        123u8, 112u8, 143u8, 242u8, 212u8, 88u8, 18u8, 112u8, 25u8, 70u8, 53u8, 116u8, 10u8, 183u8,
        244u8, 103u8, 56u8, 23u8, 47u8, 125u8, 200u8, 5u8, 142u8, 215u8, 211u8, 242u8, 145u8,
        211u8, 242u8, 173u8, 235u8, 1u8, 124u8, 196u8, 118u8, 215u8, 8u8, 108u8, 226u8, 116u8,
        72u8, 180u8, 66u8, 238u8, 104u8, 182u8, 45u8, 70u8, 240u8, 196u8, 11u8, 156u8, 129u8,
        212u8, 238u8, 144u8, 119u8, 51u8, 140u8, 110u8, 73u8, 8u8, 55u8, 223u8, 95u8, 59u8, 216u8,
        104u8, 42u8, 237u8, 172u8, 85u8, 93u8, 240u8, 251u8, 190u8, 243u8, 111u8, 43u8, 74u8, 92u8,
        43u8, 0u8, 252u8, 53u8, 2u8, 221u8, 90u8, 94u8, 250u8, 203u8, 101u8, 220u8, 251u8, 27u8,
        49u8, 108u8, 182u8, 38u8, 214u8, 118u8, 180u8, 252u8, 40u8, 37u8, 116u8, 31u8, 132u8, 87u8,
        191u8, 69u8, 189u8, 126u8, 244u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [62u8, 157u8, 54u8, 69u8, 241u8, 147u8, 225u8, 250u8, 217u8, 145u8, 182u8, 123u8, 104u8, 45u8, 26u8, 10u8, 110u8, 143u8, 249u8, 21u8, 81u8, 145u8, 133u8, 91u8, 210u8, 58u8, 185u8, 203u8, 183u8, 145u8, 131u8, 184u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_ef801d25eb2ae1bb")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x003e9d3645f193e1fad991b67b682d1a0a6e8ff9155191855bd23ab9cbb79183b8\x00=======END GROTH16 VK SETUP V1=======\x00";
