// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        6u8, 176u8, 18u8, 220u8, 146u8, 85u8, 193u8, 40u8, 150u8, 221u8, 33u8, 124u8, 44u8, 5u8,
        94u8, 156u8, 234u8, 100u8, 222u8, 104u8, 217u8, 25u8, 86u8, 161u8, 84u8, 88u8, 102u8,
        161u8, 173u8, 31u8, 125u8, 125u8, 21u8, 134u8, 47u8, 91u8, 228u8, 226u8, 61u8, 176u8, 38u8,
        249u8, 93u8, 88u8, 130u8, 210u8, 250u8, 102u8, 114u8, 65u8, 189u8, 45u8, 132u8, 57u8, 18u8,
        121u8, 58u8, 100u8, 182u8, 67u8, 193u8, 135u8, 128u8, 144u8,
    ],
    [
        43u8, 180u8, 74u8, 201u8, 70u8, 121u8, 245u8, 98u8, 204u8, 175u8, 78u8, 253u8, 59u8, 148u8,
        215u8, 97u8, 194u8, 62u8, 179u8, 31u8, 233u8, 163u8, 16u8, 167u8, 39u8, 143u8, 228u8,
        215u8, 181u8, 165u8, 140u8, 158u8, 11u8, 144u8, 218u8, 228u8, 146u8, 250u8, 147u8, 225u8,
        236u8, 64u8, 27u8, 50u8, 76u8, 242u8, 116u8, 186u8, 201u8, 90u8, 27u8, 247u8, 32u8, 70u8,
        104u8, 105u8, 65u8, 49u8, 178u8, 57u8, 30u8, 242u8, 185u8, 218u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        5u8, 51u8, 19u8, 252u8, 239u8, 247u8, 196u8, 240u8, 166u8, 8u8, 217u8, 34u8, 84u8, 246u8,
        153u8, 193u8, 203u8, 242u8, 200u8, 108u8, 134u8, 84u8, 106u8, 106u8, 214u8, 130u8, 118u8,
        182u8, 89u8, 220u8, 98u8, 4u8, 19u8, 105u8, 98u8, 159u8, 58u8, 46u8, 216u8, 111u8, 45u8,
        168u8, 178u8, 36u8, 143u8, 216u8, 249u8, 234u8, 239u8, 144u8, 90u8, 109u8, 99u8, 156u8,
        112u8, 173u8, 18u8, 68u8, 255u8, 227u8, 224u8, 208u8, 235u8, 131u8,
    ],
    vk_beta_g2: [
        25u8, 58u8, 216u8, 21u8, 183u8, 222u8, 7u8, 124u8, 255u8, 68u8, 143u8, 63u8, 12u8, 221u8,
        128u8, 203u8, 63u8, 123u8, 231u8, 130u8, 84u8, 4u8, 219u8, 48u8, 11u8, 224u8, 75u8, 99u8,
        118u8, 120u8, 154u8, 27u8, 2u8, 118u8, 97u8, 17u8, 173u8, 180u8, 4u8, 126u8, 157u8, 194u8,
        16u8, 110u8, 13u8, 163u8, 211u8, 119u8, 36u8, 150u8, 182u8, 142u8, 131u8, 7u8, 142u8,
        239u8, 135u8, 51u8, 214u8, 30u8, 182u8, 158u8, 130u8, 59u8, 9u8, 213u8, 73u8, 53u8, 222u8,
        45u8, 168u8, 179u8, 185u8, 121u8, 100u8, 40u8, 61u8, 89u8, 177u8, 111u8, 228u8, 110u8,
        210u8, 142u8, 132u8, 45u8, 22u8, 24u8, 111u8, 90u8, 52u8, 47u8, 138u8, 225u8, 190u8, 122u8,
        44u8, 8u8, 219u8, 0u8, 127u8, 106u8, 229u8, 13u8, 12u8, 169u8, 66u8, 122u8, 194u8, 173u8,
        3u8, 43u8, 173u8, 41u8, 8u8, 134u8, 58u8, 206u8, 219u8, 18u8, 47u8, 106u8, 72u8, 183u8,
        225u8, 182u8, 35u8, 206u8,
    ],
    vk_gamma_g2: [
        0u8, 131u8, 103u8, 201u8, 168u8, 173u8, 102u8, 80u8, 110u8, 54u8, 201u8, 81u8, 118u8,
        180u8, 109u8, 60u8, 158u8, 120u8, 73u8, 205u8, 28u8, 82u8, 112u8, 127u8, 123u8, 110u8,
        155u8, 187u8, 234u8, 20u8, 76u8, 225u8, 30u8, 195u8, 78u8, 161u8, 253u8, 38u8, 243u8, 36u8,
        130u8, 62u8, 154u8, 12u8, 46u8, 103u8, 25u8, 77u8, 138u8, 60u8, 132u8, 166u8, 23u8, 50u8,
        212u8, 158u8, 201u8, 12u8, 60u8, 83u8, 120u8, 157u8, 12u8, 105u8, 30u8, 83u8, 103u8, 108u8,
        232u8, 249u8, 19u8, 155u8, 14u8, 40u8, 158u8, 162u8, 5u8, 164u8, 118u8, 240u8, 72u8, 25u8,
        34u8, 249u8, 169u8, 114u8, 225u8, 55u8, 22u8, 233u8, 55u8, 234u8, 181u8, 168u8, 20u8, 84u8,
        35u8, 97u8, 125u8, 36u8, 146u8, 40u8, 155u8, 175u8, 54u8, 59u8, 203u8, 27u8, 198u8, 68u8,
        218u8, 203u8, 223u8, 123u8, 51u8, 208u8, 240u8, 190u8, 219u8, 86u8, 248u8, 28u8, 221u8,
        213u8, 215u8, 102u8, 84u8, 144u8,
    ],
    vk_delta_g2: [
        0u8, 135u8, 227u8, 85u8, 107u8, 250u8, 204u8, 130u8, 130u8, 65u8, 58u8, 195u8, 60u8, 217u8,
        0u8, 188u8, 152u8, 133u8, 200u8, 155u8, 56u8, 51u8, 210u8, 72u8, 42u8, 37u8, 1u8, 28u8,
        45u8, 62u8, 65u8, 231u8, 20u8, 102u8, 123u8, 34u8, 84u8, 231u8, 248u8, 149u8, 62u8, 235u8,
        159u8, 189u8, 26u8, 153u8, 95u8, 18u8, 244u8, 71u8, 48u8, 89u8, 50u8, 147u8, 99u8, 125u8,
        98u8, 152u8, 174u8, 5u8, 40u8, 110u8, 200u8, 160u8, 22u8, 150u8, 248u8, 231u8, 120u8,
        142u8, 178u8, 243u8, 180u8, 87u8, 178u8, 135u8, 18u8, 142u8, 191u8, 216u8, 58u8, 206u8,
        200u8, 54u8, 185u8, 172u8, 1u8, 47u8, 139u8, 29u8, 108u8, 195u8, 39u8, 130u8, 105u8, 37u8,
        25u8, 38u8, 116u8, 229u8, 64u8, 92u8, 53u8, 12u8, 124u8, 189u8, 36u8, 55u8, 194u8, 62u8,
        201u8, 167u8, 117u8, 91u8, 104u8, 57u8, 17u8, 239u8, 198u8, 252u8, 73u8, 251u8, 128u8,
        144u8, 101u8, 11u8, 242u8, 98u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [126u8, 63u8, 252u8, 34u8, 144u8, 80u8, 161u8, 214u8, 214u8, 169u8, 228u8, 52u8, 139u8, 107u8, 209u8, 22u8, 4u8, 16u8, 140u8, 83u8, 89u8, 156u8, 49u8, 154u8, 61u8, 213u8, 159u8, 81u8, 88u8, 5u8, 155u8, 163u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_4d07478f8854ca0b")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x007e3ffc229050a1d6d6a9e4348b6bd11604108c53599c319a3dd59f5158059ba3\x00=======END GROTH16 VK SETUP V1=======\x00";
