// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        38u8, 241u8, 67u8, 251u8, 127u8, 149u8, 234u8, 65u8, 68u8, 238u8, 243u8, 110u8, 185u8,
        233u8, 96u8, 206u8, 3u8, 217u8, 5u8, 236u8, 9u8, 27u8, 112u8, 220u8, 64u8, 216u8, 245u8,
        231u8, 158u8, 103u8, 87u8, 254u8, 15u8, 9u8, 188u8, 222u8, 19u8, 183u8, 94u8, 234u8, 156u8,
        12u8, 1u8, 13u8, 145u8, 251u8, 16u8, 134u8, 181u8, 199u8, 80u8, 80u8, 246u8, 176u8, 121u8,
        218u8, 42u8, 177u8, 99u8, 72u8, 84u8, 217u8, 247u8, 6u8,
    ],
    [
        11u8, 146u8, 126u8, 165u8, 73u8, 175u8, 198u8, 227u8, 50u8, 54u8, 164u8, 117u8, 62u8,
        230u8, 47u8, 48u8, 224u8, 116u8, 135u8, 197u8, 163u8, 91u8, 143u8, 132u8, 8u8, 93u8, 121u8,
        17u8, 82u8, 130u8, 44u8, 196u8, 26u8, 220u8, 255u8, 5u8, 228u8, 238u8, 190u8, 193u8, 219u8,
        61u8, 30u8, 8u8, 236u8, 23u8, 115u8, 5u8, 144u8, 46u8, 141u8, 158u8, 131u8, 168u8, 252u8,
        91u8, 156u8, 231u8, 9u8, 220u8, 31u8, 59u8, 218u8, 189u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        27u8, 28u8, 53u8, 77u8, 49u8, 255u8, 107u8, 118u8, 45u8, 35u8, 146u8, 48u8, 44u8, 105u8,
        167u8, 242u8, 221u8, 204u8, 21u8, 26u8, 234u8, 149u8, 19u8, 131u8, 39u8, 171u8, 20u8, 81u8,
        166u8, 153u8, 74u8, 180u8, 8u8, 207u8, 238u8, 159u8, 39u8, 68u8, 253u8, 200u8, 37u8, 102u8,
        23u8, 76u8, 200u8, 48u8, 104u8, 208u8, 41u8, 68u8, 170u8, 16u8, 97u8, 95u8, 34u8, 235u8,
        206u8, 11u8, 202u8, 153u8, 137u8, 104u8, 21u8, 108u8,
    ],
    vk_beta_g2: [
        1u8, 69u8, 202u8, 145u8, 192u8, 220u8, 222u8, 13u8, 249u8, 181u8, 106u8, 244u8, 76u8,
        134u8, 170u8, 161u8, 246u8, 182u8, 94u8, 228u8, 197u8, 43u8, 237u8, 246u8, 50u8, 158u8,
        118u8, 114u8, 121u8, 140u8, 180u8, 7u8, 46u8, 141u8, 200u8, 128u8, 193u8, 100u8, 251u8,
        83u8, 27u8, 30u8, 218u8, 104u8, 80u8, 226u8, 178u8, 13u8, 211u8, 116u8, 195u8, 196u8, 3u8,
        133u8, 146u8, 2u8, 173u8, 149u8, 53u8, 3u8, 89u8, 175u8, 160u8, 129u8, 38u8, 72u8, 53u8,
        29u8, 19u8, 111u8, 207u8, 226u8, 61u8, 192u8, 240u8, 83u8, 204u8, 110u8, 153u8, 103u8,
        217u8, 98u8, 116u8, 204u8, 205u8, 147u8, 83u8, 135u8, 57u8, 72u8, 74u8, 218u8, 43u8, 226u8,
        166u8, 246u8, 20u8, 150u8, 25u8, 14u8, 111u8, 120u8, 62u8, 228u8, 130u8, 172u8, 117u8,
        26u8, 57u8, 86u8, 197u8, 102u8, 232u8, 79u8, 128u8, 6u8, 172u8, 163u8, 211u8, 136u8, 17u8,
        254u8, 3u8, 61u8, 237u8, 117u8, 72u8, 186u8,
    ],
    vk_gamma_g2: [
        38u8, 143u8, 229u8, 80u8, 6u8, 118u8, 183u8, 37u8, 179u8, 165u8, 175u8, 96u8, 6u8, 228u8,
        142u8, 141u8, 68u8, 172u8, 248u8, 140u8, 136u8, 110u8, 138u8, 99u8, 210u8, 81u8, 176u8,
        222u8, 209u8, 226u8, 201u8, 113u8, 7u8, 227u8, 170u8, 26u8, 238u8, 122u8, 57u8, 124u8,
        127u8, 168u8, 1u8, 197u8, 63u8, 94u8, 185u8, 207u8, 22u8, 122u8, 91u8, 41u8, 75u8, 18u8,
        56u8, 130u8, 79u8, 175u8, 15u8, 248u8, 168u8, 85u8, 12u8, 180u8, 0u8, 147u8, 18u8, 135u8,
        151u8, 154u8, 98u8, 136u8, 157u8, 11u8, 4u8, 231u8, 2u8, 93u8, 198u8, 41u8, 52u8, 48u8,
        58u8, 153u8, 88u8, 223u8, 102u8, 178u8, 3u8, 237u8, 170u8, 225u8, 6u8, 57u8, 119u8, 144u8,
        24u8, 20u8, 129u8, 154u8, 243u8, 10u8, 21u8, 97u8, 212u8, 30u8, 105u8, 104u8, 115u8, 95u8,
        124u8, 193u8, 202u8, 132u8, 246u8, 103u8, 179u8, 90u8, 126u8, 40u8, 24u8, 60u8, 195u8,
        70u8, 35u8, 114u8, 40u8, 251u8,
    ],
    vk_delta_g2: [
        11u8, 55u8, 223u8, 209u8, 213u8, 156u8, 248u8, 1u8, 107u8, 103u8, 227u8, 185u8, 13u8,
        226u8, 190u8, 187u8, 119u8, 169u8, 213u8, 172u8, 234u8, 191u8, 46u8, 63u8, 192u8, 242u8,
        66u8, 184u8, 115u8, 193u8, 90u8, 149u8, 12u8, 64u8, 162u8, 245u8, 105u8, 106u8, 221u8,
        86u8, 47u8, 44u8, 138u8, 240u8, 221u8, 198u8, 181u8, 53u8, 195u8, 65u8, 199u8, 228u8, 50u8,
        114u8, 246u8, 240u8, 68u8, 225u8, 105u8, 100u8, 15u8, 95u8, 28u8, 30u8, 47u8, 67u8, 208u8,
        83u8, 149u8, 26u8, 170u8, 216u8, 192u8, 82u8, 13u8, 155u8, 5u8, 92u8, 184u8, 115u8, 34u8,
        154u8, 177u8, 70u8, 164u8, 100u8, 207u8, 214u8, 113u8, 234u8, 71u8, 142u8, 73u8, 170u8,
        68u8, 191u8, 30u8, 182u8, 232u8, 62u8, 123u8, 131u8, 11u8, 124u8, 179u8, 113u8, 225u8,
        163u8, 75u8, 178u8, 197u8, 202u8, 44u8, 30u8, 21u8, 153u8, 58u8, 248u8, 255u8, 130u8, 67u8,
        155u8, 68u8, 13u8, 118u8, 161u8, 110u8, 54u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [39u8, 254u8, 65u8, 133u8, 18u8, 238u8, 11u8, 229u8, 203u8, 47u8, 130u8, 41u8, 14u8, 171u8, 74u8, 178u8, 14u8, 210u8, 211u8, 37u8, 73u8, 225u8, 216u8, 215u8, 191u8, 161u8, 250u8, 91u8, 69u8, 223u8, 98u8, 233u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_077ca459124f1a2d")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0027fe418512ee0be5cb2f82290eab4ab20ed2d32549e1d8d7bfa1fa5b45df62e9\x00=======END GROTH16 VK SETUP V1=======\x00";
