// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        46u8, 12u8, 130u8, 147u8, 249u8, 69u8, 59u8, 189u8, 152u8, 143u8, 190u8, 101u8, 31u8,
        176u8, 132u8, 33u8, 117u8, 149u8, 196u8, 169u8, 189u8, 116u8, 124u8, 158u8, 106u8, 36u8,
        204u8, 71u8, 66u8, 224u8, 55u8, 103u8, 24u8, 144u8, 113u8, 105u8, 123u8, 159u8, 231u8,
        150u8, 75u8, 173u8, 104u8, 126u8, 106u8, 137u8, 135u8, 226u8, 124u8, 78u8, 50u8, 179u8,
        141u8, 48u8, 215u8, 179u8, 153u8, 175u8, 161u8, 63u8, 67u8, 212u8, 145u8, 64u8,
    ],
    [
        41u8, 247u8, 42u8, 157u8, 39u8, 140u8, 57u8, 203u8, 220u8, 111u8, 255u8, 171u8, 53u8, 19u8,
        8u8, 59u8, 203u8, 195u8, 17u8, 116u8, 187u8, 221u8, 46u8, 103u8, 249u8, 239u8, 229u8, 36u8,
        243u8, 27u8, 18u8, 64u8, 38u8, 58u8, 250u8, 111u8, 251u8, 72u8, 209u8, 223u8, 20u8, 164u8,
        31u8, 194u8, 153u8, 172u8, 232u8, 252u8, 201u8, 157u8, 73u8, 83u8, 116u8, 97u8, 120u8,
        52u8, 206u8, 109u8, 154u8, 102u8, 83u8, 177u8, 69u8, 125u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        14u8, 174u8, 113u8, 157u8, 237u8, 157u8, 183u8, 114u8, 246u8, 199u8, 180u8, 253u8, 152u8,
        86u8, 10u8, 42u8, 114u8, 253u8, 34u8, 209u8, 162u8, 65u8, 102u8, 119u8, 37u8, 187u8, 42u8,
        133u8, 35u8, 76u8, 73u8, 53u8, 14u8, 127u8, 94u8, 55u8, 93u8, 113u8, 204u8, 118u8, 155u8,
        192u8, 68u8, 31u8, 109u8, 99u8, 244u8, 162u8, 119u8, 23u8, 121u8, 189u8, 140u8, 149u8,
        114u8, 107u8, 15u8, 192u8, 35u8, 47u8, 96u8, 168u8, 19u8, 166u8,
    ],
    vk_beta_g2: [
        37u8, 86u8, 213u8, 51u8, 45u8, 151u8, 170u8, 201u8, 180u8, 45u8, 152u8, 250u8, 162u8, 95u8,
        255u8, 141u8, 174u8, 113u8, 59u8, 75u8, 161u8, 123u8, 125u8, 3u8, 105u8, 100u8, 121u8,
        153u8, 77u8, 187u8, 176u8, 135u8, 15u8, 144u8, 74u8, 116u8, 212u8, 95u8, 4u8, 167u8, 234u8,
        56u8, 241u8, 64u8, 65u8, 192u8, 156u8, 225u8, 218u8, 238u8, 53u8, 40u8, 242u8, 180u8,
        201u8, 179u8, 240u8, 208u8, 247u8, 63u8, 85u8, 47u8, 25u8, 98u8, 29u8, 26u8, 34u8, 54u8,
        122u8, 135u8, 183u8, 201u8, 119u8, 31u8, 69u8, 162u8, 45u8, 152u8, 192u8, 87u8, 99u8,
        233u8, 168u8, 238u8, 242u8, 106u8, 51u8, 134u8, 55u8, 186u8, 114u8, 232u8, 103u8, 242u8,
        110u8, 80u8, 40u8, 1u8, 55u8, 100u8, 67u8, 241u8, 57u8, 226u8, 76u8, 242u8, 54u8, 153u8,
        179u8, 229u8, 186u8, 35u8, 165u8, 241u8, 43u8, 136u8, 138u8, 11u8, 41u8, 242u8, 191u8,
        141u8, 31u8, 72u8, 181u8, 38u8, 162u8, 31u8,
    ],
    vk_gamma_g2: [
        17u8, 123u8, 126u8, 90u8, 104u8, 231u8, 225u8, 165u8, 19u8, 109u8, 66u8, 31u8, 236u8,
        254u8, 66u8, 157u8, 203u8, 103u8, 220u8, 240u8, 116u8, 223u8, 65u8, 62u8, 103u8, 213u8,
        225u8, 44u8, 34u8, 120u8, 14u8, 238u8, 20u8, 32u8, 251u8, 250u8, 42u8, 101u8, 184u8, 245u8,
        166u8, 205u8, 9u8, 182u8, 164u8, 13u8, 255u8, 123u8, 136u8, 114u8, 6u8, 199u8, 57u8, 160u8,
        30u8, 3u8, 186u8, 82u8, 12u8, 207u8, 0u8, 123u8, 70u8, 20u8, 39u8, 249u8, 87u8, 195u8,
        96u8, 32u8, 117u8, 129u8, 2u8, 10u8, 232u8, 38u8, 126u8, 227u8, 59u8, 93u8, 192u8, 98u8,
        15u8, 207u8, 58u8, 222u8, 254u8, 178u8, 60u8, 207u8, 231u8, 113u8, 136u8, 224u8, 135u8,
        85u8, 2u8, 32u8, 225u8, 216u8, 95u8, 90u8, 158u8, 13u8, 187u8, 222u8, 143u8, 180u8, 92u8,
        234u8, 49u8, 42u8, 192u8, 92u8, 36u8, 77u8, 214u8, 129u8, 61u8, 128u8, 188u8, 36u8, 108u8,
        48u8, 50u8, 113u8, 225u8, 99u8,
    ],
    vk_delta_g2: [
        38u8, 15u8, 129u8, 231u8, 1u8, 230u8, 78u8, 51u8, 19u8, 60u8, 69u8, 223u8, 42u8, 203u8,
        227u8, 97u8, 78u8, 18u8, 29u8, 55u8, 96u8, 28u8, 238u8, 209u8, 189u8, 156u8, 236u8, 253u8,
        102u8, 66u8, 112u8, 106u8, 16u8, 215u8, 34u8, 199u8, 156u8, 196u8, 149u8, 187u8, 104u8,
        192u8, 165u8, 204u8, 197u8, 127u8, 240u8, 105u8, 221u8, 1u8, 188u8, 112u8, 139u8, 185u8,
        31u8, 75u8, 252u8, 156u8, 50u8, 94u8, 195u8, 44u8, 125u8, 239u8, 4u8, 239u8, 100u8, 4u8,
        141u8, 187u8, 225u8, 56u8, 97u8, 90u8, 80u8, 110u8, 62u8, 232u8, 116u8, 235u8, 39u8, 239u8,
        187u8, 65u8, 157u8, 4u8, 53u8, 33u8, 211u8, 102u8, 125u8, 25u8, 146u8, 220u8, 167u8, 180u8,
        32u8, 164u8, 139u8, 177u8, 29u8, 79u8, 140u8, 26u8, 204u8, 36u8, 218u8, 184u8, 122u8,
        212u8, 200u8, 140u8, 229u8, 218u8, 185u8, 228u8, 180u8, 39u8, 127u8, 166u8, 124u8, 154u8,
        155u8, 217u8, 121u8, 100u8, 124u8, 252u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [20u8, 114u8, 42u8, 200u8, 140u8, 255u8, 37u8, 13u8, 154u8, 213u8, 49u8, 150u8, 130u8, 112u8, 230u8, 212u8, 158u8, 45u8, 59u8, 134u8, 176u8, 52u8, 47u8, 26u8, 174u8, 199u8, 197u8, 197u8, 218u8, 214u8, 221u8, 14u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_ce2a05cc050dc073")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0014722ac88cff250d9ad531968270e6d49e2d3b86b0342f1aaec7c5c5dad6dd0e\x00=======END GROTH16 VK SETUP V1=======\x00";
