// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        17u8, 65u8, 171u8, 51u8, 195u8, 168u8, 149u8, 137u8, 97u8, 176u8, 9u8, 190u8, 55u8, 64u8,
        118u8, 180u8, 127u8, 14u8, 97u8, 144u8, 233u8, 187u8, 144u8, 51u8, 46u8, 112u8, 58u8, 51u8,
        70u8, 92u8, 160u8, 99u8, 20u8, 11u8, 107u8, 30u8, 208u8, 58u8, 221u8, 227u8, 71u8, 108u8,
        231u8, 55u8, 167u8, 163u8, 224u8, 31u8, 28u8, 44u8, 212u8, 69u8, 251u8, 97u8, 70u8, 244u8,
        243u8, 31u8, 9u8, 219u8, 79u8, 142u8, 54u8, 21u8,
    ],
    [
        20u8, 114u8, 18u8, 74u8, 50u8, 223u8, 152u8, 24u8, 152u8, 97u8, 81u8, 214u8, 132u8, 233u8,
        91u8, 166u8, 235u8, 181u8, 39u8, 162u8, 185u8, 168u8, 205u8, 254u8, 101u8, 88u8, 39u8,
        147u8, 62u8, 180u8, 75u8, 197u8, 40u8, 217u8, 229u8, 0u8, 255u8, 68u8, 83u8, 151u8, 76u8,
        119u8, 47u8, 133u8, 183u8, 39u8, 61u8, 87u8, 67u8, 110u8, 153u8, 141u8, 40u8, 51u8, 226u8,
        177u8, 74u8, 114u8, 80u8, 172u8, 10u8, 27u8, 142u8, 7u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        30u8, 99u8, 244u8, 125u8, 166u8, 29u8, 111u8, 78u8, 125u8, 23u8, 158u8, 0u8, 87u8, 28u8,
        89u8, 243u8, 92u8, 162u8, 143u8, 144u8, 232u8, 76u8, 28u8, 191u8, 219u8, 130u8, 19u8, 45u8,
        97u8, 159u8, 198u8, 182u8, 20u8, 230u8, 176u8, 25u8, 151u8, 216u8, 101u8, 255u8, 253u8,
        188u8, 206u8, 36u8, 124u8, 32u8, 254u8, 25u8, 190u8, 188u8, 250u8, 53u8, 5u8, 206u8, 167u8,
        116u8, 183u8, 206u8, 208u8, 180u8, 112u8, 243u8, 131u8, 172u8,
    ],
    vk_beta_g2: [
        43u8, 189u8, 76u8, 250u8, 212u8, 180u8, 199u8, 93u8, 100u8, 168u8, 106u8, 147u8, 30u8,
        20u8, 183u8, 82u8, 212u8, 221u8, 16u8, 156u8, 115u8, 227u8, 20u8, 188u8, 96u8, 222u8,
        227u8, 182u8, 165u8, 218u8, 157u8, 113u8, 20u8, 88u8, 68u8, 181u8, 116u8, 139u8, 18u8,
        43u8, 204u8, 2u8, 191u8, 251u8, 135u8, 99u8, 175u8, 29u8, 135u8, 174u8, 108u8, 108u8, 62u8,
        38u8, 185u8, 102u8, 213u8, 71u8, 142u8, 197u8, 183u8, 206u8, 83u8, 57u8, 11u8, 85u8, 170u8,
        54u8, 219u8, 60u8, 136u8, 43u8, 185u8, 39u8, 193u8, 114u8, 67u8, 213u8, 213u8, 102u8, 18u8,
        125u8, 64u8, 96u8, 165u8, 251u8, 251u8, 107u8, 225u8, 161u8, 101u8, 22u8, 90u8, 27u8, 22u8,
        82u8, 14u8, 86u8, 126u8, 8u8, 201u8, 84u8, 190u8, 173u8, 105u8, 234u8, 27u8, 91u8, 72u8,
        163u8, 214u8, 210u8, 180u8, 132u8, 20u8, 30u8, 23u8, 193u8, 101u8, 84u8, 182u8, 24u8, 13u8,
        91u8, 157u8, 21u8, 162u8, 16u8,
    ],
    vk_gamma_g2: [
        41u8, 78u8, 62u8, 57u8, 210u8, 143u8, 39u8, 65u8, 225u8, 80u8, 255u8, 222u8, 116u8, 123u8,
        70u8, 215u8, 237u8, 90u8, 96u8, 148u8, 142u8, 129u8, 133u8, 41u8, 247u8, 92u8, 247u8, 21u8,
        36u8, 24u8, 188u8, 11u8, 12u8, 244u8, 185u8, 140u8, 116u8, 78u8, 253u8, 23u8, 3u8, 86u8,
        21u8, 91u8, 4u8, 27u8, 248u8, 185u8, 127u8, 116u8, 38u8, 64u8, 203u8, 222u8, 90u8, 78u8,
        24u8, 211u8, 53u8, 0u8, 172u8, 103u8, 96u8, 84u8, 38u8, 23u8, 213u8, 67u8, 122u8, 166u8,
        207u8, 1u8, 191u8, 231u8, 173u8, 189u8, 188u8, 176u8, 42u8, 106u8, 90u8, 221u8, 126u8,
        72u8, 254u8, 162u8, 119u8, 91u8, 33u8, 241u8, 165u8, 65u8, 8u8, 49u8, 68u8, 115u8, 33u8,
        137u8, 192u8, 185u8, 116u8, 131u8, 31u8, 176u8, 21u8, 39u8, 251u8, 74u8, 114u8, 32u8,
        117u8, 104u8, 116u8, 89u8, 128u8, 253u8, 222u8, 215u8, 180u8, 143u8, 220u8, 226u8, 90u8,
        208u8, 146u8, 163u8, 249u8, 239u8,
    ],
    vk_delta_g2: [
        27u8, 77u8, 214u8, 107u8, 132u8, 44u8, 125u8, 205u8, 46u8, 40u8, 117u8, 103u8, 201u8,
        106u8, 235u8, 48u8, 238u8, 174u8, 33u8, 97u8, 243u8, 24u8, 179u8, 124u8, 71u8, 115u8,
        170u8, 50u8, 174u8, 156u8, 5u8, 138u8, 15u8, 111u8, 153u8, 51u8, 40u8, 95u8, 27u8, 240u8,
        190u8, 179u8, 182u8, 236u8, 164u8, 59u8, 64u8, 131u8, 75u8, 182u8, 46u8, 178u8, 54u8, 77u8,
        105u8, 55u8, 132u8, 220u8, 241u8, 3u8, 209u8, 226u8, 145u8, 38u8, 29u8, 50u8, 151u8, 34u8,
        201u8, 118u8, 28u8, 118u8, 66u8, 250u8, 75u8, 177u8, 110u8, 111u8, 182u8, 0u8, 165u8,
        240u8, 148u8, 101u8, 185u8, 107u8, 66u8, 254u8, 162u8, 97u8, 82u8, 226u8, 237u8, 180u8,
        244u8, 254u8, 28u8, 161u8, 85u8, 29u8, 111u8, 3u8, 203u8, 145u8, 154u8, 30u8, 238u8, 146u8,
        236u8, 70u8, 140u8, 159u8, 24u8, 252u8, 158u8, 93u8, 63u8, 2u8, 233u8, 14u8, 53u8, 172u8,
        177u8, 30u8, 165u8, 143u8, 111u8, 51u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [73u8, 117u8, 52u8, 98u8, 208u8, 174u8, 143u8, 68u8, 30u8, 188u8, 234u8, 75u8, 105u8, 241u8, 58u8, 142u8, 59u8, 151u8, 136u8, 45u8, 181u8, 14u8, 202u8, 4u8, 146u8, 57u8, 119u8, 41u8, 171u8, 226u8, 106u8, 26u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_fb1d27cbda148674")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x0049753462d0ae8f441ebcea4b69f13a8e3b97882db50eca0492397729abe26a1a\x00=======END GROTH16 VK SETUP V1=======\x00";
