// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        24u8, 190u8, 245u8, 143u8, 175u8, 135u8, 66u8, 225u8, 47u8, 40u8, 220u8, 47u8, 17u8, 137u8,
        161u8, 175u8, 219u8, 245u8, 113u8, 223u8, 15u8, 248u8, 57u8, 112u8, 204u8, 50u8, 98u8,
        183u8, 85u8, 94u8, 121u8, 92u8, 42u8, 195u8, 4u8, 161u8, 181u8, 28u8, 68u8, 214u8, 247u8,
        105u8, 71u8, 36u8, 120u8, 180u8, 37u8, 138u8, 128u8, 68u8, 243u8, 219u8, 37u8, 188u8,
        190u8, 169u8, 217u8, 238u8, 114u8, 152u8, 236u8, 171u8, 76u8, 111u8,
    ],
    [
        14u8, 18u8, 187u8, 99u8, 70u8, 171u8, 190u8, 45u8, 75u8, 137u8, 75u8, 243u8, 46u8, 191u8,
        170u8, 61u8, 112u8, 42u8, 6u8, 97u8, 48u8, 4u8, 245u8, 135u8, 173u8, 67u8, 138u8, 104u8,
        87u8, 214u8, 191u8, 135u8, 2u8, 121u8, 9u8, 31u8, 16u8, 120u8, 18u8, 94u8, 6u8, 171u8,
        54u8, 239u8, 241u8, 106u8, 37u8, 147u8, 21u8, 193u8, 180u8, 161u8, 163u8, 178u8, 10u8,
        181u8, 42u8, 222u8, 237u8, 170u8, 211u8, 110u8, 77u8, 24u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        26u8, 131u8, 172u8, 255u8, 155u8, 136u8, 142u8, 219u8, 37u8, 105u8, 196u8, 124u8, 80u8,
        110u8, 219u8, 181u8, 17u8, 6u8, 61u8, 197u8, 26u8, 33u8, 92u8, 253u8, 235u8, 25u8, 22u8,
        209u8, 74u8, 172u8, 93u8, 206u8, 39u8, 58u8, 217u8, 105u8, 220u8, 98u8, 72u8, 217u8, 110u8,
        210u8, 239u8, 102u8, 230u8, 184u8, 255u8, 118u8, 136u8, 109u8, 205u8, 173u8, 94u8, 139u8,
        2u8, 1u8, 210u8, 127u8, 159u8, 33u8, 108u8, 9u8, 28u8, 82u8,
    ],
    vk_beta_g2: [
        8u8, 59u8, 76u8, 8u8, 158u8, 68u8, 196u8, 167u8, 69u8, 106u8, 98u8, 168u8, 65u8, 230u8,
        230u8, 39u8, 182u8, 156u8, 25u8, 165u8, 104u8, 65u8, 50u8, 15u8, 226u8, 17u8, 87u8, 113u8,
        89u8, 248u8, 40u8, 213u8, 14u8, 237u8, 30u8, 142u8, 216u8, 168u8, 68u8, 124u8, 19u8, 102u8,
        165u8, 103u8, 196u8, 195u8, 111u8, 205u8, 27u8, 35u8, 135u8, 151u8, 70u8, 193u8, 1u8,
        122u8, 117u8, 85u8, 232u8, 59u8, 152u8, 234u8, 255u8, 7u8, 20u8, 34u8, 228u8, 107u8, 157u8,
        20u8, 19u8, 240u8, 9u8, 191u8, 12u8, 212u8, 85u8, 16u8, 253u8, 227u8, 47u8, 90u8, 112u8,
        83u8, 150u8, 83u8, 214u8, 175u8, 16u8, 142u8, 103u8, 213u8, 97u8, 234u8, 72u8, 108u8, 3u8,
        75u8, 181u8, 94u8, 8u8, 72u8, 98u8, 158u8, 135u8, 69u8, 57u8, 20u8, 128u8, 170u8, 62u8,
        137u8, 218u8, 230u8, 157u8, 182u8, 149u8, 179u8, 123u8, 223u8, 60u8, 30u8, 178u8, 229u8,
        9u8, 254u8, 219u8, 238u8,
    ],
    vk_gamma_g2: [
        24u8, 170u8, 254u8, 234u8, 110u8, 36u8, 1u8, 152u8, 252u8, 25u8, 198u8, 17u8, 142u8, 25u8,
        211u8, 1u8, 97u8, 113u8, 134u8, 16u8, 123u8, 207u8, 43u8, 34u8, 54u8, 75u8, 254u8, 66u8,
        49u8, 218u8, 28u8, 74u8, 34u8, 242u8, 219u8, 1u8, 151u8, 144u8, 140u8, 209u8, 9u8, 234u8,
        109u8, 218u8, 36u8, 110u8, 26u8, 154u8, 182u8, 172u8, 89u8, 124u8, 116u8, 255u8, 154u8,
        65u8, 69u8, 124u8, 133u8, 84u8, 104u8, 157u8, 120u8, 54u8, 19u8, 114u8, 56u8, 173u8, 230u8,
        202u8, 78u8, 135u8, 56u8, 150u8, 177u8, 244u8, 143u8, 235u8, 85u8, 119u8, 139u8, 155u8,
        31u8, 14u8, 113u8, 136u8, 138u8, 222u8, 99u8, 15u8, 174u8, 234u8, 184u8, 210u8, 8u8, 202u8,
        31u8, 154u8, 35u8, 212u8, 100u8, 37u8, 25u8, 136u8, 238u8, 170u8, 142u8, 20u8, 173u8,
        145u8, 54u8, 39u8, 181u8, 51u8, 92u8, 185u8, 54u8, 79u8, 19u8, 101u8, 149u8, 23u8, 196u8,
        95u8, 233u8, 171u8, 75u8, 91u8,
    ],
    vk_delta_g2: [
        5u8, 123u8, 1u8, 10u8, 208u8, 213u8, 164u8, 51u8, 81u8, 197u8, 242u8, 237u8, 170u8, 66u8,
        207u8, 237u8, 0u8, 16u8, 98u8, 16u8, 51u8, 9u8, 189u8, 75u8, 198u8, 236u8, 243u8, 106u8,
        89u8, 12u8, 153u8, 202u8, 43u8, 230u8, 220u8, 221u8, 222u8, 59u8, 199u8, 22u8, 216u8,
        157u8, 84u8, 159u8, 135u8, 101u8, 98u8, 168u8, 181u8, 116u8, 21u8, 189u8, 33u8, 129u8,
        18u8, 2u8, 88u8, 225u8, 153u8, 2u8, 96u8, 196u8, 109u8, 132u8, 18u8, 183u8, 130u8, 234u8,
        20u8, 85u8, 206u8, 178u8, 222u8, 48u8, 165u8, 116u8, 49u8, 9u8, 228u8, 238u8, 225u8, 110u8,
        5u8, 28u8, 86u8, 183u8, 141u8, 213u8, 10u8, 133u8, 51u8, 125u8, 128u8, 35u8, 153u8, 43u8,
        34u8, 174u8, 104u8, 249u8, 252u8, 254u8, 156u8, 178u8, 53u8, 31u8, 145u8, 124u8, 19u8,
        190u8, 54u8, 255u8, 242u8, 224u8, 248u8, 123u8, 1u8, 25u8, 131u8, 120u8, 115u8, 58u8, 35u8,
        121u8, 159u8, 174u8, 92u8, 217u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [43u8, 201u8, 70u8, 182u8, 7u8, 202u8, 205u8, 235u8, 114u8, 249u8, 161u8, 222u8, 41u8, 207u8, 24u8, 167u8, 114u8, 215u8, 238u8, 57u8, 46u8, 20u8, 110u8, 110u8, 169u8, 50u8, 165u8, 22u8, 196u8, 64u8, 22u8, 242u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_38a8c35096aabdef")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x002bc946b607cacdeb72f9a1de29cf18a772d7ee392e146e6ea932a516c44016f2\x00=======END GROTH16 VK SETUP V1=======\x00";
