// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        18u8, 209u8, 255u8, 210u8, 23u8, 47u8, 139u8, 179u8, 52u8, 84u8, 132u8, 170u8, 147u8, 75u8,
        235u8, 139u8, 220u8, 206u8, 90u8, 3u8, 139u8, 56u8, 28u8, 10u8, 46u8, 79u8, 106u8, 5u8,
        183u8, 204u8, 110u8, 254u8, 41u8, 225u8, 184u8, 109u8, 204u8, 244u8, 43u8, 116u8, 206u8,
        103u8, 144u8, 168u8, 81u8, 2u8, 199u8, 14u8, 146u8, 92u8, 69u8, 171u8, 89u8, 190u8, 33u8,
        12u8, 181u8, 251u8, 53u8, 253u8, 55u8, 164u8, 61u8, 194u8,
    ],
    [
        16u8, 155u8, 180u8, 85u8, 221u8, 83u8, 131u8, 112u8, 148u8, 20u8, 88u8, 174u8, 196u8,
        103u8, 116u8, 246u8, 187u8, 77u8, 34u8, 37u8, 99u8, 24u8, 253u8, 147u8, 86u8, 79u8, 59u8,
        42u8, 145u8, 60u8, 246u8, 249u8, 4u8, 206u8, 147u8, 245u8, 97u8, 178u8, 243u8, 59u8, 66u8,
        229u8, 171u8, 156u8, 203u8, 170u8, 145u8, 55u8, 69u8, 248u8, 86u8, 20u8, 180u8, 240u8,
        214u8, 167u8, 241u8, 226u8, 135u8, 192u8, 179u8, 157u8, 209u8, 39u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        32u8, 64u8, 232u8, 65u8, 199u8, 176u8, 81u8, 203u8, 220u8, 186u8, 47u8, 214u8, 180u8,
        240u8, 170u8, 168u8, 165u8, 254u8, 110u8, 237u8, 236u8, 93u8, 54u8, 91u8, 241u8, 135u8,
        78u8, 246u8, 38u8, 250u8, 149u8, 54u8, 24u8, 246u8, 53u8, 218u8, 151u8, 0u8, 216u8, 183u8,
        30u8, 141u8, 96u8, 157u8, 21u8, 84u8, 37u8, 38u8, 128u8, 137u8, 229u8, 142u8, 28u8, 239u8,
        180u8, 102u8, 7u8, 243u8, 69u8, 89u8, 161u8, 178u8, 4u8, 79u8,
    ],
    vk_beta_g2: [
        7u8, 10u8, 137u8, 212u8, 100u8, 69u8, 210u8, 87u8, 167u8, 169u8, 169u8, 155u8, 240u8, 61u8,
        59u8, 88u8, 144u8, 154u8, 202u8, 242u8, 197u8, 44u8, 24u8, 108u8, 89u8, 7u8, 204u8, 148u8,
        68u8, 223u8, 89u8, 181u8, 0u8, 202u8, 155u8, 33u8, 15u8, 229u8, 198u8, 18u8, 175u8, 185u8,
        4u8, 69u8, 86u8, 232u8, 205u8, 23u8, 119u8, 88u8, 121u8, 87u8, 36u8, 209u8, 70u8, 133u8,
        54u8, 147u8, 137u8, 94u8, 84u8, 80u8, 24u8, 226u8, 8u8, 119u8, 111u8, 52u8, 133u8, 125u8,
        145u8, 16u8, 234u8, 203u8, 112u8, 140u8, 88u8, 52u8, 104u8, 79u8, 187u8, 94u8, 238u8, 54u8,
        100u8, 193u8, 140u8, 100u8, 70u8, 232u8, 137u8, 80u8, 68u8, 106u8, 186u8, 186u8, 29u8,
        99u8, 129u8, 83u8, 109u8, 124u8, 195u8, 185u8, 63u8, 97u8, 200u8, 91u8, 162u8, 80u8, 69u8,
        158u8, 3u8, 19u8, 107u8, 209u8, 218u8, 153u8, 253u8, 211u8, 157u8, 16u8, 95u8, 163u8, 49u8,
        74u8, 180u8, 227u8,
    ],
    vk_gamma_g2: [
        18u8, 65u8, 89u8, 146u8, 16u8, 144u8, 75u8, 62u8, 145u8, 100u8, 3u8, 142u8, 8u8, 109u8,
        111u8, 178u8, 187u8, 93u8, 130u8, 121u8, 179u8, 170u8, 226u8, 19u8, 110u8, 112u8, 13u8,
        19u8, 109u8, 50u8, 163u8, 19u8, 32u8, 205u8, 237u8, 180u8, 204u8, 91u8, 18u8, 145u8, 5u8,
        0u8, 120u8, 178u8, 102u8, 160u8, 140u8, 116u8, 155u8, 70u8, 239u8, 82u8, 62u8, 150u8, 65u8,
        101u8, 76u8, 134u8, 196u8, 98u8, 113u8, 115u8, 43u8, 144u8, 29u8, 67u8, 189u8, 255u8,
        240u8, 234u8, 156u8, 109u8, 20u8, 176u8, 246u8, 34u8, 117u8, 59u8, 247u8, 227u8, 118u8,
        103u8, 78u8, 242u8, 180u8, 147u8, 73u8, 105u8, 144u8, 112u8, 64u8, 24u8, 132u8, 144u8,
        175u8, 238u8, 35u8, 167u8, 44u8, 28u8, 112u8, 78u8, 188u8, 7u8, 117u8, 162u8, 112u8, 231u8,
        95u8, 149u8, 203u8, 52u8, 195u8, 142u8, 111u8, 235u8, 182u8, 83u8, 66u8, 58u8, 38u8, 53u8,
        53u8, 168u8, 98u8, 203u8, 63u8, 35u8,
    ],
    vk_delta_g2: [
        29u8, 18u8, 231u8, 113u8, 250u8, 223u8, 191u8, 62u8, 169u8, 19u8, 82u8, 181u8, 10u8, 16u8,
        165u8, 153u8, 90u8, 242u8, 197u8, 90u8, 26u8, 161u8, 202u8, 200u8, 43u8, 170u8, 206u8,
        178u8, 56u8, 172u8, 118u8, 25u8, 43u8, 156u8, 83u8, 231u8, 145u8, 68u8, 112u8, 178u8, 55u8,
        199u8, 49u8, 176u8, 153u8, 168u8, 235u8, 66u8, 105u8, 23u8, 233u8, 49u8, 166u8, 253u8,
        17u8, 81u8, 19u8, 23u8, 53u8, 2u8, 221u8, 184u8, 188u8, 130u8, 1u8, 238u8, 82u8, 211u8,
        190u8, 55u8, 22u8, 174u8, 253u8, 44u8, 19u8, 215u8, 50u8, 113u8, 142u8, 73u8, 235u8, 90u8,
        163u8, 69u8, 48u8, 53u8, 186u8, 3u8, 15u8, 106u8, 70u8, 155u8, 75u8, 79u8, 253u8, 211u8,
        11u8, 83u8, 196u8, 178u8, 23u8, 149u8, 23u8, 139u8, 197u8, 206u8, 169u8, 222u8, 184u8,
        161u8, 227u8, 128u8, 252u8, 204u8, 60u8, 177u8, 247u8, 105u8, 83u8, 6u8, 101u8, 18u8,
        135u8, 150u8, 172u8, 10u8, 65u8, 98u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [57u8, 117u8, 218u8, 112u8, 246u8, 141u8, 170u8, 218u8, 174u8, 21u8, 176u8, 64u8, 117u8, 238u8, 107u8, 245u8, 163u8, 14u8, 50u8, 172u8, 96u8, 27u8, 22u8, 34u8, 44u8, 185u8, 164u8, 86u8, 236u8, 182u8, 222u8, 247u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_d1b819c7f0b025bf")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x003975da70f68daadaae15b04075ee6bf5a30e32ac601b16222cb9a456ecb6def7\x00=======END GROTH16 VK SETUP V1=======\x00";
