// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        35u8, 205u8, 70u8, 217u8, 38u8, 236u8, 63u8, 41u8, 233u8, 48u8, 233u8, 103u8, 39u8, 198u8,
        242u8, 89u8, 235u8, 231u8, 115u8, 90u8, 39u8, 210u8, 146u8, 54u8, 214u8, 200u8, 135u8,
        97u8, 48u8, 40u8, 88u8, 84u8, 23u8, 110u8, 22u8, 6u8, 140u8, 53u8, 196u8, 213u8, 208u8,
        125u8, 94u8, 163u8, 5u8, 121u8, 143u8, 155u8, 234u8, 242u8, 239u8, 56u8, 37u8, 7u8, 141u8,
        30u8, 14u8, 181u8, 74u8, 222u8, 224u8, 219u8, 111u8, 38u8,
    ],
    [
        11u8, 209u8, 252u8, 97u8, 182u8, 221u8, 226u8, 167u8, 116u8, 127u8, 19u8, 133u8, 79u8,
        125u8, 203u8, 174u8, 173u8, 67u8, 136u8, 172u8, 18u8, 91u8, 36u8, 244u8, 145u8, 157u8,
        123u8, 250u8, 49u8, 15u8, 71u8, 52u8, 47u8, 110u8, 70u8, 27u8, 214u8, 29u8, 68u8, 226u8,
        244u8, 44u8, 14u8, 45u8, 28u8, 171u8, 172u8, 44u8, 190u8, 184u8, 153u8, 15u8, 41u8, 43u8,
        182u8, 22u8, 25u8, 41u8, 89u8, 142u8, 125u8, 80u8, 125u8, 249u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        31u8, 158u8, 152u8, 49u8, 25u8, 250u8, 218u8, 169u8, 83u8, 41u8, 29u8, 26u8, 73u8, 243u8,
        204u8, 119u8, 118u8, 149u8, 71u8, 245u8, 112u8, 65u8, 72u8, 75u8, 75u8, 18u8, 239u8, 71u8,
        237u8, 101u8, 101u8, 123u8, 36u8, 58u8, 161u8, 44u8, 2u8, 110u8, 30u8, 113u8, 114u8, 176u8,
        224u8, 51u8, 194u8, 78u8, 149u8, 218u8, 6u8, 119u8, 122u8, 108u8, 249u8, 63u8, 110u8,
        252u8, 144u8, 102u8, 57u8, 125u8, 79u8, 53u8, 143u8, 214u8,
    ],
    vk_beta_g2: [
        4u8, 81u8, 146u8, 242u8, 255u8, 60u8, 143u8, 99u8, 249u8, 51u8, 94u8, 219u8, 25u8, 56u8,
        227u8, 154u8, 238u8, 144u8, 158u8, 153u8, 136u8, 19u8, 39u8, 3u8, 37u8, 3u8, 37u8, 74u8,
        127u8, 85u8, 188u8, 105u8, 32u8, 160u8, 214u8, 197u8, 120u8, 211u8, 156u8, 203u8, 83u8,
        229u8, 223u8, 248u8, 205u8, 56u8, 98u8, 243u8, 142u8, 197u8, 37u8, 219u8, 87u8, 243u8,
        180u8, 123u8, 245u8, 59u8, 46u8, 113u8, 109u8, 200u8, 209u8, 6u8, 29u8, 246u8, 131u8, 39u8,
        183u8, 156u8, 222u8, 191u8, 202u8, 212u8, 168u8, 77u8, 8u8, 224u8, 150u8, 208u8, 168u8,
        163u8, 173u8, 181u8, 182u8, 199u8, 15u8, 34u8, 224u8, 45u8, 197u8, 103u8, 241u8, 150u8,
        113u8, 171u8, 2u8, 62u8, 1u8, 23u8, 102u8, 44u8, 125u8, 167u8, 105u8, 248u8, 117u8, 67u8,
        135u8, 152u8, 175u8, 220u8, 201u8, 213u8, 9u8, 167u8, 62u8, 239u8, 212u8, 16u8, 124u8,
        214u8, 193u8, 52u8, 97u8, 112u8, 130u8, 101u8,
    ],
    vk_gamma_g2: [
        12u8, 207u8, 85u8, 193u8, 9u8, 23u8, 169u8, 63u8, 111u8, 93u8, 93u8, 67u8, 222u8, 205u8,
        207u8, 223u8, 105u8, 47u8, 82u8, 129u8, 68u8, 184u8, 85u8, 120u8, 142u8, 25u8, 58u8, 140u8,
        131u8, 138u8, 64u8, 153u8, 14u8, 206u8, 50u8, 82u8, 103u8, 191u8, 206u8, 64u8, 56u8, 140u8,
        10u8, 24u8, 192u8, 43u8, 176u8, 123u8, 237u8, 11u8, 4u8, 83u8, 34u8, 74u8, 138u8, 29u8,
        239u8, 80u8, 147u8, 63u8, 176u8, 20u8, 180u8, 241u8, 21u8, 233u8, 255u8, 198u8, 152u8,
        43u8, 188u8, 111u8, 221u8, 20u8, 150u8, 228u8, 230u8, 142u8, 167u8, 250u8, 208u8, 121u8,
        82u8, 5u8, 137u8, 132u8, 156u8, 239u8, 157u8, 73u8, 136u8, 3u8, 233u8, 93u8, 44u8, 89u8,
        43u8, 109u8, 77u8, 135u8, 103u8, 143u8, 170u8, 126u8, 251u8, 45u8, 160u8, 28u8, 121u8,
        182u8, 50u8, 151u8, 174u8, 45u8, 179u8, 18u8, 242u8, 82u8, 186u8, 23u8, 110u8, 237u8, 55u8,
        17u8, 70u8, 136u8, 120u8, 80u8,
    ],
    vk_delta_g2: [
        46u8, 154u8, 209u8, 172u8, 1u8, 81u8, 5u8, 171u8, 176u8, 158u8, 6u8, 232u8, 73u8, 165u8,
        73u8, 136u8, 151u8, 116u8, 227u8, 56u8, 250u8, 173u8, 85u8, 102u8, 93u8, 56u8, 43u8, 139u8,
        185u8, 103u8, 111u8, 60u8, 3u8, 37u8, 45u8, 239u8, 122u8, 44u8, 47u8, 138u8, 17u8, 11u8,
        88u8, 199u8, 232u8, 90u8, 47u8, 108u8, 25u8, 81u8, 214u8, 191u8, 245u8, 147u8, 191u8,
        222u8, 51u8, 113u8, 140u8, 0u8, 31u8, 186u8, 204u8, 88u8, 21u8, 92u8, 11u8, 44u8, 83u8,
        199u8, 229u8, 32u8, 83u8, 13u8, 238u8, 236u8, 122u8, 238u8, 213u8, 43u8, 235u8, 193u8,
        28u8, 211u8, 180u8, 228u8, 162u8, 150u8, 141u8, 225u8, 90u8, 144u8, 61u8, 118u8, 169u8,
        2u8, 5u8, 161u8, 45u8, 95u8, 64u8, 119u8, 245u8, 117u8, 78u8, 161u8, 242u8, 126u8, 149u8,
        160u8, 163u8, 55u8, 107u8, 220u8, 56u8, 158u8, 149u8, 107u8, 22u8, 115u8, 60u8, 187u8,
        163u8, 93u8, 142u8, 184u8, 36u8, 84u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [21u8, 88u8, 199u8, 178u8, 9u8, 141u8, 220u8, 17u8, 231u8, 219u8, 61u8, 128u8, 120u8, 53u8, 50u8, 110u8, 42u8, 187u8, 219u8, 87u8, 71u8, 135u8, 177u8, 22u8, 211u8, 233u8, 113u8, 194u8, 158u8, 90u8, 108u8, 126u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_97667d8d7a458691")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x001558c7b2098ddc11e7db3d807835326e2abbdb574787b116d3e971c29e5a6c7e\x00=======END GROTH16 VK SETUP V1=======\x00";
