// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        13u8, 224u8, 243u8, 36u8, 19u8, 92u8, 233u8, 155u8, 75u8, 168u8, 188u8, 111u8, 179u8,
        250u8, 205u8, 37u8, 39u8, 94u8, 148u8, 51u8, 131u8, 46u8, 249u8, 248u8, 7u8, 98u8, 92u8,
        221u8, 82u8, 255u8, 95u8, 103u8, 10u8, 119u8, 131u8, 197u8, 127u8, 106u8, 246u8, 185u8,
        140u8, 165u8, 91u8, 58u8, 122u8, 250u8, 24u8, 168u8, 207u8, 192u8, 128u8, 151u8, 243u8,
        226u8, 20u8, 45u8, 215u8, 57u8, 41u8, 134u8, 238u8, 250u8, 55u8, 151u8,
    ],
    [
        38u8, 55u8, 237u8, 154u8, 49u8, 167u8, 198u8, 23u8, 197u8, 57u8, 238u8, 14u8, 13u8, 67u8,
        137u8, 250u8, 246u8, 216u8, 165u8, 120u8, 168u8, 236u8, 47u8, 207u8, 251u8, 128u8, 81u8,
        235u8, 102u8, 237u8, 13u8, 129u8, 11u8, 179u8, 108u8, 154u8, 102u8, 202u8, 159u8, 210u8,
        228u8, 8u8, 109u8, 211u8, 133u8, 147u8, 140u8, 19u8, 230u8, 107u8, 226u8, 79u8, 228u8,
        67u8, 63u8, 211u8, 132u8, 62u8, 148u8, 151u8, 126u8, 166u8, 64u8, 57u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        20u8, 73u8, 239u8, 120u8, 56u8, 170u8, 255u8, 40u8, 204u8, 223u8, 229u8, 109u8, 171u8,
        100u8, 7u8, 65u8, 36u8, 24u8, 221u8, 112u8, 99u8, 193u8, 206u8, 147u8, 252u8, 219u8, 167u8,
        112u8, 19u8, 128u8, 120u8, 110u8, 16u8, 167u8, 114u8, 52u8, 229u8, 72u8, 72u8, 115u8,
        104u8, 175u8, 9u8, 140u8, 244u8, 150u8, 247u8, 66u8, 99u8, 206u8, 22u8, 105u8, 49u8, 15u8,
        107u8, 18u8, 45u8, 234u8, 241u8, 36u8, 43u8, 73u8, 35u8, 175u8,
    ],
    vk_beta_g2: [
        35u8, 39u8, 199u8, 1u8, 16u8, 84u8, 126u8, 23u8, 87u8, 9u8, 35u8, 60u8, 28u8, 116u8, 66u8,
        28u8, 242u8, 17u8, 242u8, 138u8, 89u8, 144u8, 120u8, 6u8, 169u8, 38u8, 122u8, 157u8, 163u8,
        75u8, 2u8, 239u8, 6u8, 111u8, 139u8, 142u8, 241u8, 26u8, 116u8, 219u8, 160u8, 108u8, 194u8,
        119u8, 0u8, 164u8, 185u8, 202u8, 166u8, 208u8, 98u8, 33u8, 208u8, 154u8, 180u8, 98u8,
        130u8, 12u8, 50u8, 149u8, 81u8, 151u8, 187u8, 125u8, 26u8, 5u8, 4u8, 224u8, 214u8, 95u8,
        139u8, 65u8, 161u8, 104u8, 85u8, 218u8, 4u8, 180u8, 209u8, 234u8, 215u8, 234u8, 18u8,
        172u8, 62u8, 132u8, 65u8, 189u8, 109u8, 158u8, 177u8, 216u8, 249u8, 163u8, 67u8, 21u8,
        34u8, 95u8, 199u8, 135u8, 179u8, 101u8, 4u8, 246u8, 24u8, 94u8, 157u8, 99u8, 67u8, 99u8,
        39u8, 53u8, 44u8, 20u8, 199u8, 191u8, 203u8, 110u8, 229u8, 123u8, 240u8, 48u8, 233u8,
        107u8, 185u8, 81u8, 53u8, 167u8,
    ],
    vk_gamma_g2: [
        15u8, 232u8, 226u8, 195u8, 52u8, 220u8, 155u8, 167u8, 140u8, 206u8, 193u8, 165u8, 58u8,
        250u8, 61u8, 200u8, 34u8, 91u8, 92u8, 102u8, 176u8, 34u8, 191u8, 126u8, 65u8, 193u8, 166u8,
        146u8, 168u8, 131u8, 68u8, 133u8, 46u8, 69u8, 194u8, 88u8, 1u8, 81u8, 101u8, 171u8, 40u8,
        84u8, 124u8, 8u8, 217u8, 36u8, 82u8, 208u8, 10u8, 164u8, 76u8, 82u8, 24u8, 205u8, 145u8,
        52u8, 16u8, 118u8, 244u8, 176u8, 245u8, 215u8, 22u8, 66u8, 42u8, 75u8, 134u8, 157u8, 83u8,
        244u8, 115u8, 169u8, 30u8, 93u8, 146u8, 75u8, 152u8, 65u8, 79u8, 103u8, 27u8, 82u8, 206u8,
        248u8, 225u8, 73u8, 82u8, 129u8, 128u8, 151u8, 242u8, 79u8, 81u8, 25u8, 230u8, 142u8, 33u8,
        28u8, 220u8, 248u8, 149u8, 198u8, 146u8, 147u8, 199u8, 169u8, 154u8, 107u8, 234u8, 75u8,
        55u8, 238u8, 71u8, 111u8, 235u8, 151u8, 21u8, 16u8, 84u8, 188u8, 175u8, 76u8, 72u8, 2u8,
        19u8, 8u8, 107u8, 202u8,
    ],
    vk_delta_g2: [
        45u8, 45u8, 31u8, 136u8, 181u8, 52u8, 25u8, 140u8, 64u8, 56u8, 89u8, 168u8, 105u8, 181u8,
        71u8, 103u8, 88u8, 48u8, 239u8, 219u8, 30u8, 212u8, 114u8, 87u8, 177u8, 59u8, 57u8, 93u8,
        193u8, 200u8, 69u8, 229u8, 11u8, 4u8, 225u8, 70u8, 193u8, 203u8, 64u8, 27u8, 195u8, 245u8,
        130u8, 71u8, 156u8, 79u8, 147u8, 62u8, 22u8, 45u8, 157u8, 239u8, 199u8, 148u8, 34u8, 128u8,
        138u8, 75u8, 62u8, 54u8, 245u8, 125u8, 216u8, 2u8, 27u8, 127u8, 144u8, 114u8, 141u8, 3u8,
        34u8, 31u8, 238u8, 106u8, 236u8, 179u8, 205u8, 83u8, 12u8, 163u8, 204u8, 220u8, 87u8,
        108u8, 11u8, 182u8, 183u8, 56u8, 240u8, 68u8, 242u8, 199u8, 211u8, 237u8, 209u8, 186u8,
        37u8, 86u8, 135u8, 164u8, 168u8, 251u8, 143u8, 221u8, 219u8, 123u8, 129u8, 190u8, 222u8,
        245u8, 101u8, 45u8, 162u8, 75u8, 148u8, 93u8, 185u8, 54u8, 214u8, 206u8, 248u8, 131u8,
        219u8, 178u8, 115u8, 77u8, 1u8, 12u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [80u8, 56u8, 50u8, 231u8, 196u8, 236u8, 169u8, 248u8, 190u8, 40u8, 41u8, 219u8, 144u8, 249u8, 14u8, 100u8, 102u8, 217u8, 120u8, 248u8, 22u8, 212u8, 107u8, 132u8, 114u8, 192u8, 34u8, 27u8, 51u8, 42u8, 10u8, 81u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_a014556d451bad32")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00503832e7c4eca9f8be2829db90f90e6466d978f816d46b8472c0221b332a0a51\x00=======END GROTH16 VK SETUP V1=======\x00";
