// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        0u8, 92u8, 123u8, 203u8, 236u8, 28u8, 30u8, 56u8, 19u8, 125u8, 245u8, 61u8, 183u8, 168u8,
        234u8, 163u8, 227u8, 103u8, 169u8, 128u8, 117u8, 106u8, 180u8, 20u8, 85u8, 196u8, 57u8,
        109u8, 187u8, 18u8, 122u8, 38u8, 11u8, 173u8, 108u8, 249u8, 169u8, 173u8, 28u8, 83u8, 83u8,
        158u8, 247u8, 112u8, 201u8, 162u8, 51u8, 136u8, 86u8, 95u8, 159u8, 93u8, 113u8, 255u8,
        255u8, 226u8, 47u8, 207u8, 157u8, 177u8, 169u8, 199u8, 103u8, 185u8,
    ],
    [
        29u8, 103u8, 244u8, 177u8, 10u8, 201u8, 179u8, 134u8, 240u8, 245u8, 15u8, 236u8, 229u8,
        131u8, 211u8, 243u8, 252u8, 101u8, 27u8, 15u8, 83u8, 110u8, 108u8, 111u8, 240u8, 1u8, 95u8,
        214u8, 173u8, 109u8, 227u8, 115u8, 23u8, 63u8, 137u8, 72u8, 189u8, 167u8, 216u8, 248u8,
        82u8, 102u8, 207u8, 222u8, 10u8, 126u8, 166u8, 36u8, 42u8, 221u8, 14u8, 106u8, 102u8,
        191u8, 67u8, 150u8, 88u8, 1u8, 36u8, 45u8, 45u8, 200u8, 68u8, 15u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        39u8, 181u8, 208u8, 190u8, 103u8, 87u8, 55u8, 79u8, 230u8, 21u8, 83u8, 5u8, 115u8, 251u8,
        64u8, 240u8, 64u8, 30u8, 4u8, 193u8, 164u8, 241u8, 86u8, 146u8, 177u8, 14u8, 147u8, 44u8,
        191u8, 245u8, 172u8, 135u8, 13u8, 90u8, 120u8, 141u8, 67u8, 255u8, 179u8, 63u8, 135u8,
        234u8, 249u8, 183u8, 241u8, 60u8, 24u8, 177u8, 63u8, 152u8, 148u8, 31u8, 201u8, 224u8,
        224u8, 117u8, 211u8, 201u8, 6u8, 74u8, 167u8, 181u8, 103u8, 154u8,
    ],
    vk_beta_g2: [
        12u8, 158u8, 174u8, 119u8, 119u8, 19u8, 169u8, 165u8, 127u8, 38u8, 236u8, 118u8, 113u8,
        28u8, 18u8, 112u8, 229u8, 108u8, 201u8, 222u8, 28u8, 217u8, 108u8, 215u8, 207u8, 104u8,
        208u8, 60u8, 112u8, 43u8, 40u8, 230u8, 14u8, 222u8, 114u8, 235u8, 111u8, 67u8, 153u8,
        183u8, 183u8, 39u8, 63u8, 133u8, 232u8, 132u8, 63u8, 93u8, 125u8, 124u8, 234u8, 205u8, 3u8,
        3u8, 49u8, 126u8, 113u8, 238u8, 236u8, 72u8, 0u8, 42u8, 252u8, 246u8, 46u8, 49u8, 22u8,
        31u8, 205u8, 255u8, 97u8, 134u8, 68u8, 95u8, 150u8, 119u8, 43u8, 85u8, 189u8, 26u8, 245u8,
        14u8, 140u8, 77u8, 158u8, 92u8, 152u8, 136u8, 75u8, 152u8, 204u8, 134u8, 127u8, 89u8, 1u8,
        193u8, 10u8, 86u8, 234u8, 120u8, 232u8, 142u8, 39u8, 76u8, 187u8, 183u8, 185u8, 164u8,
        120u8, 121u8, 58u8, 148u8, 87u8, 129u8, 214u8, 181u8, 2u8, 141u8, 211u8, 179u8, 156u8,
        38u8, 128u8, 52u8, 165u8, 221u8, 201u8, 216u8,
    ],
    vk_gamma_g2: [
        48u8, 63u8, 148u8, 96u8, 24u8, 143u8, 145u8, 103u8, 216u8, 90u8, 38u8, 5u8, 46u8, 180u8,
        209u8, 198u8, 93u8, 100u8, 229u8, 230u8, 35u8, 129u8, 62u8, 244u8, 39u8, 216u8, 44u8, 92u8,
        82u8, 40u8, 99u8, 236u8, 45u8, 193u8, 5u8, 252u8, 220u8, 116u8, 0u8, 38u8, 79u8, 162u8,
        94u8, 40u8, 64u8, 248u8, 78u8, 25u8, 189u8, 24u8, 60u8, 3u8, 205u8, 67u8, 211u8, 146u8,
        249u8, 189u8, 224u8, 247u8, 19u8, 105u8, 45u8, 98u8, 20u8, 194u8, 5u8, 68u8, 50u8, 5u8,
        199u8, 105u8, 229u8, 165u8, 152u8, 173u8, 152u8, 189u8, 215u8, 135u8, 45u8, 164u8, 32u8,
        99u8, 190u8, 44u8, 119u8, 160u8, 52u8, 69u8, 63u8, 27u8, 42u8, 163u8, 230u8, 212u8, 18u8,
        239u8, 249u8, 211u8, 245u8, 30u8, 17u8, 92u8, 207u8, 90u8, 190u8, 161u8, 19u8, 85u8, 111u8,
        224u8, 12u8, 39u8, 93u8, 103u8, 15u8, 15u8, 61u8, 207u8, 16u8, 55u8, 121u8, 31u8, 88u8,
        170u8, 135u8, 84u8,
    ],
    vk_delta_g2: [
        0u8, 110u8, 117u8, 237u8, 176u8, 35u8, 198u8, 64u8, 39u8, 46u8, 39u8, 194u8, 242u8, 85u8,
        69u8, 33u8, 215u8, 119u8, 137u8, 178u8, 113u8, 245u8, 100u8, 251u8, 108u8, 78u8, 21u8,
        54u8, 222u8, 108u8, 33u8, 125u8, 7u8, 51u8, 253u8, 159u8, 37u8, 10u8, 62u8, 18u8, 104u8,
        12u8, 83u8, 54u8, 170u8, 57u8, 50u8, 73u8, 153u8, 62u8, 99u8, 88u8, 50u8, 250u8, 77u8,
        70u8, 160u8, 130u8, 63u8, 73u8, 42u8, 205u8, 123u8, 218u8, 10u8, 200u8, 184u8, 105u8,
        144u8, 6u8, 186u8, 223u8, 100u8, 195u8, 112u8, 226u8, 222u8, 215u8, 23u8, 71u8, 106u8,
        21u8, 25u8, 164u8, 240u8, 186u8, 145u8, 58u8, 184u8, 65u8, 159u8, 93u8, 195u8, 160u8,
        210u8, 28u8, 44u8, 78u8, 6u8, 113u8, 134u8, 81u8, 9u8, 24u8, 150u8, 173u8, 122u8, 65u8,
        120u8, 17u8, 108u8, 67u8, 66u8, 18u8, 22u8, 14u8, 143u8, 180u8, 224u8, 247u8, 204u8, 158u8,
        123u8, 149u8, 170u8, 245u8, 207u8, 138u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [244u8, 175u8, 37u8, 199u8, 61u8, 12u8, 75u8, 64u8, 181u8, 43u8, 130u8, 203u8, 225u8, 243u8, 144u8, 3u8, 15u8, 3u8, 75u8, 240u8, 26u8, 223u8, 51u8, 5u8, 10u8, 49u8, 124u8, 159u8, 193u8, 188u8, 111u8, 121u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_f23ba6101a3f7a0c")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00f4af25c73d0c4b40b52b82cbe1f390030f034bf01adf33050a317c9fc1bc6f79\x00=======END GROTH16 VK SETUP V1=======\x00";
