// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        34u8, 239u8, 198u8, 132u8, 227u8, 226u8, 174u8, 17u8, 111u8, 253u8, 238u8, 204u8, 21u8,
        59u8, 195u8, 76u8, 202u8, 42u8, 118u8, 97u8, 130u8, 37u8, 229u8, 39u8, 151u8, 54u8, 113u8,
        224u8, 16u8, 70u8, 241u8, 149u8, 29u8, 233u8, 142u8, 62u8, 106u8, 142u8, 149u8, 200u8,
        54u8, 43u8, 62u8, 97u8, 92u8, 138u8, 3u8, 162u8, 146u8, 83u8, 180u8, 78u8, 248u8, 5u8,
        128u8, 254u8, 242u8, 114u8, 201u8, 197u8, 159u8, 157u8, 87u8, 112u8,
    ],
    [
        6u8, 53u8, 52u8, 239u8, 236u8, 87u8, 3u8, 136u8, 227u8, 219u8, 106u8, 225u8, 173u8, 253u8,
        254u8, 112u8, 221u8, 115u8, 123u8, 143u8, 244u8, 216u8, 33u8, 129u8, 81u8, 198u8, 71u8,
        3u8, 204u8, 75u8, 135u8, 54u8, 4u8, 155u8, 66u8, 150u8, 92u8, 161u8, 211u8, 104u8, 130u8,
        50u8, 148u8, 34u8, 84u8, 36u8, 217u8, 92u8, 63u8, 93u8, 184u8, 153u8, 22u8, 195u8, 153u8,
        208u8, 49u8, 129u8, 164u8, 186u8, 56u8, 213u8, 217u8, 253u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        29u8, 52u8, 194u8, 187u8, 92u8, 105u8, 129u8, 229u8, 180u8, 14u8, 132u8, 106u8, 101u8,
        125u8, 61u8, 193u8, 163u8, 243u8, 160u8, 166u8, 225u8, 43u8, 133u8, 27u8, 131u8, 102u8,
        73u8, 202u8, 23u8, 232u8, 42u8, 236u8, 2u8, 152u8, 102u8, 67u8, 90u8, 54u8, 165u8, 55u8,
        190u8, 7u8, 210u8, 101u8, 204u8, 202u8, 24u8, 136u8, 120u8, 43u8, 45u8, 69u8, 89u8, 126u8,
        158u8, 157u8, 247u8, 115u8, 230u8, 109u8, 123u8, 63u8, 91u8, 223u8,
    ],
    vk_beta_g2: [
        45u8, 162u8, 187u8, 90u8, 57u8, 145u8, 65u8, 36u8, 169u8, 73u8, 203u8, 146u8, 156u8, 227u8,
        64u8, 3u8, 90u8, 143u8, 206u8, 81u8, 198u8, 39u8, 19u8, 229u8, 59u8, 48u8, 91u8, 228u8,
        155u8, 137u8, 202u8, 121u8, 38u8, 182u8, 217u8, 226u8, 237u8, 143u8, 231u8, 161u8, 186u8,
        228u8, 31u8, 165u8, 40u8, 87u8, 23u8, 6u8, 45u8, 8u8, 149u8, 148u8, 227u8, 158u8, 24u8,
        62u8, 173u8, 196u8, 112u8, 88u8, 211u8, 138u8, 124u8, 144u8, 21u8, 83u8, 36u8, 250u8, 48u8,
        13u8, 87u8, 250u8, 183u8, 80u8, 8u8, 52u8, 98u8, 212u8, 54u8, 53u8, 46u8, 45u8, 46u8,
        130u8, 16u8, 145u8, 75u8, 42u8, 198u8, 64u8, 166u8, 21u8, 102u8, 67u8, 233u8, 142u8, 40u8,
        184u8, 193u8, 205u8, 121u8, 203u8, 105u8, 22u8, 58u8, 93u8, 125u8, 251u8, 16u8, 161u8,
        192u8, 120u8, 239u8, 154u8, 172u8, 34u8, 53u8, 18u8, 44u8, 22u8, 96u8, 19u8, 54u8, 119u8,
        246u8, 207u8, 125u8, 176u8,
    ],
    vk_gamma_g2: [
        37u8, 111u8, 240u8, 87u8, 138u8, 51u8, 36u8, 254u8, 93u8, 38u8, 225u8, 60u8, 163u8, 33u8,
        68u8, 162u8, 89u8, 35u8, 182u8, 158u8, 192u8, 228u8, 8u8, 170u8, 137u8, 161u8, 84u8, 229u8,
        134u8, 122u8, 40u8, 125u8, 22u8, 86u8, 52u8, 199u8, 13u8, 202u8, 182u8, 60u8, 224u8, 34u8,
        89u8, 194u8, 49u8, 100u8, 48u8, 145u8, 22u8, 13u8, 144u8, 41u8, 237u8, 164u8, 226u8, 185u8,
        253u8, 252u8, 25u8, 54u8, 113u8, 212u8, 247u8, 255u8, 21u8, 3u8, 95u8, 114u8, 89u8, 69u8,
        255u8, 244u8, 82u8, 133u8, 184u8, 26u8, 93u8, 127u8, 91u8, 168u8, 132u8, 81u8, 61u8, 1u8,
        247u8, 175u8, 144u8, 210u8, 162u8, 137u8, 93u8, 151u8, 113u8, 41u8, 11u8, 115u8, 8u8,
        218u8, 220u8, 49u8, 208u8, 92u8, 95u8, 112u8, 131u8, 139u8, 238u8, 150u8, 105u8, 15u8,
        98u8, 246u8, 10u8, 67u8, 225u8, 166u8, 122u8, 22u8, 51u8, 153u8, 47u8, 149u8, 95u8, 1u8,
        123u8, 201u8, 98u8, 133u8,
    ],
    vk_delta_g2: [
        32u8, 108u8, 163u8, 14u8, 174u8, 123u8, 1u8, 51u8, 87u8, 42u8, 58u8, 32u8, 145u8, 221u8,
        61u8, 221u8, 210u8, 157u8, 10u8, 2u8, 167u8, 125u8, 160u8, 77u8, 214u8, 173u8, 232u8, 24u8,
        61u8, 199u8, 46u8, 122u8, 21u8, 143u8, 133u8, 43u8, 11u8, 146u8, 61u8, 92u8, 212u8, 233u8,
        116u8, 177u8, 127u8, 105u8, 4u8, 82u8, 201u8, 38u8, 114u8, 98u8, 8u8, 212u8, 174u8, 20u8,
        192u8, 227u8, 236u8, 119u8, 218u8, 255u8, 98u8, 125u8, 14u8, 100u8, 192u8, 160u8, 225u8,
        188u8, 148u8, 222u8, 161u8, 10u8, 129u8, 126u8, 219u8, 6u8, 205u8, 101u8, 140u8, 20u8,
        48u8, 87u8, 156u8, 244u8, 237u8, 46u8, 225u8, 13u8, 26u8, 208u8, 206u8, 222u8, 190u8, 41u8,
        39u8, 137u8, 194u8, 248u8, 162u8, 8u8, 81u8, 46u8, 211u8, 26u8, 169u8, 186u8, 5u8, 166u8,
        65u8, 160u8, 176u8, 36u8, 117u8, 37u8, 246u8, 163u8, 86u8, 250u8, 127u8, 60u8, 26u8, 100u8,
        159u8, 42u8, 253u8, 115u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [242u8, 71u8, 138u8, 46u8, 39u8, 88u8, 241u8, 183u8, 37u8, 238u8, 226u8, 237u8, 136u8, 201u8, 218u8, 21u8, 185u8, 54u8, 12u8, 244u8, 44u8, 11u8, 86u8, 49u8, 141u8, 231u8, 89u8, 234u8, 232u8, 167u8, 91u8, 71u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_b05a1c0e92055fc8")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00f2478a2e2758f1b725eee2ed88c9da15b9360cf42c0b56318de759eae8a75b47\x00=======END GROTH16 VK SETUP V1=======\x00";
