// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        24u8, 144u8, 4u8, 207u8, 45u8, 40u8, 198u8, 66u8, 94u8, 54u8, 245u8, 221u8, 35u8, 226u8,
        233u8, 39u8, 91u8, 223u8, 82u8, 140u8, 218u8, 254u8, 89u8, 220u8, 150u8, 177u8, 50u8,
        102u8, 197u8, 56u8, 101u8, 216u8, 27u8, 71u8, 151u8, 31u8, 151u8, 88u8, 162u8, 54u8, 185u8,
        8u8, 20u8, 234u8, 159u8, 55u8, 238u8, 65u8, 200u8, 29u8, 71u8, 250u8, 141u8, 37u8, 174u8,
        87u8, 12u8, 91u8, 86u8, 180u8, 7u8, 247u8, 155u8, 26u8,
    ],
    [
        24u8, 202u8, 13u8, 126u8, 254u8, 184u8, 168u8, 244u8, 147u8, 230u8, 180u8, 249u8, 213u8,
        110u8, 21u8, 16u8, 32u8, 235u8, 137u8, 20u8, 232u8, 85u8, 175u8, 76u8, 84u8, 195u8, 103u8,
        202u8, 88u8, 234u8, 73u8, 182u8, 13u8, 156u8, 82u8, 102u8, 81u8, 168u8, 121u8, 142u8,
        242u8, 9u8, 116u8, 136u8, 69u8, 43u8, 6u8, 68u8, 187u8, 34u8, 94u8, 67u8, 191u8, 226u8,
        249u8, 254u8, 10u8, 74u8, 113u8, 184u8, 128u8, 246u8, 19u8, 157u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        16u8, 46u8, 4u8, 56u8, 233u8, 64u8, 197u8, 28u8, 198u8, 17u8, 100u8, 133u8, 83u8, 66u8,
        54u8, 142u8, 168u8, 31u8, 155u8, 150u8, 7u8, 50u8, 173u8, 186u8, 216u8, 116u8, 171u8,
        145u8, 48u8, 63u8, 61u8, 50u8, 4u8, 178u8, 196u8, 171u8, 31u8, 181u8, 138u8, 74u8, 1u8,
        123u8, 72u8, 199u8, 125u8, 222u8, 221u8, 12u8, 44u8, 177u8, 255u8, 214u8, 7u8, 113u8, 53u8,
        180u8, 65u8, 53u8, 143u8, 188u8, 172u8, 104u8, 130u8, 190u8,
    ],
    vk_beta_g2: [
        0u8, 1u8, 152u8, 17u8, 138u8, 165u8, 43u8, 35u8, 231u8, 106u8, 46u8, 22u8, 200u8, 170u8,
        229u8, 215u8, 241u8, 171u8, 60u8, 127u8, 156u8, 35u8, 117u8, 180u8, 200u8, 155u8, 243u8,
        30u8, 251u8, 36u8, 226u8, 139u8, 48u8, 94u8, 147u8, 227u8, 222u8, 63u8, 107u8, 219u8,
        231u8, 225u8, 81u8, 134u8, 43u8, 150u8, 166u8, 210u8, 62u8, 122u8, 189u8, 129u8, 135u8,
        111u8, 242u8, 81u8, 233u8, 56u8, 162u8, 33u8, 72u8, 16u8, 89u8, 206u8, 37u8, 81u8, 7u8,
        68u8, 156u8, 198u8, 240u8, 76u8, 96u8, 248u8, 165u8, 181u8, 224u8, 204u8, 248u8, 179u8,
        247u8, 233u8, 227u8, 220u8, 165u8, 192u8, 25u8, 162u8, 215u8, 160u8, 82u8, 127u8, 239u8,
        195u8, 159u8, 91u8, 43u8, 170u8, 124u8, 194u8, 71u8, 209u8, 117u8, 229u8, 0u8, 233u8, 58u8,
        222u8, 246u8, 137u8, 71u8, 147u8, 155u8, 225u8, 93u8, 127u8, 164u8, 100u8, 67u8, 50u8,
        245u8, 59u8, 72u8, 253u8, 80u8, 206u8, 129u8, 99u8,
    ],
    vk_gamma_g2: [
        37u8, 250u8, 180u8, 69u8, 35u8, 22u8, 77u8, 33u8, 225u8, 51u8, 99u8, 22u8, 112u8, 36u8,
        87u8, 131u8, 177u8, 98u8, 45u8, 174u8, 152u8, 174u8, 113u8, 45u8, 52u8, 25u8, 16u8, 118u8,
        17u8, 10u8, 56u8, 0u8, 14u8, 251u8, 243u8, 135u8, 236u8, 49u8, 136u8, 59u8, 56u8, 25u8,
        66u8, 125u8, 194u8, 35u8, 162u8, 75u8, 19u8, 197u8, 137u8, 230u8, 167u8, 117u8, 30u8,
        247u8, 11u8, 67u8, 52u8, 240u8, 167u8, 37u8, 133u8, 13u8, 41u8, 250u8, 1u8, 101u8, 30u8,
        148u8, 77u8, 20u8, 219u8, 0u8, 27u8, 113u8, 7u8, 66u8, 44u8, 243u8, 82u8, 11u8, 29u8,
        142u8, 31u8, 25u8, 76u8, 190u8, 216u8, 151u8, 189u8, 170u8, 125u8, 135u8, 101u8, 250u8,
        6u8, 11u8, 216u8, 144u8, 37u8, 165u8, 132u8, 249u8, 86u8, 149u8, 139u8, 178u8, 171u8, 98u8,
        186u8, 232u8, 139u8, 172u8, 134u8, 131u8, 48u8, 223u8, 235u8, 196u8, 142u8, 238u8, 16u8,
        221u8, 85u8, 186u8, 97u8, 179u8,
    ],
    vk_delta_g2: [
        21u8, 136u8, 183u8, 41u8, 226u8, 17u8, 48u8, 31u8, 249u8, 215u8, 171u8, 19u8, 197u8, 189u8,
        133u8, 6u8, 162u8, 237u8, 115u8, 209u8, 1u8, 196u8, 92u8, 107u8, 230u8, 170u8, 250u8,
        190u8, 131u8, 147u8, 249u8, 66u8, 27u8, 13u8, 27u8, 235u8, 192u8, 124u8, 248u8, 38u8, 0u8,
        65u8, 165u8, 202u8, 125u8, 124u8, 107u8, 136u8, 67u8, 251u8, 106u8, 115u8, 249u8, 11u8,
        188u8, 98u8, 148u8, 233u8, 25u8, 181u8, 144u8, 204u8, 179u8, 193u8, 26u8, 170u8, 47u8,
        88u8, 18u8, 134u8, 175u8, 52u8, 191u8, 25u8, 82u8, 53u8, 58u8, 84u8, 213u8, 136u8, 243u8,
        189u8, 165u8, 16u8, 111u8, 104u8, 173u8, 98u8, 178u8, 253u8, 57u8, 171u8, 137u8, 230u8,
        204u8, 116u8, 34u8, 177u8, 50u8, 96u8, 175u8, 129u8, 250u8, 233u8, 164u8, 63u8, 201u8,
        74u8, 84u8, 115u8, 164u8, 167u8, 249u8, 5u8, 35u8, 24u8, 168u8, 20u8, 65u8, 58u8, 197u8,
        107u8, 40u8, 8u8, 242u8, 160u8, 44u8, 148u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [233u8, 255u8, 63u8, 7u8, 113u8, 92u8, 146u8, 174u8, 146u8, 111u8, 142u8, 163u8, 96u8, 19u8, 166u8, 205u8, 121u8, 254u8, 0u8, 176u8, 109u8, 191u8, 152u8, 215u8, 70u8, 25u8, 252u8, 239u8, 197u8, 62u8, 183u8, 73u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = false;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_3e74bac74d091091")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00false\x00proving_key_sha256\x00e9ff3f07715c92ae926f8ea36013a6cd79fe00b06dbf98d74619fcefc53eb749\x00=======END GROTH16 VK SETUP V1=======\x00";
