[unix_http_server]
file=%(here)s/supervisor.sock
chmod=0700
[supervisord]
logfile=%(here)s/logs/supervisor.log
pidfile=%(here)s/supervisor.pid
childlogdir=%(here)s/logs
[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface
[supervisorctl]
serverurl=unix://%(here)s/supervisor.sock
[program:photon]
command=/bin/bash %(here)s/current/run-service.sh %(here)s photon
user=zolana_gpu
autostart=true
autorestart=true
stopsignal=INT
stopasgroup=true
killasgroup=true
stopwaitsecs=30
stdout_logfile=%(here)s/logs/photon.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=2
redirect_stderr=true
[program:prover]
command=/bin/bash %(here)s/current/run-service.sh %(here)s prover
user=zolana_gpu
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=60
stdout_logfile=%(here)s/logs/prover.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=2
redirect_stderr=true
