#!/usr/bin/env bash
set -euo pipefail

server_dir="$(cd "$(dirname "$0")/.." && pwd)"
repo_root="$(cd "$server_dir/../.." && pwd)"
cd "$server_dir"

keys_dir="${1:-./proving-keys}"
vkey_dir="$repo_root/program-libs/interface/src/verifying_keys"
tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

go build -o light-prover .
(cd "$repo_root" && cargo build -q -p xtask)
xtask="$repo_root/target/debug/xtask"

keys="$(find "$keys_dir" -maxdepth 1 -type f \( -name 'transfer_*.key' -o -name 'merge_*.key' \) | sort)"
if [ -z "$keys" ]; then
    echo "no transfer or merge proving keys in $keys_dir"
    exit 1
fi

modules=""
for key in $keys; do
    stem="$(basename "$key" .key)"
    module="${stem//-/_}"
    vk_bin="$tmp_dir/${stem}.vkbin"

    echo "exporting raw vk: $stem"
    if ! ./light-prover export-vk --keys-file "$key" --output "$vk_bin" >/dev/null; then
        echo "WARN: export-vk failed, skipping $stem"
        continue
    fi

    if "$xtask" bsb22-vk \
        "$vk_bin" "$key" "$vkey_dir" "${module}.rs"; then
        modules="${modules}${module} ${stem}"$'\n'
    else
        echo "WARN: vk codegen failed, skipping $stem"
    fi
done

{
    echo '//! Committed Groth16 verifying keys.'
    echo '//!'
    echo '//! The key modules are generated by `regenerate_all_vkeys.sh` from Prover keys.'
    echo
    echo "mod circuit;"
    echo "pub use circuit::{valid_cache_writes, Bsb22Commitment, CacheAccess, CacheWrite, CircuitId, OutputOwnerMode, RingP256ProofData, MAX_CACHE_WRITES};"
    echo
    echo "$modules" | sort -u | while read -r module _stem; do
        if [ -n "$module" ]; then
            echo '#[cfg(feature = "verifying-keys")]'
            echo "pub mod $module;"
        fi
    done
    echo
    echo "/// Proving key file name, as in proving-keys.lock and the prover's"
    echo '/// `/proving-keys`, and the sha256 its committed verifying key pins.'
    echo '#[cfg(feature = "verifying-keys")]'
    echo 'pub const PROVING_KEY_SHA256S: &[(&str, [u8; 32])] = &['
    echo "$modules" | sort -u | while read -r module stem; do
        if [ -n "$module" ]; then
            echo "    (\"${stem}.key\", ${module}::VERIFYINGKEY_PROVING_KEY_SHA256),"
        fi
    done
    echo '];'
} >"$vkey_dir/mod.rs"

rustfmt "$vkey_dir"/*.rs

echo "Regenerated verifying keys into $vkey_dir"
