[package]
name = "swap-prover"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "swap_prover"
path = "src/lib.rs"

[[bin]]
name = "swap-prover-setup"
path = "src/bin/setup.rs"

[dependencies]
zolana-gnark-prover = { workspace = true }
swap-program = { path = "../program" }
zolana-client = { workspace = true }

[build-dependencies]
zolana-gnark-prover-build = { workspace = true }
