[package]
name = "dynamic-swap-prover"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "dynamic_swap_prover"
path = "src/lib.rs"

[[bin]]
name = "dynamic-swap-prover-setup"
path = "src/bin/setup.rs"

[dependencies]
zolana-gnark-ffi-prover = { workspace = true }
zolana-client = { workspace = true }

[build-dependencies]
zolana-gnark-ffi-prover-build = { workspace = true }
