// Turns the compiled wasm into the TypeScript module the packages import.
//
// The artifact is inlined as base64 rather than shipped beside the JavaScript
// because the packages emit plain `tsc` output with no bundler step: a sibling
// `.wasm` would have to be located at runtime, and both ways of doing that are
// closed to us. `fetch(new URL(..., import.meta.url))` does not read a `file:`
// URL in Node, and `node:fs` is what the browser gate exists to keep out.
//
// usage: node sdk-libs/ts/hasher/scripts/embed.mjs
import { execFileSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const crateRoot = path.resolve(packageRoot, "../../hasher-wasm");
const artifact = path.join(
  crateRoot,
  "target/wasm32-unknown-unknown/release/zolana_hasher_wasm.wasm",
);

execFileSync("cargo", ["build", "--release", "--target", "wasm32-unknown-unknown"], {
  cwd: crateRoot,
  stdio: "inherit",
});

const bytes = await readFile(artifact);
const base64 = bytes.toString("base64");

// One string literal on one line. Wrapping it into concatenated chunks reads
// better and overflows the evaluator's stack at this length. The `: string`
// annotation is what keeps the declaration file from restating the literal, and
// with it the artifact from shipping twice.
await writeFile(
  path.join(packageRoot, "src/artifact.ts"),
  `// Generated by scripts/embed.mjs from sdk-libs/hasher-wasm. Do not edit.
// ${bytes.length} bytes of WebAssembly, base64 encoded.
export const ARTIFACT_BYTE_LENGTH = ${bytes.length};
export const ARTIFACT: string = "${base64}";\n`,
);

console.log(`embedded ${bytes.length} bytes as ${base64.length} base64 characters`);
