export {
  buildRegistrationTransaction,
  decodeUserRecordAccount,
  ensureRegistered,
  fetchUserRecord,
  fetchUserRecordChecked,
  fetchUserRecordOptionalChecked,
  isWalletRegistered,
  recipientConfidentialViewTag,
  registerIfAbsent,
  resolveRegisteredAddress,
  resolvedAddressFromRecord,
  senderViewingPublicKey,
  tryResolveRegisteredAddress,
  validateRegisteredKeypair,
  type ResolvedAddress,
  type StrictRegistration,
  type SyncDelegateEntry,
  type UserRecord,
} from "../registry.js";
