//! An index of every function name defined in the workspace.
//!
//! The ledger cites tests by bare name (`sol_deposit_rejects_a_readonly_depositor`).
//! Verifying those citations means asking "does a function with this name
//! exist?", which the shell version approximated with
//! `git grep -qE "fn ${tok}\("`. That interpolates an arbitrary token into a
//! regex — a citation containing regex metacharacters matches the wrong thing —
//! and it only sees definitions whose `fn name(` fits on one line.
//!
//! Parsing with `syn` answers the question directly: free functions, inherent
//! and trait `impl` methods, and functions nested inside `mod` blocks all land
//! in the same set regardless of formatting.
//!
//! Known limitation, shared with the shell version: a function generated by a
//! macro has no syntax node here and so is invisible. Go functions are matched
//! textually for the same reason the shell version did — the ledger cites a
//! handful of prover symbols and pulling in a Go parser is not worth it.

use std::{collections::HashSet, path::Path};

use anyhow::Result;
use syn::{visit::Visit, ImplItemFn, ItemFn, TraitItemFn};
use walkdir::WalkDir;

#[derive(Default)]
pub struct SymbolIndex {
    functions: HashSet<String>,
}

impl SymbolIndex {
    /// Walk `roots`, parsing every `.rs` file and recording its function names.
    /// Unparseable files are skipped: this index exists to confirm a name is
    /// present, and a file that does not parse cannot be defining the symbol a
    /// citation refers to. Compilation errors are the compiler's job to report.
    pub fn build(roots: &[&Path]) -> Result<Self> {
        let mut index = Self::default();
        for root in roots {
            if !root.exists() {
                continue;
            }
            for entry in WalkDir::new(root).into_iter().filter_map(Result::ok) {
                let path = entry.path();
                if path.extension().is_none_or(|ext| ext != "rs") {
                    continue;
                }
                let Ok(source) = std::fs::read_to_string(path) else {
                    continue;
                };
                index.add_rust_source(&source);
            }
        }
        Ok(index)
    }

    pub fn add_rust_source(&mut self, source: &str) {
        if let Ok(file) = syn::parse_file(source) {
            let mut visitor = FnCollector {
                functions: &mut self.functions,
            };
            visitor.visit_file(&file);
        }
    }

    pub fn contains(&self, name: &str) -> bool {
        self.functions.contains(name)
    }

    pub fn len(&self) -> usize {
        self.functions.len()
    }
}

/// Collects every `fn` name in a file, at any nesting depth.
struct FnCollector<'a> {
    functions: &'a mut HashSet<String>,
}

impl<'ast> Visit<'ast> for FnCollector<'_> {
    fn visit_item_fn(&mut self, node: &'ast ItemFn) {
        self.functions.insert(node.sig.ident.to_string());
        syn::visit::visit_item_fn(self, node);
    }

    fn visit_impl_item_fn(&mut self, node: &'ast ImplItemFn) {
        self.functions.insert(node.sig.ident.to_string());
        syn::visit::visit_impl_item_fn(self, node);
    }

    fn visit_trait_item_fn(&mut self, node: &'ast TraitItemFn) {
        self.functions.insert(node.sig.ident.to_string());
        syn::visit::visit_trait_item_fn(self, node);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn indexes_functions_at_every_nesting_depth() {
        let mut index = SymbolIndex::default();
        index.add_rust_source(
            r#"
            fn free_function() {}
            struct S;
            impl S {
                fn inherent_method(&self) {}
                pub(crate) async fn async_method() {}
            }
            trait T {
                fn trait_method(&self);
            }
            mod nested {
                fn nested_function() {}
                #[test]
                fn a_test_case() { assert!(true) }
            }
            "#,
        );

        for name in [
            "free_function",
            "inherent_method",
            "async_method",
            "trait_method",
            "nested_function",
            "a_test_case",
        ] {
            assert!(index.contains(name), "missing {name}");
        }
        assert!(!index.contains("absent_function"));
    }

    /// The shell version matched `fn name(` textually, so a signature split
    /// across lines by rustfmt was invisible. Parsing does not care.
    #[test]
    fn finds_a_signature_broken_across_lines() {
        let mut index = SymbolIndex::default();
        index.add_rust_source(
            r#"
            fn wrapped_signature(
                first: u64,
                second: u64,
            ) -> u64 { first + second }
            "#,
        );
        assert!(index.contains("wrapped_signature"));
    }

    #[test]
    fn unparseable_sources_are_skipped_rather_than_failing_the_run() {
        let mut index = SymbolIndex::default();
        index.add_rust_source("this is not rust !!!");
        assert_eq!(index.len(), 0);
    }
}
