[package]
name = "zolana-transaction" # TODO: rename as zolana-sdk
version = "0.1.0"
description = "TSPP output UTXO serialization: plaintext and encrypted UTXO layouts for transfer and split, encrypted and decrypted via zolana-keypair."
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
zolana-interface = { workspace = true }
zolana-event = { workspace = true }
zolana-hasher = { workspace = true }
zolana-keypair = { workspace = true }
zolana-program = { workspace = true }
borsh = { workspace = true }
thiserror = { workspace = true }
wincode = { workspace = true }
solana-address = { workspace = true }
solana-signature = { workspace = true }
num-bigint = { workspace = true }

[dev-dependencies]
hex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[[test]]
name = "behavior"
path = "tests/behavior.rs"
