//! Engine-level tests: the linked cgo archive, a real trusted setup, and a real
//! proof over a witness that satisfies the circuit.

use std::sync::Once;

use custom_ring_prover::{ffi, AuditorKeyEncryptionProofInputs, CircuitId};

// A witness the circuit accepts. Generated by the same host recompute that
// circuits/auditor_key_encryption/circuit_test.go runs (P-256 scalars 0x11 /
// 0x22 / 0x33 for the tx, ephemeral and auditor keys, private_tx_hash 0xabcdef,
// public_input_hash the pinned eight-element chain over them). Proving against
// it is the end-to-end check of the ffi contract: witness-map keys, array
// ordering, key loading and the proof encoding. The Rust host implementation of
// this derivation lives in the sdk crate, which is where the cross-language
// consistency test belongs.
const PUBLIC_INPUT_HASH: [u8; 32] = [
    24, 191, 117, 99, 166, 70, 117, 193, 16, 174, 125, 64, 139, 151, 60, 152, 0, 90, 250, 198, 208,
    107, 138, 225, 119, 244, 67, 93, 126, 110, 2, 11,
];
const PRIVATE_TX_HASH: [u8; 32] = [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 171,
    205, 239,
];
const TX_VIEWING_SK: [u8; 32] = [
    1, 16, 19, 18, 21, 20, 23, 22, 25, 24, 27, 26, 29, 28, 31, 30, 1, 0, 3, 2, 5, 4, 7, 6, 9, 8,
    11, 10, 13, 12, 15, 14,
];
const EPH_SK: [u8; 32] = [
    1, 35, 32, 33, 38, 39, 36, 37, 42, 43, 40, 41, 46, 47, 44, 45, 50, 51, 48, 49, 54, 55, 52, 53,
    58, 59, 56, 57, 62, 63, 60, 61,
];
const AUDITOR_PK: [u8; 65] = [
    4, 157, 197, 27, 89, 0, 107, 19, 241, 67, 148, 77, 78, 67, 45, 183, 192, 50, 36, 28, 235, 54,
    152, 166, 204, 12, 218, 186, 223, 41, 183, 29, 236, 32, 85, 73, 70, 17, 145, 94, 125, 188, 165,
    106, 176, 45, 249, 243, 183, 5, 16, 233, 35, 226, 146, 82, 68, 228, 56, 188, 140, 235, 240,
    230, 53,
];

fn valid_inputs() -> AuditorKeyEncryptionProofInputs {
    AuditorKeyEncryptionProofInputs {
        public_input_hash: PUBLIC_INPUT_HASH,
        private_tx_hash: PRIVATE_TX_HASH,
        tx_viewing_sk: TX_VIEWING_SK,
        eph_sk: EPH_SK,
        auditor_pk: AUDITOR_PK,
    }
}

/// Generates the keys into their canonical build directory once per process.
/// `Once` also serializes the tests that need them: two concurrent setups would
/// write `pk.bin` at the same time.
fn ensure_keys() {
    static KEYS: Once = Once::new();
    KEYS.call_once(|| {
        let circuit = CircuitId::AuditorKeyEncryption;
        let dir = ffi::build_dir(circuit);
        if !dir.join("pk.bin").exists() || !dir.join("vk.bin").exists() {
            ffi::setup(circuit, &dir).expect("gnark setup");
        }
    });
}

/// Without the archive every engine call fails, so a skipped cgo build must not
/// pass silently as "no tests to run". Absent keys are fine here: `MissingKeys`
/// is already an answer from the linked archive.
#[test]
fn the_go_circuits_are_linked() {
    match ffi::preload(CircuitId::AuditorKeyEncryption) {
        Ok(()) | Err(ffi::Error::MissingKeys(_)) => {}
        Err(error) => panic!("the Go circuits are not usable: {error}"),
    }
}

/// Ignored: a trusted setup plus a proof over 327883 constraints takes tens of
/// seconds and writes a ~74 MB proving key. Run with
/// `cargo test -p custom-ring-prover --test auditor_key_encryption -- --ignored`.
#[test]
#[ignore = "runs a gnark trusted setup and a full proof"]
fn setup_then_prove_a_valid_witness() {
    ensure_keys();

    let proof = valid_inputs().prove().expect("prove a valid witness");

    // The 192 bytes the program's wincode AuditProof reads, in field order.
    let mut wire = Vec::new();
    wire.extend_from_slice(&proof.proof_a);
    wire.extend_from_slice(&proof.proof_b);
    wire.extend_from_slice(&proof.proof_c);
    wire.extend_from_slice(&proof.commitment);
    wire.extend_from_slice(&proof.commitment_pok);
    assert_eq!(wire.len(), 192);

    // Every field is a compressed curve point, so none of them can be zero; the
    // commitment pair in particular must be present for this circuit.
    assert_ne!(proof.proof_a, [0u8; 32]);
    assert_ne!(proof.proof_b, [0u8; 64]);
    assert_ne!(proof.proof_c, [0u8; 32]);
    assert_ne!(proof.commitment, [0u8; 32]);
    assert_ne!(proof.commitment_pok, [0u8; 32]);
}

/// A witness the circuit rejects must fail in the solver, not in the assigner:
/// an assigner error would mean the witness map itself is malformed.
#[test]
#[ignore = "needs proving keys and runs the solver"]
fn prove_rejects_a_tampered_witness() {
    ensure_keys();

    let mut inputs = valid_inputs();
    inputs.private_tx_hash = [7u8; 32];
    let error = inputs
        .prove()
        .expect_err("a public input that is not in the chain must not prove")
        .to_string();
    assert!(
        !error.contains("witness:"),
        "expected a solver error, got a witness-assignment error: {error}"
    );
}
