pub const PROTOCOL_CONFIG_MAX_MERGE_AUTHORITIES: usize = 16;
pub const CONFIG_AUTHORITY_OFFSET: usize = 8;
pub const CONFIG_AUTHORITY_END: usize = CONFIG_AUTHORITY_OFFSET + 32;

pub const PROTOCOL_CONFIG_MERGE_AUTHORITY_COUNT_OFFSET: usize = CONFIG_AUTHORITY_END;
pub const PROTOCOL_CONFIG_MERGE_AUTHORITIES_OFFSET: usize =
    PROTOCOL_CONFIG_MERGE_AUTHORITY_COUNT_OFFSET + core::mem::size_of::<u64>();
pub const PROTOCOL_CONFIG_ACCOUNT_LEN: usize =
    PROTOCOL_CONFIG_MERGE_AUTHORITIES_OFFSET + PROTOCOL_CONFIG_MAX_MERGE_AUTHORITIES * 32;

pub const ZONE_CONFIG_ENABLED_OFFSET: usize = CONFIG_AUTHORITY_END;
pub const ZONE_CONFIG_BUMP_OFFSET: usize = ZONE_CONFIG_ENABLED_OFFSET + 1;
pub const ZONE_CONFIG_ACCOUNT_LEN: usize = ZONE_CONFIG_BUMP_OFFSET + 1;
