pub const PROTOCOL_CONFIG_MAX_MERGE_AUTHORITIES: usize = 16;
pub const PROTOCOL_CONFIG_ACCOUNT_LEN: usize = 48 + PROTOCOL_CONFIG_MAX_MERGE_AUTHORITIES * 32;
pub const ZONE_CONFIG_ACCOUNT_LEN: usize = 42;
