pub const TREE_ACCOUNT_DISCRIMINATOR: u8 = 1;
pub const PROTOCOL_CONFIG: u8 = 3;
pub const ZONE_CONFIG: u8 = 4;
pub const SPL_ASSET_REGISTRY: u8 = 5;
pub const SPL_ASSET_COUNTER: u8 = 6;
pub const BATCH_QUEUE_ACCOUNT_DISCRIMINATOR: u8 = 7;
