pub mod config;
pub mod discriminator;

pub use config::{
    CONFIG_AUTHORITY_END, CONFIG_AUTHORITY_OFFSET, PROTOCOL_CONFIG_ACCOUNT_LEN,
    PROTOCOL_CONFIG_MAX_MERGE_AUTHORITIES, PROTOCOL_CONFIG_MERGE_AUTHORITIES_OFFSET,
    PROTOCOL_CONFIG_MERGE_AUTHORITY_COUNT_OFFSET, ZONE_CONFIG_ACCOUNT_LEN, ZONE_CONFIG_BUMP_OFFSET,
    ZONE_CONFIG_ENABLED_OFFSET,
};
