use sea_orm_migration::prelude::*;

use super::super::super::model::table::{
    RingsOutputPayloads, RingsOutputs, RingsTransactionPayloads, RingsTransactions,
    RingsTxNullifiers, Transactions,
};

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(RingsTransactions::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(RingsTransactions::RingsTxId)
                            .big_integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(RingsTransactions::Signature)
                            .binary_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RingsTransactions::EventIndex)
                            .small_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RingsTransactions::Slot)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RingsTransactions::RingsProgramId)
                            .binary_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RingsTransactions::SourceInstructionTag)
                            .small_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RingsTransactions::OutputTree)
                            .binary_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RingsTransactions::FirstOutputLeafIndex)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RingsTransactions::TxViewingPk)
                            .binary_len(33)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RingsTransactions::Salt)
                            .binary_len(16)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RingsTransactions::Proofless)
                            .boolean()
                            .not_null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("rings_transactions_signature_fk")
                            .from(RingsTransactions::Table, RingsTransactions::Signature)
                            .to(Transactions::Table, Transactions::Signature)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_rings_transactions_signature_event")
                    .table(RingsTransactions::Table)
                    .col(RingsTransactions::Signature)
                    .col(RingsTransactions::EventIndex)
                    .unique()
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_rings_transactions_slot_id")
                    .table(RingsTransactions::Table)
                    .col(RingsTransactions::Slot)
                    .col(RingsTransactions::RingsTxId)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_rings_transactions_program_slot_id")
                    .table(RingsTransactions::Table)
                    .col(RingsTransactions::RingsProgramId)
                    .col(RingsTransactions::Slot)
                    .col(RingsTransactions::RingsTxId)
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(RingsTransactionPayloads::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(RingsTransactionPayloads::RingsTxId)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RingsTransactionPayloads::EncryptedUtxos)
                            .binary()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RingsTransactionPayloads::RawEvent)
                            .binary()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RingsTransactionPayloads::ParseVersion)
                            .small_integer()
                            .not_null(),
                    )
                    .primary_key(
                        Index::create()
                            .name("pk_rings_transaction_payloads")
                            .col(RingsTransactionPayloads::RingsTxId),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("rings_transaction_payloads_tx_fk")
                            .from(
                                RingsTransactionPayloads::Table,
                                RingsTransactionPayloads::RingsTxId,
                            )
                            .to(RingsTransactions::Table, RingsTransactions::RingsTxId)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(RingsOutputs::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(RingsOutputs::OutputId)
                            .big_integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(RingsOutputs::RingsTxId)
                            .big_integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(RingsOutputs::Slot).big_integer().not_null())
                    .col(
                        ColumnDef::new(RingsOutputs::OutputIndex)
                            .small_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RingsOutputs::OutputTree)
                            .binary_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RingsOutputs::LeafIndex)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RingsOutputs::ViewTag)
                            .binary_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RingsOutputs::UtxoHash)
                            .binary_len(32)
                            .not_null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("rings_outputs_tx_fk")
                            .from(RingsOutputs::Table, RingsOutputs::RingsTxId)
                            .to(RingsTransactions::Table, RingsTransactions::RingsTxId)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_rings_outputs_tx_output")
                    .table(RingsOutputs::Table)
                    .col(RingsOutputs::RingsTxId)
                    .col(RingsOutputs::OutputIndex)
                    .unique()
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_rings_outputs_tree_leaf")
                    .table(RingsOutputs::Table)
                    .col(RingsOutputs::OutputTree)
                    .col(RingsOutputs::LeafIndex)
                    .unique()
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_rings_outputs_view_tag_slot_id")
                    .table(RingsOutputs::Table)
                    .col(RingsOutputs::ViewTag)
                    .col(RingsOutputs::Slot)
                    .col(RingsOutputs::OutputId)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_rings_outputs_slot_id")
                    .table(RingsOutputs::Table)
                    .col(RingsOutputs::Slot)
                    .col(RingsOutputs::OutputId)
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(RingsOutputPayloads::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(RingsOutputPayloads::OutputId)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RingsOutputPayloads::Payload)
                            .binary()
                            .not_null(),
                    )
                    .primary_key(
                        Index::create()
                            .name("pk_rings_output_payloads")
                            .col(RingsOutputPayloads::OutputId),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("rings_output_payloads_output_fk")
                            .from(RingsOutputPayloads::Table, RingsOutputPayloads::OutputId)
                            .to(RingsOutputs::Table, RingsOutputs::OutputId)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(RingsTxNullifiers::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(RingsTxNullifiers::NullifierId)
                            .big_integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(RingsTxNullifiers::RingsTxId)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RingsTxNullifiers::Slot)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RingsTxNullifiers::InputIndex)
                            .small_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RingsTxNullifiers::NullifierTree)
                            .binary_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RingsTxNullifiers::InputQueueSeq)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RingsTxNullifiers::Nullifier)
                            .binary_len(32)
                            .not_null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("rings_tx_nullifiers_tx_fk")
                            .from(RingsTxNullifiers::Table, RingsTxNullifiers::RingsTxId)
                            .to(RingsTransactions::Table, RingsTransactions::RingsTxId)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_rings_tx_nullifiers_tx_input")
                    .table(RingsTxNullifiers::Table)
                    .col(RingsTxNullifiers::RingsTxId)
                    .col(RingsTxNullifiers::InputIndex)
                    .unique()
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_rings_tx_nullifiers_tree_nullifier")
                    .table(RingsTxNullifiers::Table)
                    .col(RingsTxNullifiers::NullifierTree)
                    .col(RingsTxNullifiers::Nullifier)
                    .unique()
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_rings_tx_nullifiers_slot_id")
                    .table(RingsTxNullifiers::Table)
                    .col(RingsTxNullifiers::Slot)
                    .col(RingsTxNullifiers::NullifierId)
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(RingsTxNullifiers::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(RingsOutputPayloads::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(RingsOutputs::Table).to_owned())
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(RingsTransactionPayloads::Table)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(Table::drop().table(RingsTransactions::Table).to_owned())
            .await
    }
}
