# Forester

default:
    @just --list

check:
    cargo check -p forester --all-targets

build:
    cargo build -p forester

build-release:
    cargo build -p forester --release

test:
    cargo test -p forester
