# Forester - skeleton crate. Foresting recipes will be reintroduced once the
# combined address+state tree type ships.

default:
    @just --list

build:
    cargo build -p forester --release

check:
    cargo check -p forester --all-targets
